### ISSUE TITLE
profile-selectors hotkey for groups

### ISSUE THREAD

**Issue by BaccanoMob** [Eugeny/tabby#10008]
Currently these are the hotkeys in Tabby for profile-selector

![image](https://github.com/user-attachments/assets/64c88f75-a0dd-4123-bc25-ebf5d0137d39)

It is restrictive to a particular connection type. While individual connection/saved layout can be assigned a hotkey when opening as new tab, but groups (with a set of connections and/or saved layouts mixed up) does not have a hotkey to open as profile-selector.

For example, I have a group set up for a particular project or work with some different connections and saved layouts. I want to avoid opening `profile-selector` with a large number of options but only for a particular group which I set the needed connections/layouts.

**Comment by Clem-Fern** [comment]
+1

I'll be happy to submit a PR to implement this feature if @Eugeny is OK with it.

**Comment by Eugeny** [comment]
Sure, sounds good!
