### ISSUE TITLE
A way to temporarily install dependencies and then have them auto delete after

### ISSUE THREAD

**Issue by RustoMCSpit** [Eugeny/tabby#10011]
# Description of the new feature/enhancement

If someone wants to build an app from source, they need dependencies. However, people do not want to clog up their systems with useless dependencies. Having the ability to install a multitude of dependencies and have them auto delete automatically once the terminal is closed would be ideal.

e.g. https://github.com/minetest/minetest/issues/15198#issuecomment-2420730855

# Proposed technical implementation details (optional)

something along the lines of
``` 
sudo apt install -t g++ make libc6-dev cmake libpng-dev libjpeg-dev libxi-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext
```

the terminal would then check which of these are already installed and ignore them, but download those that arent temporarily. you could then close the app and the ones that were downloaded would delete whilst the ones that were already on your system would stay

(i use linux by the way, so the sudo command would be something else)

**Comment by Eugeny** [comment]
Not directly related to terminals, this would rather be something like a wrapper shell.

**Comment by RustoMCSpit** [comment]
> Not directly related to terminals, this would rather be something like a wrapper shell.

where do i find the repo for that

**Comment by RustoMCSpit** [comment]
what "wrapper shell" does tabby use and where is its repo?

**Comment by Eugeny** [comment]
None, it was an idea for how you could implement your concept. There's nothing in it that needs a specific terminal app though.

**Comment by RustoMCSpit** [comment]
> None, it was an idea for how you could implement your concept. There's nothing in it that needs a specific terminal app though.

oh, what repo do you think my idea would be best on in then?

**Comment by Eugeny** [comment]
Sorry, not to sound mean but you don't seem to be grasping the complexity of this and I can't help you
