### ISSUE TITLE
Choose input position

### ISSUE THREAD

**Issue by nleconte-csgroup** [Eugeny/tabby#10021]
**Is your feature request related to a problem? Please describe.**
I would like to change the position of the input. At the moment, it's locked to the bottom of the screen after few commands.
![image](https://github.com/user-attachments/assets/727d1f57-1e52-4f30-a773-c695bcad139f)

_Feature request 1_ : I want to be able to put the input on top of the terminal.

_Feature request 2_ : I would also like to be able to change the order of the last X commands that are visible in my terminal. At the moment, the order is first to last. I want to be able to choose last to first ordering.

**Describe the solution you'd like**
I would like to be able to put my terminal input on the top of my screen like that AND be able to choose the order of the last X commands displayed in the terminal. For e.g :
- use case 1 : Terminal input at top, and order history from last to first :
  ![image](https://github.com/user-attachments/assets/848ec2a0-8e9a-442c-ac5b-66b2b150c245)
- use case 2 : Terminal input at top, and order history from first to last :
  ![image](https://github.com/user-attachments/assets/adacbbe1-dd7f-4ae2-8a40-01a22f32cbb3)

**Describe alternatives you've considered**
I didn't find any alternative in tabby.

**Additional context**
Screenshots are already provided in the previous steps.

**Comment by Eugeny** [comment]
Prompt placement is a feature of the shell, not the terminal. I'm not aware of any that do this though.
