### ISSUE TITLE
Read Master Passphrase from file (Keyless vault) and/or have timeout to avoid passphrase popups

### ISSUE THREAD

**Issue by BaccanoMob** [Eugeny/tabby#10032]
When I am syncing between OSes the file paths gets messed up. But if I set up a vault beforehand, It is possible to sync without issues but I get `Enter Passphrase` popup every single time which is annoying. I really like the vault features, like I can replace keys, passwords, etc in one place though.

Some possible (and preferred in order) solutions:

- Vault settings to allow passphrase to be saved
  -  read it in a config.yml set it in external file under vault (similar to how keys are saved with filesystem) with so it will be keyless in UI. 
    ```
    vault:
        passphrase: file://path/to/key
    ```
    Only if its missing or does not exist or not valid path (incase of different OS), it will prompt master passphrase pop ups whenever needed (the default). This way I can get all vault features without entering passphrase every single time. (While I do get its less secure vault but it will be a favorable feature for ones who want just the features with basic security)
  - or timeout so you only have to re-enter passphrase after specific intervals.
  - or while tabby is active so you enter passphrase once (aka timeout is infinity or not set).

**Comment by BaccanoMob** [comment]
I just found that there is a timeout feature but its very hidden (in the right top corner). So im closing this.

![image](https://github.com/user-attachments/assets/3ce443c6-8add-4192-bd50-1fe6749452d7)

**Comment by gitthangbaby** [comment]
Never seen it working #5535 I'd love the vault not ask for password for 7 days like it's promised.
