### ISSUE TITLE
sftp为什么不能搜索和同步当前位置路径

### ISSUE THREAD

**Issue by Skylush** [Eugeny/tabby#10046]
比如我现在/etc/ssh，，但是打开sftp还是在/目录开始，也没有搜索功能快速定位目录这个很不方便
<img width="933" alt="image" src="https://github.com/user-attachments/assets/84238a06-ce7b-4786-b79d-b9ae3069b3c7">

**Comment by stefanie6** [comment]
双击路径的地方可以修改直达

**Comment by Skylush** [comment]
get到了
