### ISSUE TITLE
Security Advisory - Vulnerability Submission Channel Required

### ISSUE THREAD

**Issue by senzee1984** [Eugeny/tabby#10095]
Hi there,

I have identified several security risks in Tabby Terminal related to privacy permissions and privilege escalation. These findings warrant review due to potential impact on the growing user base.

However, Private Vulnerability Reporting is currently disabled in the repository. Once this feature is enabled, I can submit a detailed security analysis through the proper private channel, allowing secure review before any public disclosure.

![image](https://github.com/user-attachments/assets/89fc1e9e-fa86-4852-9db8-a08fa8a42068)

Please enable Private Vulnerability Reporting to facilitate responsible security disclosure. Thank you for your attention.

**Comment by Eugeny** [comment]
Enabled
