### ISSUE TITLE
It keeps stuck at this interface. How can I solve it?

### ISSUE THREAD

**Issue by iseesec** [Eugeny/tabby#10109]
![20241225151247](https://github.com/user-attachments/assets/1b8ed81c-c787-4fb7-a781-788766099e47)

**Comment by Unviray** [comment]
Same issue
```
'/private/var/folders/vr/5dhryr8j1454698b9gqtp7nm0000gp/T/.${teamId}.org.tabby.nPtToU'
code signature in <3F9A3629-E54B-3197-A21E-40AE33C74DF8> '/private/var/folders/vr/5dhryr8j1454698b9gqtp7nm0000gp/T/.${teamId}.org.tabby.nPtToU' not valid for use in process:
mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by lixeon** [comment]
Same issue, major bug.

**Comment by Eugeny** [comment]
Please reinstall it by downloading it from the [releases page](https://github.com/Eugeny/tabby/releases/tag/v1.0.216) and let me know if it's still happening

**Comment by lixeon** [comment]
> Please reinstall it by downloading it from the [releases page](https://github.com/Eugeny/tabby/releases/tag/v1.0.216) and let me know if it's still happening

same issue but back 1.0.215, fine. (Apple M1 Pro 14-inch, 2021 15.2 (24C101))

**Comment by pluxi** [comment]
same issue on macOS 11.7.10

**Comment by Eugeny** [comment]
@pluxi x64 or arm64?

**Comment by iseesec** [comment]
arm64

**Comment by pluxi** [comment]
> @pluxi x64 or arm64?

x64 (MacBook Pro late 2013, Intel Core i5), 1.0.215 works

**Comment by Eugeny** [comment]
New build coming asap

**Comment by Eugeny** [comment]
Fixed now
