### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by shihuili1218** [Eugeny/tabby#10106]
dear team, any plans to support android?

**Comment by Eugeny** [comment]
No, currently not.

**Comment by Spider999999** [comment]
What a pity !

**Comment by Michi4** [comment]
i made a compatible android client (unofficial) https://github.com/Michi4/tabby-android just bc i needed it and i switched from termius

<blockquote><img src="https://opengraph.githubassets.com/3c3823fc44e8bf83ae642aa3ad8f404af3dbaa3fd056425ccc2b9e5e8e338a69/Michi4/tabby-android" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Michi4/tabby-android">GitHub - Michi4/tabby-android</a></strong></div><div>Contribute to Michi4/tabby-android development by creating an account on GitHub.</div></blockquote>

**Comment by shihuili1218** [comment]
@Michi4 Cool! I also made one myself. I don't want to wait for Tabby anymore.
