### ISSUE TITLE
Tabby 1.0.216 Freezes on the Startup Screen

### ISSUE THREAD

**Issue by ZheCheng** [Eugeny/tabby#10111]
**Describe the problem**:
After updating to Tabby version 1.0.216, the application consistently freezes on the startup screen and cannot proceed further. The issue persists after multiple attempts to restart the application and the system. Previous versions of Tabby worked without issues.

**To Reproduce**:
Launch the application.
Observe that the app freezes on the startup screen and does not respond.

**Expected Behavior**:
The application should start successfully and display the terminal interface.

**Actual Behavior**:
The application freezes on the startup screen with no further progress.

**Environment**:

OS:  macOS Sonoma 14.7.2
Tabby Version: 1.0.216

**Screenshots**:
![image](https://github.com/user-attachments/assets/83c07956-8b4c-4d52-9cb4-08fbdffafd04)

**Comment by Jaaayden** [comment]
This issue is happened on tabby 1.0.215 in my situation.

macOS 15.0

**Comment by OrenZhang** [comment]
+1

**Comment by hmucheng** [comment]
same on macOS 15.2

**Comment by Eugeny** [comment]
Please try reinstalling it from the [releases page](https://github.com/Eugeny/tabby/releases/tag/v1.0.216) - I've already replaced the build with a fixed one.

**Comment by OrenZhang** [comment]
> Please try reinstalling it from the [releases page](https://github.com/Eugeny/tabby/releases/tag/v1.0.216) - I've already replaced the build with a fixed one.

I'm using macos on m3, and i find that the release still shows 11 hours ago

**Comment by 24Arise** [comment]
_Same problem in macOS 15.2_

**Comment by iamchating** [comment]
The apple arm64 build does not update,  

Install a x86-64 version for a temp workaround

if tabby does not work, I will have no work. :)

**Comment by imperialwool** [comment]
> Install a x86-64 version for a temp workaround
It worked, but arm64 build still just freezes

Looked in developer tools, looks like a signing issue ...?
<img width="1318" alt="screenshot" src="https://github.com/user-attachments/assets/67c560cf-82da-45c1-a008-61925a5fdac0" />

**Comment by Eugeny** [comment]
Very weird - it works on my Mac but I'll replace that build anyway

**Comment by Jaaayden** [comment]
1.0.214 work for me.

**Comment by Eugeny** [comment]
The new arm64 build is there
