### ISSUE TITLE
Tabby does not load and is stuck on the initial loading screen, with new version update.

### ISSUE THREAD

**Issue by ravibandaru-lab** [Eugeny/tabby#10114]
**Describe the problem**:
Apologies if this is not a descriptive issue, but my Tabby terminal was automatically updated to the newest version 1.0.216 on macOS Sequoia 15.2, and it stopped loading. This persisted after force quitting the app multiple times, and restarting my computer twice. I then went and redownloaded and replaced the 1.0.216 with 1.0.215 and it started working. 

**To Reproduce**:
Not entirely sure but I would suggest referring to the above, or perhaps if others are facing the same issue they might consider reacting to this or supplying more details on their environment to see if there are commonalities (i.e. only on MacOS, only on 15.2, etc.) But 1.0.216 was flat out not working/loading for me.

**Comment by Eugeny** [comment]
It should be fixed in the reuploaded installer - please download it again and see if that helps - #10111
