### ISSUE TITLE
最新版本为什么删除旧主题希望恢复

### ISSUE THREAD

**Issue by Lee911861472** [Eugeny/tabby#10137]
当前的这个版本为什么要删除旧主题呢，旧主题标准模式(旧版)就是最合适的，目前的所有配色方案都特别的差劲
Version: 1.0.216
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

**Comment by nullaegy** [comment]
Totally agree, standard (legacy) is my favorite, the others are too fancy for me.
Please don't remove this legacy theme!

**Comment by Eugeny** [comment]
@nullaegy the new default theme is _very_ close to the old "standard", and you can freely tweak its colors to your liking now
