### ISSUE TITLE
SSH Connection settings suddenly disappeard.

### ISSUE THREAD

**Issue by summershrimp** [Eugeny/tabby#1106]
SSH connection settings closed when drag mouse to select texts (sush as Host, or Name) but move mouse outside the dialog.
Seems that click the parent would close pop-up dialog, but the listener is onmouseup rather than onclick.
Version 1.0.82 official release.

**Comment by summershrimp** [comment]
Windows reproduce:
1. Navigate to Settings - SSH - Add Connection  
2. Type 'asdasdasdasd' to Name field in modal frame.
3. Select from last char to the first but not release left mouse key
4. Move mouse outside the modal frame.
5. Release your left mouse key.

**Comment by ehwarren** [comment]
This is an issue with angular bootstrap modals.

https://github.com/ng-bootstrap/ng-bootstrap/issues/1950
https://github.com/ng-bootstrap/ng-bootstrap/pull/3181

Currently the workaround would be to disable background click detection altogether, but i'm not sure if this is an ideal solution.

`const modal = this.ngbModal.open(EditConnectionModalComponent, {backdrop: false});`

**Comment by Eugeny** [comment]
Already fixed
