### ISSUE TITLE
memory usage is so high

### ISSUE THREAD

**Issue by guoqi** [Eugeny/tabby#1309]
I installed terminus on win7 system and use it to connect remote development machine whose system is linux. I just opened 5 sessions and find out the memory usage of terminus is up to 2.4G! The program is stuck and sometimes doesn't respond when I type a command. 

I don't install any themes or any plugins.

**Comment by IgnusG** [comment]
This might be caused by electron (very difficult to "fix"). Its apps are generally very resource hungry

**Comment by qcq** [comment]
I agree, I opened only 4 sessions, which cost about 800MB+ memory, which incredible. I am not agree to close, seems I have to back putty. which so great.

**Comment by Charlieglider** [comment]
Same here, but I have only 2 sessions open and it's using 3.8 gigs! I understand Electron is resource hungry but this is a lot, can I request a fix for this?

**Comment by MostHated** [comment]
I am not quite sure what you are expecting to happen? It says right in the middle of the info about it that it is pretty heavy.

![](https://i.imgur.com/bv80CHo.png)

**Comment by Charlieglider** [comment]
It’s fine, not an issue anymore.

**Comment by Veltix** [comment]
In ventura termius uses 12GB. Not normal ..

**Comment by topclaudy** [comment]
Memory usage was ~50Gb on my 64Gb Mac M1 today!!
