### ISSUE TITLE
CTRL+V hotkey setup adds additional characters

### ISSUE THREAD

**Issue by ChipwizBen** [Eugeny/tabby#1360]
I've changed the CTRL+Shift+V paste hot key to CTRL+V, but it produces extra unwanted characters. There are many consistency issues with paste. Examples:

Copy String: **test-string**:
- Right click, paste output: **test-string**
- CTRL+Shift+V output: **test-string**
- CTRL+V output: **0\~test-string1\~**
- Middle click output: **0\~test-string1\~test-string**

**Comment by ChipwizBen** [comment]
This is still a problem.

**Comment by teachmeter** [comment]
For me the cmd+V add additional characters, cmd+shift+V doesn't paste anything. When i right click and paste also with additional characters. But When i go to menu and click Paste item it is working correctly

Mac 10.15.2
Terminus 1.0.97

**Comment by MostHated** [comment]
Having this issue as well on Windows. It is extremely annoying.

Using 'test-string' as the OP did, pasting ends up showing this:
[200~test-string[201~

**Comment by Eugeny** [comment]
@MostHated this means your shell doesn't support bracketed paste - disable it under Settings -> Terminal

**Comment by SergioSuarezDev** [comment]
i have the same issue

**Comment by SergioSuarezDev** [comment]
check here 

![image](https://user-images.githubusercontent.com/3636232/92013975-ccf40e80-ed4e-11ea-821a-61adf69f7c38.png)
