### ISSUE TITLE
[Feature] Allow SSH Plugin reading from .ssh/config

### ISSUE THREAD

**Issue by jaesbit** [Eugeny/tabby#1528]
Would be more practical if the SSH plugin allows integration with local ssh configurations (`~/.ssh/config`).

It simplifies the usage of user@domain and path for local keys.

Thanks for this amazing terminal!

**Comment by jaesbit** [comment]
Some news about this feature?

**Comment by koto137** [comment]
**+1** Vote for this feature

**Comment by Shaddy** [comment]
@Eugeny I agree this is an interesting feature and should not be a big deal. Is anything we can do from our side to move forward with this? Thank you!

**Comment by Eugeny** [comment]
@Shaddy it's just about finding time to do this. `.ssh/config` supports a crapton of options and I'll have to dig through and see what can be mapped to Terminus.

**Comment by koto137** [comment]
on Windows supporting /.ssh/config in the means of tab-auto-completion of hostnames, would be just enough and might be a fast fix, as OpenSSH takes care of rest
everything else is working flawlessly

**Comment by Eugeny** [comment]
The built-in SSH implementation in Terminus doesn't use OpenSSH. As for tab completion in the local terminal itself, that depends on each individual shell and not on the terminal app.

**Comment by function2-llx** [comment]
Any progress on this? I'm looking forward to this feature, too. It will be pretty cool if terminus could import from local ssh configurations, since we only need to configure once.

**Comment by MostHated** [comment]
I agree, I have a ton of connection details in my .ssh/config that I would like to add, but don't want to have to do it manually, one at a time in the interface. Can they be added directly to Terminus config somewhere? I assume there must be a file somewhere that contains them? If I can just script it to take my config and put it into a format that Terminus likes, that would work well enough for me.

**Comment by Eugeny** [comment]
@MostHated yes - go to Settings -> Config file -> Show config file

**Comment by lj19950508** [comment]
i need this feature

**Comment by lj19950508** [comment]
> 我需要这个功能
https://stackoverflow.com/questions/2419566/best-way-to-use-multiple-ssh-private-keys-on-one-client

**Comment by sendaoYan** [comment]
@Eugeny Hi, it seems that linux support this feature, but windows do not support this feature with the latest tabby version?

linux(ubuntu22):

<img width="924" height="266" alt="Image" src="https://github.com/user-attachments/assets/e2de6b71-87ba-4c7d-913c-e17d08862a92" />


windows:

<img width="833" height="280" alt="Image" src="https://github.com/user-attachments/assets/f9c26f1a-d43a-42f3-b728-972a6658e806" />
