### ISSUE TITLE
Freezing when closing a tab

### ISSUE THREAD

**Issue by tabarra** [Eugeny/tabby#1584]
Version: 1.0.91
Platform: win32 10.0.18362
Plugins: none
  
Sometimes when I close a tab terminus freezes mid-animation.    
Sorry if I don't have more information.

**Comment by sburkett** [comment]
Possibly a dupe of #1564  ...

**Comment by jack1142** [comment]
Same happens to me sometimes, I tried looking for errors in dev tools console, but there is nothing there really except for this warning (which happens several times while Terminus is running but it doesn't seem to be connected to this problem as it doesn't just happen when the freeze occurs)
```
Could not resize xterm Error: This API does not accept floating point numbers
    at eval (VM693 57:1)
    at Array.forEach (<anonymous>)
    at e._verifyIntegers (VM693 57:1)
    at e.resize (VM693 57:1)
    at xtermFrontend_XTermFrontend.resizeHandler (xtermFrontend.ts:101)
    at ResizeObserver.eval (xtermFrontend.ts:139)
```

The freeze looks like this, it happens mid-animation when I try to close a tab sometimes, the interface can't be interacted with anymore after this happens (Dev Tools still work if you would me to help you debug the issue somehow):
![image](https://user-images.githubusercontent.com/6032823/67128387-c96d9c80-f1fb-11e9-9e96-fe07c917f1f7.png)

To fix the issue, I have to kill Terminus with task manager as window's buttons don't work like rest of the interface and closing with taskbar doesn't seem to do anything either.

---

Version: 1.0.92
Platform: win32 10.0.18362
Plugins: clickable-links, save-output

**Comment by tabarra** [comment]
Yes, that's exactly whats happening!  
It freezes in the middle of the tab (more or less) animation.

**Comment by Soncomander** [comment]
This issue only happened for me on Cmder.
Disabling plugins didn't show effect.

Tested shells:
* CMD (Clink)
* CMD (Stock)
* Powershell
* Powershell Core
* Cmder
* Cmder (Admin)
* Cygwin
* Git-Bash
* WSL / Default Distro
* WSL / Ubuntu 18..04

---
Version: 1.0.92
Platform: win32 10.0.18362
Frontend: xterm
Used profile: Cmder
Plugins: clickable-links, relaxed-theme, scrollbar, shell-selector, theme-windows10

**Comment by jack1142** [comment]
@Eugeny I know this probably isn't *that* easy to fix or debug but any chance to get information if you can reproduce this or if we can help in any other way with debugging this issue? I don't have required knowledge to fix whatever the underlying issue that needs to be fixed is code-wise, but I would love to help in some way if I can :)

**Comment by Eugeny** [comment]
@jack1142 I'll try to get to this as soon as I have a free evening again :)

**Comment by joelmgallant** [comment]
Doing some of my own testing on this issue - I found I could **not** reproduce it I disabled the "Use ConPTY" flag.

Otherwise, I always get a hard freeze on tab close.

Version: 1.0.103
OS: Win10
Frontend: any
Shell: WSL Ubuntu w/ fish
Plugins: community-color-schemes, core, plugin-manager, settings, terminal

**Comment by mullerch** [comment]
> Doing some of my own testing on this issue - I found I could **not** reproduce it I disabled the "Use ConPTY" flag.
> 
> Otherwise, I always get a hard freeze on tab close.
> 
> Version: 1.0.103
> OS: Win10
> Frontend: any
> Shell: WSL Ubuntu w/ fish
> Plugins: community-color-schemes, core, plugin-manager, settings, terminal

I confirm, only reproductible with ConPTY flag. Occurs very frequently when using Cmder

**Comment by tabarra** [comment]
Any updates on this confirmed issue?

**Comment by joelmgallant** [comment]
Just re-tested on 1.0.108 with same settings as above.
Also cleared Roaming profiles.

Same freezing behavior, unfortunately... 
No errors or uncaught exceptions that I can see in DevTools.
*only* seems to occur when closing tabs via window interaction methods - typing `exit` command doesn't seem to cause freezes.

**Comment by huangzy-zj** [comment]
> This issue only happened for me on Cmder.
> Disabling plugins didn't show effect.
> 
> Tested shells:
> 
> * CMD (Clink)
> * CMD (Stock)
> * Powershell
> * Powershell Core
> * Cmder
> * Cmder (Admin)
> * Cygwin
> * Git-Bash
> * WSL / Default Distro
> * WSL / Ubuntu 18..04
> 
> Version: 1.0.92
> Platform: win32 10.0.18362
> Frontend: xterm
> Used profile: Cmder
> Plugins: clickable-links, relaxed-theme, scrollbar, shell-selector, theme-windows10

Same  happens to me on Cmder, and I have to kill Terminus with task manager.

![image](https://user-images.githubusercontent.com/20430306/80781042-8d03fb80-8ba3-11ea-822c-f97c13a3a0f4.png)

**Comment by LarsOlt** [comment]
Same problem, Terminus

> > This issue only happened for me on Cmder.
> > Disabling plugins didn't show effect.
> > Tested shells:
> > 
> > * CMD (Clink)
> > * CMD (Stock)
> > * Powershell
> > * Powershell Core
> > * Cmder
> > * Cmder (Admin)
> > * Cygwin
> > * Git-Bash
> > * WSL / Default Distro
> > * WSL / Ubuntu 18..04
> > 
> > Version: 1.0.92
> > Platform: win32 10.0.18362
> > Frontend: xterm
> > Used profile: Cmder
> > Plugins: clickable-links, relaxed-theme, scrollbar, shell-selector, theme-windows10
> 
> Same happens to me on Cmder, and I have to kill Terminus with task manager.
> 
> ![image](https://user-images.githubusercontent.com/20430306/80781042-8d03fb80-8ba3-11ea-822c-f97c13a3a0f4.png)

+1

**Comment by tabarra** [comment]
Since this issue doesn't even have an label, I can only assume nobody is even looking at it.  
unfortunately this bug fucked me up one too many times. Can't use this anymore.

**Comment by yusiwen** [comment]
This issue is really annoying, any updates?

**Comment by tabarra** [comment]
> This issue is really annoying, any updates?

At this point, you could probably just try another app.  
I gave up on Terminus and changed to the new Microsoft Terminal.  
It is not a full replacement for Terminus, but with some minor `settings.json` changes for styling and adding git bash, I'm fine with it (never had any issues).

https://github.com/microsoft/terminal

**Comment by twoz** [comment]
Wanted to give a Terminus a try, but this issue has 100% repro rate in my environment. Makes this unusable. 
Windows 10.0.18362 Build 18362
Terminus Alpha 120
