### ISSUE TITLE
Drag-selecting field value in a modal closes it

### ISSUE THREAD

**Issue by amurad** [Eugeny/tabby#1648]
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: save-output, scrollbar, shell-selector

In Connections when editing an entry, if any word is selected/highlighted with mouse in any field for editing purpose, the screen disappears. Can only use backspace key to make a correction.

![image](https://user-images.githubusercontent.com/2021240/67132838-c0ff6c80-f1cf-11e9-8beb-bb05f0b7267f.png)

**Comment by bliteknight** [comment]
This might not be a bug but an annoyance, if you highlight within the modal window you can delete the highlighted text...but if you highlight and release the click outside the window, it will register as a click outside the window and close it

e.g. In the gif below - I highlight the Name filed and its fine, but when I highlight the Group filed and release it outside the screen window, it disappears

![bug_issue](https://user-images.githubusercontent.com/8250359/67355173-2fb82f00-f51c-11e9-9a0a-64c41ab8ab63.gif)

**Comment by Eugeny** [comment]
Already fixed
