### ISSUE TITLE
Remember passwords with keyboard-interactive auth

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/tabby#1790]
Connecting to XXX.XXX.XXX.XXX
SHA256 fingerprint: XYZ.
Trying saved password
Keyboard-interactive auth requested: .......

And I get a password prompt to type the password that I already have saved to the ssh session.

**Comment by Eugeny** [comment]
What os/device are you connecting to? Keyboard-interactive auth is not the usual password request, but is explicitly initiated by the remote side

**Comment by Onepamopa** [comment]
I'm using Windows 10. "Keyboard-interactive" auth is used by default on FreeBSD.
Is there a way to pass the saved password ?

**Comment by Onepamopa** [comment]
I tried using "login scripts" but it didn't work for some reason ...

**Comment by Onepamopa** [comment]
Perhaps "Typing saved password" should come after it checks the authentication type?

**Comment by Onepamopa** [comment]
By the way PuTTY-nd doesn't have such problems "expect/place" scripts work fine.

**Comment by Onepamopa** [comment]
@Eugeny Any info on this? Is there a fix planned? Just installed the latest version and the problem still exists:
Trying saved password
Keyboard-interactive auth requested: .........  and keeps . . . . until I enter the password manually.

**Comment by Eugeny** [comment]
@Onepamopa I haven't got around to it yet. I'm working on Terminus in my free time, which is limited.
If you would like a quick workaround and you control the server, you can change the preferred authentication type from `keyboard-interactive` to `password` in the SSH server conf.

**Comment by Eugeny** [comment]
Fixed in master
