### ISSUE TITLE
Feature Request: Console Init scripts

### ISSUE THREAD

**Issue by luckcolors** [Eugeny/tabby#181]
Hi.
I've started using Terminus recently and it's amazing! Keep up the good work! :)

The only basic feature i think it's missing is the possibility of executing scripts before starting a console tab, for example i have one where i set all of the necessary Environment variables.

**Comment by Eugeny** [comment]
Shouldn't this be solved via `.bash_profile` / `.zshrc` ?

**Comment by luckcolors** [comment]
Ah right i forgot to mention, I'm on windows.

**Comment by Eugeny** [comment]
But you still can set them via Computer Properties > Environment Variables :)

**Comment by luckcolors** [comment]
I know, but the entire point was to not edit the system wide Environment Variables.

**Comment by sylveon** [comment]
https://stackoverflow.com/questions/17404165/how-to-run-a-command-on-command-prompt-startup-in-windows

**Comment by luckcolors** [comment]
Yeah but that seems too invasive as every single cmd session on the machine would be affected.

**Comment by luckcolors** [comment]
If you feel this use case is too distant from what you want from reminus, it's all good. Feel free to close the issue in that case. :)

**Comment by Eugeny** [comment]
@luckcolors I'm going to keep it open as a feature request for now.

**Comment by kk-hiraskar** [comment]
Please implement this,
This feature is already available in many ssh clients, 
like even in PuTTY, Remote Command Option
![image](https://github.com/Eugeny/tabby/assets/19647561/4503421f-1064-498b-a2a9-1ff708235c6d)

This is just auto triggering a command as soon after login.
Their are many advantages of this:
* if we are using same server for many different works, and if we don't want any configuration to be stored in server, then this is a best way
* Open some lengthy folder path soon it's logged in
* and many, depends on user and usage.

It is just a init command to be executed, just same like PuTTY's Remote Command option.

**Comment by Eugeny** [comment]
It already exists and is called "login scripts" in tabby

**Comment by kk-hiraskar** [comment]
> It already exists and is called "login scripts" in tabby

@Eugeny 
But login scripts option in tabby seems different with regex options etc.,
Any document or link which explains how to use?

**Comment by kk-hiraskar** [comment]
@Eugeny 
I tried many things even before, here their is a lot confusion due to multiple fields expect, and another send.., 
I am sorry, but I am not getting actually.
<img src="https://github.com/Eugeny/tabby/assets/19647561/c0dbca97-9334-454d-a601-33572ca581da" width="500"/>

where I should enter script or command, in dropdown even if I don't select anything, by default Exact match already their..

**Comment by Eugeny** [comment]
No worries! You can leave "expect" empty so that tabby isn't waiting for any specific output in the terminal and our your command plus a \n line break into "send" which is what Tabby sends into the terminal

**Comment by kk-hiraskar** [comment]
Ah now got it worked. Thanks @Eugeny 

And also one more thing where I was failing is, after updating SSH connection settings, I was just closing tabby and re-opening, it was not working!
Later realized the changed settings is not getting applied and the terminals that are auto reopened are something like from cache.

Manually terminated all opened terminals in split layout, and freshly when opened new SSH connection, then login script worked like a charm :-)

Thanks @Eugeny
