### ISSUE TITLE
First opened tab has wrong font

### ISSUE THREAD

**Issue by TheBitEater** [Eugeny/tabby#1850]
The first tab I open in terminus always has an ugly font - not the one configured. All following tabs have the correct font.

First Tab:
![20191203 First Tab](https://user-images.githubusercontent.com/58459794/70026875-0968c300-15a1-11ea-93f2-0fd19ceee4b2.png)

Following Tabs:
![20191203 Second Tab](https://user-images.githubusercontent.com/58459794/70026876-0968c300-15a1-11ea-82ce-3c1fedf11575.png)

Any ideas on how to solve that?

Thank you

**Comment by yacoob** [comment]
Same behaviour here, Terminus 1.0.111 on win10. Specifically, this happens on startup if Terminus needs to restore an ssh tab. If I close that tab and open a new tab with the same connection, everything's fine.

**Comment by yacoob** [comment]
Err, correction. It's just first opened tab, or any tabs restored. Subsequent tabs are ok.

**Comment by oktayaa** [comment]
I think this happens with some fonts, not all. I remember evaluating terminus on linux first and setting a font that worked. Fancier fonts tend not to work. (Like light variants of existing fonts. Or mono variants)
