### ISSUE TITLE
[Feature request] Multi language support

### ISSUE THREAD

**Issue by StormYudi** [Eugeny/tabby#1931]
I am a developer from China, and I love this app, but it's in English, I hope it can add multiple language support, we can help to translate.

**Comment by TJ619** [comment]
Ready to help for translate in Fr :)

**Comment by cayenne17** [comment]
I am willing to help translate into French

**Comment by Paul75** [comment]
Hello,

If you want help ....

**Comment by mingzijian** [comment]
Multi language support.

> I am a developer from China, and I love this app, but it's in English, I hope it can add multiple language support, we can help to translate.

hope too!

**Comment by mingzijian** [comment]
It can be a plugin to support multi language.

**Comment by Eugeny** [comment]
Duplicate of #2538
