### ISSUE TITLE
Hotkeys to scroll the terminal

### ISSUE THREAD

**Issue by dafesata** [Eugeny/tabby#194]
Is it possible scroll up or down in the terminal??

**Comment by Eugeny** [comment]
Yes, with the mouse wheel.

**Comment by TeroBlaZe** [comment]
Can't scroll with the mouse wheel on Linux

**Comment by gonwms** [comment]
The scroll wheel only works on the terminal. it don't work on settings panels, hotkeys panel... and so on...

**Comment by gonwms** [comment]
Custom css fix de the problem: 
`.tab-content{height: 100%; overflow-y:scroll !important}`

**Comment by Eugeny** [comment]
Fixed in alpha 82

**Comment by heitorthecoder** [comment]
is there anything similar to ctrl + shift + upkey or downkey ?

**Comment by Eugeny** [comment]
No, there are no hotkeys to scroll the terminal. I just came back here and saw all the negative reactions - I honestly didn't realize that OP was asking about keyboard shortcuts 😳

**Comment by konstantin83** [comment]
Is there already a keyboard shortcut to Scroll to the Top of the terminal window?
It's really needed with a lot of lines in stdout.

**Comment by Boubou8** [comment]
+1 - mouse wheel don't work for me

**Comment by Blue-Robin-Taken** [comment]
pain

**Comment by aresstokrat** [comment]
it's not working by default in the ssh terminal of ubuntu
