### ISSUE TITLE
icon on tab for SSH connection

### ISSUE THREAD

**Issue by ak1dd** [Eugeny/tabby#1943]
It is difficult to determine which tab is what kind of connection easily.  How about a little terminal or globe icon on a window?

Version: 1.0.98
Platform: win32 10.0.18363
Plugins: none

**Comment by mgrulich** [comment]
An option to show the connection profile icon on tab next or instead of tab index would be great!

**Comment by Eugeny** [comment]
Now available in the nightly, thanks @mgrulich
