### ISSUE TITLE
Screen is clipped at bottom

### ISSUE THREAD

**Issue by andrefecto** [Eugeny/tabby#2182]
In the settings menu you can't see the whole thing because the settings go farther than the scroll.
Here is a picture:
![image](https://user-images.githubusercontent.com/899058/75369443-abd2d280-5880-11ea-8a16-bc5e34f69823.png)

Seems to happen on all of the screens in the settings.

Version: 1.0.103
Platform: win32 10.0.17763
Plugins: none

**Comment by Tarkken** [comment]
Having the same problem consistently.

Version: 1.0.106
Platform: win32 10.0.18363
Plugins: altair, clickable-links, relaxed-theme, theme-gruvbox, theme-hype, theme-windows10, title-control
