### ISSUE TITLE
pasting multiple lines between powershell tabs doesn't work properly

### ISSUE THREAD

**Issue by pvradu** [Eugeny/tabby#2311]
So, copy & paste in powershell core (v7.0.0) tabs doesn't work properly. I think it might be from the line ending, but I'm not sure.

Thing is, if I open 2 powershell windows (not Terminus) I can actually copy&paste multiple lines from one to the other (e.g. a certificate). When using Terminus and Powershell Core profile, I can't do the same.

Version: 1.0.105
Platform: win32 10.0.19041
Plugins: save-output, theme-windows10

**Comment by Eugeny** [comment]
Is this a duplicate of #1558?

**Comment by pvradu** [comment]
I'm not sure. In that bug, it's about like wrapping. In my case, it's about multiple lines. I'm trying to copy & paste a certificate and I only get the first line when I paste.
