### ISSUE TITLE
No icon for custom terminal

### ISSUE THREAD

**Issue by gigi206** [Eugeny/tabby#2315]
Icons are missing for custom terminal profile.

It would be great if we could specify a custom icon.

**Comment by washicjr** [comment]
I completely agree. I would be great to assign and Icon to a custom terminal profile. It would also be nice if the icons would show up in the tab as well.

**Comment by Natetronn** [comment]
I'd like to see this when selecting a profile and for tabs too. We can change the color of a tab but, the icon would be even better, I agree.

![terminus-select-profile](https://user-images.githubusercontent.com/582149/95667070-86e05680-0b15-11eb-898a-bdf99a54af3a.png)

**Comment by Eugeny** [comment]
Icons are now available.
