### ISSUE TITLE
SSH Keys Permission Denied

### ISSUE THREAD

**Issue by idwpan** [Eugeny/tabby#2333]
Hi, I'm having a strange problem that I haven't had before and can't figure out how to fix it.

All of a sudden, any time I try to login with SSH, it errors out with 

    Command failed: C:\Program Files\Terminus\resources\extras\ssh-keygen\ssh-keygen.exe -p -P  -N  -m PEM -f C:\Users\User\AppData\Local\Temp\f-202031-23228-1v5bj2k.2jy2
    Failed to load key C:\\Users\\User\\AppData\\Local\\Temp\\f-202031-23228-1v5bj2k.2jy2: Permission denied

I've tried reinstalling both for my user and all users, and have tried elevating Terminus to administrator, but nothing seems to work. It's weird because it's the folder it creates right before trying to access it. My user also doesn't seem to have access, and I have to go in, manually give my user full access, and then I can delete the directories in Temp\.

Any suggestions? I'd be happy to provide more information too, just let me know.

Terminus has been great for me for a while now, but just now has this one problem. Hope I can get it fixed. Thanks!

Edit: I'm on 1.0.106-nightly.0, but I upgraded from 1.0.104 or something because it stopped working then

**Comment by nipeone** [comment]
i have the same problem. the previous release can not work,so i update to alpha 105.

**Comment by DeepDarkOdyssey** [comment]
Same issue here with alpha 105
