### ISSUE TITLE
Terminus not starting without the Internet connection

### ISSUE THREAD

**Issue by amnesia-drop** [Eugeny/tabby#2371]
Unless there is an Internet connection, the app is not starting. Does this mean that the saved profiles are also saved on your servers?

**Comment by Eugeny** [comment]
There are no online features in Terminus apart from auto-updating and crash reporting.

**Comment by amnesia-drop** [comment]
Why is it starting without an Internet connection?

**Comment by aacebedo** [comment]
Same problem on Linux and alpha 120

Without internet stuck on the splash screen. 
Nothing on the debug tools too.
