### ISSUE TITLE
Duplicate SSH channel

### ISSUE THREAD

**Issue by pwwang** [Eugeny/tabby#2380]
Are we able to duplicate SSH channel using existing SSH connection? So that we don't need to enter the password again for the same server connection, just like one of the functions that XShell has.

**Comment by Eugeny** [comment]
Terminus can duplicate a tab without asking for the password if the password is saved. IS there any particular reason to why the session needs to be shared between tabs?

**Comment by pwwang** [comment]
Thanks for the prompt reply.
One of the reasons is that the server I am using is requiring a dynamic password, which is actually an RSA token that changes every minute. I need multiple connections (tabs) for daily work. But every time I open a tab, I need to open the RSA app on my cell phone and enter the password there to get a 6-digit token...

**Comment by pwwang** [comment]
Keep it alive.

**Comment by zhangyulu** [comment]
> 

that's exactly what I want, now I'm using secureCRT, it duplicates ssh channel by default so I don't need to enter password again

**Comment by jaydu666** [comment]
i need it too

**Comment by Eugeny** [comment]
This is the default behaviour already.

**Comment by jaydu666** [comment]
but it need to enter the password. create new socket, not mutiplex socket

**Comment by Eugeny** [comment]
@jaydu666 if you want a new connection instead, you can disable multiplexing in the profile settings (under Advanced)

**Comment by jaydu666** [comment]
thank you for the answer. i am sorry that i said it wrong. i think i want something like xshell duplicate ssh channl.
