### ISSUE TITLE
Ligatures doesn't seem to work

### ISSUE THREAD

**Issue by waspoza** [Eugeny/tabby#2412]
In the option window it looks good. There's the right arrow on the font preview pane:

![2020-04-15 23_20_32-Settings](https://user-images.githubusercontent.com/4631033/79390963-ee578800-7f70-11ea-8dc5-15519e2a5fc4.jpg)

But in terminal window there are no ligatures:

![2020-04-15 23_18_55-mc  root@leto _~_docker_dovecot_data_mail](https://user-images.githubusercontent.com/4631033/79391051-1810af00-7f71-11ea-9fe3-83f409b37bf2.jpg)

Terminus version 1.0.106-portable.

**Comment by Eugeny** [comment]
Which frontend are you using? Ligatures are only supported on `xterm` (non-WebGL)

**Comment by waspoza** [comment]
I tried all 3 and on my system it works only on hterm frontend. Thanks for the tip!

**Comment by subnut** [comment]
> 
> 
> Which frontend are you using? Ligatures are only supported on `xterm` (non-WebGL)

Nope. It just doesn't. It works on hterm, but not on either of the xterm modes.

**Comment by Eugeny** [comment]
Just to clarify - have you opened a fresh new tab after changing the frontend?

**Comment by Eugeny** [comment]
Ligatures are now supported in the WebGL frontend
