### ISSUE TITLE
the shell session tab will become a zombie tab after a long time to not use

### ISSUE THREAD

**Issue by leiboo** [Eugeny/tabby#2440]
the shell session tab will become a zombie tab after a long time to not use.
we can do nothing at this tab.

Version: 1.0.106
Platform: linux 4.19.5-300.fc25.x86_64
Plugins: none

**Comment by 11721206** [comment]
I meet the same problem

**Comment by Spinestars** [comment]
I had the same problem with windows10, which seems to have been around since 1.0.106.
When I don't do anything for a long time, the whole window is blank and I can't do anything.
You can only kill it from the task manager
