### ISSUE TITLE
Font ligatures completely breaks Terminus with the MesloLGS NF font

### ISSUE THREAD

**Issue by LeSeulArtichaut** [Eugeny/tabby#2493]
I recently tried Powerlevel10k and the recommanded font (MesloLGS NF) along with it. However, if I try to turn on font ligatures, Terminus doesn't display any text.

I tried running my unmodified sh or bash, but Terminus seems to recognize keyboard input (e.g running `git status` on a big repo then trying to close the window gives me the expected "git is still running" message), but doesn't display anything. As for my zsh with Powerlevel10k, I first get a colored rectangle where I'd expect the bars p10k provides, but I won't get anything else.

However, switching to another font (e.g Source Code Pro for Powerline) resolves the issue.

Version: 1.0.103
Platform: darwin 19.0.0
Plugins: clickable-links

**Comment by LeSeulArtichaut** [comment]
Seems like switching to the `xterm (WebGL)` frontend causes the same issue. Are font ligatures linked to WebGL somehow?

**Comment by LeSeulArtichaut** [comment]
Switching to the `hterm` frontend causes no issue with font ligatures activated.

**Comment by Edger** [comment]
Same issue I encountered.
