### ISSUE TITLE
Translating Tabby / multiple languages / localization

### ISSUE THREAD

**Issue by milotype** [Eugeny/tabby#2538]
Do you support translating Terminus into other languages?
If so, please let me know how (I couldn't find anything about it).
I'd  like to translate into Croatian and German.

**Comment by milotype** [comment]
Please decide, if you're going to support translating **Terminus**.
If so, I'd suggest to use a free translation system (my preference would be [Weblate](https://weblate.org/). Others: Crowdin, Transifex, …). If none of it suits you, you could implement it within GitHub and allow pull requests for translations.

Sorry, but I'm not a programmer, so I can't help to implement it ... so it's more or less a "feature request" ...

**Comment by Eugeny** [comment]
I don't have the bandwidth to invest into integrating translations right now, but I'll gladly merge translation support if someone integrates it.

**Comment by SergioSuarezDev** [comment]
I would love to provide the Spanish translation

**Comment by HaoLi-Rainbow** [comment]
I need Chinese translation, I think deepl translator is very good, you start trying to use it to do i18n
@Eugeny

**Comment by Aixzk** [comment]
I would like to provide Chinese translation :-)

**Comment by Aixzk** [comment]
我尝试了一下，如果在源码中一个个找对应文本，实在是太麻烦且费时间。于是我尝试直接替换文本（条件是在文件里是唯一的），但是不适用于一些单词，会造成 Tabby 卡在加载界面，应该是改了代码而不是文本。在这里直接使用机翻的，目前效果是这样的：

![图片](https://user-images.githubusercontent.com/80463781/145675262-75b2dea6-1bab-4a3c-9967-b70b1de6340e.png)

**Comment by 18215569765** [comment]
Can you support Chinese?

**Comment by Aixzk** [comment]
我花了一些时间将 Tabby 翻译成了中文版：[tabbyCN](https://github.com/Aixzk/tabbyCN) ，目前看起来是这样的：
I spent some time translating Tabby into a Chinese version: [tabbyCN](https://github.com/Aixzk/tabbyCN) , which currently looks like this:

![homepage](https://user-images.githubusercontent.com/80463781/148265707-2dd3a941-70c3-45e7-8c33-dae05d0ae0d7.png)

![setting](https://user-images.githubusercontent.com/80463781/148263782-f59dd765-314e-4f77-b80e-362d656b1274.png)

![ssh](https://user-images.githubusercontent.com/80463781/148267637-b4b83fd0-cadf-431f-a5c6-8983042a0691.png)

在这里 @ 一下可能想要中文版的人（若有打扰，请见谅）：
Here @ those who might want a Chinese version (Please forgive me if I disturb you):

@Yafine @China-huc-hk @not-know @wordhui @gexiaosen @mrxu0 @enjoqy @18215569765 @wxyShine @shuncon @psyuhen @kikyoulg @Starrry @GuoSongyu @lihao0324 @18215569765 @Trump-Shuai @zhaoxiaozhang @zhangxiansheng123 @tonycody @gitbeiji @17635093322 @sinohut @kikyoulg @KeKouShi

**Comment by psyuhen** [comment]
> 我花了一些时间将虎斑翻译成了中文版：[tabbyCN](https://github.com/Aixzk/tabbyCN)，目前看起来是这样的： 我花了一些时间转换成大花猫中国版：[tabbyCN](https://github.com/Aixzk/tabbyCN)，目前看起来是这样的：
> 
> ![主页](https://user-images.githubusercontent.com/80463781/148265707-2dd3a941-70c3-45e7-8c33-dae05d0ae0d7.png)
> 
> ![环境](https://user-images.githubusercontent.com/80463781/148263782-f59dd765-314e-4f77-b80e-362d656b1274.png)
> 
> ![ssh](https://user-images.githubusercontent.com/80463781/148267637-b4b83fd0-cadf-431f-a5c6-8983042a0691.png)
> 
> 在这里@一下可能想要中文版的人（若有打扰，请见谅）： 这里@那些可能想要中文版的人（请原谅我打扰你）：
> 
> @Yafine @China-huc-hk @not-know @wordhui @gexiaosen @mrxu0 @enjoqy @18215569765 @wxyShine @shuncon @psyuhen @kikyoulg @Starrry @GuoSongyu @lihao0324 @18215569haoSongyu @ lihao0324 @18215569haoSonghuat @mrxu0 @enjoqy @ 18215569765 @wxyShine @17635093322 @sinohut @kikyoulg @KeKouShi



哥，你这样改，如果官方版本更新了，你这怎么办呢。

**Comment by tonycody** [comment]
推给官方去支持多语言吧，这样搞比较难维护。没什么意义吧，我感觉！
&nbsp;




&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年1月7日(星期五) 上午8:53
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Eugeny/tabby] Translating Tabby / multiple languages / localization (#2538)





  
我花了一些时间将虎斑翻译成了中文版：tabbyCN，目前看起来是这样的： 我花了一些时间转换成大花猫中国版：tabbyCN，目前看起来是这样的：
 

 

 

 
在这里@一下可能想要中文版的人（若有打扰，请见谅）： 这里@那些可能想要中文版的人（请原谅我打扰你）：
 
@Yafine @China-huc-hk @not-know @wordhui @gexiaosen @mrxu0 @enjoqy @18215569765 @wxyShine @shuncon @psyuhen @kikyoulg @Starrry @GuoSongyu @lihao0324 @18215569haoSongyu @ lihao0324 @18215569haoSonghuat @mrxu0 @enjoqy @ 18215569765 @wxyShine @17635093322 @sinohut @kikyoulg @KeKouShi
  
哥，你这样改，如果官方版本更新了，你这怎么办呢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aixzk** [comment]
@tonycody @psyuhen 官方没有做多语言支持，目前只能这么改了，官方更新了我肯定不能马上跟着更新的，这样子改挺繁琐的，只能是大版本更新时才跟进。

**Comment by ydcool** [comment]
We're looking for a more extendable and flexible multi language solution, like what vscode does, something like the language pack.

**Comment by 17635093322** [comment]
官方可以把插件啥的库弄成平台呀……集大众之思维，软件不是会发展得更好吗


发自我的iPhone

**Comment by Eugeny** [comment]
Text is now up for translation at https://translate.tabby.sh/  🚀🚀 !

**Comment by boonkerz** [comment]
Currently i'm working on german.
