### ISSUE TITLE
Copy on selection to excel or word

### ISSUE THREAD

**Issue by hyunsuklee90** [Eugeny/tabby#2540]
First of all, thx for the development of this excellent terminal.
I really love the app experience for about an year.

I have one issue copy from terminus to excel or word. 
The copy works well generally. However, it goes wrong when I copy to excel.
It copy whole line not I only the part that I selected, and it also copy the font and colors. 

Best regards,

**Comment by Martyrer** [comment]
i have the same issue, but it occurs to me all the time regardless where i copy to.. it always copy whole line
