### ISSUE TITLE
Tab names are lost at restart

### ISSUE THREAD

**Issue by piakbt** [Eugeny/tabby#2639]
Version: 1.0.110
Platform: win32 10.0.18363
Plugins: none

Usually I have two tabs opened, I name them shell and liquibase.
But when I restart Terminus, the tabs are there, but their names are standard: MINGW64:/c/...

**Comment by vrnvorona** [comment]
Same on macos catalina

**Comment by pinpins** [comment]
Would appreciate you can make tab names for SSH connections configurable. I am using few hosts, and would like to configure short name of it, instead of using format user@hostname.

Also if I rename those manually, after restart those names get reset.

**Comment by Eugeny** [comment]
@pinpins you can disable dynamic tab title per connection - it will then use connection name as tab title instead.

**Comment by pinpins** [comment]
@Eugeny ohh, thanks! it was not obvious to find at first place. Now I see those are there in SSH advanced!

Appreciating!
