### ISSUE TITLE
Bell is audible when option is set to visual

### ISSUE THREAD

**Issue by maldrasen** [Eugeny/tabby#2640]
Version: 1.0.113-nightly.0
Platform: win32 10.0.18363
Plugins: none

Maybe I'm not understanding how the "Terminal bell" option works, but I have the bell set to "Visual" but I still hear an audible bell. I just need to open a terminal and hit backspace to make it ring.

**Comment by jhyot** [comment]
In fact, the bell is also audible even when set to "none".

My shell: WSL 1 with zsh
Terminus: 1.0.120

Reproduce:
1. Set Bell to off
2. Open WSL 1 shell
3. Type "cd" and press Tab a few times
-> A bell will be audible
