### ISSUE TITLE
Resizing window cropping content

### ISSUE THREAD

**Issue by SheepRock** [Eugeny/tabby#2653]
When resizing down a window and resizing back the contents are being cropped. Tested with powershell 7.0 and cmd. SSH seems not affected.

![erroResize](https://user-images.githubusercontent.com/20205505/83526096-4fed9a80-a4bc-11ea-9291-686f5379b17f.png)

Version: 1.0.112
Platform: win32 6.3.9600
Plugins: none

**Comment by SheepRock** [comment]
This issue is still happening.

**Comment by tlucanti** [comment]
And now this is still happening
