### ISSUE TITLE
Corrupted text 

### ISSUE THREAD

**Issue by M4N0JKUM4R** [Eugeny/tabby#2659]
First of all, thanks for this application. Makes me love working with console/terminal instead of running away from it :)

After weeks of usage, suddenly when I see this window, the text looks corrupted. Is there a workaround for this? 

![image](https://user-images.githubusercontent.com/11471878/83719309-6f1f3000-a654-11ea-9c93-3e85f049e15f.png)

**Comment by Eugeny** [comment]
Please try upgrading to the latest release.

**Comment by M4N0JKUM4R** [comment]
I upgraded it. Happens again and again. Probably when I minimize it and reopen.

![image](https://user-images.githubusercontent.com/11471878/84154411-b5292900-aa84-11ea-9bc8-5dfa77c3fb5d.png)
