### ISSUE TITLE
Vi doesnt work well via telnet

### ISSUE THREAD

**Issue by carlosyaen** [Eugeny/tabby#2663]
Version: 1.0.112
Platform: win32 10.0.18363
Plugins: none

Using vi in a virtual machine via telnet looks like the document does not refresh. The command dd (double d) to delete a line, should move 1 line up every line below the cursor and the enter botton should do the opposite. It does not. I tried the new Windows Terminal and it does fine. (just in case the TERM variable might be involve but looks it is not) I use Ubuntu 18.04 (WSL)

**Comment by cibrhusk** [comment]
I have the same issue with vim over ssh.
I'm using cygwin with terminus locally, ssh to a fedora box and use vim there.
