### ISSUE TITLE
(macOS) Opening new shell tab always uses zsh even when selecting something else

### ISSUE THREAD

**Issue by SquareBottle** [Eugeny/tabby#2721]
## Steps to Reproduce the Issue

1. Open Terminus
2. Right click on a tab and select New with profile → bash.
3. In the new tab, type `echo "$SHELL"` to find out what shell is running.  

## What I Expected

I expected the output to be `/bin/bash`, which would indicate a bash shell.

## What Happened Instead

The output was `/bin/zsh`, which indicates a zsh shell.

# Other Comments

Zsh is my default shell. It has been the default shell for macOS since Catalina came out (macOS 10.15.0), so that's not uncommon.

I happened to be trying to open a bash shell, but the result appears to be the same if you attempt to open any other type of shell.

Apologies if I'm overlooking something basic. I'm not an expert at this stuff. If this is the case, then please evaluate this as a UX issue (because I doubt I'm the only macOS user who'd expect a bash shell when following the steps I took).

Thank you for considering, and for all your other hard work!

# System Info

- OS: macOS 10.15.5
- Terminus version: 1.0.112

**Comment by peterlymo** [comment]
seems its same problem in windiw too,, whenever i am opening new tab ,, its powershell opens ehh

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
