### ISSUE TITLE
Blank terminal window

### ISSUE THREAD

**Issue by boomerling** [Eugeny/tabby#2763]
Version: 1.0.112
Platform: darwin 19.5.0
Plugins: none

If `exit` a terminal session and it's the last one, and close terminus, when I open it the text time, Terminal one is just an empty pane.  User interaction is not allowed.  Have to close and open a new shell to start.  2 extra unnecessary steps.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by boomerling** [comment]
Resolved itself after I made changes to settings and reverted back…

I click on the Developer icon, but can’t access.
