### ISSUE TITLE
Local prompt

### ISSUE THREAD

**Issue by JosselinBeaumont** [Eugeny/tabby#2782]
Version: 1.0.104
Platform: win32 10.0.17763
Plugins: altair, relaxed-theme, save-output, scrollbar, theme-gruvbox, theme-hype, theme-windows10

Hello.
When I click on the + button I can no longer open my local disk. 
The tab opens and closes immediately.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by JosselinBeaumont** [comment]
[-1594372225983.log](https://github.com/Eugeny/terminus/files/4902174/-1594372225983.log)
