### ISSUE TITLE
`clear` doesn't clear in Git Bash

### ISSUE THREAD

**Issue by naeemrashid** [Eugeny/tabby#28]
clear command does not work properly in windows 8.1. instead of clearing the terminal only cursor goes at the start of the terminal.I am using git bash as terminal.

**Comment by dejames** [comment]
same issue for me too. Neither `Ctrl+L` or `clear` works. The cursor just moves to the top of the page without clearing anything in the window.

![capture](https://user-images.githubusercontent.com/16666625/27814362-7a527e86-6099-11e7-8dca-e777e3ff6a57.PNG)

* Terminus : 1.0.0-alpha.15
* Windows : 7
* Git Bash : 2.7.0

Neither does `Alt+F8` works.

**Comment by compliment** [comment]
It's just git bash. I checked on all others.

**Comment by Eugeny** [comment]
I confirm that this is indeed only git-bash related, but I haven't been able to find a solution yet.

**Comment by PolCPP** [comment]
Same seems to happen if you run `clear` under ssh even if you start the console using cmd-clink

**Comment by gigioSouza** [comment]
The same for me.
I'm in a Windows 10 Pro, Terminus 1.0.0-alpha.14 using Git Bash.

**Comment by kattheliving** [comment]
Hi, aren't we supposed to close an issue if its resolved or if its considered a non-issue(duplicate, irrelevant etc.)?
I went through all the issues that are closed but found no solution in any of them, can't we keep one open for people to provide a solution?

**Comment by Eugeny** [comment]
@kattheliving this has been fixed in the aforementioned commit. If it still doesn't work for you with the latest version, please feel free to reopen!

**Comment by oveysrostami** [comment]
Hello
I Install Latest Version on terminus and I have same issue when using git command like git pull or others git command.

**Windows 10**

**Comment by Eugeny** [comment]
@oveysrostami what's the issue with the git commands? They don't cause a screen clear AFAIK

**Comment by ECer23** [comment]
When I'm using PowerShell as the terminal, the `clear` command works.

**Comment by oveysrostami** [comment]
> @oveysrostami what's the issue with the git commands? They don't cause a screen clear AFAIK

When I use git command ,I see just blink nothing else.

**Comment by firiceguo** [comment]
> > @oveysrostami what's the issue with the git commands? They don't cause a screen clear AFAIK
> 
> When I use git command ,I see just blink nothing else.

Hi, When I use ssh to connect to other machine, and the shell on remote is zsh (oh-my-zsh), I have the same issue, see just blink nothing else, and did not execute the command as well.
Git commands like `git pull` `git push` `git fetch` 
I checked bash shell, no bugs on my machine.

I'm using the latest version, Windows 10

**Comment by winniebosy** [comment]
I also had the same problem with clear after setting up SSH keys. However, the CTRL + L works totally fine. Anyone facing the same issue should use the above. Regards

**Comment by alindesign** [comment]
Any update there? 
I have same use with git-bash on Windows, it look like something remain cached or something like that ...
But if a scroll 1 step it disappear.

**Comment by whyboris** [comment]
I'm on Windows 10, `alpha 65` seemed to be working fine (`clear` command in _Git-Bash_ would clear the screen) but updating to `alpha 71` seemed to break the functionality: `clear` returns the caret to the top of the screen, but doesn't clear out all the previous output, eg:

![image](https://user-images.githubusercontent.com/17264277/53301960-e72e6180-3826-11e9-8a3f-3da31a2a6b9e.png)

**Comment by jdlyga** [comment]
This also happens in WSL with Ubuntu.  If you open and quit vim, the last line still appears on the screen

![Untitled](https://user-images.githubusercontent.com/4921961/57244827-4965c880-7007-11e9-916a-78990a18cfd0.png)

**Comment by mathiasgrimm** [comment]
I can confirm this still happens.
It clears the screen but jumps to the beginning then to the end of the screen while im typing. That doesn't now happen if i write `clear` but only when using Control+L

**Comment by Dawid-Ohia** [comment]
I am still having this issue. Clear and CTRL+L both have the same effect. Cursor jumps to the top o the terminal view and overwrites an existing content.

**Comment by dexter800** [comment]
Try command  reset . It works for  me.

**Comment by Pauldb8** [comment]
"clear" only goes back to the top of the screen, but does not erase anything (Win7 + git bash).
"reset" command works perfectly, this is magic !
But why ???? "clear" should work as well.
Btw both "clear" and "reset" works in SSH remotely. So must come from git bash I believe. Very nice terminal btw.

**Comment by kushal9291** [comment]
I have same issue. Was working fine just few hours ago.  However it does get clear when i scroll through.

**Comment by whyboris** [comment]
I wonder if the solution is the same as in #729, namely:

Switching to `hterm` or `xterm (WebGL)` from `xterm` (Settings | Appearance | Frontend)

**Comment by ejbulaong** [comment]
CLS

**Comment by dmitriy-pritula** [comment]
The same form me.
Win10, Terminus 1.0.108a - neither of terminal types are not cleared

**Comment by hmistry-lz** [comment]
You can set a shortcut for `Clear Terminal` under Settings -> Hotkeys.

![image](https://user-images.githubusercontent.com/53185673/82085984-6d94c480-96b3-11ea-9d26-a70673696450.png)

**Comment by fippy** [comment]
This is still an issue running Windows 10 Pro 19042.1586 with git version 2.35.1.windows.2 but only when using the terminal within VSCode. Outside VSCode, using the clear command removes the scrollback whereas CTRL+L doesn't.

Even "reset" and "tput reset" maintain scrollback (but only inside VSCode.

**Comment by damiangreen** [comment]
its also an issue outside of vscode
