### ISSUE TITLE
Option to hide tabs in fullscreen

### ISSUE THREAD

**Issue by viniarck** [Eugeny/tabby#280]
Hi, 

Is there a way to hide tabs if there's only one open? I want to save space on my screen.

Awesome project! Thanks.

**Comment by viniciusarcanjo** [comment]
@Eugeny is there a way? Thank you.

**Comment by Eugeny** [comment]
@viniciusarcanjo how exactly would that work? The window controls still need to be present, so they would either require their own bar (as right now), or overlap with the terminal content.

If you're having the window maximized, consider the fullscreen mode (#283) that hides everything except the terminal itself

**Comment by viniciusarcanjo** [comment]
@Eugeny I see. Regarding hiding the tabs, I was thinking about the same way KDE Konsole implements this feature. On Konsole, there's an option in the settings where you can set the tab bar to only show up once you've got more than one tab. As a result, you save a few pixels if you only have a single tab. 

@Eugeny F11 doesn't make terminus full screen, I'm running it on Ubuntu. I don't see any other options to redefine the full-screen shortcut. Could you shed some light? 

Thank you!

**Comment by Eugeny** [comment]
Fullscreen support isn't in the released builds yet.
Do you perhaps have your tabs on bottom as in Konsole? In this case they indeed use extra screen estate. If you keep them on top and set the titlebar to "thin" in Settings, tabs will share vertical space with the window controls

**Comment by viniciusarcanjo** [comment]
Perfect. I've changed to the top with this thin configuration. Thank you!

**Comment by bernastoc** [comment]
> Hi,
> 
> Is there a way to hide tabs if there's only one open? I want to save space on my screen.
> 
> Awesome project! Thanks.

I'm not sure why this issue was closed. While fullscreen support has been added and looks great, there's still no way to hide the tab bar. E.g. Gnome terminal and Mobaxterm both allow this, albeit each with a different method. I'm partial to the Gnome method, where F11 enables fullscreen with the tab bar, and right-clicking and unselecting 'Show Menubar' hides whatever's left of the terminal GUI.

**Comment by pkosek** [comment]
+1

**Comment by hustcer** [comment]
+99
I like to work in fullscreen mode with no tab bar at all. Thanks.

**Comment by rkitover** [comment]
Hi, thank you for your work on this, just found out about it and switched from MS terminal.

It would be even nicer if the tab bar could auto-unhide on mouse edge detection at the top of the screen, like in firefox/edge fullscreen mode.

If not, just having an option to not show it in fullscreen would be good enough for me and many other people I'm sure.

**Comment by timseriakov** [comment]
Indeed, that's the first thing I noticed - the lack of ability to hide the tab bar.

**Comment by renatocarvalho** [comment]
+1 here!

**Comment by Eugeny** [comment]
It's already implemented
