### ISSUE TITLE
Cursor does not work in nano

### ISSUE THREAD

**Issue by dust0vich** [Eugeny/tabby#2811]
Version: 1.0.113
Platform: win32 10.0.19041
Plugins: clickable-links, relaxed-theme, scrollbar, theme-hype, theme-windows10, title-control

See picture. The cursor is invisible, text entry is happening where I am indicating in the text and also at the bottom shows the location. Some times there is a phantom cursor at the end of the line, other times if I type fast enough the cursor flashes where it actually is. When using arrow keys to move you will never see the cursor. This does not happen when running in a standard cmd shell. Does not matter if I am using xterm or hterm, or if ligatures are on or off or different cursor types.

![image](https://user-images.githubusercontent.com/17212092/88346243-805bf300-cd0d-11ea-908f-30be14ee99b3.png)

Also when doing some more troubleshooting, terminal resizing does not work with nano, even if resizing after exiting nano. Kind of weird behavior. This might affect other applications also.
![image](https://user-images.githubusercontent.com/17212092/88347361-21e44400-cd10-11ea-971c-948b6f76a0c2.png)

Thanks for making a great terminal program. If you need anything else from me let me know.

**Comment by dustovich1** [comment]
Also, terminal resizing does not work with nano, even if resizing after exiting nano. Kind of weird behavior.
![image](https://user-images.githubusercontent.com/17212092/88347361-21e44400-cd10-11ea-971c-948b6f76a0c2.png)
