### ISSUE TITLE
Arrow keys and terminal sizing do not work in admin shells

### ISSUE THREAD

**Issue by dust0vich** [Eugeny/tabby#2812]
Version: 1.0.113
Platform: win32 10.0.19041
Plugins: clickable-links, relaxed-theme, scrollbar, theme-hype, theme-windows10, title-control

See picture. This happens in all admin shells. No issue in non-admin shells. Arrow keys come up as [D[A[C[B depending on which key you press, powershell core acts even weirder. xterm or hterm does not matter.

![image](https://user-images.githubusercontent.com/17212092/88346807-d2e9df00-cd0e-11ea-8ed7-a937a44d22a7.png)

You can see in this one that nano does not expand to the entire size of the window
![image](https://user-images.githubusercontent.com/17212092/88346942-33791c00-cd0f-11ea-9b95-fa83f28bbfea.png)
This one pressing enter will not go down to the bottom of the window
![image](https://user-images.githubusercontent.com/17212092/88347073-776c2100-cd0f-11ea-9f84-54d31f4a3848.png)

Thanks again

**Comment by Caligari** [comment]
+1
The admin tab is usable, if I think about it carefully, but when I'm using admin it tends to be for more dangerous tasks.

**Comment by docsav** [comment]
FWIW, I found that this doesn't happen when launching the entire Terminus application as Admin. Of course, it isn't really good practice to be running in admin all the time, but it is a workaround if needed.

**Comment by PipeItToDevNull** [comment]
This is a duplicate of #691 which appears to be closed on inactivity. FWIW, it is still an issue on 120
