### ISSUE TITLE
massive number of dns queries for sdk.split.io

### ISSUE THREAD

**Issue by Revan67** [Eugeny/tabby#2817]
So for those unfamiliar, I keep an eye on my network with an application called pi-hole and it has recorded almost 4,000 DNS queries in 1-2 minute intervals. I was able to ID the computer and then the application that was making the calls and I am fairly certain its terminus as I just installed it on the 23rd and as I said already its generated a ton of DNS queries. Is there a reason this is phoning home so much?

![2020-07-24 19_56_29-_Ethernet](https://user-images.githubusercontent.com/8174203/88445374-cbe2cf80-cde7-11ea-9616-29ab73e9c8dc.png)

![2020-07-24 19_53_43-Pi-hole - pihole](https://user-images.githubusercontent.com/8174203/88445330-78708180-cde7-11ea-903e-c233d025064f.png)

**Comment by Eugeny** [comment]
I'm not using split.io in Terminus. The optional telemetry only reports basic info (OS and version) to Mixpanel. Try disabling analytics in Settings -> Application and see if these are related.
