### ISSUE TITLE
Admin powershell tab has 120 char limit (1.0.116 nightly)

### ISSUE THREAD

**Issue by poweredbyporkers** [Eugeny/tabby#2847]
Normal powershell tab
![image](https://user-images.githubusercontent.com/3979789/88980029-27d8b700-d306-11ea-91b1-435ec6c60fcd.png)

Admin tab (wraps around 120 chars)
![image](https://user-images.githubusercontent.com/3979789/88980043-32934c00-d306-11ea-9975-18426292d958.png)

**Comment by dustovich1** [comment]
Pretty sure this is a duplicate of #2812
