### ISSUE TITLE
Feature request: retro text effects

### ISSUE THREAD

**Issue by hm72747** [Eugeny/tabby#2899]
Please add support for retro text effects like Cool retro term for linux or Cathode for mac!

![0__zAFQvkoxv95VjZa](https://user-images.githubusercontent.com/69722291/90314238-4337ea80-dee0-11ea-8838-d66c585a84aa.png)

![0_6i7gRTGXhdqMOGZ6](https://user-images.githubusercontent.com/69722291/90314240-4632db00-dee0-11ea-95a2-3d82757576ef.png)

![217824-cathode1_606_original](https://user-images.githubusercontent.com/69722291/90314245-48953500-dee0-11ea-86a9-8f1f5bcabed1.png)

![dae9a9fb65_cool-retro-term-ubuntu-ppa](https://user-images.githubusercontent.com/69722291/90314246-4af78f00-dee0-11ea-8c2a-c57f9f07469c.png)

**Comment by pquerner** [comment]
Is it possible to add external programs inside Tabby?
Like this: https://github.com/Swordfish90/cool-retro-term/wiki/Build-Instructions-(Linux)
