### ISSUE TITLE
request for german hotkey config

### ISSUE THREAD

**Issue by stefangweichinger** [Eugeny/tabby#2956]
Does someone maybe already have a working config file for a german keyboard?
For example zooming in and out does not work with `Ctrl++`  `Ctrl+-` here, and mouse zooming doesn't work at all (using the wheel).

I tried to reassign, but somehow that lead to some "infinite zoom" ;-)  will retry ...

Maybe someone has already gone through that work, I just kindly ask.

**Comment by vs1998** [comment]
I assigned <kbd>Ctrl++</kbd> and <kbd>Ctrl+-</kbd> as zoom in and zoom out. For me that was working (for german keyboard layout and no infinite zooming). Maybe try to upgrade to latest version or reinstalling. 

Also: The keybinding shown in the terminus were <kbd>Ctrl+[</kbd>(for<kbd>Ctrl++</kbd>) and <kbd>Ctrl+/</kbd> (for <kbd>Ctrl+-</kbd>) but the zoom is working as expected.

**Comment by stefangweichinger** [comment]
> Also: The keybinding shown in the terminus were Ctrl+[(forCtrl++) and Ctrl+/ (for Ctrl+-) but the zoom is working as expected.

Tried again, config file shows:

```
hotkeys:
  profile: {}
  shell: {}
  zoom-in:
    - - 'Ctrl-]'
  zoom-out:
    - - Ctrl-/
```

seems to work now, thanks. A full german hotkey file might be interesting, I wonder which other hotkeys might make sense.
