### ISSUE TITLE
[SSH] No running agent is detected, but mine is running

### ISSUE THREAD

**Issue by BenoitPoulet** [Eugeny/tabby#3013]
Hello,

I'm using Kagent for years, and i'm unable to use it with Terminus.

Tried with buid 1.0.120.

```
 SSH  Connecting to eirv-xxx-ma-logs-1

Private key auth selected, but no key is loaded


Agent auth selected, but no running agent is detected

  Host key fingerprint:
   SHA256  5b138f1ed9218dad18224c1bb5298462feb714223093255d38b6ceed5ca749de 
 X  Timed out while waiting for handshake

```

**Comment by killjoy1221** [comment]
You will need to enable the service and add your keys. If you're on windows, you can follow this guide.
https://snowdrift.tech/cli/ssh/git/tutorials/2019/01/31/using-ssh-agent-git-windows.html

**Comment by DaaanielTV** [comment]
I have got the same error, but i get the error then i connect to my Debian machine.
