### ISSUE TITLE
[SSH] "ssh -6" (ipv6 domain) support

### ISSUE THREAD

**Issue by HookeLiu** [Eugeny/tabby#3018]
It always report "ENOTFOUND" when I use the "SSH connections" button to connect a domain which recorded to ipv6. 
It looks like no way to add arguments like "-6". 
(There is no problem with "ssh -6 xxx@domain.ipv6").

Version: 1.0.120
Platform: win32 10.0.19041

**Comment by Eugeny** [comment]
This is now supported. To connect to an IPv6 host in the "quick connect" box specifically, use square brackets - i.e. `[::1234]`
