### ISSUE TITLE
ssh config more friendly

### ISSUE THREAD

**Issue by qtdwzAdam** [Eugeny/tabby#3057]
![image](https://user-images.githubusercontent.com/3243008/95547977-b66c6180-0a36-11eb-9293-18063b9d899b.png)

1. Can save username, port on default, otherwise, i have to set them evertime
2. Can it juse using ~/.ssh/config file or loading from it
3. Can copy from the exists item to quick add a connection

**Comment by function2-llx** [comment]
2 was discussed in #1528

**Comment by Eugeny** [comment]
It's been a while and now you can both change the default username / port (settings -> profiles -> advanced -> defaults), and duplicate connections.
