### ISSUE TITLE
The progress bar appeares when I was using vim, and the speed becames slow

### ISSUE THREAD

**Issue by gaoming714** [Eugeny/tabby#3062]
![Image 1](https://user-images.githubusercontent.com/7444968/95753859-cc974d80-0cd4-11eb-9475-6197dcc703c8.png)

When I use the shell normally, such as git, the progress bar returns the progress very well.

But when I use vim, the progress bar reflects the line where I am, which causes a problem, vim becomes slow.
I mean, I feel that when I change the cursor up and down in VIM, terminus will refresh the progress bar, which takes time.

I used two kinds of vim, one is vim in windows environment based on msys2, which has a slow progress bar, and the other is vim from SSH to ubuntu without a progress bar, which is very fast.

Is there any way I can use that variable to control not to use this progress bar in vim? Or you have other suggestions to improve the speed of vim. Or can you explain the relevant code, and can I try to mention PR.

**Comment by Eugeny** [comment]
Hi, the progress bar is triggered when a program outputs a string that matches the `\s\d+%` pattern (i.e. a number and a percent sign), and only when the program is not in the "alternate screen" mode (the fullscreen mode that vi/nano/etc use). It looks like the alternate screen mode isn't detected properly with msys2. Can you please try doing the same under e.g. WSL or cygwin and see if the progress bar still appears then? Also changing the "Use ConPTY" setting under Settings -> Shell could help.

**Comment by gaoming714** [comment]
Great, indeed this is the key to the problem. When I opened it with mintty, he recognized the alternate screen, and the scroll wheel can be used in the vim environment, but terminus is not available at the moment. I will carefully see if I can find a solution from mintty .
