### ISSUE TITLE
select all / copy all

### ISSUE THREAD

**Issue by fusionneur** [Eugeny/tabby#3081]
how can i select and copy all output ?

**Comment by InvisibleRain** [comment]
I assume you can do that with tmux regardless of the terminal being used.
According to [this](https://gist.github.com/MohamedAlaa/2961058) cheat-sheet, you need to:
1. Start or attach to a tmux session with `tmux` or `tmux a`
2. Switch tmux to vim-mode: `tmux setw -g mode-keys vi`
3. (Optional) Save the `setw -g mode-keys vi` part in  the `~/.tmux.conf` config file
4. Open tmux in copy mode by typing `Ctrl+b` followed by `[` key
5. Press `Space` to start selection, then move to the begining of output by pressing `gg`, and then copy into the tmux buffer with `Enter`
6. You can paste the contents of the buffer by pressing `Ctrl+b` followed by `]`

**Comment by fusionneur** [comment]
umm.. thanks for the idea .. but really we need something simple like ctrl+a or right click > select all

**Comment by InvisibleRain** [comment]
Once you set this up, this is really simple. Alternatively, you can select everything by dragging the selection to the top of the terminal and then copying everything by either right-clicking or typing `Ctrl+Shift+C`
