### ISSUE TITLE
"SSH - Keep Alive" setting not working?

### ISSUE THREAD

**Issue by Geddard** [Eugeny/tabby#3132]
Hey there, I found Terminus recently and I'm super happy with it. I'm only sad I didn't find it earlier :)

But I'm curious about the SSH Keep Alive setting, I'm working through SSH constantly in my  employer's assigned VM.
I've set the Keep Alive settings to 5000ms and count to 999 so it doesn't stop working, but if go do something else for around 10m or more, when I come back the VM connection has died and I have to wait until it times out or restart the whole app and reconnect to the ssh.

Am I doing something wrong here?

Thanks!

**Comment by Geddard** [comment]
No one?

**Comment by ninadpchaudhari** [comment]
Hey,
Generally, the server will drop the connection if the client is inactive for some time & hence the Keep Alive setting should be a good place to set the time which the client sends a message to the server, just to maintain the connection active. 
- Try setting it to 240 [Reference](Keep Alive setting)

I can see the "Keep Alive setting" seem to be correctly relaying the value to the ssh2 package terminus uses for ssh connections, I do believe setting it to 240 should be good. 
[Reference](https://www.npmjs.com/package/ssh2#user-content-client-methods:~:text=keepaliveInterval%20%2D)


Also, for your particular problem, 
have you considered using the screen utlity? [Screen-Linux](https://linuxize.com/post/how-to-use-linux-screen/)

A ssh connection might drop for multiple reasons, if you want to run the app on the screen, it is always better to start a screen session, then disconnec the screen session & hence keep it running even if the ssh connection drops.
