### ISSUE TITLE
SSH and SCP commands don't work

### ISSUE THREAD

**Issue by Usmanovsky** [Eugeny/tabby#3156]
Hello, whenever I use ssh or scp on Terminus, the connections time out. The same commands work on Windows Terminal so what's going on? How can I fix it on Terminus?

**Comment by ninadpchaudhari** [comment]
more details/steps appreciated. 
SSH & SCP seem to be working in general as expected.
What is your host ( Local / Internet/port)?
What exactly is the error? 
Do you have steps to reproduce the problems? 
which terminal does it work? CMD/Powershell /SOmething else?
