### ISSUE TITLE
Config Backup and Sync

### ISSUE THREAD

**Issue by ronappleton** [Eugeny/tabby#3164]
Fantastic work, terminus is great.

I was wondering if it's possible to move the config.yaml to a config folder or something similar.
Just so its possible to use tools like google drive to backup up the config to prevent loss.

Cheers

**Comment by coLATin** [comment]
before the sync function, I have to push github private depo, hmmmm.....

**Comment by starxg** [comment]
[terminus-sync-config](https://github.com/starxg/terminus-sync-config)

**Comment by cburkins** [comment]
@Eugeny I really like the idea of the config sync, and I'm trying to get it working between Windows client and Web client.   I've got the same config loaded in both locations ("Tabby Config 01" in my case).   But doesn't seem to be syncing my "Profiles & Connections".   Is it supposed to ?

**Comment by cburkins** [comment]
Holy cow, you're responsive !  Loving this tool so far BTW.   I move desktops alot (Mac, Windows, Linux), and having a consistent terminal/profile experience is very exciting to me.    Let me glance and Devtools, and get back to you.

**Comment by cburkins** [comment]
![image](https://user-images.githubusercontent.com/9342308/146212819-01df5c54-1626-4dfd-b361-86c0fecf1cd1.png)

**Comment by cburkins** [comment]
Any easy way to see what's in the config sync itself ?  This is my first time through this, I'm happy to re-create either my "Profiles & Connections", or my Config to "refresh" it.

**Comment by Eugeny** [comment]
Oh just to be clear, you don't need to set up sync in the web version - configs are already in the cloud. You just select the one you want via the "configs" button in the sidebar.

**Comment by Eugeny** [comment]
Are settings other than profiles getting synced?

**Comment by cburkins** [comment]
> 

That's helpful, troubleshooting now.

**Comment by cburkins** [comment]
I cleared the Config Sync on the web version by clearing this field (see below)
I cleared the Config Sync on the web version by clearing this field (see below)

![image](https://user-images.githubusercontent.com/9342308/146218496-b06fffaa-567c-40c3-90ec-36745ca2407a.png)


Per your point, I can open the configs on web version, and still see them (see below)

![image](https://user-images.githubusercontent.com/9342308/146218787-0445798c-6ec8-40c7-b800-8c5162dcd912.png)


Here's my Windows desktop client, with the same config selected. also clicked upload:

![image](https://user-images.githubusercontent.com/9342308/146218994-b34ebfe8-10e0-44b2-ae2b-79e7ab620b3f.png)

And on my desktop client, I can see my profiles defined within my config file.

![image](https://user-images.githubusercontent.com/9342308/146219148-05a2c36a-c2b1-49da-afcf-23cc640182fe.png)

But these same profiles are not showing up on my web config file (see below)

![image](https://user-images.githubusercontent.com/9342308/146219464-d5f0bd6f-ba0c-413a-87f3-6de2a8dfa1da.png)

**Comment by Eugeny** [comment]
Looks like it's just not syncing at all - are you getting a "config uploaded" notification when clicking "upload"? If not, check the devtools console in the app itself.

**Comment by cburkins** [comment]
Yes, I'm getting a brief "config uploaded" confirmation, see screenshot below.

(how do I open devtools in a desktop electron app, as F12 doesn't work)

![image](https://user-images.githubusercontent.com/9342308/146220124-9f92b8c2-85b5-4797-92ac-16bf4ff2337a.png)

**Comment by Eugeny** [comment]
> (how do I open devtools in a desktop electron app, as F12 doesn't work)

Settings -> Application -> Devtools

**Comment by cburkins** [comment]
That's fun !

I don't see any obvious problems.

![image](https://user-images.githubusercontent.com/9342308/146223200-e1f22116-a515-4f69-9649-2b13cccb4c4b.png)

**Comment by Eugeny** [comment]
I don't see any issues either. On the server side, there's some config in the "01" profile but "02" is absolutely empty. Do you think you could back up your config and try with a fresh one to see if it gets pushed successfully?

**Comment by cburkins** [comment]
What does "fresh one" mean in this context ?   I think you mean a new config ?   And I think I can only create a new config via the web version, do I have that right ?

**Comment by Eugeny** [comment]
Yes, but on the client side - you can close the app, move away / rename your config file, and set up sync again, pushing it as a separate config.

**Comment by cburkins** [comment]
Oh, I see, you'd like me to blow away my local config completely, I see.  Good idea, I can do that.  Where does it get stored on Windows 10 ?

**Comment by Eugeny** [comment]
`%APPDATA%\Tabby`: https://github.com/Eugeny/tabby/wiki/Config-file

**Comment by cburkins** [comment]
I'm in the process of creating a new config for my local Windows Tabby app, and see this error now.  Unsure exactly when this happened, but figured I would share

![image](https://user-images.githubusercontent.com/9342308/146239754-ce46a516-232f-48ba-b396-1f3b566f2136.png)

**Comment by Eugeny** [comment]
This just looks like an incorrect/empty sync auth token - not harmful

**Comment by cburkins** [comment]
This is what I did:

1.  Shutdown my local windows app
2. Removed all config.yaml* files (there were three of them....  )
3. Started local app again
4. Created "Tabby Config 03"
5. Created a new profile
6. Uploaded
7. Went to Web app
8. I can see "Tabby Config 03" (see screenshot)
9. But my config file still looks empty on web

![image](https://user-images.githubusercontent.com/9342308/146240344-a686433f-e786-46c0-a387-dc7389538a9a.png)

**Comment by cburkins** [comment]
At one point during my initial use, I briefly turned on Vault with a master passphrase, but have since deleted that passphrase to keep things simple.

**Comment by cburkins** [comment]
With the Console sidebar open, I can now see more messages, namely that it looks like my configs are being downloaded, and the JSON appears empty.

![image](https://user-images.githubusercontent.com/9342308/146251428-33d801ac-d867-4d98-92ea-79f446841af6.png)

**Comment by cburkins** [comment]
Can also now see the outbound network connection/call when I click upload.  I clicked "Upload" next to "Tabby Config 03", but looks like it's sending all my configs, and they're all empty.

![image](https://user-images.githubusercontent.com/9342308/146252606-1ae44609-eb17-4074-b89e-f50a1a4151c3.png)

**Comment by Eugeny** [comment]
The request on the screenshot is where it's downloading and checking existing configs before uploading yours - there should be a separate `PATCH` request going out when you press Upload.

**Comment by cburkins** [comment]
I can double-check, but I don't think that's happening.

**Comment by Eugeny** [comment]
Holy shit I screwed up. Config sync used to be an experimental feature hidden behind the `enableExperimentalFeatures` config flag. I've removed these checks everywhere except for the config upload button. Add `enableExperimentalFeatures: true` to the end of your current config file and you're good.

**Comment by cburkins** [comment]
Yup !   Enabled on both native clients, and it's working nicely !  I can also see the PATCH api call going through now.     No worries, we all make mistakes :).   Happy Holidays !
