### ISSUE TITLE
Cannot run 'mtr 1.1.1.1'

### ISSUE THREAD

**Issue by nanedi** [Eugeny/tabby#3211]
Version: 1.0.98
Platform: win32 10.0.19042
Plugins: none

Cannot run 'mtr 1.1.1.1'

**Comment by dysondi** [comment]
You need to install that tool in your OS, it is not terminus problem

**Comment by kudouyuzi** [comment]
```
root@me:~# mtr 1.1.1.1

[SSH] Could not connect to the X server :6000: Error: connect ECONNREFUSED 127.0.0.1:6000

(.:2275): Gtk-WARNING **: 15:17:36.787: cannot open display: localhost:10.0
```

This is the error code

**Comment by dysondi** [comment]
Try to connect using another ssh client like putty 
will there be the same error?

**Comment by kudouyuzi** [comment]
No, I cannot copy the same issues on that putty.
