### ISSUE TITLE
ssh  : X  Handshake failed: no matching client->server HMAC

### ISSUE THREAD

**Issue by dhrxyz** [Eugeny/tabby#3262]
hi,

thanks for doing incredible work here, absolutely love the design aesthetics and what you do has lived to your aim - it indeed is the best terminal emulator I've seen so far. Absolute best.

I need help in fixing this problem : or identifying why its happening. In one of the main servers (jump server) I tried connect to I am getting this error : while same server tried through PuTTY, MobaXTerm, or WSL terminal, or even Windows CMD works fine. 

**Agent auth selected, but no running agent is detected

 X  Handshake failed: no matching client->server HMAC**
 
 
I have spent well over a day trying different combinations even tweaking index.js under terminal-ssh but to no avail - I'm no javascript guy so that didnt help. Just going by the literal error thrown I went to check 

ssh -Qmac (and all other combinations) there are MANY overlaps between the Terminus client HMAC and the Server HMAC (I am finding out server HMAC by ssh -Qmac _after_ connecting to the server through other terminals)

Please help! I really want to use this terminal and jump is the main server to be able to connect to before I do! Thanks

**Comment by Eugeny** [comment]
Have you already tried enabling additional HMAC algos in the advanced tab of your connection's settings?

**Comment by dhrxyz** [comment]
Hi, yes all of the algos are enabled : but it says handshake failed. 

Putty and other things work though...

**Comment by dondia-lab** [comment]
Hi! same problem...

**Comment by alexw1982** [comment]
most likely you are using stronger hmac algos. In my testing I had to unfortunatly add ```hmac-sha2-512``` to the ssh config on the server. Ideally Terminus would support stronger configs such as:

``` MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com ```

These MACs have been supported in openssh since 6.2 ... released in 2013.

**Comment by dhrxyz** [comment]
latest tabby allows for chacha poly cipher that is making it work now. 

Thanks a lot Eugeny, also xferred 10 USD as a token of appreciation for your work.

One more request, can we make the show "recent connections" in profile tab as configurable to user choice please? 

IT is very painful for some users like me to see the recent ones - we work with muscle memory on which connection,  I want to go to (say 3rd from top or 2nd etc) but this goes in total disarray with any number of recent connections showing up at top throwing our memory to disarray
