### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by suban1597** [Eugeny/tabby#3281]
"New Terminal" and "New Terminal with Profile" 
Can't work

https://user-images.githubusercontent.com/59216475/103476743-fbf8ba80-4dea-11eb-80ad-5bf65b8002cf.mp4

https://user-images.githubusercontent.com/59216475/103476757-103cb780-4deb-11eb-851d-6fa6ec6b1a94.mp4

Version: 1.0.123
Platform: darwin 20.2.0
Plugins: none

**Comment by DucretJe** [comment]
Same issue on Big Sure 11.1 (intel CPU)
Reverting to 1.0.122 fixes the issue.

**Comment by wenbingzhang** [comment]
Version: 1.0.125  Still unable to use

**Comment by ducretje-evooq** [comment]
@suban1597 can you edit your post's title for a more explicit one please?

**Comment by DucretJe** [comment]
@suban1597 can you modify your post's title for a more explicit one please?

**Comment by Dirdmaster** [comment]
I'm confirming what's @DucretJe is saying
I'm also on Big Sure 11.11 (intel CPU)
Reverting to 1.0.122 also fixes the issue for me.

**Comment by StormYudi** [comment]
Same problem here.
MacOS BigSur 11.1 (MBA mid 2020, intel i5)

**Comment by caodaqian** [comment]
Same like problem on Win10 19042.685  (intel CPU)
Reverting to 1.0.122 also fixes the issue for me.

https://user-images.githubusercontent.com/29157472/104265063-be212380-54c7-11eb-96ed-a4d907ef9139.mp4
