### ISSUE TITLE
Start Terminus in Background

### ISSUE THREAD

**Issue by nofunatall** [Eugeny/tabby#3307]
Is there a way to start Terminus in the background?

Either via a settings/config file option or a shortcut target switch like: 
"C:\Program Files\Terminus\Terminus.exe" --background

If this functionality is not already available I think it should be submitted as a feature request as this is very useful especially when you have the terminus set to start on boot.

**Comment by diegodario88** [comment]
I would love to see this feature. Or at least a flag to start terminus minimized or docked, anything that hides terminus when I boot my machine.

**Comment by Eugeny** [comment]
This has actually been long implemented (`tabby --hidden`)
