### ISSUE TITLE
Icon's not showing correctly

### ISSUE THREAD

**Issue by B4tuhanY1lmaz** [Eugeny/tabby#3346]
I am looking for a good terminal emulator and i find the terminus and i installed it to my computer but there is a problem for me. I am using the nerd fonts and powerlevel10k theme with oh-my-zsh but i can't get the icons showing correctly in terminal, i changed the default fonts for terminal but problem is still going. I hope this problem can be solved in next release.
Here is a screenshot:
![Screenshot_20210117_232613](https://user-images.githubusercontent.com/70820809/104855097-d2c44800-591b-11eb-8c62-423df3cdd702.png)

**Comment by Manas73** [comment]
I am facing the same issues. 

I am using Fish with starship prompt and colorls.

**Comment by Eugeny** [comment]
Please post the specific font file you're using in both terminals and a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

**Comment by Oxicode** [comment]
anything news?
