### ISSUE TITLE
Backspace / Delete issues

### ISSUE THREAD

**Issue by HTonieto** [Eugeny/tabby#3409]
When using SSH to access some devices the backspace don't work, and the delete key returns: ~ 

In PuTTY you can fix this issue changing the keyboard from **Control-?(127)** to **Control-H**, but i didn't find this option in Terminus.

Any suggestions?

Version: 1.0.130
Platform: win32 10.0.19042
Plugins: none

**Comment by tmalaher** [comment]
See #5862

**Comment by Eugeny** [comment]
Tracking in #5862
