### ISSUE TITLE
Terminus can't connect to remote host with ssh-dss key

### ISSUE THREAD

**Issue by eugenov** [Eugeny/tabby#3430]
Hello!
Terminus 1.0.132
Platform: Win10
I get this error while linux (WSL) connects normally with "PubkeyAcceptedKeyTypes=+ssh-dss" in .ssh/config:
```
 X  Error while signing data with privateKey: error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM

 SSH   X  Remote rejected opening a shell channel: Error: Not connected
```
Seams like https://github.com/SchoofsKelvin/vscode-sshfs/issues/162, no?
CYPHERS -> Host key -> ssh-dss checked.

UPD: Terminus 1.0.134 the same.

**Comment by xgone** [comment]
I have the same problem

**Comment by An0nymous0** [comment]
same problem

**Comment by eugenov** [comment]
Strange thing: my issue dissapeared and not showing now. But I'll keep issue open as community has the same.
