### ISSUE TITLE
Configure default profiles

### ISSUE THREAD

**Issue by KalixWolf** [Eugeny/tabby#3518]
It would be great to have the ability to configure or remove default shell profiles. Currently The list of profiles is cluttered and if you need to configure, say, your default powershell profile you'd have to make a new profile, but since there's already a default profile called powershell you would have to name the custom profile something else. Additionally the powershell default profile you never want to use is just cluttering up the list of profiles.

In my opinion just having the default profiles show up under Saved Profiles and allow them to be configurable like custom profiles would be enough. Even if I had to edit a file to change them I would be fine with that.

On a related note, it seems weird to have (for the default profile on new tabs) to have a default entry that points to an existing profile (i.e. `Default (WSL / Default Distro`) as well as the entry it points to. That's a minor nitpick though.

**Comment by Eugeny** [comment]
Do you think having an option to just disable the default profiles from appearing in the list would be fine? 
The full list is useful for casual users since they just use `cmd` everyday and select another built-in profile from the list occasionally. And the power users would be able to just have their custom list with no built-in profiles in it.

The reason there is a "Default" option is so that it can be the cross-platform default that always resolves to something installed & usable.

**Comment by KalixWolf** [comment]
I think that's a good compromise, it strikes a good balance between casual usage and extra control.

**Comment by clarkwang** [comment]
To me the pre-built profiles are quite handy. How about this &ndash;

* Get rid of the `Default Profiles` terminology though pre-built profiles are still included in Terminus release.
* Get rid of the `Show default profiles in the selector`
* Rename `Saved Profiles` to just `Profiles`. The pre-built profiles are also listed here but the user has full control on them (clone/edit/delete/reorder).
* Rename `Profile (Default profile for new tabs)` to just `Default profile` (or `Default profile for new tabs`).
* For `+New profile`, get rid of the dropdown popup menu. It'll just create a new custom profile.

![image](https://user-images.githubusercontent.com/157076/109654311-04783200-7b9d-11eb-8519-099985c9a766.png)

**Comment by cjerrington** [comment]
I use PowerShell a lot and it pulls my system profile, which is fine. I've played with creating other profiles, but it still pulls the system profile. Would this idea also allow Terminus to use a specific profile in Powershell, Bach, etc and not the system profile?

**Comment by Eugeny** [comment]
Update: the latest nightly now includes a revamped profile management system:
* Local, SSH and serial profiles merged into a single editor
* Local profiles now can be grouped
* Support for custom icon, color and title settings for all three profile types
* Profile templating
* Global shell/args/env/working dir settings removed in favour of just creating a profile

I think is a good middle ground solution for both @clarkwang's and @KalixWolf's workflows - you can either keep built-in profiles enabled, or disable them and only customise the necessary ones as custom profiles.

The "new profile" still shows a selector as it's particularly important for Windows, where you need a whole bunch of base options to run e.g. Clink or Git-Bash.
