### ISSUE TITLE
the bottom of terminus hides behind taskbar

### ISSUE THREAD

**Issue by TheBadZhang** [Eugeny/tabby#3522]
when i dock the terminus on the right of screen, i cant see the bottom of terminal. although it can be solved when i hide the taskbar or move taskbar to other directions. but i wont di this.

OS: Windows 10 20H2 19042.746
Terminus: 1.0.134
Scrren: 4k

**Comment by TheBadZhang** [comment]
im also using a software `TranslucentTB` to change the style of taskbar, i dont know whether it cause the problem.

**Comment by clarkwang** [comment]
I can repro this on macOS (Big Sur). See the attached screenshot. The Terminus' windows is overlapping with macos' Dock.

![image](https://user-images.githubusercontent.com/157076/109475527-cac9fd00-7ab0-11eb-83ef-54b80c81992d.png)

**Comment by Kalabasa** [comment]
Can replicate on Windows 10 and vanilla taskbar.

![image](https://user-images.githubusercontent.com/3705081/152284587-6b09ac05-ad1e-4e2c-b1b7-1cd66697a1d3.png)

**Comment by shapez0r** [comment]
Still there on WIn11 24H2
