### ISSUE TITLE
搜狗输入法中文状态下输入的文字不能显示，而微软输入法没有此问题

### ISSUE THREAD

**Issue by bpefei** [Eugeny/tabby#3656]
Version: 1.0.135
Platform: win32 10.0.18363
Plugins: none

希望能够得到解决

**Comment by clarkwang** [comment]
Confirmed on win10. Microsoft and Google's IME (Simplified Chinese) all work fine but with Sogou IME I cannot input any Chinese chars.

**Comment by bpefei** [comment]
这个问题应该可以close了，我自己发现了解决办法：

Windows Terminal也出现了类似的情况，输入汉字正常，但不能输入汉字标点符号，我找到了这个帖子：
https://zhiqiang.org/it/windows-terminal-cannot-type-chinese-punctuations-in-ssh.html

这里面说不能输入中文是Win10自带SSH版本太低的问题，我按照帖子里的方法，下载了新版OpenSSH，果然在Windows Terminal中和Terminus中的SSH都可以用搜狗输入法输入中文了

该帖子说不知如何更新自带SSH，我想了个办法：把旧版SSH从环境变量里撤掉，新版的加上去

**Comment by bpefei** [comment]
这个问题应该可以close了，我自己发现了解决办法：

Windows Terminal也出现了类似的情况，输入汉字正常，但不能输入汉字标点符号，我找到了这个帖子：
https://zhiqiang.org/it/windows-terminal-cannot-type-chinese-punctuations-in-ssh.html

这里面说不能输入中文是Win10自带SSH版本太低的问题，我按照帖子里的方法，下载了新版OpenSSH，果然在Windows Terminal中和Terminus中的SSH都可以用搜狗输入法输入中文了

---------------------------------------------------------------------------------------------------------------------------------------------
关闭问题好像关早了，上述方法并不稳定，时灵时不灵

**Comment by bpefei** [comment]
按上述方法操作后，从右上角的小图标那里连接SSH就能用搜狗输入法输入中文，从主界面中下方的长条图标处连接，就不能输入

**Comment by youyiqin** [comment]
不连接 ssh 也不行，老版本是可以的。

**Comment by MasterOfStar** [comment]
Translation:Not display the text entered in Chinese when use Sogou Input Method , while Microsoft Input Method does not have this problem

**Comment by JiangBoy** [comment]
我也遇到了一样的问题，目前更新的版本是v159，刚更新到v159的时候  百度输入法还能进行中文输入，过了半天之后，中文输入法输入的文字就不显示了，重启电脑也没用，你那边目前有解决方案了嘛？

**Comment by Eugeny** [comment]
Sogou input is now supported in the latest Tabby release.

**Comment by JiangBoy** [comment]
> Sogou input is now supported in the latest Tabby release.

Unfortunately, I used the latest version(v1.0.161) and still reproduced

**Comment by Eugeny** [comment]
@JiangBoy please include your OS version

**Comment by JiangBoy** [comment]
> @JiangBoy please include your OS version
i update to v164, A few hours after the update is complete, the Chinese can enter normally, and after a while Chinese input method invalid again
![image](https://user-images.githubusercontent.com/12654896/142790466-8400658d-e48c-4862-9dc7-2ee4e0dc2578.png)

**Comment by huc-1296** [comment]
![image](https://user-images.githubusercontent.com/68998432/150921862-1d050ef9-7daa-40bc-bacd-76573edca3b1.png)
这个版本搜狗输入法还是无法输入中文

**Comment by huc-1296** [comment]
1.0.170这个版本搜狗输入法还是无法输入中文
