### ISSUE TITLE
Terminus struggles to connect to legacy SSH server using password authentication method

### ISSUE THREAD

**Issue by robpomeroy** [Eugeny/tabby#3678]
I can't log in to some legacy CentOS 6 servers using a stored password. (Key-based and interactive mode work fine.)

**Terminus version:** 1.0.135
**Remote server sshd version:** OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

Terminus session output

```
 X  All configured authentication methods failed

 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH  172.16.2.2: session closed
Press any key to reconnect
```

DevTools output:

```
[ssh] Server does not support auth method keyboard-interactive
[ssh] Server does not support auth method hostbased
[ssh-172.16.2.2-22]  X  Remote rejected opening a shell channel: Error: Not connected
```

`/var/log/secure` on remote server:

```
Apr  7 11:39:10 foohost sshd[3100]: Received disconnect from 172.16.0.1: 11:
```

It's a pity because I've only just discovered (and fallen in love with) Terminus. Any suggestions?

**Comment by thaikolja** [comment]
I have the exact same problem. The built-in SSH feature won't connect whereas `ssh <user>@<ip>` and then the password works fine.

However, unlike OP, using a private key won't connect as well, displaying the same error message.

```
Version: 1.0.136
Platform: darwin 20.3.0
Plugins: none
```

**Comment by Eugeny** [comment]
Could you please test the latest nightly and enable all key exchange algorithms on the "Ciphers" tab in the profile settings? The oldest I could test with was `openssh-server-5.3p1-104.el6_6.1.x86_64` / `openssl-1.0.2k-12.el6.x86_64` and it works when enabling DH group 1 key exchange algorithm.

**Comment by robpomeroy** [comment]
Hi Eugeny. The bug seems to have gone away. I am using the same version of Terminus/Tabby and connecting to the same server. It now logs in without issue. The remote server has not been changed since I originally posted here.

The only thing I can think that's changed significantly is Windows. Does Tabby call a DLL? The Windows SSH version is `OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2` and its timestamp is 17 May 2021, which is after I logged this issue.

I don't know about @thaikolja, but I can no longer reproduce the issue.

**Comment by Eugeny** [comment]
Weird. Tabby's SSH implementation is completely self-contained.

**Comment by robpomeroy** [comment]
In that case I cannot explain it. Apologies for the trouble. I have now upgraded to the latest release.

I don't like bugs that "go away on their own". It makes me nervous. 😂

Again, thank you for this excellent application.
