### ISSUE TITLE
Substantial memory leak in local shell

### ISSUE THREAD

**Issue by decryptedchaos** [Eugeny/tabby#3786]
There is a memory leak causing RAM registers to not be cleared when using local cmd shell. 

My guess is,  the buffer log isn't being released from memory,  but I could be wrong.

You can reproduce this by opening many cmd shells and ping -t your gateway for a couple hours and you'll see the process eats 1MB every few seconds.

**Comment by Eugeny** [comment]
You can now reduce the amount of lines kept in the scrollback buffer in Settings -> Terminal.
