### ISSUE TITLE
Cannot start WSL with -u argument

### ISSUE THREAD

**Issue by CJ1169** [Eugeny/tabby#3877]
Near vanilla install on Win10.
Screenshot of console logs:
![image](https://user-images.githubusercontent.com/48484105/119002605-a284c880-b952-11eb-8638-a899e9dddb3e.png)
text log:
[console logs 1.txt](https://github.com/Eugeny/terminus/files/6516948/console.logs.1.txt)

Clearing arguments field allows wsl startup as expected. cmd prompt with wsl -u redacted starts as expected.

**Comment by Eugeny** [comment]
`-u` and its parameter are two separate arguments - you should add them as two items.
