### ISSUE TITLE
Restoring history brakes with editors

### ISSUE THREAD

**Issue by ghost** [Eugeny/tabby#3893]
When I have restore previous terminal tabs on and I closed the last tab inside an editor like vim, this happens:
![Screenshot from 2021-05-24 09-53-03](https://user-images.githubusercontent.com/70115516/119380656-dd9a3b00-bc75-11eb-88c7-ec7b7f696c9d.png)
I would expect it to at least restore the history with *exiting* the editor, because this just looks... broken.

**Comment by Eugeny** [comment]
Should be fixed now as history recovery now ignores the alternate buffer.
