### ISSUE TITLE
Terminus not working with MFA

### ISSUE THREAD

**Issue by UrsUbigfoot** [Eugeny/tabby#3935]
I attempted to connect to a new server that requires MFA for authentication and it's not working.
Normally it should prompt for cred (this part work) and to select if you want a push notification on the MFA app or send an SMS with a code. The second part is not working.
Timed out while waiting for handshake
 SSH   X  Remote rejected opening a shell channel: Error: Not connected
If I open a tab and ho ssh user@server_name I get prompted for creds. I enter the creds and then I get prompted for the MFA options and login is successful.

**Comment by myselfghost** [comment]
Terminus not working with MFA, I have the same problem

**Comment by tongjingcheng** [comment]
Tabby is not working with MFA, I have the same problem

**Comment by nulinuli-nuli** [comment]
Tabby is not working with MFA, I have the same problem
connect to dev server not set MFA can connection success，pro server have MFA can not connect
