### ISSUE TITLE
Support Linux ARM

### ISSUE THREAD

**Issue by hmsjy2017** [Eugeny/tabby#3947]
I tried to install it on my Raspberry Pi. Unfortunately, the deb you provided only supports the amd64 architecture.

**Comment by hmsjy2017** [comment]
Travis CI already supports building on the arm64 architecture. I think it might be a good choice to use Travis CI to compile software that supports Raspberry Pi.

**Comment by Joshndroid** [comment]
I would like to see an arm64 package for rpi4 as well

**Comment by hmsjy2017** [comment]
@Joshndroid I successfully compiled it and packaged it as a deb. 
https://github.com/hmsjy2017/tabby/releases/tag/v1.0.153-nightly
You can install it via [Raspbian Addons](https://github.com/chunky-milk/raspbian-addons) as well.

**Comment by Joshndroid** [comment]
Awesome thanks ill give it a crack :)
