### ISSUE TITLE
[SFTP] trying to enter a folder crashes Terminus

### ISSUE THREAD

**Issue by IrwenXYZ** [Eugeny/tabby#3982]
on the latest nightly, trying to click into a folder causes the entire client to hang. only able to close it through Task Manager. DevTools doesn't show any logs at all.

### Expected behaviour:
client enters the folder & shows the content within the folder

### What happens:
client hangs & becomes unresponsive.

### How to reproduce:
1. SSH into a server
2. open the SFTP panel
3. click once on any folder

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by IrwenXYZ** [comment]
This is all I'm seeing. No errors or anything

```
[ssh-192.168.0.4-42800] Host key fingerprint:
[ssh-192.168.0.4-42800]  SHA256  260d041f3b45183751c0a5bc8006ed7e5fb1f44925d0e577f32e1ae69b4eb8f4 
[ssh] Handshake complete: {kex: "ecdh-sha2-nistp256", serverHostKey: "ssh-ed25519", cs: {…}, sc: {…}}
[ssh-192.168.0.4-42800] Loading private key from  E:\SSH\privatekey 
(27) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
```

**Comment by Eugeny** [comment]
Could you please retest with the today's nightly? Thanks.

**Comment by IrwenXYZ** [comment]
@Eugeny Just downloaded the nightly & tried it, still the same issue. Same output on DevTools, but without the last line.

**Comment by lfkdev** [comment]
I'm also facing this issue, using the installed windows version. Dev Tools shows nothing, feels like it crashes completly before getting the chance to log something.

**Comment by watchingfun** [comment]
me too,   
version: tabby-1.0.155-portable,   
The problem occurred after I followed the prompts[vim ~/.bash_profile](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting)

**Comment by watchingfun** [comment]
me too,   
version: tabby-1.0.155-portable,   
The problem occurred after I followed the prompts[vim ~/.bash_profile](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting)

**Comment by watchingfun** [comment]
> me too,
> version: tabby-1.0.155-portable,
> The problem occurred after I followed the prompts[vim ~/.bash_profile](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting)

undo vim ~/.bash_profile then SFTP does not crash

**Comment by Eugeny** [comment]
Thanks - I've updated the [wiki page](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting) with the fixed PS1 value for Bash
