### ISSUE TITLE
Hotkey setter treats backtick as tilde.

### ISSUE THREAD

**Issue by Kalabasa** [Eugeny/tabby#4006]
Using a backtick in hotkeys doesn't work because it gets converted into a tilde.

For example, if you want `` Ctrl + ` `` as the toggle key, it will be registered as `Ctrl + ~`.

Editing the config file directly works as a workaround.

**Comment by Eugeny** [comment]
Which OS and locale is this?

**Comment by Kalabasa** [comment]
MacOS Big Sur
US English Keyboard

**Comment by dbarbuzzi** [comment]
Same thing happened for me on Windows 10 Pro 20H2 with an en-US keyboard and locale (tilde is Shift+Backtick).

**Comment by dcm** [comment]
Same, Win10, en-us keyboard.
