### ISSUE TITLE
npm scripts not working

### ISSUE THREAD

**Issue by subhamBharadwaz** [Eugeny/tabby#4057]
When I run any scripts like  ***yarn start***, ***npm run dev***, it just skips that. Any solution? 
![Untitled](https://user-images.githubusercontent.com/72348711/123455527-6c94cd00-d5ff-11eb-9ad8-6a407d0c1b01.png)

**Comment by tomnguyen0811** [comment]
I also get the above error after update version of the Terminus.
Lets trying set Run as administrator to a tab, and run the NPM scripts in it.

![image](https://user-images.githubusercontent.com/66505105/123927000-a1fe3980-d9b6-11eb-88de-53a39cd582de.png)

**Comment by liaohui5** [comment]
> When I run any scripts like _**yarn start**_, _**npm run dev**_, it just skips that. Any solution?
> ![Untitled](https://user-images.githubusercontent.com/72348711/123455527-6c94cd00-d5ff-11eb-9ad8-6a407d0c1b01.png)

I also encountered the same problem, have you solved it?

**Comment by liaohui5** [comment]
I tested it, and you can run npm scripts with cmd, but you can't run them with git-bash, which is too uncomfortable

**Comment by liaohui5** [comment]
> When I run any scripts like _**yarn start**_, _**npm run dev**_, it just skips that. Any solution?
> ![Untitled](https://user-images.githubusercontent.com/72348711/123455527-6c94cd00-d5ff-11eb-9ad8-6a407d0c1b01.png)

the latest version fixed this bug

https://github.com/Eugeny/tabby/releases/tag/v1.0.145

**Comment by subhamBharadwaz** [comment]
> 
> 
> > When I run any scripts like _**yarn start**_, _**npm run dev**_, it just skips that. Any solution?
> > ![Untitled](https://user-images.githubusercontent.com/72348711/123455527-6c94cd00-d5ff-11eb-9ad8-6a407d0c1b01.png)
> 
> the latest version fixed this bug
> 
> https://github.com/Eugeny/tabby/releases/tag/v1.0.145
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Release Alpha 145 - The Big Profiles Update · Eugeny/tabby](/Eugeny/tabby/releases/tag/v1.0.145)**New profile settings
> > The new "Profiles" settings tab unifies all profile types in a single settings UI:
> > Groups, hotkeys, colors, tab icons, title settings and login scripts are now available for ...

Yes! The latest version solved the issue
