### ISSUE TITLE
New Tab, closing itself

### ISSUE THREAD

**Issue by smultar** [Eugeny/tabby#4058]
Version: 1.0.142
Platform: win32 10.0.19043
Plugins: clickable-ips, scrollbar

Creating a new tab instantly closes.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by ItsGosho** [comment]
The terminal, which is selected by default is creating that problem.

**Comment by smultar** [comment]
It for sure was the terminal the app defaulted to that didn't exist at all.
