### ISSUE TITLE
PSA: Project rename

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#4088]
📢  The next Terminus release will come with a new name - **Terminus** becomes **Tabby**.

There are multiple reasons for this:

* **Terminus** is too close to **Termius** - a commercial terminal app. This causes a number of users to end up on our issue tracker when they're actually looking for help with **Termius** - it's better to cover your butt before the lawsuit comes than regret it later.
* There's another terminal app that's literally called "[Terminus](https://gitlab.com/rastersoft/terminus)" and is packaged under this name at least in Debian and Ubuntu repos.
* It just rolls of the tongue better 🐱 

More info: https://github.com/Eugeny/tabby/discussions/4087

**Comment by bl-ue** [comment]
Great — it's already renamed on Homebrew. 🚀
