### ISSUE TITLE
Terminus could not start with your plugins

### ISSUE THREAD

**Issue by mingzijian** [Eugeny/tabby#4113]
Version: 1.0.139
Platform: win32 10.0.19042
Plugins: quick-cmds, scrollbar, sync-config, theme-gruvbox, title-control

Terminus could not start with your plugins, so all third party plugins have been disabled in this session. The error was:

**Comment by mingzijian** [comment]
Error: Can't resolve all parameters for v: ([object Object], [object Object], ?, [object Object]).

**Comment by Eugeny** [comment]
Already fixed, please upgrade.

**Comment by mingzijian** [comment]
thanks.
