### ISSUE TITLE
Serial Settings - can't find them

### ISSUE THREAD

**Issue by ChunkyBits** [Eugeny/tabby#4116]
Version: 1.0.144
Platform: win32 10.0.19041
Plugins: none

Opening a serial connection to a 3dprinter controller board with Marlin firmware.

I need to set local echo, so that I can see what I typed.
I need to set the handling of the new-line characters. /n to /cr/lf etc

It isn't obvious where I set these options. 

Thanks

**Comment by Eugeny** [comment]
Under Settings -> Serial, you can set these connection options. With the "line by line" mode enabled, you'll get a readline-based prompt where you can edit the line before sending it with Enter. 
![image](https://user-images.githubusercontent.com/161476/124246471-3dabb900-db21-11eb-9e6d-24f3028c879d.png)

**Comment by DanRoses** [comment]
If I wanted flow control on by default for serial connections I open in Tabby, Would i just need to add something like the following to the config file?

serial:
      xon: true
      xoff: true

**Comment by Eugeny** [comment]
Thanks for the suggestion - I'll track the global profile settings implementation in #4116
