### ISSUE TITLE
Unable to connect to Cisco switch via SSH

### ISSUE THREAD

**Issue by sectorogo** [Eugeny/tabby#4133]
I am unable to connect to Cisco switches via SSH with newest versions after Alpha 139. I got the following error message:

```
SSH  Connecting to X.X.X.X
X  read ECONNRESET
SSH   X  Remote rejected opening a shell channel: Error: Not connected
```

I have tried to enable all ciphers and algorithms, but nothing has changed.

It works fine with PuTTY and Terminus until version Alpha 139 included.

**Comment by sectorogo** [comment]
I forgot to mention that the authentication is set to interactive. But even when i set it to password it does not work.

**Comment by OffalGood** [comment]
This might be the same issue as what I'm seeing. 

https://github.com/Eugeny/tabby/issues/4167

**Comment by OffalGood** [comment]
Duplicate of #4167 #4167

**Comment by sectorogo** [comment]
Yes, it looks the same to me too.

**Comment by sectorogo** [comment]
This one is fixed in the latest releases.
