### ISSUE TITLE
Can't run sudo command

### ISSUE THREAD

**Issue by Vthechamp22** [Eugeny/tabby#4142]
Version: 1.0.144
Platform: linux 5.8.0-59-generic
Plugins: clickable-links

Everytme I try to run a command with sudo, it gives me an error:
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

If i try the same thing on `gnome-terminal`, it works fine.

**Comment by Vthechamp22** [comment]
I'm not sure what changed, but now it's working fine, I think it might've been an issue on my end

**Comment by tarneaux** [comment]
For anyone stumbling across this issue, restarting tabby entirely solved it for me.
