### ISSUE TITLE
Setting COMSPEC to Tabby on Windows breaks programs

### ISSUE THREAD

**Issue by datasone** [Eugeny/tabby#4143]
Version: 1.0.144
Platform: win32 10.0.17763
Plugins: none

After 7398d77, the COMSPEC environment variable is set to Tabby's path on Windows. But many programs rely on this variable to call cmd (e.g. [scoop](https://github.com/lukesampson/scoop/blob/092005046454d94d141d5c68fdbdb4c4a1229ae9/lib/psmodules.ps1#L29) and lua). As the Tabby's cli isn't compatible with cmd, this leads to some unexpected result (e.g. calling `%COMSPEC% /c [command]` will result in opening a new tab, and the caller cannot get the command's return value).

I wonder if this feature can be made optional (as a setting item in shell settings), as it keeps some programs from operating normally. Though for people don't use those programs, it may provide better experience.

P.S. I found this problem with the msys2 shell, as the cmd isn't using the Tabby COMSPEC. In Windows 10, the default env var name is ComSpec, which isn't overwritten by COMSPEC and is prioritized as it was set earlier. Just like:
```
C:\Users\datasone>set COMSPEC
ComSpec=C:\Windows\system32\cmd.exe
COMSPEC=C:\Users\datasone\AppData\Local\Programs\Tabby\Tabby.exe

C:\Users\datasone>echo %COMSPEC%
C:\Windows\system32\cmd.exe
```
Don't know why they made the OS mostly case insensitive but sensitive here...

**Comment by Eugeny** [comment]
Thanks for the investigation - it's optional and off by default now
