### ISSUE TITLE
[Feature request] A modern FTP/SFTP client integrated in Tabby

### ISSUE THREAD

**Issue by newolonos** [Eugeny/tabby#4152]
Hey, I really like tabby: The modern design, the powerful features and plugins. But I think one (**big**) function is missing:

A modern, good-looking, powerful FTP/SFTP client integrated in Tabby, so that you can manage your files and other things on your server. :)

**Comment by Eugeny** [comment]
There's both an SFTP client and a WinSCP integration. You can access the former via the SSH session toolbar, and the latter via the context menu.

**Comment by newolonos** [comment]
Oh, I didn't know that. Thank you for the quick and detailed answer. :)

**Comment by Eugeny** [comment]
No problem. I've updated the toolbar design in v145 to make it easier to find for new users.
