### ISSUE TITLE
High-contrast Windows themes ruin the UI

### ISSUE THREAD

**Issue by AxelTerizaki** [Eugeny/tabby#4165]
Hello.

I'm visually impaired and use Windows' high-contrast feature to be able to read my screen properly. However, on some apps, the high-contrast theme is forced even though you have suitable dark modes available (I guess from the screenshots). For example it makes switches unusable and makes terminal themes useless as well. I don't know if you can fix this but I'd be interested if you could.

See some screenshots :

![Tabby_oojBmv61Pc](https://user-images.githubusercontent.com/4531597/124883909-16963100-dfd2-11eb-8f53-bdbdedb57ee0.png)
![Tabby_vhmkki53dR](https://user-images.githubusercontent.com/4531597/124883922-18f88b00-dfd2-11eb-951a-9370f5c16b7f.png)

**Comment by Eugeny** [comment]
I've adjusted the toggles to follow the high contrast theme's colors. Let me know if you find other places where the UI breaks with the HC theme.

**Comment by AxelTerizaki** [comment]
Thanks for the quick fix.

There's also the issue of the terminal themes not working. For example if you select any theme there's no background change in the terminal, only the font colors are changed.

Honestly the high-contrast theme in Windows sucks, but it makes any old Win32 app look usable to people who're blinded by light. Apps like yours which have a dark color scheme by default shouldn't apply the high-contrast settings in Windows and ignore them. 

I've had that issue in my  electron app and fixed it with that in the CSS : 

```
* {
	forced-color-adjust: none;
}
```

This *should* prevent Windows from forcing your app's colors. Up to you if you wish to use it or not, as it would override the system's high-contrast toggle for your app, basically.

**Comment by Eugeny** [comment]
I've added the fix for the terminal schemes as well, but you might need to set "terminal background = from color scheme" for it to work. I think it's nice that it's actually somewhat usable with the HC theme as it helps people who want/need higher contrast and there's currently no native UI theme available with higher contrast.

If you just want to disable the HC mode's effect compeltely, you can use paste this into the "Custom CSS" setting (a media query was required for it to work on my Win 11):

```css
@media screen and (forced-colors: active) {
}```

**Comment by AxelTerizaki** [comment]
Hmmm, I'm not sure where to find that custom CSS option.

However, I just tested version 146 and it looks fine as themes are now taken into account, and you can change the background to take either the theme or color scheme into account, which suits me fine.

I'll tell you if I see other possible UI bugs with the Windows HC theme :) Thanks again!

**Comment by AxelTerizaki** [comment]
Actually, I just noticed something, in the options :

![Tabby_ZkoEKQonlt](https://user-images.githubusercontent.com/4531597/125080869-9fda6000-e0c5-11eb-98c6-0a08eb0075b4.png)

Basically you can't see the difference between "From theme" or "from color scheme" here as both are about the same color (or something close to but my eyes can't tell.) so it's hard to tell with these switch which one is selected.

**Comment by Eugeny** [comment]
Are you on v146 already? (where the fix is in)

**Comment by AxelTerizaki** [comment]
Yep, I'm on 146, I see the new switches and themes just fine.

The opacity slider is invisible though in the options : 

![Tabby_F56qJFgHdY](https://user-images.githubusercontent.com/4531597/125083514-c9e15180-e0c8-11eb-981e-d274d4256127.png)

And I think that's all I saw. :)
