### ISSUE TITLE
Main dashboard - flickering/pulsing buttons

### ISSUE THREAD

**Issue by fusionneur** [Eugeny/tabby#4166]
Version: 1.0.145
Platform: win32 10.0.19043
Plugins: save-output, clickable-links

To reproduce:
- open a lot of new terminals and then exit them (ctrl+d) until there is none => main dashboard is shown as below
![image](https://user-images.githubusercontent.com/7840350/124891634-d63eaf00-dfe1-11eb-9256-a1f6ac508b08.png)

- When i hover the mouse over "New terminal", "New tab with profile" or "Setttings" the buttons flicker/pulse with increasing speed depending on how many terminals were opened before

- when the flickering speed is too high, the buttons cannot be clicked anymore, thus it is not only a visual bug

To workaround:
- restart tabby => stops flickering at startup

**Comment by princemaple** [comment]
https://user-images.githubusercontent.com/1329716/125006000-70fdc300-e0a0-11eb-95f7-d45cf7b40461.mp4

I made a screen recording of the bug

**Comment by princemaple** [comment]
Another workaround: use hotkeys, ignore the buttons :)

**Comment by Eugeny** [comment]
Could you please record a performance trace in the DevTools window? See https://developer.chrome.com/docs/devtools/evaluate-performance/reference/#record

**Comment by princemaple** [comment]
It does seem relevant to how many tabs you have opened and closed before.

@Eugeny however I don't think it's performance related. Simply opening one tab and closing it causes the flicker, with a low frequency. As I keep working, opening new tabs and closing them, the `New terminal` flickering becomes faster.

**Comment by princemaple** [comment]
[Profile-20210709T172407.zip](https://github.com/Eugeny/tabby/files/6789562/Profile-20210709T172407.zip)
