### ISSUE TITLE
SSH failed (read ECONNRESET) with release 140-145; Worked in release 139. SSH protocol error? Thanks.

### ISSUE THREAD

**Issue by OffalGood** [Eugeny/tabby#4167]
I'm unable to connect using SSH access to RHEL (Redhat) from release 140-145. The same SSH connection worked in release 139.

```
SSH  Connecting to x.y.com.
 X  read ECONNRESET
 SSH   X  Remote rejected opening a shell channel: Error: Not connected
```

On the server side, it's running OpenSSH_7.4p1. SSHD appears to be closing the connection because tabby didn't pass identification string (see below).

`Jul  8 12:43:28 x sshd[93603]: Did not receive identification string from 10.1.1.100 port 64842`

Oddly, SSH in Release 140-145 works if I connect to **Ubuntu/Debian, running OpenSSH 8.x** (but failed if **RHEL & OpenSSH 7.x**). Unfortunately, I don't own the RHEL, so can't update SSHD on it.

Interestingly, Wireshark network capture on the client side, decodes those fragmented packet as "SSH" but malformed.

```
SSH Protocol
[Malformed Packet: SSH]
    [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
```
![Capture](https://user-images.githubusercontent.com/25124547/124971643-1193aa80-dfef-11eb-8ca4-e80118278d3a.PNG)

When I failback to putty, the 1st packet gets decoded as  SSHv2 (see below).

```
SSH Protocol
    Protocol: SSH-2.0-PuTTY_Release_0.71
    [Direction: client-to-server]

```

Thanks for your great work on Tabby! Love it as do many others! 👍🏼

**Comment by Eugeny** [comment]
Hi, thanks for the detailed report. It appears that Wireshark fails to parse the packet because `node-ssh2` sends the ident string and CRLF in two separate TCP packets. I've patched them together and now Wireshark sees the SSH packet structure again: 
![image](https://user-images.githubusercontent.com/161476/125168551-5dd51b00-e1a6-11eb-9e0d-05ddc2fce3fa.png)

That said, it already worked before with a CentOS machine running `openssh-7.4p1-21.el7.x86_64`.

I'll push this change anyway - let's see it it helps

**Comment by Eugeny** [comment]
Build should be done soon: https://github.com/Eugeny/tabby/actions/runs/1018258488

**Comment by OffalGood** [comment]
Still unable to connect to RHEL SSH server using 1.0.147-nightly.0 portable build.

On the SSH server side, seeing the error below:
Jul 14 10:25:43 x sshd[93648]: Did not receive identification string from 10.1.1.100 port 55513

Wireshark TCP dump shows tabby sends the ident string in 2 packets.

![1](https://user-images.githubusercontent.com/25124547/125649688-976bd71e-d3b5-40f4-801f-a169576ffe5e.PNG)

![2](https://user-images.githubusercontent.com/25124547/125649712-b5f386fc-3faa-4f3d-8ff7-7285636340fe.PNG)
![3](https://user-images.githubusercontent.com/25124547/125649723-b29920a8-9261-45ce-9502-b37a8b916ac8.PNG)

Thanks for helping troubleshoot this.

**Comment by Eugeny** [comment]
Just to be sure - are you using a recent nightly build? They're all called `nightly.0`. I've just retested this to be sure and I'm seeing a single TCP packet.

**Comment by OffalGood** [comment]
@Eugeny  You are right! Nightly fixed the SSH with older SSHD! 

Sorry, I thought I was on nightly! Thanks! 👍🏼
