### ISSUE TITLE
New Install missing SSH Connection

### ISSUE THREAD

**Issue by bliteknight** [Eugeny/tabby#4170]
Hello,
I just installed the latest release on a new PC and I cannot add any SSH connections. 
The button to add is missing or am I missing something.

The is what the console log looks like after starting...

`entry.ts:56 Window bootstrap data: Object
plugins.ts:131 Found community-color-schemes in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found core in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found electron in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found local in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found plugin-manager in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found serial in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found settings in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found ssh in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found telnet in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:131 Found terminal in C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(10)
plugins.ts:177 Loading terminal: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:177 Loading telnet: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:177 Loading ssh: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:177 Loading settings: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:177 Loading serial: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:177 Loading plugin-manager: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:177 Loading local: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:177 Loading electron: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:177 Loading core: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:177 Loading community-color-schemes: C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10267 [main] v 1.0.145
C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10267 [updater] Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Users\dee\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\dee\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\dee\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
doLog @ C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10267
C:\Users\dee\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10267 [hostApp] CLI arguments received: Object`

![image](https://user-images.githubusercontent.com/8250359/124994126-fdf63d00-e00a-11eb-88f6-2d98511dd815.png)

**Comment by Eugeny** [comment]
Hi, you can add SSH connections on the Profiles settings page

**Comment by bliteknight** [comment]
Thanks
