### ISSUE TITLE
SSH Connection ECONNRESET

### ISSUE THREAD

**Issue by bmk1189** [Eugeny/tabby#4171]
Version: 1.0.145
Platform: darwin 19.6.0
Plugins: none

Issue when trying to connect to a jump server on an ssh connection. Tried all authentication methods.
If I open a local bash console and do an ssh manually, it works as expected.

 SSH  Connecting to [SERVER]
 X  read ECONNRESET
 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH [SERVER]: session closed
Press any key to reconnect

**Comment by OffalGood** [comment]
I believe this is the same as issue I opened up earlier.

[SSH failed with release 140-145; Worked in release 139. SSH protocol error?](https://github.com/Eugeny/tabby/issues/4167)

**Comment by OffalGood** [comment]
Duplicate of #4167

**Comment by bmk1189** [comment]
> I believe this is the same as issue I opened up earlier.
> 
> [SSH failed with release 140-145; Worked in release 139. SSH protocol error?](https://github.com/Eugeny/tabby/issues/4167)

Yes, it is. Sorry for the duplicate.
