### ISSUE TITLE
Connect via SSH in the profile select dropdown.

### ISSUE THREAD

**Issue by artu-ole** [Eugeny/tabby#4181]
I might be missing something, but I believe following was connecting via SSH just couple of versions back.
![image](https://user-images.githubusercontent.com/15938416/125104390-01122b80-e0e6-11eb-9d99-2d299d137242.png)
Now it's a telnet connection by default. 
Is there a way to force it to be an ssh connection again not to require user to create profiles for disposable one-time connections? Specifying the port does not help and ssh might not be on default port either.

**Comment by Eugeny** [comment]
Yes - you can use the "SSH profiles" hotkey to open the "classic" profile selector where typing in an address initiates an SSH connection.

However the default in the "new" selector was supposed to be SSH, not telnet.
