### ISSUE TITLE
use profile can't connect to server

### ISSUE THREAD

**Issue by liaohui5** [Eugeny/tabby#4199]
You can't connect to the server using profile, but you can connect to the server normally using the git-bash command line

![image](https://user-images.githubusercontent.com/29266093/125391778-9f98d800-e3d7-11eb-9ed5-633cb66e745d.png)
![image](https://user-images.githubusercontent.com/29266093/125391800-a7587c80-e3d7-11eb-8199-8c7ee68fcea7.png)

![image](https://user-images.githubusercontent.com/29266093/125391827-b2131180-e3d7-11eb-8ff0-89ccbae350c3.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by liaohui5** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/tabby](https://github.com/Eugeny/tabby)**A terminal for a more modern age (formerly Terminus) - Eugeny/tabby


the error info like this:
![image](https://user-images.githubusercontent.com/29266093/125470598-d3e6699a-bf9c-4da3-a15c-f1bec87f97d8.png)
