### ISSUE TITLE
Option for Save Output to automatically start logging on connect

### ISSUE THREAD

**Issue by tmay94** [Eugeny/tabby#4205]
A feature request or enhancement for the 'Save Output' function.
To allow it to automatically start recording a ssh/console session on connection to a device.
Either with a timestamped/dated/hostname filename or a customizable per flags (like putty) filename.

I thought this was a feature with it before but it doesn't look like that is the case.

Currently, you have to manually right-click the session then select 'Save output to file...' in the sub menu.

Since our team uses this to login to a hundred or more devices a day and each session has to be logged.
This would be an extremely useful time saver and very helpful UX change.

**Comment by Eugeny** [comment]
You can enable this in Settings -> Save Output: 
![image](https://user-images.githubusercontent.com/161476/125641574-407cbb41-2d81-404c-bd0d-811c00d4e384.png)
