### ISSUE TITLE
Duplicate SSH tab broken

### ISSUE THREAD

**Issue by pinpins** [Eugeny/tabby#4219]
Hello,

When Duplicating SSH tab, setting of "Disable Dynamic tab title" are not transferred. 

The same happens in case of reconnection to SSH, tab title gets replaces by username and path instead of configured tab name

**Comment by pinpins** [comment]
would appreciate someone checks, that blocks me from upgrading to TAbby from 1.0.139 version

**Comment by Eugeny** [comment]
Fixed in the latest nightly
