### ISSUE TITLE
SSH session closing: more options except "Press any key to reconnect"?

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/tabby#4245]
For example:

~~~
- Press ENTER to close tab
- Press R to reconnect
~~~

**Comment by Eugeny** [comment]
I'd say this works already since there's a shortcut to close the tab.

**Comment by clarkwang** [comment]
> I'd say this works already since there's a shortcut to close the tab.

The issue is the shortcut (mine is ALT-W) to close the tab usually involves ctrl/alt/shift or functional keys which is not as easy as pressing one single key.
