### ISSUE TITLE
Typing clear command does not clear everything on the screen, it just move the scroll position

### ISSUE THREAD

**Issue by ajcastro** [Eugeny/tabby#4249]
Hello! 
I entered command `clear` and I was expecting all in the screen would be cleared but it just move the scroll position. 
I am using a git bash profile. 
I end up opening a new tab just to make sure the screen is all cleared. 
Sometimes I need fully-cleared screen when debugging long error logs from phpunit tests for example. That way, the long error logs will not mixed up with the previous runs.

**Comment by estorski** [comment]
Could second, that's a little bit annoying. Both `clear` and `reset` are affected
