### ISSUE TITLE
Lastest Windows nightly doesnt open GUI (shows in task manager)

### ISSUE THREAD

**Issue by Joshndroid** [Eugeny/tabby#4261]
I came here through some Googling and thought to give this project a try.
It looks quite nice in the images.

I downloaded the latest nightly - tabby-1.0.149-nightly.0-setup

Installed as necessary within windows 10

I click to open the program and the GUI will not load. 

I checked task manager and it is within the processes to which I see 4 running, however I then can't even kill it off to try again.
After a reboot and attempt it does the same thing.
I tried reinstalling, it does the same.

I do not see this issue within the .deb version of the nightly.

**Comment by awkaw** [comment]
+1

**Comment by Eugeny** [comment]
This is caused by a previous alpha release corrupting its [config file](https://github.com/Eugeny/tabby/wiki/Config-file) and emptying it. Please remove the latest release (1.0.152), and remove the config file if it's empty.

**Comment by Joshndroid** [comment]
Thank you mate. Loving the Linux version so I'll give this a whirl again on the Windows machine
