### ISSUE TITLE
Tabby sz download file>50M, decompression failed

### ISSUE THREAD

**Issue by garywu520** [Eugeny/tabby#4282]
Fast recurrence:
(Premise: use tabby ssh to log in to the server)
When the size of the zip or tar compressed directory is >50M, after the download is completed using the sz command, the decompression fails

If <50M, the decompression is normal

**Comment by garywu520** [comment]
Can no one else reproduce it ？

**Comment by gongmingtao0601** [comment]
I have got the same bug.

**Comment by garywu520** [comment]
> I have got the same bug.

For the author, it seems that the center of gravity is not here, very helpless.
