### ISSUE TITLE
Improve pane separator visibility

### ISSUE THREAD

**Issue by mullerch** [Eugeny/tabby#4291]
When using multiple panes, the separator between the panes is not visible until hovering with the mouse over it.

This has downsides:

- It is hard to see in which pane some content is. E.g. with horizontally split panes and newlines
- It is hard to target quickly the separator to resize the panes

I would suggest either:

- Make the separator visible by default
- Make the separator visibility configurable

Workaround: with horizontally split panes, the toolbar of the pane can be pinned

**Comment by Eugeny** [comment]
Separators are now visible by default in the latest nightly
