### ISSUE TITLE
Linux - dragging tab to create new window split, the new split is blank

### ISSUE THREAD

**Issue by MostHated** [Eugeny/tabby#4295]
Hey there,
   I went to test out the new drag/split capability and ran into an issue. When I drag the tab to create a new split, the column or row of the new split ends up blank. I fired up a Windows VM to see if I experienced the same thing there, and I did not, it seemed to work as expected. Demonstrated in the clip below, I first have the windows version in a vm, then attempt to do the same thing on my desktop. The split divider keeps getting stuck on my mouse after the initial click, too, and is hard to get it unstuck, as if I was holding the left mouse button, when I am not. I had clicked, dragged a little, then let go and it remains attached.

![](https://i.imgur.com/jhHexV7.gif)

This is on Pop_OS 21.04.

Thanks,
-MH

**Comment by Eugeny** [comment]
Thanks for the detailed report! Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by MostHated** [comment]
Well, shoot. I opened devtools, then wanted to clear everything out to start fresh, so I closed Tabby while devtools was opened, then went to reopen it, and now the UI will not display at all.

(had to do mp4, as my gif recorder can't record my taskbar)
https://i.imgur.com/hG79WeK.mp4

**Comment by Eugeny** [comment]
This is definitely https://github.com/Eugeny/tabby/issues/4293#issuecomment-889369035 - any idea what triggered it? (closing with devtools opened is fine)

**Comment by MostHated** [comment]
Yeah, quite literally the only thing I did was open devtools, then close tabby, then attempt to reopen it.

**Comment by MostHated** [comment]
My bad, I had almost forgot. Here is the log.

[tabby_console2.log](https://github.com/Eugeny/tabby/files/6911614/tabby_console2.log)

**Comment by MostHated** [comment]
I posted in another thread about how when I updated to 1.0.152 my keyboard input didn't work anymore when using hterm and switching to xterm webgl fixed it. While playing around to see if anything else was acting up, I tried dragging a tab again, this time it seemed to work. :+1: 

![](https://i.imgur.com/M4yuppy.png)

**Comment by Eugeny** [comment]
Thanks for testing - hterm is an old frontend that lacks support for lots of things - apparently reattaching itself to a new tab is one of them. Unfortunately I can't afford to spend any more time on hterm - but let me know if you run into anything with xterm :+1:

**Comment by MostHated** [comment]
It seems that hterm was selected by default? I don't recall having selected it. I know I played around with things on Terminus when trying to get rid of the ghosting, but I thought I had put it on xterm webgl, so not sure why it was on hterm. If that's the case, might be a good idea to just remove it?

**Comment by Eugeny** [comment]
Good point - done!
