### ISSUE TITLE
Tabby is running in task manager, but there is no visible console window 

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [Eugeny/tabby#4296]
Tabby was installed successfully - Profile all users.

On the first run, it worked.

On the restart, I see not terminal windows.

I can see 4 tabby processes running, but no visible window has come up.

Windows Server 2012

![image](https://user-images.githubusercontent.com/1735005/127543439-982b426c-e433-4298-b8ce-0f078f4d0f74.png)

**Comment by Eugeny** [comment]
Duplicate of #4296

**Comment by CharlesOkwuagwu** [comment]
> Duplicate of #4296

Please which duplicate?

**Comment by Eugeny** [comment]
This issue is the same as the issue #4296 <- click here to view that issue

**Comment by Eugeny** [comment]
My bad, it's #4293
