### ISSUE TITLE
Buttons on startup screen not working.

### ISSUE THREAD

**Issue by ginkcode** [Eugeny/tabby#4298]
Version: 1.0.149
Platform: win32 10.0.19042
Plugins: none

After exit the last tab, the startup screen will show up again.
But all the buttons are just flickering on mouse hover, can't click any more.

![image](https://user-images.githubusercontent.com/9301098/127584582-26a15d01-7793-4e00-b149-f959f34e53a2.png)

**Comment by Eugeny** [comment]
Could you please create a short (5s) [performance trace](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/#save) from DevTools and send it to me at e@ajenti.org? Thanks.

**Comment by ginkcode** [comment]
[Profile-20210731T005427.zip](https://github.com/Eugeny/tabby/files/6909287/Profile-20210731T005427.zip)
Hi @Eugeny I've recorded one and attached it here.

**Comment by Eugeny** [comment]
Thanks, are you using the xterm WebGL terminal frontend?

**Comment by ginkcode** [comment]
I've tested with hterm, xterm, xterm webgl and the issue still there.
Checked on latest version 1.0.150
