### ISSUE TITLE
Jump host not work

### ISSUE THREAD

**Issue by dallaslu** [Eugeny/tabby#4307]
Message:  
  X  Invalid username
  X  Not connected

Error: core.js:6456

  ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'end' of undefined
  TypeError: Cannot read property 'end' of undefined
      at SSHSession.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:35223)

**Comment by Eugeny** [comment]
Are you able to connect to the jump host directly with the same connection?

**Comment by dallaslu** [comment]
Yes, it can be connected normally. I have tried two different jumpers with the same result.

**Comment by dallaslu** [comment]
After I deleted the file `config.yaml`, I rebooted tabby and everything was back to normal.

**Comment by dallaslu** [comment]
After copying the `config.yaml` file between mac and windows, the problem occurs again.
