### ISSUE TITLE
Save configs of a serial connection does't work

### ISSUE THREAD

**Issue by Skips75** [Eugeny/tabby#4325]
Trying to change and save the `input newlines` and/or the `Output newlines` does not work.
On my Windows 10 machine the `input newlines` always keep the setting `keep` and the
`Output newlines` always retains the `Force CRLF` value.
Tabby installed via *scoop* install manager.
I thought to force the serial setting editing in a proper way the `serial: {}` section of the
**Config file** but not found some docs that enumerates all the relates tags to use to
change the serial connection things.

**Comment by Eugeny** [comment]
What's your Tabby version? Also please paste the relevant portion of the config file

**Comment by Eugeny** [comment]
Are you sure this is right config file? It only has one saved SSH profile and no serial profiles.

**Comment by Skips75** [comment]
The reason why I opened this issue is because of when I used old *Terminus v.1.0.143*, the logs that I captured on the COM
were not interspersed with **CR/LF** characters (they are sent by the remote application).

Using instead *Tabby 1.0.150* what I see is that every log has additional **CR/LF** characters..

So the next step that I made was to go into the `Profile` section of the `Settings` menu of *Tabby* and click on the "Double Sheet" icon to open Serial Setting dialog box.

From there the intent was to change the value of the option `Output newlines` from `Force CRLF` value to `Keep` value and to
check again if the added **CR/LF** characters disappear.

Reentering again in the Serial Setting dialog box always shows the option `Output newlines` to have the `Force CRLF` value
(and still the logs are interspersed with **CR/LF** characters).

**Comment by Skips75** [comment]
The image that I posted is a screenshot of the last lines of config.yaml that I found in my `xxx\AppData\Roaming\tabby`
folder.

Previously I also attached a `config.yaml.log` that is the same `config.yalm` but renamed so that I was allowed to attach it there.

The  `xxx\AppData\Roaming\tabby` folder is automatically open if I press `Show condig file` present in the `Config file`
page of the `Settings` menu.

**Comment by Eugeny** [comment]
Thanks, I've figured it out! The "double sheet" button in fact duplicates a built-in profile into a custom one.

There is a bug where, if you don't give the new profile a name, it will not be saved. I'll add a default name for copied profiles as well as revert default CRLF processing for serial.
