### ISSUE TITLE
Paste into terminal with keyboard shortcut is not working

### ISSUE THREAD

**Issue by parampreetss** [Eugeny/tabby#4326]
Version: 1.0.151
Platform: linux 5.11.0-25-generic
Plugins: title-control, theme-windows10, theme-hype, theme-gruvbox, scrollbar, save-output, relaxed-theme, quick-cmds, clickable-links, altair

Unable to paste with keyboard shortcuts (tried Shift+Insert, Ctrl+Shift+V, Ctrl+V). Shortcuts don't seem to do anything.
Pasting via context menu is working fine.

**Comment by parampreetss** [comment]
After reading issue #4355, I checked and found that many of these hotkey combinations don't work. Specially (but not limited to) the ones involving Shift key.

**Comment by MostHated** [comment]
I am having this issue as well. I can't hotkey to paste. Right-click and paste works. 

Not sure if this is related but the shortcuts show up multiple times in the settings menu.

![](https://i.imgur.com/S2Qynxq.gif)
