### ISSUE TITLE
[Feature Request] Custom configuration file path

### ISSUE THREAD

**Issue by dallaslu** [Eugeny/tabby#4327]
The default path is `tabby/config.yaml`, there are many other files in the same folder. This makes it difficult to sync using a web drive client such as Dropbox, Nextcloud.

Once you can customize the path, it's easy to switch configurations (may be useful in some very specific cases).

At the very least, key text files such as config.yaml can be moved to a folder. For Example: `tabby/con/config.yaml`.

**Comment by clarkwang** [comment]
What about adding something like an `includes` option? Then it'll also be easier to share the conf between Mac/Windows/Linux.

~~~
includes:
  - /my/tabby/common.yaml
  - /my/tabby/win10.yaml
~~~

**Comment by dallaslu** [comment]
What about the changes made in the tabby settings screen, are they saved to config.yaml or the include file?
