### ISSUE TITLE
Proxy Command issue

### ISSUE THREAD

**Issue by snegodick** [Eugeny/tabby#4328]
Version: 1.0.150
Platform: darwin 20.6.0
Plugins: none

For example, In my ssh profile i have this in "Proxy command":
`ssh hostname.com -p 55222`
And i get this error:
```
 SSH  Connecting to hostname.com
 SSH   Proxy command  Using ssh hostname.com -p 55222
 SSH   Proxy command  Pseudo-terminal will not be allocated because stdin is not a terminal.
 SSH   Proxy command  mesg: ttyname failed:
 SSH   Proxy command  Inappropriate ioctl for device
 SSH   Proxy command  -bash: line 1: $'SSH-2.0-ssh2js1.1.0\r': command not found
```
When i use this command:
`ssh -tt hostname.com -p 55222`
I get:
```
 SSH  Connecting to hostname.com
 SSH   Proxy command  Using ssh -tt hostname.com -p 55222
 X  Timed out while waiting for handshake
 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH  hostname.com: session closed
Press any key to reconnect
```
I originally wanted to connect through a socks proxy, so I used "Proxy command":
ssh root@hostname.com -p 55222 -o "ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p"
And i get: 
```
 SSH  Connecting to hostname.com
 SSH   Proxy command  Using ssh -tt root@hostname.com -p 55222 -o "ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p"
 X  Timed out while waiting for handshake
 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH  hostname.com: session closed
Press any key to reconnect
```
I love Tabby, but please help make connection with Socks-proxy. I use it on Mac OS with M1 processor.

**Comment by Eugeny** [comment]
1. You can't use `ssh` as a ProxyCommand because it's not how ProxyCommand works in general. Use a _jump host_ which is already available in Tabby as a profile option (under Advanced)
2. Tabby doesn't expand OpenSSH style variables in ProxyCommand (or any others, and there's nowhere it could get %h and %p values from anyway) - you just need to use `nc -X 5 -x 127.0.0.1:9050 hostname.com 55222` as your proxy command.

**Comment by snegodick** [comment]
```
 SSH  Connecting to hostname.com
 SSH   Proxy command  Using nc -X 5 -x 127.0.0.1:9050 hostname.com 55222
 X  Timed out while waiting for handshake
 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH  hostname.com: session closed
Press any key to reconnect
```

Same problem.

**Comment by Eugeny** [comment]
If your proxy command (`nc -X 5 -x 127.0.0.1:9050 hostname.com 55222`) is right, the server ident string (`SSH-2.0-ssh2js1.1.0`) should show up if you just execute it in the terminal - does it?

**Comment by snegodick** [comment]
Yes
```
% nc -X 5 -x 127.0.0.1:9050 hostname.com 55222
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
```

**Comment by snegodick** [comment]
In Developer tools:
```
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:36078 Uncaught TypeError: process.stdout.read is not a function
    at ProxyCommandStream._read (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:36078)
    at ProxyCommandStream.Readable.read (internal/streams/readable.js:481)
    at resume_ (internal/streams/readable.js:968)
    at processTicksAndRejections (internal/process/task_queues.js:80)
_read @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:36078
Readable.read @ internal/streams/readable.js:481
resume_ @ internal/streams/readable.js:968
processTicksAndRejections @ internal/process/task_queues.js:80

```

**Comment by snegodick** [comment]
I think it because Tabby sandboxed, it means they can't communicate with other apps (like nc ) so there is no way to access local shell nor authentication agent (like ssh-agent).

**Comment by snegodick** [comment]
In version 1.0.156-nightly.0 all works fine! Thank you!
