### ISSUE TITLE
RFE: Add feature to format CURL JSON response automatically.

### ISSUE THREAD

**Issue by livesamarthgupta** [Eugeny/tabby#4329]
Since we are going to make it the best terminal in the world, why not add the feature to auto-format JSON response from a curl request (SSH/Non-SSH) terminal.

**Comment by Eugeny** [comment]
You're looking for https://github.com/deftek/json_pp

**Comment by livesamarthgupta** [comment]
This requires me to have PHP installed already in the command line. Isn't there a way to make a plugin for tabby which can do the similar job?
