### ISSUE TITLE
`Split to bottom` now splits to top

### ISSUE THREAD

**Issue by princemaple** [Eugeny/tabby#4348]
Version: 1.0.151
Platform: win32 10.0.19043
Plugins: clickable-links

**Comment by Okumura2** [comment]
I've got the same issue here.
Reverting to 1.0.150 fixes the issue.

Version: 1.0.151
Platform: win64 10.0.19042
Plugins: none

**Comment by princemaple** [comment]
confirm 1.0.152 fixed it
