### ISSUE TITLE
Hotkeys can't work

### ISSUE THREAD

**Issue by YM14532** [Eugeny/tabby#4355]
such as crtl+tab/crtl+shift+v can't work in verison 150 and above. crtl+shit+‘+’ and ‘-’ working fine.

does anyone face this bug ?

**Comment by YM14532** [comment]
Version: 1.0.148
Platform: win32 10.0.17763
Plugins: relaxed-theme

> crtl+tab/crtl+shift+v 

I test this version, the hotkeys working fine which can't work in 150/151 version. hope new version got this bug fixed =-= , come on super tabby !

**Comment by parampreetss** [comment]
I also reported similar problem (Can't paste text into terminal with hotkeys) via issue #4326. 
Experienced the problem in both versions 150,151.
Reading your issue, I checked and found that many of these hotkey combinations don't work. Specially (but not limited to) the ones involving Shift key.
I'd suggest merging these two issues into one, although I am not sure how to do that. I am more familiar with JIRA, where you can mark issues related to each other.

**Comment by YM14532** [comment]
> I also reported similar problem (Can't paste text into terminal with hotkeys) via issue #4326.
> Experienced the problem in both versions 150,151.
> Reading your issue, I checked and found that many of these hotkey combinations don't work. Specially (but not limited to) the ones involving Shift key.
> I'd suggest merging these two issues into one, although I am not sure how to do that. I am more familiar with JIRA, where you can mark issues related to each other.

I have return to version 148  =-=
