### ISSUE TITLE
Tabby no start on Windows 64 after update

### ISSUE THREAD

**Issue by awkaw** [Eugeny/tabby#4366]
After installing version 151 on Windows 64, Tabby no longer starts. Installing the previous version (149) does not help. Tabby won't start. It is present in the processes, but nothing happens visually.

**Comment by Eugeny** [comment]
This is caused by a previous alpha release corrupting its [config file](https://github.com/Eugeny/tabby/wiki/Config-file) and emptying it. Please remove the latest release (1.0.152), and remove the config file if it's empty.
