### ISSUE TITLE
Last 2-3 updates broke repeated Hotkey combinaiton pressing 

### ISSUE THREAD

**Issue by amajauskas** [Eugeny/tabby#4368]
For example, when wanting to change windows I use to hold the hotkeys Ctrl+Shift and press Left Arrow/Right Arrow to move to different panes. Since the last 2-3 updates this does not work anymore and Ctrl+Shift have to be repressed for the whole combination to work.

This is the same for when wanting to move the window by holding Ctrl+Shift and pressing PgUp/PgDn, now Ctrl+Shift have to be re-pressed every time.

**Comment by Eugeny** [comment]
I've just fixed this in v152
