### ISSUE TITLE
Keyboard input not showing in terminal windows after autoupdate to 1.0.152 on MacOS 11.5.1

### ISSUE THREAD

**Issue by michelvankessel** [Eugeny/tabby#4370]
Version: 1.0.152
Platform: darwin 20.6.0
Plugins: scrollbar

for some reason I cannot use Tabby anymore. Keystrokes don't show in terminal windows. 

After a downgrade to 1.0.151, everything works normal

**Comment by Eugeny** [comment]
Please post your config file, thanks.

**Comment by michelvankessel** [comment]
terminal:
  searchOptions: {}
  colorScheme:
    name: Brogrammer
    foreground: '#d6dbe5'
    background: '#131313'
    cursor: '#b9b9b9'
    colors:
      - '#1f1f1f'
      - '#f81118'
      - '#2dc55e'
      - '#ecba0f'
      - '#2a84d2'
      - '#4e5ab7'
      - '#1081d6'
      - '#d6dbe5'
      - '#d6dbe5'
      - '#de352e'
      - '#1dd361'
      - '#f3bd09'
      - '#1081d6'
      - '#5350b9'
      - '#0f7ddb'
      - '#ffffff'
  background: colorScheme
  ligatures: true
  profile: local:binzsh
  frontend: hterm
  fontSize: 18
  font: Courier New
  fallbackFont: Menlo
  copyOnSelect: true
  showRecentProfiles: 5
hotkeys:
  shell: {}
  profile: {}
  rearrange-panes:
    - ⌘-Shift
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  telnet-profile-selector: []
  restart-telnet-session: []
  ssh-profile-selector: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
serial: {}
ssh:
  warnOnClose: true
appearance:
  opacity: 0.99
  frame: native
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - serial
version: 3

**Comment by michelvankessel** [comment]
When I switch to XTERM or XTERM(WebGL) it works again. So HTERM seems to be broken

**Comment by parampreetss** [comment]
Same problem with hterm in Ubuntu.

(Version: 1.0.152
Platform: linux 5.11.0-25-generic
Plugins: title-control, theme-windows10, theme-hype, theme-gruvbox, scrollbar, save-output, relaxed-theme, quick-cmds, clickable-links, altair)

**Comment by MostHated** [comment]
I can paste now with ctrl + shift + V, but I can't seem to type any characters on Pop_OS 21.04

**Comment by Eugeny** [comment]
hterm frontend has now been removed permanently in the nightly, please switch to xterm or xterm-webgl.
