### ISSUE TITLE
slow zmodem  and error

### ISSUE THREAD

**Issue by exGrogu** [Eugeny/tabby#4373]
Host: Windows 10 Home Edition, 21H1
Remote: linux 5.4 x86_64
Tabby: 1.0.152

Transmission rate of lsz/sz command is about 200KB/s, and  command always report error message like " Error  PROTOCOL: Only thing after ZFIN should be “OO” (79,79), not: 27,91,48,59,51,49,109,91,114,111,111,116,64,126,47,111,110,101,119,97,121,71,65,80,47,112,97,116,99,104,47,118,105,114,100,98,93,36,27,91,48,59,51,50,109" 

If using previous version Terminus 1.0.120, the speed is about 3MB/s and no error message.

**Comment by Siogian** [comment]
Version: 1.0.167
Platform: Windows x64 10.0.22000
Plugins: save-output
Frontend: xterm

❯ sz main.c
 ZMODEM  Session started            
------------------------            
 Received  main.c            
 Error  PROTOCOL: Only thing after ZFIN should be “OO” (79,79), not: 27,91,49,109,27,91,55,109,37,27,91,50,55,109,27,91,49,109,27,91,48,109,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,13,32,13,27,93,49,51,51,55,59,67,117,114,114,101,110,116,68,105,114,61,47,104,111,109,101,47,120,105,97,111,106,105,97,110,7,27,93,50,59,120,105,97,111,106,105,97,110,64,86,77,45,48,45,52,45,117,98,117,110,116,117,58,126,7,27,93,49,59,126,7  

在最新版本中此问题依然存在。
