### ISSUE TITLE
Minor: Switching tabs with hotkeys works with quirks

### ISSUE THREAD

**Issue by estorski** [Eugeny/tabby#4381]
Version: 1.0.151
Platform: win32 10.0.19043
Plugins: none

I remember before I could have pressed Ctrl (keep holding it) and then press 1, then 2, then 3, then 4 to see what's going on in each tab.
Now, that does not work anymore past number 1. I have to first de-press Ctrl before trying to switch to a different tab.

**Comment by Eugeny** [comment]
Already fixed in 1.0.152
