### ISSUE TITLE
pin top-ribbon menu overlaps first shell line during ssh session

### ISSUE THREAD

**Issue by tmay94** [Eugeny/tabby#4384]
![image](https://user-images.githubusercontent.com/72574380/128739910-55041d8c-de2f-4e61-ac59-229632ab0a5c.png)

The above bar overlaps the first line of the console session when you authenticate into the machine.
This seems like a small graphical issue. When pinned it doesn't consider the ribbon a hard-start after the ribbon. 

I would expect it to look like this (without having to hit enter 3 times to get it below the ribbon):
![image](https://user-images.githubusercontent.com/72574380/128740328-1dfb82da-6bbf-4b80-9417-89ac85201be0.png)

**Comment by Eugeny** [comment]
Which theme are you using?

**Comment by tmay94** [comment]
I don't have any extra theme. This does however only happen when the theme is set to "Compact". This does not happen on "Standard".

**Comment by Eugeny** [comment]
Fixed in the nightly builds
