### ISSUE TITLE
Prompt for a password when launching the application

### ISSUE THREAD

**Issue by tvelf009** [Eugeny/tabby#4390]
Hi.
Thank you very much for the most user-friendly terminal.
Especially for the fact that there is integration with Pageant
I am using a client with saved passwords and would like
You will be asked to add the functionality of requesting a password when starting the program.
This is useful if access to important servers is stored.
Is this possible?

**Comment by Eugeny** [comment]
Yes, you can enable it in Settings -> Vault. This will encrypt stored passwords and ask for a passphrase when connecting. If you additionally enable "encrypt config file", it will ask for passphrase when starting the app.
