### ISSUE TITLE
Cannot input standard characters in terminal or ssh

### ISSUE THREAD

**Issue by ysaak** [Eugeny/tabby#4391]
After updating from 1.0.144 to 1.0.152, I can't input standard characters, only the hotkeys are working.

I tried the following actions: 
 - renaming the config folder and restart the application
 - uninstalling and reinstalling (without config folder) the application 
But none of them are working.

The only error in the devtool window is: 
```
[updater] Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler
```

Downgrading to 1.0.151 make it work again.

Version: 1.0.152
Platform: win32 10.0.19042
Plugins: none

**Comment by Eugeny** [comment]
If you're using the `hterm` terminal frontend, it's unsupported and will be removed in the next release - please switch over to xterm or xterm-webgl.

**Comment by ysaak** [comment]
Thanks for the quick response.
You're right, I was using `hterm` and switching to `xterm`solve the problem.
