### ISSUE TITLE
Jump connections don't obtain default values

### ISSUE THREAD

**Issue by mymarche** [Eugeny/tabby#4396]
Version: 1.0.152
Platform: win32 10.0.19043
Plugins: none

Hello!

When i try to connect via jump host with user "root", i had a error:
```
 SSH  Connecting to HOST
 X  Invalid username
 X  Not connected
```

But if i add `user: root`  into `config.yaml`  then everything is fine.

I think error in this line
https://github.com/Eugeny/tabby/blob/bf5d037cff0f3b67db94ff1946b0e05aeb831a4c/tabby-ssh/src/components/sshTab.component.ts#L81
Profile data getting from config and don't getting obtain default values before usage in this line
https://github.com/Eugeny/tabby/blob/bf5d037cff0f3b67db94ff1946b0e05aeb831a4c/tabby-ssh/src/components/sshTab.component.ts#L126
 and here
https://github.com/Eugeny/tabby/blob/bf5d037cff0f3b67db94ff1946b0e05aeb831a4c/tabby-ssh/src/services/ssh.service.ts#L132

**Comment by Eugeny** [comment]
Thanks for the detailed report :+1:
