### ISSUE TITLE
Can't leave the page "Hotkeys"

### ISSUE THREAD

**Issue by Mirulmaar** [Eugeny/tabby#4403]
Version: 1.0.152
Platform: win32 10.0.19043
Plugins: none

Hello! 
After upgrading from v.150 to v.152 can't leave the hotkeys page in menu. Needs a restart to continue working. 
Log in attached file.
Spoiler -​ ERROR TypeError: Cannot read property 'Trad' of undefined
    at HotkeySettingsTabComponent.getHotkey (C:\Users\kkote\AppDa…\dist\index.js:9930)

[-1628750338049.log](https://github.com/Eugeny/tabby/files/6973323/-1628750338049.log)

**Comment by Eugeny** [comment]
Could you please attach your config file?

**Comment by Mirulmaar** [comment]
There he is. Deleted profiles, other settings as they are.
[config.txt](https://github.com/Eugeny/tabby/files/6988199/config.txt)

**Comment by Eugeny** [comment]
The problem is definitely related to profile names, but Russian / other Unicode characters are fine. Do you have any profiles with dots in their names? Then you'd have to edit the profile ID manually and remove the dots (dots are removed automatically for new profiles in v152+)

**Comment by Mirulmaar** [comment]
> The problem is definitely related to profile names, but Russian / other Unicode characters are fine. Do you have any profiles with dots in their names? Then you'd have to edit the profile ID manually and remove the dots (dots are removed automatically for new profiles in v152+)

Yes, I had names with dots. I removed them and everything worked. Thanks a lot!
