### ISSUE TITLE
Can't provide new hotkeys 

### ISSUE THREAD

**Issue by livesamarthgupta** [Eugeny/tabby#4404]
Hotkeys are not getting registered for any command.

**Comment by livesamarthgupta** [comment]
Also if I try to register a new hotkey, first it won't register then any hotkeys registered earlier will stop working unless tabby is restarted.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by livesamarthgupta** [comment]
My bad, the latest version doesn't have this issue. Hotkeys page, as well as hotkey registration, both are working fine.
