### ISSUE TITLE
Profile color not visible in selector [How to set icon color of Profiles?]

### ISSUE THREAD

**Issue by ech0-py** [Eugeny/tabby#4405]
Hey, just a question: How to set icon color of particular Profile/ssh connection?
Also isn't clear for me: where are such icons located physically?
![img](https://user-images.githubusercontent.com/415353/129178505-3d0663ae-03d1-488c-bf35-3a762af6dc05.png)

**Comment by livesamarthgupta** [comment]
While creating a new profile there is a field for the font awesome icons, by default, it is fa-fa-desktop for ssh, you can edit it right there.

**Comment by livesamarthgupta** [comment]
I just tried it out, I am right. Just do it this way in the custom css box.
```.fa-cloud { color:red !important}```
Change icon class as required.

**Comment by ech0-py** [comment]
@livesamarthgupta wow, thanks a lot, that works

To maintainers: mb we can add such information into wiki pages? It could be very useful for users without frontend experience

**Comment by Eugeny** [comment]
The icon actually uses the profile's tab color, which you can set/change in profile's settings.

**Comment by ech0-py** [comment]
@Eugeny but profile's color doesn't apply to the icon in profile-selector popup, while the solution provided by @livesamarthgupta works in both cases: Settings->Profiles and profile-selector

**Comment by Eugeny** [comment]
Oh good point - I'll make sure it applies in the selector too!
