### ISSUE TITLE
how to restart `tabby` program entirely

### ISSUE THREAD

**Issue by seyoatda** [Eugeny/tabby#4417]
When I try to set system environment, in windows terminal everything works fine, but `tabby` seems can't find the new environment, and I tried to restart it several times. After I install the update version, finally it can recognize the new environment variables. So I think maybe `tabby` has some invisible process hanging backend so that it can't refresh the env variables ?

**Comment by Eugeny** [comment]
There are no background processes - it exists as soon as you close the last window.

**Comment by seyoatda** [comment]
> There are no background processes - it exists as soon as you close the last window.

it seems this bug is caused by powershell. Now everything works fine and I can't reproduce it now. Thanks for your reply.
