### ISSUE TITLE
Cannot install on Debian 11

### ISSUE THREAD

**Issue by saudiqbal** [Eugeny/tabby#4425]
When I install tabby in Debian 11 with Discover I get 'Dependency resolution failed' is there any other way to install tabby in debian?

**Comment by Eugeny** [comment]
Please try installing it manually via `apt` to see which specific dependencies are failing.

**Comment by saudiqbal** [comment]
Looks like I cannot install libappincicator1 on Debian11
This is what I get

apt-get install libappindicator1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libappindicator1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
