### ISSUE TITLE
How do I close tabs quickly ?

### ISSUE THREAD

**Issue by sober-wang** [Eugeny/tabby#4435]
I want disable the `Press any key to reconnect` , so what should I do ?
![image](https://user-images.githubusercontent.com/35804630/129822159-38b5f529-19dd-40c4-a839-73e10049a531.png)

And when I do close tabs quickly , can you tall me the hotkey  or how do set the hotkey?

**Comment by Eugeny** [comment]
It's the "close tab" hotkey in Settings -> Hotkeys, default Ctrl-Shift-W / Cmd-W
