### ISSUE TITLE
Stuck processes, cannot restart app

### ISSUE THREAD

**Issue by qqgu** [Eugeny/tabby#4442]
no response by double click on tabby.exe after installation.

**Comment by Okumura2** [comment]
On Alpha 154, tabby's tasks will continue remain even if the app was closed.
I think that causes the app to not be able to launch.

Platform: win64 10.0.19042
Plugins: none

**Comment by veelasky** [comment]
Have the same issue, background process still running when the app was closed.

Version: 1.0.154
Platform: Windows x64 10.0.22000
Plugins: none
Frontend: xterm

**Comment by drumm2k** [comment]
Same issue - background processes still running after relaunching app so i can't terminate or run them
Version: 1.0.168
Platform: MacOS 12.0.1 arm64
Plugins: none
Frontend: xterm
