### ISSUE TITLE
How to run inital command on SSH profile?

### ISSUE THREAD

**Issue by yphastos** [Eugeny/tabby#4452]
when I connect to a remote server via command line, I can run a `ssh` with an initial command like this:
e.g.
`ssh -o ServerAliveInterval=100 -t user@x.x.x.x "cd /custom/path/ ; bash"`

Being `cd /custom/path/ ; bash` the initial command, so in this case I always jump to such path instead of being at my home (~).

In other tools like MobaXterm, I can simply use the `Execute command` option under `Advanced SSH Settings`
How can I do it on Tabby?

Or instead of an initial custom command, is there another way to specify the initial path upon connection?

Sorry if it is obvious, but I have just installed Tabby and playing around with it.

**Comment by Eugeny** [comment]
You could add "cd ...\n" as a login script, using an empty string or a part of your prompt as the "expect" pattern. These only execute once after the connection and should work well for your purpose

**Comment by yphastos** [comment]
@Eugeny Thanks! It worked perfectly! 

However, is there a reason you suggested to add `\n` at the end of the command? I guess it is intended to act as a return (Enter) to run the command? Because I didn't add it and still worked.

I'm closing the issue as you solution solves it.

But, going a bit off-topic, I'd like to ask, what is the original intended purpose of the Expect / Send login scripts anyway? Some examples would be useful.

Thanks again.

**Comment by Eugeny** [comment]
Glad it worked. You can use login scripts whenever the remote system asks for data during login - which is often the case for serial or telnet connections - in this case Tabby can listen for the prompt and answer automatically. A good example is the standard Linux login prompt (username and password) on Telnet. Also see [expect(1)](https://linux.die.net/man/1/expect)

**Comment by yphastos** [comment]
oh I see! so I guess the remote system could prompt you with different "terms", and that's why you can have several expect-send options, to have response for each. Interesting!
