### ISSUE TITLE
SFTP uploads always fail

### ISSUE THREAD

**Issue by preechaw** [Eugeny/tabby#4455]
Version: 1.0.155
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

When I upload a file, it will appear with a size of zero bytes and with .tabby-upload suffix added.
<img width="207" alt="2021-08-20_13h01_44" src="https://user-images.githubusercontent.com/23615475/130187307-1b5fe863-3604-4e84-9af3-218b5ce32fad.png">

There will be a floating box named "File transfers".
<img width="274" alt="2021-08-20_13h00_30" src="https://user-images.githubusercontent.com/23615475/130187124-738b725f-5d84-4e59-8254-7bd85c84bcc7.png">

The upload will fail eventually.

I'm not sure if it's a configuration problem.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by dbahmatov** [comment]
Same issue #4383
