### ISSUE TITLE
hotkeys for changing from split to split?

### ISSUE THREAD

**Issue by stefangweichinger** [Eugeny/tabby#4456]
Sorry for opening an issue for such a small question, but I couldn't yet find it in this repo, in the issues or the hotkeys in the app:

are there hotkeys to change from split window to split window? It would be great to be able to hop between them without using the mouse. Thanks for any information on this, keep up the good work ;-)

**Comment by Eugeny** [comment]
Yep - it's the "Focus the pane on the top/bottom/left/right" and "Focus previous/next pane" hotkeys in Settings -> Hotkeys.

**Comment by stefangweichinger** [comment]
That doesn't work for me. Ctrl-Alt-Up writes "A" ... Ctrl-Alt-Down writes "B" ... maybe something in my bash-config?
