### ISSUE TITLE
WinSCP really should be available from rt clicking on the tab.

### ISSUE THREAD

**Issue by watchingfun** [Eugeny/tabby#4468]
Thanks @bernardyip . Found out that it is visible in a right click on terminal but not on rt click on the tab itself at the top. In addition, I had rt. click set to "paste" in settings, so I had to change that to expose WinSCP option.
WinSCP really should be available from rt clicking on the tab.

![image](https://user-images.githubusercontent.com/32370793/102808307-fe7ffc80-4374-11eb-84c1-f94f4d06fe39.png)

_Originally posted by @plrnr in https://github.com/Eugeny/tabby/issues/3138#issuecomment-749118802_

**Comment by Eugeny** [comment]
This has already been fixed since then - "Launch WinSCP" is available through the tab menu
