### ISSUE TITLE
SFTP upload cannot work , version 1.0.155

### ISSUE THREAD

**Issue by oushuifa** [Eugeny/tabby#4475]
[-1629790032356.log](https://github.com/Eugeny/tabby/files/7037361/-1629790032356.log)
This is my log file
![123](https://user-images.githubusercontent.com/53784478/130576668-dfa67698-84fb-4544-8ebe-e9d15efa04ef.png)
This is the error screenshot

**Comment by Eugeny** [comment]
Should be fixed in the latest nightly
