### ISSUE TITLE
The colors are not changed by base16-shell

### ISSUE THREAD

**Issue by henry-hsieh** [Eugeny/tabby#4492]
In [base16-shell](https://github.com/chriskempson/base16-shell), the colors are controlled by [Xterm Control Sequences](https://www.xfree86.org/current/ctlseqs.html#VT100%20Mode) using ANSI escape code. For example, `\033]4;c;spec\033\\` is used to change color number `c` to the color specified by `spec`. `\033]10;spec\033\\` is used to change foreground color specified by `spec`. The feature is supported by VTE terminals in Linux, e.g., Gnome Terminal. It's also supported by Windows Terminal, too. Currently, the displayed color is enforced by Tabby's colorscheme. Is there any chance that Tabby supports the feature?

**Comment by Eugeny** [comment]
Tabby does support both base16 and color customization through escape sequences in general, however on Windows, you need to enable ConPTY (Settings -> Shell) for it to work.

**Comment by henry-hsieh** [comment]
I have the same issue on certain version of Windows Terminal Preview a few months ago. Not sure whether they're related to ConPTY. For now Tabby (Alpha 174), Windows Terminal (1.12.10732.0), and Windows Terminal Preview (1.13.10983.0) are working fine. I'll close this issue. Thanks for your help!
