### ISSUE TITLE
No option in Settings to enable/disable global Ctrl-Enter hotkey?

### ISSUE THREAD

**Issue by nibble-4bits** [Eugeny/tabby#4493]
Version: 1.0.155
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm

---

So on the very first install of Tabby, the first window that appears shows an option to enable or disable the global `Ctrl-Enter` hotkey, which when used brings Tabby to the foreground:

![image](https://user-images.githubusercontent.com/38052706/131232905-ddbfe94c-6f80-497b-97f1-baaaf74e9207.png)

I've been looking for this option in Settings, but I couldn't find it anywhere. I don't know if this option can be toggled through the config file either.

The only fix I found for the moment was to uninstall Tabby and delete the `appData` directory (`<User>/AppData/Roaming/tabby` in my case, as I'm using Windows). That way I can access the option again on the first launch.

**Comment by Eugeny** [comment]
It's in Settings - Hotkeys - Toggle Window
