### ISSUE TITLE
Fix the name of conection - on tab 

### ISSUE THREAD

**Issue by KonsentoX** [Eugeny/tabby#4516]
Version: 1.0.146
Platform: win32 10.0.19043
Plugins: none

hi fellas, 
who opens a lot of connections will miss this feature. the tab shows exactly the same name Root@admin
and i already send wrong commands to a machine thinking that was another.

**Comment by Eugeny** [comment]
Could you clarify a bit? If you mean that all tabs are showing the same root@host value as title, you can either:
* Adjust your shell to report a better window name (the value shown is coming directly from the remote shell)
* Tick "Disable dynamic tab title" in connection settings to show the profile name instead.
