### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by ouvanous** [Eugeny/tabby#4531]
Hi, 

Just after installing Tabby, I accidentally unauthorized te access to te Documents folder on MacOS.
I don't know how to re-ask for permission on this folder? 
Now even after re-installed Tabby, i still can't access this folder. 
Many thanks for any hint 
Samuel

**Comment by Eugeny** [comment]
You need to re-enable it in macOS security settings: 
![image](https://user-images.githubusercontent.com/161476/131853219-996f52db-abdc-4164-bf34-2b650e6d6bd8.png)

Alternatively, add Tabby to the Full Disk Access list.

**Comment by ouvanous** [comment]
Many thanks!
