### ISSUE TITLE
Publish an official Arch Linux AUR package

### ISSUE THREAD

**Issue by mnixry** [Eugeny/tabby#4538]
Now, we have the `.pacman` package that can be installed perfectly on Arch Linux. #3761

And due to the renaming of the project, there is currently no AUR package with the same name as the package name `tabby-terminal`

Although I do not understand the packaging process of Electron applications, since we can already build usable `.pacman` files, we possible only need to set a GitHub Action which will be trigged by `release` to release AUR package.

So I think it's time to release an official AUR package so that users can get continuous and stable updates. I honestly believe this is what the majority of Arch users are willing to see.

**Comment by Xenolphthalein** [comment]
There is this AUR package: https://aur.archlinux.org/packages/tabby/
But sadly it's poorly maintained as the maintainer has not enough time to do it. 
But as SolarAquarion (the maintainer) said, it would be possible to add someone as co-maintainer. (See #176 )

I second the idea of @mnixry with github actions as it is a clean automated way for distributing the newest update to the arch users doorstep.

**Comment by Eugeny** [comment]
I'm still very new to Arch - could you please link the relevant documentation on publishing .pacman packages on AUR?

**Comment by mnixry** [comment]
> Could you please link the relevant documentation on publishing .pacman packages on AUR?

It seems that we just only need to [write a `PKGBUILD` file](https://wiki.archlinux.org/title/PKGBUILD) that gets the released version of the `.pacman` file from GitHub. And publish it with this [Github Action](https://github.com/marketplace/actions/publish-aur-package) at release.

For instance, here is an AUR package that is similar to Tabby for your reference: https://aur.archlinux.org/packages/yesplaymusic/

**Comment by ErikReider** [comment]
Here's an [example](https://github.com/ErikReider/SwayNotificationCenter/blob/75894f50ff49b31e9024df3fe6ce97f09f6eb6ad/PKGBUILD) that I created a while ago.

There's more documentation here: https://wiki.archlinux.org/title/PKGBUILD

**Comment by Plarpoon** [comment]
would actually love to see that, gonna be honest installing it this way gave me a headache. Keep up the good work, terminal looks clean!

**Comment by mnixry** [comment]
I've published an AUR package named [`tabby-terminal`](https://aur.archlinux.org/packages/tabby-terminal). Welcome to have a try!

@Eugeny If you prefer, you can reply to me at any time, I can add you as Co-maintainer to this package.

---

I'm also working on a GitHub Action to publish this automatically, and I'll submit a PR to the repository when I'm done with that

**Comment by Eugeny** [comment]
Thanks! Is there anything I have to keep in mind when releasing updates?

**Comment by mnixry** [comment]
> Thanks! Is there anything I have to keep in mind when releasing updates?

For now, please keep the release file in the same format, I am writing it like this:
```shell
https://github.com/Eugeny/tabby/releases/download/v${pkgver}/tabby-${pkgver}-linux.pacman
```

---

> I'm also working on a GitHub Action to publish this automatically, and I'll submit a PR to the repository when I'm done with that

I found it's difficult to integrate the Action to this repository. I'll keep an outside repository with GitHub Action to keep the package up-to-date.

If anyone has better ideas or solutions on this matter, please feel free to reply to me!

**Comment by mnixry** [comment]
> I'll keep an outside repository with GitHub Action to keep the package up-to-date.

I have done this, and it is written in the [GitHub Action file in my repository](https://github.com/mnixry/mixout-aur/blob/master/.github/workflows/check-release.yml). 

Expectedly, it will check for Tabby updates every hour, and post the new version to AUR within two hours. I think that's probably enough.

I'll close this Issue, because I think I've served the purpose of this issue. Feel free to keep replying to this issue. I'll reply as much as I can.

**Comment by SolarAquarion** [comment]
@mnixry what is your aur username

**Comment by SealsRock12** [comment]
> I've published an AUR package named [`tabby-terminal`](https://aur.archlinux.org/packages/tabby-terminal). Welcome to have a try!

That link doesn't work, am I missing something?

**Comment by SolarAquarion** [comment]
It should work. But you need to do an actual source build. I'll add tabby
to chaotic at worst
