### ISSUE TITLE
problem with syncing ftp folder

### ISSUE THREAD

**Issue by patricheg** [Eugeny/tabby#4546]
Version: 1.0.156
Platform: Windows x64 10.0.19042
Plugins: cloud-settings-sync
Frontend: xterm

Hi. I can`t use ftp sync, i tried any servers and services, but tabby couldn`t connect. Server logs said that everything is ok.

**Comment by Eugeny** [comment]
This is a third party plugin, please report issues to https://github.com/niceit/tabby-cloud-sync-settings
