### ISSUE TITLE
Merge pane

### ISSUE THREAD

**Issue by 17379152565** [Eugeny/tabby#4563]
Hi, How can I merge these panels?

![image](https://user-images.githubusercontent.com/50432760/132459212-61448958-cc25-4b53-8ff8-21aae6203221.png)

I split a panel into multiple panels by pressing shortcut keys, and then how do I merge them?

Version: 1.0.155
Platform: macOS x64 19.6.0
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
There's no way to "detach" panes back into tabs at this time
