### ISSUE TITLE
Cannot properly input "~" symbol from keyboard

### ISSUE THREAD

**Issue by HF0** [Eugeny/tabby#4564]
I use the `AltGr + 4` combination to input the `~` symbol. For example, usually pressing `AltGr + 4` and then `<space>` will show `~`.
However in tabby I get a weird behaviour. If I press `AltGr + 4` and then `<space>`, `4~` is shown. This only seems to happen with this key not the rest of symbols that can be input using AltGr

Os: Win10 x64

**Comment by Eugeny** [comment]
Could you please retest with the latest release?

**Comment by HF0** [comment]
I can confirm that this bug has been solved in version 1.0.156 alpha
