### ISSUE TITLE
Some hotkeys don't auto repeat themselves when keeping keys pressed.

### ISSUE THREAD

**Issue by yphastos** [Eugeny/tabby#4566]
I've notice that at least a few hotkeys, specially the ones using the `Ctrl` key, don't auto-repeat the action when they are kept pressed.

e.g. if I do `Ctrl+right_arrow` or `Ctrl+left_arrow`, I expect to jump between words constantly, until I depress the keys, but instead, only one word is jumped, and if I want to jump another one, I have to depress the arrow and press it again.

It is very annoying under certain cases. e.g. I sometimes write long commit messages, and then I realize I made a typo at the beginning of the message, and need to quickly jump a bunch of words back. Needing to keep tapping the arrows instead of keeping them depressed is bothersome.

I know I could use the `home`or `end` keys to quickly jump to the beginning or end of the line, but I still need to jump a bunch of  words on either direction.

I don't know if this behavior is expected, or just a bug. But if it is expected, what's the reason? In any case you could give us an option to toggle it.

Thanks!

**Comment by yphastos** [comment]
Forgot to say that it also happens at least with the `Ctrl+Backspace`  and `Ctrl+Delete` hotkeys.

Also, I'm using windows if that's relevant.

**Comment by cpecorari** [comment]
Hi, +1, on Macos Monterey M1 Pro, Tabby `1.0.167` .
And pretty annoying as previously mentionned to come back quickly in a command and change a parameter for example.
Thanks !

**Comment by JLarky** [comment]
Can confirm, `option`+`anykey` doesn't repeat in Monteray in `1.0.167`

**Comment by cpecorari** [comment]
Hey, just found out that removing tabby setting hotkey `Alt+Left` and right, i just get default OS behavior and auto-repeat keys 👍

**Comment by JLarky** [comment]
unfortunately, that's not the case for me :)
![image](https://user-images.githubusercontent.com/7026/147880050-54c3631d-1a76-4021-8262-175b63cb637e.png)

**Comment by cpecorari** [comment]
Sorry it's not really `Alt` but the Mac `Option` key :
<img width="727" alt="Capture d’écran 2022-01-02 à 19 19 57" src="https://user-images.githubusercontent.com/56672657/147885478-4d30ccd9-bf52-4ded-9c7c-cda2cb3fc3d0.png">
Here remove the `Jump to previous word` and jump to next word ;)

**Comment by JLarky** [comment]
> Sorry it's not really `Alt` but the Mac `Option` key : 
> Here remove the `Jump to previous word` and jump to next word ;)

thanks! I rarely use MacOS :) but indeed, removing "jump to previous word" and "jump to next word" helped! 
![image](https://user-images.githubusercontent.com/7026/147889380-8f92eacf-256d-46ea-b822-e1c4f87dbfce.png)

**Comment by yphastos** [comment]
> Here remove the `Jump to previous word` and jump to next word ;)

Well, in windows it wouldn't make sense, because jumping words is precisely the hotkeys I want to get repeated.
Update, now I get it! the point is precisely to remove the Tabby hotkeys altogether, and let the OS take over. It indeed works for me, at least for `Jump Left/Right`. Thanks.

N.B. For some reason, in my hotkeys list, each left and right show TWICE:

![image](https://user-images.githubusercontent.com/13773388/147952352-7d0fa330-e625-40d2-ba7c-5ccfa72a00ea.png)

and removing/editing either affects the other duplicated one.

I don't know if it's an additional bug or something, but at least I got it working.

**Comment by cpecorari** [comment]
> N.B. For some reason, in my hotkeys list, each left and right show TWICE:
> and removing/editing either affects the other duplicated one.
> 
> I don't know if it's an additional bug or something, but at least I got it working.

You are right, same for me, did not focus on that as it is not ground breaking, but maybe we should start a new issue on this one, the search by keyword pops twice the results.
