### ISSUE TITLE
[Question] How to prevent opening previous session on start? 

### ISSUE THREAD

**Issue by recolic** [Eugeny/tabby#4583]
By default, when I'm starting terminus, it will keep all history, and `cd` into the previous directory. It's trying to pretend that, the previous session is still alive. 

How to disable this feature? I'm expecting a new SSH session, instead of a unclean strange screen filled with useless output.

**Comment by Eugeny** [comment]
![image](https://user-images.githubusercontent.com/161476/132886548-abca358e-f492-4df4-a814-80b7dddd2703.png)

You can disable it in the settings.
