### ISSUE TITLE
Font ligatures doesn't work on Mac M1 (Bigsur v11.5.2)

### ISSUE THREAD

**Issue by lthoangg** [Eugeny/tabby#4584]
![Enable](https://user-images.githubusercontent.com/59216583/132933205-630f2524-1efe-4787-a442-532c313e47e6.png) 
Enable font ligatures is on but it doesn't work at all (image below)
![Doesn't work](https://user-images.githubusercontent.com/59216583/132933241-2e0b7c11-871b-42e0-ba6f-1c6b0ec1b8fc.png)

I'm using Tabby version *1.0.157*.
Somebody with the same issue?
Thanks

**Comment by Eugeny** [comment]
Does the Menlo font actually include any ligatures?

**Comment by lthoangg** [comment]
I've tried to change many different fonts and switch _ligatures_ on off but it doesn't seem to work at all.

Can you help me?
Thanks.

**Comment by Eugeny** [comment]
System fonts don't normally support ligatures, you need a special font like Fira Code or one of the Nerd font series.
