### ISSUE TITLE
[Feature request] Option to choose Color scheme each tab/profile

### ISSUE THREAD

**Issue by kobemtl** [Eugeny/tabby#4593]
Hi, Thanks I want to thanks for the great job. Been using Tabby (Teminus) for a long time and love it a lot. I am just wondering if it's possible to have a option to choose different colour schema on each tab? or set different schema on different profile? Thanks.

**Comment by Eugeny** [comment]
It's currently not possible, but thanks for the suggestion!

**Comment by pglezen** [comment]
For SSH users, this would really help avoid the error of typing a command in the wrong window.  Typically one uses different backgrounds (or color schemes) for different environments such as DEV, TEST and PROD.

**Comment by vicmunoz** [comment]
Yes please, basic feature. Different font size if I work on laptop display or external monitor.
