### ISSUE TITLE
can't open new tab as admin - windows 11

### ISSUE THREAD

**Issue by BicheT0rdue** [Eugeny/tabby#4594]
Version: 1.0.157
Platform: Windows 11 x64 22000.184
Plugins: theme-hype, quick-cmds, clippy, clickable-links
Frontend: xterm

even if i launch the app as administrator when i try to open a new tab as admin it doesn't work.

**Comment by terpenes** [comment]
Same with me on Windows 10 brother. I thought I was going crazy.
