### ISSUE TITLE
Can't open admin tab.

### ISSUE THREAD

**Issue by terpenes** [Eugeny/tabby#4601]
Version: 1.0.157
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

Unable to open an admin tab on Windows 10, meanwhile the old Terminus works flawlessly. I had to download terminus to check to make sure.

**Comment by ggiesen** [comment]
I have the same issue. Reverting to 1.0.146 seems to solve it (broken from 1.0.147 onward)

**Comment by devopsmyth** [comment]
Same issue here on Windows 11
Tabby version 1.0.168
