### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by SebUll** [Eugeny/tabby#4607]
Version: 1.0.157
Platform: macOS arm64 20.6.0
Plugins: none
Frontend: xterm

Hi...

i downloaded the color shemes but it is only black an white... is this my mistake or an misunderstood or is this behavior right?

![Bildschirmfoto 2021-09-16 um 14 38 06](https://user-images.githubusercontent.com/43009765/133613663-029dce21-0449-4b36-a3fa-8e07bba394cc.png)

thanks for this app

**Comment by Eugeny** [comment]
You have chosen a set of colours, but the programs you're running (e.g. `ls`) aren't producing coloured output. Check this out: https://apple.stackexchange.com/questions/33677/how-can-i-configure-mac-terminal-to-have-color-ls-output

**Comment by SebUll** [comment]
Ich dachte wenn ich eine Farbschema auswähle dann wird es auch übernommen?

<img width="804" alt="Bildschirmfoto 2021-09-16 um 15 58 07" src="https://user-images.githubusercontent.com/43009765/133625650-867a402c-e8be-4771-ae74-e5e479f2d4f6.png">

**Comment by Eugeny** [comment]
Yes, but Tabby doesn't magically colorize the black-and-white output of other programs. Your output needs to be colorized in the first place, color schemes only change the colours themselves. Compare `ls` and `ls --color=always`
