### ISSUE TITLE
Support Ubuntu inside Windows 10+

### ISSUE THREAD

**Issue by maxbrito500** [Eugeny/tabby#4638]
Hello,

Nowadays is possible to install Ubuntu natively inside Windows using the Linux sub-system. This means access to the normal linux command line tools and mechanisms such as "ls", "apt" and so on.

Using the console available by default from Ubuntu is functional from a technical perspective but uses the same style/theme as the cmd.exe and that is simply disappointing. This is where tabby could help.

Perhaps possible to detect with the linux sub-system is available and permit running the linux commands as well?

Many thanks

**Comment by Eugeny** [comment]
Yes, you can find your WSL distros in the profile list.

**Comment by maxbrito500** [comment]
Thanks, found it. What an amazing console. ^_^
