### ISSUE TITLE
How to configure the language

### ISSUE THREAD

**Issue by slatonwu** [Eugeny/tabby#4640]
How to configure the language?

**Comment by psyuhen** [comment]
不知道哪里配置的

**Comment by Jonnyan404** [comment]
暂时不支持,估计得等等了...

**Comment by slatonwu** [comment]
The software itself should be internationalized。

![image](https://user-images.githubusercontent.com/9948988/134631014-8fb407d9-6ad5-4bc7-99bf-395ede46e1cd.png)

**Comment by ydcool** [comment]
> The software itself should be internationalized。
> 
> ![image](https://user-images.githubusercontent.com/9948988/134631014-8fb407d9-6ad5-4bc7-99bf-395ede46e1cd.png)

I think those language files are from the Electron...

**Comment by Eugeny** [comment]
Duplicate of #2538
