### ISSUE TITLE
ZSH set powerline font still display abnormal

### ISSUE THREAD

**Issue by JiangBoy** [Eugeny/tabby#4682]
Version: 1.0.158
Platform: Windows x64 10.0.17763
Plugins: none
Frontend: xterm

![image](https://user-images.githubusercontent.com/12654896/135427589-57b2dc3a-3897-4ddd-8e09-6d3593a75ef3.png)

![image](https://user-images.githubusercontent.com/12654896/135427410-909e1886-6f17-413b-ad39-620eea757a9b.png)

**Comment by Eugeny** [comment]
You need to select the Powerline version of Dejavu Sans Mono in the Font field.

**Comment by JiangBoy** [comment]
> You need to select the Powerline version of Dejavu Sans Mono in the Font field.

![image](https://user-images.githubusercontent.com/12654896/135560568-f894cc39-ae7a-4b02-9e62-92723da67358.png)
![image](https://user-images.githubusercontent.com/12654896/135560665-32d780ce-d3eb-4acc-8933-47212ec155dc.png)

**Comment by JiangBoy** [comment]
> > You need to select the Powerline version of Dejavu Sans Mono in the Font field.
> 
> i try select Powerline font, but the terminal display is even stranger
> 
> ![image](https://user-images.githubusercontent.com/12654896/135560568-f894cc39-ae7a-4b02-9e62-92723da67358.png) ![image](https://user-images.githubusercontent.com/12654896/135560665-32d780ce-d3eb-4acc-8933-47212ec155dc.png)

i found another problem, i use microsoft recommend font is ok, but use other recommend font is fail
https://github.com/microsoft/cascadia-code/
https://github.com/powerline/fonts

**Comment by stayupthetree** [comment]
I am having the same issue all powerline fonts appear that way forcing me to use non powerline which means missing fonts in my terminal, forcing me fallback to plain bash

**Comment by huangcs427** [comment]
> I am having the same issue all powerline fonts appear that way forcing me to use non powerline which means missing fonts in my terminal, forcing me fallback to plain bash

You can try to install the font on https://www.nerdfonts.com/font-downloads and set the font in Tabby, 
![image](https://user-images.githubusercontent.com/31842636/148032751-7e6dda40-f488-4e68-adc5-4d50cf2cba9a.png)

I installed JetBrainsMono font, it can display the icon of zsh theme normally
![image](https://user-images.githubusercontent.com/31842636/148032812-5fc4860e-3e86-4c85-a33c-0eff8898a8b4.png)

**Comment by 1JunGu** [comment]
> > I am having the same issue all powerline fonts appear that way forcing me to use non powerline which means missing fonts in my terminal, forcing me fallback to plain bash
> 
> You can try to install the font on https://www.nerdfonts.com/font-downloads and set the font in Tabby, ![image](https://user-images.githubusercontent.com/31842636/148032751-7e6dda40-f488-4e68-adc5-4d50cf2cba9a.png)
> 
> I installed JetBrainsMono font, it can display the icon of zsh theme normally ![image](https://user-images.githubusercontent.com/31842636/148032812-5fc4860e-3e86-4c85-a33c-0eff8898a8b4.png)

Hi, I have downloaded this font but confused about how to set the font in Tabby, could you please tell me how? 
OS: Win 11
tabby version: Alpha 172
