### ISSUE TITLE
Missing SSH feature

### ISSUE THREAD

**Issue by namth0712** [Eugeny/tabby#4738]
Hi, I can't see SSH tab or create SSH connection for profile in my macos, (still see in my windows).
What I'm missing?

If I import config from existing, they still shows on profile list, but not clickable.

OS: macOS Big Sur
Tabby version: Alpha 159

<img width="1377" alt="Screen Shot 2021-10-11 at 12 24 45" src="https://user-images.githubusercontent.com/44791771/136737620-7ebba5dc-21d1-4d16-8980-819b283a7a00.png">

**Comment by Eugeny** [comment]
Is the SSH plugin enabled in Settings -> Plugins?

**Comment by namth0712** [comment]
Oh, I found it, "Disabled". Thank you.
