### ISSUE TITLE
Admin Tab Doesn't Work as Expected

### ISSUE THREAD

**Issue by gssakash** [Eugeny/tabby#4793]
The Admin Tab Does not seem to work for any of the command-line shell variants that are generally used ranging from Git Bash to the normal Command Prompt on Windows. 
I am attaching a video below demonstrating the issue.

https://user-images.githubusercontent.com/52027687/137927609-d29cbc0d-5343-4eb8-a9c1-e0ce43044a46.mp4

**Comment by Darkmagister** [comment]
i'm having the same issue with the latest tabby version 1.0.168 and windows 10 19044.1348

**Comment by spydx** [comment]
+1 , experiencing the same 
Version: 1.0.169
Platform: Windows x64 10 19043.1415
Frontend: xterm

**Comment by devopsmyth** [comment]
+1 for same issue

### Windows OS
OS Name:	`Microsoft Windows 11 Pro for Workstations`
Version:	`10.0.22000 Build 22000`

### Tabby
Version: `1.0.168`

### Problem Description
> As soon as the tab opens, it immediately closes before I can see anything. Doesn't matter which shell I'm attempting to open and I'm running Tabby with Administrator privileges (**Elevated**).

**Comment by E9C81F815E536B97AB4086B7A60D79D5178B435** [comment]
+1 for the same issue

Version: 1.0.170
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm

**Comment by Fakas** [comment]
Same here.
OS: Windows 11 Pro
OS Build: 22000.493
Tabby: 1.0.173
Frontend: xterm 
Plugins: None.

**Comment by wuminhao** [comment]
same issue

**Comment by gwojtak** [comment]
I am running into the same issue.  I found that if I start Tabby as Administrator and then launch a CMD profile that is marked as Administrator, it does work.  Seems to be some issue with spawning the Administrator profile from a process started without Admin privileges.

**Comment by Fronix** [comment]
Same issue here

```
Version: 1.0.174
Platform: Windows x64 10.0.19044
Plugins: workspace-manager
Frontend: xterm
```
