### ISSUE TITLE
When selecting a tab with a session containing multiple panes needing vault unlocking, unlocking is asked multiple times

### ISSUE THREAD

**Issue by mullerch** [Eugeny/tabby#4811]
Reproduction:

1. Open tabby
2. Create a profile with a saved password (vault enabled)
3. Open two session in a single tab with this profile
4. Close tabby
5. Open tabby, it opens the tab with the two session tab by default

Expected result : the vault unlock is asked one. When unlocked, both sessions can connect

Actual result: the vault unlock is asked once by session

**Comment by psyuhen** [comment]
这是一个操蛋的功能。。。真是操心的功能。
