### ISSUE TITLE
Can't see text

### ISSUE THREAD

**Issue by sonphung90** [Eugeny/tabby#4840]
Version: 1.0.159
Platform: macOS x64 21.1.0
Plugins: sync-config
Frontend: xterm

After update macOS to Monterey i got this issue

![image](https://user-images.githubusercontent.com/13192845/138993923-e162dd91-1985-457f-b5d2-24cfe9962f77.png)

**Comment by Eugeny** [comment]
Is the problem specific to the font you're using? It looks like the issue happens when trying to parse the font data for ligature support.

**Comment by sonphung90** [comment]
> Is the problem specific to the font you're using? It looks like the issue happens when trying to parse the font data for ligature support.

I use nomal font: Monaco
![image](https://user-images.githubusercontent.com/13192845/139613802-31fb54f8-77aa-40cd-b2e6-bb8afaf69771.png)

**Comment by sonphung90** [comment]
Update: After disable font ligatures, issue is gone
![image](https://user-images.githubusercontent.com/13192845/139614012-3fe0847a-7768-4ce8-88a5-8c8e14741e84.png)
