### ISSUE TITLE
Feature Request: Start a web-search with marked text

### ISSUE THREAD

**Issue by darkiop** [Eugeny/tabby#4858]
First of all a big praise for this great piece of software ;) 

I had the thought today while checking the logfile how great it would be if you could put marked text directly from the terminal into the search engine of the default browser.

Would something like that be possible?

**Comment by composer404** [comment]
Hi, I wrote a plugin that gives you a possibility to open an internet search engine with a selected text. 
https://github.com/composer404/tabby-search-in-browser

Let me know if this solution is helpful for you and if you have any problems or ideas, create an issue in plugin's repository :)

**Comment by darkiop** [comment]
Hi, thx a lot! It works pretty fine!

What I have noticed in this context: Normally I use the direct insert with the right mouse button and therefore I don't have a context menu. Instead of the right mouse button I could use the middle one or @Eugeny would it be possible to open the context menu via a long right click (= short = paste / long = menu)?

@composer404 Maybe you could rename Open in Browser to "Search with Browser" - but that's just cosmetic ;)

**Comment by Eugeny** [comment]
@darkiop done!
