### ISSUE TITLE
File Transfers can not show information

### ISSUE THREAD

**Issue by lxy85034** [Eugeny/tabby#4860]
Version: 1.0.159
Platform: Windows 10 x64 20H2 19042.1288
If i set the "Tabs location" is left, file transfers can not show information. It was covered by terminal window。
![issue](https://user-images.githubusercontent.com/28258195/139610512-924f5b40-a068-411f-adee-0f7b8e2a554e.png)

**Comment by Eugeny** [comment]
Fixed in the latest release
