### ISSUE TITLE
ssh Handshake failed: signature verification failed

### ISSUE THREAD

**Issue by qliang0816** [Eugeny/tabby#4864]
I use the latest version(v1.0.161).
when connect some service,it shows handshake failed,but other tools like termius、electerm works.
And * ssh id@ip * also works.
![capture-screen_c48d93c0-3ba8-11ec-b68d-f018980478e7](https://user-images.githubusercontent.com/24631867/139799600-f49a12a7-2de4-4cc6-8001-e75911bc1a89.png)

**Comment by JaminYe** [comment]
Me too, did you solve it

**Comment by qliang0816** [comment]
no

**Comment by psyuhen** [comment]
Me too, if your password has contains  * #  ,.

**Comment by qliang0816** [comment]
my pass dont`t have these words..

**Comment by KerwinKwong** [comment]
Me too, did you solve it

**Comment by qliang0816** [comment]
> Me too, did you solve it

no

**Comment by jdlaroche** [comment]
I had this issue when connecting to an older OS and I solved it by unchecking some of the "Host key" ciphers in the profile.

**Comment by qliang0816** [comment]
> I had this issue when connecting to an older OS and I solved it by unchecking some of the "Host key" ciphers in the profile.

i uncheck all the "host key" and it works.thanks.

**Comment by KerwinKwong** [comment]
I still can't use the old switch after doing this
