### ISSUE TITLE
tabby-docker can not download

### ISSUE THREAD

**Issue by SemiThin** [Eugeny/tabby#4873]
where i download plugins docker is error

![图片](https://user-images.githubusercontent.com/12593507/140039931-9707c818-970c-4698-985f-660e59aad44c.png)

![图片](https://user-images.githubusercontent.com/12593507/140038783-38df970e-c59d-4c1f-9070-b8143b6783a3.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by SemiThin** [comment]
![图片](https://user-images.githubusercontent.com/12593507/141615286-4afafbd2-645b-4614-af80-7cf08de88bd1.png)

![图片](https://user-images.githubusercontent.com/12593507/141615289-7addb22b-f1ab-4571-a8dc-4ec148f37e89.png)
@Eugeny

**Comment by Eugeny** [comment]
Fixed in v0.1.0
