### ISSUE TITLE
Bug "Open Tabby here" not available in Windows 11

### ISSUE THREAD

**Issue by pthoelken** [Eugeny/tabby#4875]
Windows 10: "Open / Start Tabby here" is avilable
Windows 11: "Open / Start Tabby here" is not available

I've already re-install Tabby by the setup.

![image](https://user-images.githubusercontent.com/12643853/140223508-fc8fe136-3c2c-44c8-8ad6-285bf1631248.png)

**Comment by Eugeny** [comment]
Is shell integration enabled in Settings -> Application?

**Comment by pthoelken** [comment]
My bad. Sorry #closed

**Comment by unikzforce** [comment]
@Eugeny There is still one little problem.

In windows 11 you have to click on `show more items` to see `open tabby here` and it's not visible by default:

![image](https://user-images.githubusercontent.com/7010566/175758336-6d512c99-3eca-45c7-8e51-9fcfe3a8f193.png)

![image](https://user-images.githubusercontent.com/7010566/175758359-6a8f8710-22e1-44b9-b0e5-e3bbf2d75230.png)

**Comment by pthoelken** [comment]
https://pureinfotech.com/bring-back-classic-context-menu-windows-11/

**Comment by lukasong** [comment]
I'm not sure why this was marked as closed as this is not a solution what so ever.
