### ISSUE TITLE
[linux] can't open New terminal

### ISSUE THREAD

**Issue by Paul75** [Eugeny/tabby#4881]
Version: 1.0.161
Platform: Linux x64 5.14.16-204.current
Plugins: clickable-links
Frontend: xterm

Hello,

In linux I can't open New terminal when I click nothing to do. Same to Profiles and connections....

Thanks

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by TraceyC77** [comment]
Version: 1.0.169
Platform: Linux x64 5.14.21-210.current
Plugins: theme-gruvbox, relaxed-theme
Frontend: xterm

I've just duplicated this bug, running tabby from the extracted tarball for Linux on Solus (Plasma)
When launching tabby --debug I immediately see an error in the console. It complains about there being no such file or directory `/etc/shells`. Indeed, that file does not exist on Solus, which uses `/usr/share/defaults/etc/shells`

```js
ERROR Error: Uncaught (in promise): Error: ENOENT: no such file or directory, open '/etc/shells'
Error: ENOENT: no such file or directory, open '/etc/shells'
    at resolvePromise (zone.js:1213)
    at zone.js:1120
    at zone.js:1136
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28653)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
```
When I try to launch a new shell, I see the same error in console.
