### ISSUE TITLE
Sending scripts via serial like MTPutty

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#4901]
### Discussed in https://github.com/Eugeny/tabby/discussions/4900

<div type='discussions-op-text'>

<sup>Originally posted by **stevoid17** November  9, 2021</sup>
Hey all

I was wondering if there's a way of sending a script/config to devices via serial line by line, like the 'send script' option in MTPutty that stops serial adapters freaking out at the amount of data?

If not, it should definitely be added to the list!

Thanks

Steve</div>

**Comment by Eugeny** [comment]
@stevoid17 does MTPutty actually do anything besides splitting the input into lines and sending them one by one? Would it be enough to just do this while pasting? (i.e. you'd enable a "split paste into lines" option and then paste the script into the session and I'll feed it into the serial session line by line)

**Comment by stevoid17** [comment]
Apologies for the delay.

From what I can tell using it, it sends each character one by one as to not overload the paltry 9600 BAUD that cisco seems to prefer at default.

Split paste into lines should be OK as its only when you send whole configs that it bombs out, when using serial without the MTputty plugin using just putty, you have to break up your config into chunks.


Thanks!

**Comment by Eugeny** [comment]
Just pushed the implementation - let me know if it works for you!
