### ISSUE TITLE
There's no color 

### ISSUE THREAD

**Issue by blackgun** [Eugeny/tabby#4906]
I can't see any color whatever the theme I selected or restart. 

Env: macos 11.6, M1, tabby 1.0.161

**Comment by Eugeny** [comment]
To see color, the CLI application you're running should be producing colored output. In case you're testing with `ls -l`, color is disabled for it by default in macOS. 

Try `CLICOLOR=1 ls` or enable it permanently: https://apple.stackexchange.com/a/33679
