### ISSUE TITLE
Encoding troubles

### ISSUE THREAD

**Issue by shmd001** [Eugeny/tabby#4919]
Have some troubles with encoding
![issue](https://user-images.githubusercontent.com/36565312/141661164-b2761468-bd68-4fd7-814d-d7fe63632298.png)

**Comment by xtechman** [comment]
have same problems,can't find encode

**Comment by wawosz** [comment]
same problem, too.

**Comment by Eugeny** [comment]
Should be fixed now, please feel free to reopen if the issue repeats
