### ISSUE TITLE
macos: Auto update installs wrong architecture

### ISSUE THREAD

**Issue by Codex-** [Eugeny/tabby#4977]
Just an FYI, every time an update occurs with Tabby on M1 mac I'm finding that it installs the `x86_64` package instead of `arm64`

This consequently means that it runs terminals in an 'emulated' type of mode and causes odd behaviour or errors in things that are specifically expecting the correct architecture, such as brew:
```
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

Reinstalled every update to the arm64 package so far resolves this.

**Comment by Eugeny** [comment]
The latest release now uses Keygen and separate update channels per arch, so this won't come up again with the next update.

**Comment by piersandro** [comment]
Hi @Eugeny I recently updated to .185 and .186 but in both cases the update from the "Update" button in the settings downloaded the Intel version instead of the Apple Silicon one.

**Comment by piersandro** [comment]
.186 to .187 worked!

**Comment by Eugeny** [comment]
Good to hear! I still have no idea what could have gone wrong with .186 unfortunately as x64 and arm64 builds are now completely different "products" in the auto-updater service
