### ISSUE TITLE
confusion about ssh proxy command

### ISSUE THREAD

**Issue by BrunuhVille** [Eugeny/tabby#4981]
Hello,
My device is Windows 10, and I have a proxy which is socks5 listening on 127.0.0.1:10808
I have a Debian VPS abroad, and I want to connect it through the proxy, 
just assume the VPS ipv4 and ssh port is 6.6.6.6:22
How can I set the proxy command?

I have searched in issues, there is something like "nc -X 5 -x 127.0.0.1:10808 6.6.6.6 22", showing result "Proxy command has failed to start: spawn nc ENOENT"

Thank you very much

**Comment by xieccc** [comment]
> Hello, My device is Windows 10, and I have a proxy which is socks5 listening on 127.0.0.1:10808 I have a Debian VPS abroad, and I want to connect it through the proxy, just assume the VPS ipv4 and ssh port is 6.6.6.6:22 How can I set the proxy command?
> 
> I have searched in issues, there is something like "nc -X 5 -x 127.0.0.1:10808 6.6.6.6 22", showing result "Proxy command has failed to start: spawn nc ENOENT"
> 
> Thank you very much

You can try the `connect` command in windows

**Comment by BrunuhVille** [comment]
> 

Is there a official website to download connect.exe?
I'm pretty noob...

**Comment by BrunuhVille** [comment]
> You can try the `connect` command in windows

Is there a official website to download connect.exe?
I'm pretty noob...

**Comment by phpmaple** [comment]
When I use connect -S 127.0.0.1:7890 6.6.6.6 22, show result also  "Proxy command has failed to start: spawn connect ENOENT"

**Comment by Eugeny** [comment]
`connect` is a command that you need to install on your local machine. You can also try the nightly build, which has native support for SOCKS proxies without `ProxyCommand`
