### ISSUE TITLE
Is there a switch to disable the spirit?

### ISSUE THREAD

**Issue by wjiuxing** [Eugeny/tabby#4985]
Recently I upgrade the Tabby app to the version 1.0.164.
I'm curious if there is a switch that can disable or hide the spirit at the bottom right of my window.
It's strange as it always makes animations and sounds suddenly, even though the window is not active.

Thank you very much.

![image](https://user-images.githubusercontent.com/4176744/143195121-03281c8a-e32a-4565-9aff-45088316875c.png)

**Comment by Eugeny** [comment]
It's the `tabby-clippy` plugin, uninstall it.

**Comment by wjiuxing** [comment]
Got it. Thanks a lot.
