### ISSUE TITLE
how to save a terminal output, installed the plugin save-output, but not able to understand how to use to save terminal output

### ISSUE THREAD

**Issue by jayapalrb** [Eugeny/tabby#4994]
Version: 1.0.164
Platform: Windows x64 10.0.19042
Plugins: title-control, theme-hype, save-output, relaxed-theme, quick-restart, quick-cmds, fit-screen, elastic-quick-cmds, docker, clickable-links, clickable-ips
Frontend: xterm

**Comment by Eugeny** [comment]
The save-output plugin adds a context menu item that allows you to start streaming output into a file, or you can set it up in Settings -> Save Output so that all sessions are saved automatically.
