### ISSUE TITLE
 X  Handshake failed: signature verification failed

### ISSUE THREAD

**Issue by kussatom** [Eugeny/tabby#4995]
it's a beautiful tool ,but  i cannot use it to connect  network device ,such as cisco ,huawei ,the error is : X  Handshake failed: signature verification failed . how can i  fix this ,respect

**Comment by kussatom** [comment]
![image](https://user-images.githubusercontent.com/33589915/143518879-23cba315-c4f7-4e91-9076-b9931e74ab8d.png)

**Comment by fkurth** [comment]
Having this error as well. It's a mismatch between the KexChange algorithms tabby supports and the servers algorithms.
For the server i'm accessing (but cannot reconfigure), its set as:

`KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1`

None of these Algorithms are available in tabby. How to overcome this? Maybe its just a naming problem?

**Comment by fkurth** [comment]
Added the missing ciphers to config.json solved.

`      kex:
          - diffie-hellman-group-exchange-sha1
          - diffie-hellman-group-exchange-sha256
  `
But it only worked if these are the only entries there. Simply placing them on top of the ciphers list is not enough.

**Comment by pitylee** [comment]
This needs a solution.

**Comment by FrancisHG** [comment]
This is an issue for me, I cannot connect to one of my servers. Interesting that if I am using Tabby client locally it works fine, if I use Tabby.sh/app through the gateway it fails with this error. Same connection, but different results.

Handshake failed: signature verification failed
