### ISSUE TITLE
Any shortcut or key to zoom in 1 window of spilt windows

### ISSUE THREAD

**Issue by fanghuaqi** [Eugeny/tabby#4998]
Hi there, I want to find a shortcut to zoom in 1 window of split windows, but I don't find one, any hint?

Like the **Maximise terminal** feature present in gnome-terminator https://gnome-terminator.readthedocs.io/en/latest/gettingstarted.html#zooming-the-terminal

**Comment by Eugeny** [comment]
Yes - it's the "maximize active pane" hotkey (default: Cmd-Alt-Enter)

**Comment by fanghuaqi** [comment]
Ok, it works, I tried  gnome-terminator before, I found tabby.sh is a bit slow than it, any method to speed up it. 

The slow cases are like:
1. insert and remove is slow
2. scroll up and down is slow 

But tabby.sh has the feature of store windows layout, which is useful.

**Comment by fanghuaqi** [comment]
And for serial port, I didn't find a way to disconnect it without change terminal connection
