### ISSUE TITLE
[DOCS] Tabby doesn't support old, LTS linux versions

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [Eugeny/tabby#5004]
I understand that you linked against libc 2.28 and that you probably don't want to support old linux versions. Please add a note to the docs explicitly stating this so folks don't have to scroll through issues to figure it out. Unsupported versions include Ubuntu <=18.04 and Centos 7.

**Comment by Eugeny** [comment]
This wasn't by design - I've switched the GH Actions build to run on 18.04 - the next release will run on 2.26 again, and the nightly builds already do

**Comment by rafmagns-skepa-dreag** [comment]
thanks! this doesn't actually help me because I'm running centos 7 but I'm not about to ask you to support libc < 2.18
