### ISSUE TITLE
Tabby detects the backtick as tilde when binding keys.

### ISSUE THREAD

**Issue by KevinMallinson** [Eugeny/tabby#5005]
When attempting to bind the toggle to ```` Ctrl + ` ```` tabby thinks I am pressing `~`

![image](https://user-images.githubusercontent.com/46643032/143959047-63a245e3-daaf-480a-b68b-80b6d0544efc.png)

Thus, when I perform this keybind it does not toggle, because tilde requires a SHIFT on EN-US keyboard. I didn't press shift when binding it, yet it thinks I want `Ctrl+ ~` as my binding.

The only way to fix this is to update it manually in the config:

![image](https://user-images.githubusercontent.com/46643032/143959223-f3f88c4f-3517-4628-a7bb-6c214fa566ff.png)

**Comment by Eugeny** [comment]
Fixed in the nightly.
