### ISSUE TITLE
why  cannot  input chinese

### ISSUE THREAD

**Issue by chanhuiwumeng** [Eugeny/tabby#5018]

**Comment by YangChern** [comment]
最新版可以用搜狗拼音输入中文了，旧版本确实不行

**Comment by chanhuiwumeng** [comment]
ok,谢啦，试过了，确实可以了，但是这个设置背景，颜色主题不怎么好看呀

**Comment by chanhuiwumeng** [comment]
> 最新版可以用搜狗拼音输入中文了，旧版本确实不行

ok,谢啦，试过了，确实可以了，但是这个设置背景，颜色主题不怎么好看呀

**Comment by Eugeny** [comment]
@chanhuiwumeng which input method did you use before Sogou?

**Comment by chanhuiwumeng** [comment]
> @chanhuiwumeng which input method did you use before Sogou?

no method ,use new version Sougou can input chinese

**Comment by Eugeny** [comment]
got it, thanks

**Comment by seasonyuu** [comment]
> 最新版可以用搜狗拼音输入中文了，旧版本确实不行

用着用着就不能输入了，新建一个终端能重置状态

**Comment by chanhuiwumeng** [comment]
> > 最新版可以用搜狗拼音输入中文了，旧版本确实不行
> 
> 用着用着就不能输入了，新建一个终端能重置状态

最新版Sougou确实有这个问题，还是不太方便感觉，使用docker容易卡死。
