### ISSUE TITLE
highlight with customized color when search Ctrl-F

### ISSUE THREAD

**Issue by thienphuoc86** [Eugeny/tabby#5032]
Can we highlight with customized color when search Ctrl-F? If not please help to develop this ability

**Comment by Eugeny** [comment]
Currently waiting on xtermjs/xterm.js#1653

**Comment by junyicc** [comment]
Looking forward to this enhancement!

**Comment by dpdpbj** [comment]
@Eugeny good news, the issue https://github.com/xtermjs/xterm.js/issues/1653
 may be fixed in this month.
```
 it's on the plan for VS Code this month, we're looking at decorations in the scroll bar first though (https://github.com/microsoft/vscode/issues/144595)
```
