### ISSUE TITLE
Remove or hide built-in profile

### ISSUE THREAD

**Issue by FishMagic** [Eugeny/tabby#5034]
Built-in profiles are so confusion, such as there are 4 options for wsl, and 3 in it are the same target. But I have not way to make it disappear for selectable list.

**Comment by SamAdum** [comment]
Settings / Profiles and connections / Advanced tab / Show built-in profiles in selector is not what you are looking for ?

**Comment by EternityForest** [comment]
Ideally I'm not sure they should be there at all.  I don't even know what /dev/ttyS0 is for anymore, let alone /dev/ttyS31.  All usb serial devices I know about use /dev/ttyACMx or /dev/ttyUSBx, and more than maybe 4 hardware serial ports would be some extreme specialist gear.

I don't know what rbash and dash are for either, or when anyone would use plain sh on purpose, but it seems like they could easily make a custom profile for more specialist needs.

**Comment by sayomelu** [comment]
> Settings / Profiles and connections / Advanced tab / Show built-in profiles in selector is not what you are looking for ?

if you dont say that, most people wont find this way to hide it, mybe put the button to the 'profile' tab?

**Comment by Eugeny** [comment]
It's already in the `Profiles & Connections` tab, and I didn't want this "one time" option to take space away from the profile list.

**Comment by hubertsvk** [comment]
hello , In Profiles & Connections I don`t see any option to delete/hide Built-in profiles, 
![image](https://user-images.githubusercontent.com/38318597/151596877-cf4cd0cd-f1a7-4f74-ac4f-655ec19df906.png)

**Comment by Eugeny** [comment]
Yes, on the Advanced tab.

**Comment by hubertsvk** [comment]
what on Advanced tab?
![image](https://user-images.githubusercontent.com/38318597/151629629-efd78cd8-3f17-4fd2-bd38-2767d153f9dc.png)
![image](https://user-images.githubusercontent.com/38318597/151629665-5447fdee-aed1-45e6-b600-ecd5ca523951.png)

**Comment by ryan7n** [comment]
think you, it's work, very subtle

**Comment by GregWierzchowski** [comment]
I just found this looking for something similar. Sorry if this is a dumb question, but how do I hide some default profiles and not others? I don't want to see serial connections, but I want other ones to be visible.

**Comment by Eugeny** [comment]
@GregWierzchowski if you just don't need serial in general, you can disable it in Settings -> Plugins. But to actually customize the list, you'd need to clone the built-in profiles you need, and then hide built-in profiles completely.

**Comment by GregWierzchowski** [comment]
Thanks! That worked for me.
