### ISSUE TITLE
It seems that the file never gets uploaded

### ISSUE THREAD

**Issue by grow-cub** [Eugeny/tabby#5035]
![image](https://user-images.githubusercontent.com/34758517/144703654-ad4522c5-6182-424a-a2d7-fd6a694fe40a.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by grow-cub** [comment]
> 请在问题发生时捕获 DevTools 控制台日志：[https](https://github.com/Eugeny/terminus/wiki/Debug-logs) : [//github.com/Eugeny/terminus/wiki/Debug-logs](https://github.com/Eugeny/terminus/wiki/Debug-logs)
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[调试日志 · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**更现代的终端（以前称为 Terminus） - 调试日志 · Eugeny/tabby Wiki

![image](https://user-images.githubusercontent.com/34758517/144705008-794a07ce-f0d3-481e-9201-1bd54e2a9082.png)

**Comment by Eugeny** [comment]
Are you logged in as root or as a limited user? Are you able to create files in that location on the remote side? On your screenshot, file modes are zero for some reason.

**Comment by grow-cub** [comment]
> 您是以 root 身份登录还是以受限用户身份登录？你能在远程的那个位置创建文件吗？在您的屏幕截图上，由于某种原因，文件模式为零。

I switched with sudo -s and the vi file succeeded

**Comment by Eugeny** [comment]
Your SSH connection itself needs to happen as a privileged user (root or otherwise) - it's not possible to switch users within an SFTP session.

**Comment by grow-cub** [comment]
> Your SSH connection itself needs to happen as a privileged user (root or otherwise) - it's not possible to switch users within an SFTP session.

But SFTP is problematic
