### ISSUE TITLE
How to get the scroll in the shell. the mouse wheel is not smooth [how to enable the scroll bar in any shell?]

### ISSUE THREAD

**Issue by kamalmost** [Eugeny/tabby#5037]
Version: 1.0.165-nightly.0
Platform: Windows x64 10.0.19042
Plugins: workspace-manager, title-control, theme-windows10, theme-hype, theme-gruvbox, save-output, relaxed-theme, quick-cmds, altair
Frontend: xterm

**Comment by freeNestor** [comment]
It's relate to window theme. I notice that there's no scrollbar until you change the theme (under window menu) to the standard theme. I suppose your current theme is not the standard theme. Hope this help and you can try other themes to see if scrollbar come back.

**Comment by kamalmost** [comment]
Yes. that is correct. I've checked and the scroll is back again. Thanks 

Is there a way to use the old Theme with scroll bar?

**Comment by freeNestor** [comment]
> Yes. that is correct. I've checked and the scroll is back again. Thanks
> 
> Is there a way to use the old Theme with scroll bar?

I'm not sure. I'm new here for this tool also. Maybe need to tweak the old theme ourselves, but I don't know how. There's such few document for this tool. Developers always believe users have strong technology ability.
