### ISSUE TITLE
Can not connect my server through a http proxy.

### ISSUE THREAD

**Issue by BOGEDABUDA** [Eugeny/tabby#5038]
I just install the latest tabby 1.0.164 on my windows 11 PC.
I am trying to use ProxyCommand to connect to my server which needs a http proxy.
I had tried using " connect -S <IP>:<Port> %h %p" as the ProxyCommand, but the terminal returns the following message:
` SSH  Connecting to 192.168.3.234`
 `SSH   !  Agent auth selected, but no running agent is detected`
 `SSH   Proxy command  Using connect -S <IP>:<Port> %h %p`
 `SSH   X  Proxy command has exited with code 1`
 `X  Proxy command has exited with code 1`

By the way, I can successfully connect to my server with the same command in the windows terminal. But i do not know why it failed in tabby.

**Comment by Eugeny** [comment]
%h/%p is OpenSSH syntax, with Tabby you don't need any variable substitutions - just use `connect -S proxy-ip:proxy-port target-host:target-port`.

P.S. or try the nightly build - it has native SOCKS proxy support in connection settings.
