### ISSUE TITLE
How download folders and files from Server? 

### ISSUE THREAD

**Issue by hardyfan** [Eugeny/tabby#5043]
Version: 1.0.164
Platform: Windows x64 10.0.19043
Plugins: fit-screen
Frontend: xterm

是否可以从服务器上下载文件夹和文件到本地。

**Comment by Eugeny** [comment]
You can use the built-in SFTP client or Zmodem.

**Comment by hardyfan** [comment]
1. 内置的SFTP好像只能上传，不能下载。如果可以下载请说明如何操作？
2. Zmodem是什么呢？请进一步指明？

**Comment by Eugeny** [comment]
1. The built-in SFTP can download files (by clicking them), but not folders yet.
2. Zmodem is a protocol to send files to/from a shell session - you need to install `lrzsz` (available in most distros) on the remove side and then use `sz <file>` to send or `rz` to receive files.
