### ISSUE TITLE
Keyboard-interactive auth show the plaintext

### ISSUE THREAD

**Issue by xiaohanqing** [Eugeny/tabby#5045]
1. connect to ssh
2. ssh need Keyboard-interactive auth
3. i can write the auth_code in the "Response" input
4. but all i write is plaintext ,as   i write "1234", the "Response" input show me "1234"  instead of "********"

**Comment by xiaohanqing** [comment]
?

**Comment by Eugeny** [comment]
I've just fixed it in the code, the fix will be available in the nightly build in a few minutes, and in the next release, thanks for the report :+1:

**Comment by xiaohanqing** [comment]
Got it, thank you
