### ISSUE TITLE
Feature Request: Copy as Plain Text

### ISSUE THREAD

**Issue by JackCuyler** [Eugeny/tabby#5050]
When copying text from Tabby's console, the background color is also copied, and is included when pasting into another app that can use this information (I.E. Outlook, Word, Zoom). It would be nice to have the option to copy as plain text, and nicer still to be able to make this the default. I use a black background in my terminals, but when I'm copy/pasting into documentation, I just want the text, not the black background.

**Comment by JackCuyler** [comment]
![tabby](https://user-images.githubusercontent.com/42480463/146936018-a2a6d613-94c3-4b94-ae79-04a9a968b76f.png)
![word](https://user-images.githubusercontent.com/42480463/146936028-23678558-39a3-4329-8f20-8ccbb841f754.png)

**Comment by EricYangHai** [comment]
agree, i have same requirement to this feature.

**Comment by coderliss** [comment]
Using Tabby as a replacement for x-shell, Tabby looks excellent to me. But pasting with a black background is really troublesome.
