### ISSUE TITLE
SSH Connect t 

### ISSUE THREAD

**Issue by king1037** [Eugeny/tabby#5051]
Tabby Version:1.0.164
Issue:i use it ssh to connect the cisco device,but will show below issue,can u help check!(i use mobaXterm or windows's cmd is normal)

 SSH  Connecting to 192.168.4.110
 SSH   !  Agent auth selected, but no running agent is detected
 X  Handshake failed: no matching key exchange algorithm

**Comment by Eugeny** [comment]
Fixed in the nightly

**Comment by hexiaogou** [comment]
> Tabby Version:1.0.164 Issue:i use it ssh to connect the cisco device,but will show below issue,can u help check!(i use mobaXterm or windows's cmd is normal)
> 
> SSH Connecting to 192.168.4.110 SSH ! Agent auth selected, but no running agent is detected X Handshake failed: no matching key exchange algorithm

Brother, have you fixed the problem?

**Comment by Admirall777** [comment]
Tabby Version:1.0.209
Cisco 3750 version 12.2
When use "diffie-hellman-group1-sha1" - connection close with "Unknown DH group".
When use other algorithm - connection close with "Handshake failed: no matching key exchange algorithm".
Whot can i do for open SSH session to the device?
Ciphers aes256-cbc
HMAC hmac-sha1
Host key ssh-rsa
