### ISSUE TITLE
customization tab title

### ISSUE THREAD

**Issue by dongyunqi2018** [Eugeny/tabby#5055]
how can i customization tab title,set to any content i like.thank you!!!

**Comment by Eugeny** [comment]
Right click -> rename. You can also pre-set tab names for your profiles in the profile settings.

**Comment by Eugeny** [comment]
Enable this profile setting to keep the profile name as tab titile even if the remote side provides a new title: 
![image](https://user-images.githubusercontent.com/161476/145171076-613256bd-c349-48b5-9c68-32f8a44e62c4.png)

**Comment by dongyunqi2018** [comment]
it just does not work, as following:

my profile setting:

![profile setting](https://user-images.githubusercontent.com/38023412/145338554-870beb6c-cfa6-4524-93d8-0440b91ae3fe.jpg)

before connnect:

![before connect sucess](https://user-images.githubusercontent.com/38023412/145338551-019ca030-b223-4df5-a2ba-5f745ab95548.jpg)


afte connect:

![after connect sucess](https://user-images.githubusercontent.com/38023412/145338548-ae0b7130-a993-416d-864a-98628f7ceead.jpg)

Version: 1.0.164
Platform: Windows x64 10.0.19042
Plugins: title-control
Frontend: xterm

**Comment by Eugeny** [comment]
The `title-control` plugin will override these settings.

**Comment by dongyunqi2018** [comment]
`title-control plugin` already uninstall,still the same result.
