### ISSUE TITLE
Remember Error

### ISSUE THREAD

**Issue by FatuityCookie** [Eugeny/tabby#5056]
Version: 1.0.164
Platform: Windows x64 10.0.22000
Plugins: none
Frontend: xterm

![image](https://user-images.githubusercontent.com/46119806/144986544-97c0b44e-65b2-482f-a5d7-1df20fa04959.png)

Entering a password is normal accessible, but checking Remember Password Verification failed

**Comment by FatuityCookie** [comment]
Timed out while waiting for handshake

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by ShaPoHun** [comment]
有遇到同样的错误！
