### ISSUE TITLE
use Proxy Command 

### ISSUE THREAD

**Issue by swtseaman** [Eugeny/tabby#5060]
nc -X 5 -x 10.1.1.1:8906 10.1.1.5:22

Tips:   SSH   X  write EPIPE

**Comment by swtseaman** [comment]
SSH  Connecting to 
 SSH   Proxy command  Using nc -X 5 -x 10.1.1.1:8906 10.1.1.5:22
 SSH   X  write EPIPE

**Comment by swtseaman** [comment]
What should I do

**Comment by Eugeny** [comment]
Try the nightly build, which adds native support for SOCKS proxies without ProxyCommand

**Comment by swtseaman** [comment]
> Try the nightly build, which adds native support for SOCKS proxies without ProxyCommand

I don't quite understand. Can you be more detailed

**Comment by Paulpatou** [comment]
same problem as @swtseaman 
with the nightly version [nightly 1.0.165 ](https://nightly.link/Eugeny/tabby/workflows/build/master )I have this error ` X  Connection lost before handshake`

**Comment by Eugeny** [comment]
@swtseaman you're using a SOCKS proxy server (`10.1.1.1:8906`) to connect to your host (`10.1.1.5:22`). In [Tabby's latest nightly build](https://nightly.link/Eugeny/tabby/workflows/build/master), you can skip ProxyCommand altogether and directly set a proxy for your connection like this:
![image](https://user-images.githubusercontent.com/161476/145013081-3845a251-cfda-4634-b76c-32f4d85d9eee.png)

**Comment by swtseaman** [comment]
Connection lost before handshake

I can use SSH's proxycommand directly

**Comment by swtseaman** [comment]
Use the new version of proxy command, but not socks proxy

**Comment by swtseaman** [comment]
Now use the socts proxy method to prompt "connection lost before handshake"

Using proxycommand mode, the speed is slow

It is normal to use the local shell and enter ssh - o ProxyCommand

How to deal with it? I still hope to use tabby normally

**Comment by swtseaman** [comment]
> Eugeny

Please have a look

**Comment by swtseaman** [comment]
@Eugeny Please have a look

**Comment by fonlan** [comment]
Same issue for me. 1.0.167 version and socks proxy. Connection lost before handshake. But same configuration working with putty.

**Comment by zazi0001** [comment]
Same issue for me. 1.0.168 version and socks proxy. Connection lost before handshake. But same configuration working with putty.

**Comment by swtseaman** [comment]
I hope it can be solved
