### ISSUE TITLE
unable to download plugins

### ISSUE THREAD

**Issue by Silocean** [Eugeny/tabby#5061]
release version: tabby-1.0.164-macos-x86_64.pkg

![image](https://user-images.githubusercontent.com/6680721/145040831-2239d264-4ac9-402a-8194-487b98904134.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Silocean** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Debug logs · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**A terminal for a more modern age (formerly Terminus) - Debug logs · Eugeny/tabby Wiki

![image](https://user-images.githubusercontent.com/6680721/145659327-304f13b5-7992-41ed-808e-ecf071b85048.png)

**Comment by Silocean** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Debug logs · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**A terminal for a more modern age (formerly Terminus) - Debug logs · Eugeny/tabby Wiki

hi! problem has been sloved, it's my router
