### ISSUE TITLE
Show ssh conn name when it is exist, maybe is a good idea

### ISSUE THREAD

**Issue by FantaZZ** [Eugeny/tabby#5070]
![image](https://user-images.githubusercontent.com/5322276/145197082-4ab43ddc-ab98-4001-9e0b-52b77fe8f023.png)

**Comment by Eugeny** [comment]
Tick this in the profile settings: 
![image](https://user-images.githubusercontent.com/161476/145197404-a5e21788-a96b-4204-8c84-645b971373ad.png)

**Comment by FantaZZ** [comment]
my miss ...

**Comment by Eugeny** [comment]
No worries 🙌
