### ISSUE TITLE
Windows 10 portable install maybe need a *.reg file

### ISSUE THREAD

**Issue by zengjiapei3000** [Eugeny/tabby#5071]
Hello, Eugeny! Tabby is a awesome terminal that have both appearance and function. Thanks for giving for this project!
  And I use tabby on **windows 10**,  installed by [Scoop](https://github.com/ScoopInstaller/Scoop) ,  a package manager in windows, and in the bucket named `Extras` have the tabby. [Extras bucket](https://github.com/ScoopInstaller/Extras) have not given the `.reg` file to create context menu like `open Tabby here`  option. Maybe the packager forgot this. Could I have some suggestion for this? thanks!

**Comment by Eugeny** [comment]
Thanks! The context menu items can be enabled or disabled dynamically in Settings -> Applications -> Shell integration
