### ISSUE TITLE
 SSH  Connecting to 192.168.2.107  X  Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by dongyunqi2018** [Eugeny/tabby#5072]
**SSH  Connecting to 192.168.2.107
 X  Handshake failed: no matching key exchange algorithm** 

how can i solve this problem.when use finalshell client is ok.

OS:MAC 10.13.6
version:1.0.164

**Comment by dongyunqi2018** [comment]
after change some configuration,
error 
->
 SSH  Host key fingerprint:
 SSH   SHA256  463d29fd3a82d8c6dca66f1eca8c6d607cdb1f3239369fe0c8a9c8f014ae59c5 
 X  Handshake failed: signature verification failed

**Comment by hexiaogou** [comment]
> **SSH Connecting to 192.168.2.107 X Handshake failed: no matching key exchange algorithm**
> 
> how can i solve this problem.when use finalshell client is ok.
> 
> OS:MAC 10.13.6 version:1.0.164

Brother, have you solved the problem? I also meet this problem in my Macbook pro.

**Comment by TangSirOnGit** [comment]
Apple M1 Pro
mac os： 12.0.1 (21A559)
tabby：1.0.164 (1.0.164)


 SSH  Connecting to xx.xx.xx.xx
 X  Handshake failed: no matching key exchange algorithm

**Comment by huxiang** [comment]
Go to Settings -> Profiles & connections -> ADVANCED, open SSH default profile, switch to CIPHERS tab, select diffie-hellman-group1-sha1 in Key exchange and save it.

Try connect to remote host again.

**Comment by Clssrie** [comment]
![image](https://github.com/Eugeny/tabby/assets/14869986/9312f9c0-8b95-4e60-b5c5-4255a9116c55)
![image](https://github.com/Eugeny/tabby/assets/14869986/f6b9bb61-8395-487f-b566-495e7c365017)

**Comment by ifgoto** [comment]
> ![image](https://private-user-images.githubusercontent.com/14869986/301413375-9312f9c0-8b95-4e60-b5c5-4255a9116c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDIwNjgsIm5iZiI6MTcwOTYwMTc2OCwicGF0aCI6Ii8xNDg2OTk4Ni8zMDE0MTMzNzUtOTMxMmY5YzAtOGI5NS00ZTYwLWI1YzUtNDI1NWE5MTE2YzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODhjN2M1MzhlYTcxYWY4MDY2ZTQ2OGZhZWJlZDIzMmQ0MDA5N2FjNTJlODI4NzgzNjRhM2RlM2E1NTljNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zt_xzvq4jECmHhlgSJ3ynQGm46LnQ2A0r-rpRfsowuQ) ![image](https://private-user-images.githubusercontent.com/14869986/301413670-f6b9bb61-8395-487f-b566-495e7c365017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDIwNjgsIm5iZiI6MTcwOTYwMTc2OCwicGF0aCI6Ii8xNDg2OTk4Ni8zMDE0MTM2NzAtZjZiOWJiNjEtODM5NS00ODdmLWI1NjYtNDk1ZTdjMzY1MDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGMyMmFkNzNmNTZmM2JjODBiZWU4Y2U0ZjQ5YWU5MjdjNmQ5MDA3Y2M5OWM0NDg2MDZkMmIyNzkzZjdiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xa6LdtG4LvfBUtpsta5KY0I3g_hgpu1CXkO_2zOhxh8)

it work for me..
