### ISSUE TITLE
Version: 1.0.165 doesn't show up anything on windows 10

### ISSUE THREAD

**Issue by lhuaizhong** [Eugeny/tabby#5078]
Version: 1.0.165
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

Version: 1.0.164 works well.

**Comment by kometchtech** [comment]
The same goes for me.

- version 1.0.165
- OS: Windows 10 Pro x64 21H2

**Comment by zlyuan99** [comment]
same for me. doesn't show on win10
![image](https://user-images.githubusercontent.com/30078049/145322519-fa8d4a2e-b72f-4c26-85ae-2623c0587e3a.png)

**Comment by wholegale39** [comment]
I have the same problem

**Comment by haibo9916** [comment]
I also have such a problem, but I don't know how to solve it

**Comment by llvvrui** [comment]
I meet the same question!

**Comment by xj1988** [comment]
I have the same problem

**Comment by shilohooo** [comment]
I have the same problem:(

**Comment by Eugeny** [comment]
Please try running `Tabby.exe --debug` from its installation folder

**Comment by shilohooo** [comment]
@Eugeny I tried, here is the result: 
![image](https://user-images.githubusercontent.com/46670399/145373606-6ea4dd0f-f4f5-4289-985d-9d4fab874ee1.png)

**Comment by Eugeny** [comment]
Fixed in v166
