### ISSUE TITLE
cost too much memory

### ISSUE THREAD

**Issue by chenbiaoyeting** [Eugeny/tabby#5085]
Version: 1.0.164
Platform: Windows x64 10.0.17763
Plugins: title-control, quick-cmds
Frontend: xterm

Tabby cont too much memory.   I don't do anyting, but cost 668.MB

**Comment by NotAShelf** [comment]
I am quite sure that it is stated in the readme that tabby, does in fact, cost a lot of RAM. My humble suggestion would be that you look into other alternatives which are also listed in the readme.
