### ISSUE TITLE
win11启动tabby失败

### ISSUE THREAD

**Issue by tanjunde** [Eugeny/tabby#5086]
win11双击启动tabby完全没反应。版本号为tabby-1.0.165-portable

**Comment by KuiYang2017** [comment]
我也遇到相似问题 .安装板跟绿色版都尝试了,没有反应

**Comment by JiZhi-Error** [comment]
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎11/‎15
操作系统版本	22000.348
体验	Windows 功能体验包 1000.22000.348.0

也无法打开，我看进程里一堆

**Comment by Eugeny** [comment]
Fixed in v166

**Comment by eazzhao** [comment]
装到默认路径，就可以
