### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by jontstaz** [Eugeny/tabby#5089]
I'm running Windows 10 and have tried using both the Windows installer version and the portable version. When I open the .exe, nothing comes up at all. However I check my task manager and Tabby.exe shows in task manager. Very strange, any ideas on how to actually get it to work?

**Comment by hulkiee** [comment]
Hi, i had the same problem and the older versions of the software can be run in win10.

**Comment by zhangjianjian** [comment]
me too

**Comment by ZZIIKKemd** [comment]
Have the same problem with Alpha 165 and Win 10. Rolled back to 164 (just installed it over 165) - it works fine.

**Comment by Eugeny** [comment]
Fixed in v166
