### ISSUE TITLE
macos 12.0.1 can not open

### ISSUE THREAD

**Issue by yanbumo** [Eugeny/tabby#5090]
![image](https://user-images.githubusercontent.com/22701127/145350767-8a6517a9-50de-4be9-a8d5-ae9cc3d8cd22.png)

**Comment by yanbumo** [comment]
version: tabby-1.0.165-macos-x86_64.pkg

**Comment by likelet** [comment]
I have the same issue with an identical version of the package and 
My system: macOS Mojave 10.14.3

**Comment by Qiming-Liu** [comment]
win 10 cant open

**Comment by Qiming-Liu** [comment]
both portable and installer, both nightly and latest release

**Comment by Eugeny** [comment]
Fixed in v166

**Comment by Qiming-Liu** [comment]
> Fixed in v166

Yeah, it works now on Win10 :) What happened?

**Comment by cltsp** [comment]
> Fixed in v166

macOS 11.5.2 can't open tabby-1.0.166-macos-x86_64

**Comment by canzh** [comment]
macOS 11.6.1 can't open tabby-1.0.166-macos-x86_64
