### ISSUE TITLE
cann't open

### ISSUE THREAD

**Issue by genius2002** [Eugeny/tabby#5091]
Version: 1.0.165
Platform: Windows x64 10.0.22000
Plugins: theme-windows10, theme-gruvbox, fit-screen, altair
Frontend: xterm-webgl

upgrade 1.0.165 from 1.0.164,but cann't open application. can find process in task manager,but no UI displayed.

**Comment by Eugeny** [comment]
Fixed in v166

**Comment by XOOLE** [comment]
I downloaded Alpha 169 , it was not opening then after seeing this I installed Alpha 166 is opening now
