### ISSUE TITLE
startup tabby from setup.exe

### ISSUE THREAD

**Issue by hubertsvk** [Eugeny/tabby#5092]
I downloaded  tabby-1.0.166-setup.exe on Windows 11 and install it, when I run it nothing happened, any error, then same when I installed Tabby with winget from https://winstall.app/apps/Eugeny.Tabby ... but when I downloaded tabby-1.0.166-portable.zip and unpack it, everything ran fine

**Comment by Eugeny** [comment]
Could you please kill any remaining tabby.exe processes via the Task Manager and try again?

**Comment by hubertsvk** [comment]
in task manager I didn`t have any tabby.exe, I was looking for with taklist | findstr tabby.exe

**Comment by hubertsvk** [comment]
I installed version 1.0.168 and problem was resolved, great job
