### ISSUE TITLE
GBK charset support

### ISSUE THREAD

**Issue by bestv5** [Eugeny/tabby#5096]
it support GBK  GB2312 GB1830 charset?   when i connection a  gbk charset linux by ssh , it cannot display Chinese。

**Comment by LiuCH4NG** [comment]
![image](https://user-images.githubusercontent.com/46369353/145528922-0e052260-6806-47a3-8ce0-1c3a7f5a78b6.png)

**Comment by bestv5** [comment]
@Eugeny   这个问题不准备支持吗

**Comment by Eugeny** [comment]
Currently there are no plans for charsets other than UTF8
