### ISSUE TITLE
I cannot input any character

### ISSUE THREAD

**Issue by ThechCorsair** [Eugeny/tabby#5101]
Hi, I am using Tabby Windows version - 1.0.167

The panes often open without receiving any keyboard input. This happens every now and then. Sometimes it works like a charm, and then the panes are semi-loaded (seems something is missing) and no input is possible.

Thanks

**Comment by timcarrutherz** [comment]
I found that I only had this issue if "Restore terminal tabs on app start" enabled. Seemed to fix the issue for me when disabled (PopOS! 21.04)

**Comment by leochien0102** [comment]
I have the same issue. In the restored terminal on app start, I can not input anything. So I toggle it OFF in Settings with "Auto-open a terminal on app start" ON.

**Comment by quannda** [comment]
I got the same issue.
