### ISSUE TITLE
cannot open a new terminal

### ISSUE THREAD

**Issue by mubashirtanveerayon** [Eugeny/tabby#5103]
Version: 1.0.167
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm

So I came across this terminal emulator today watching a video on yt, and installed it. But unfortunately clicking the new terminal button does nothing.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
