### ISSUE TITLE
Slow motion window movement (Windows 11)

### ISSUE THREAD

**Issue by iamdarkle** [Eugeny/tabby#5116]
I don't know if maybe someone has already reported it, but since I upgraded to Windows 11 I have an annoying problem and that is that if Tabby is open the movement of any window is in slow motion, moving the browser to my other screen is a suffering. The moment you minimize Tabby everything goes back to normal.

**Comment by Eugeny** [comment]
Try disabling window vibrancy in Settings -> Window or changing it from Fluent to Blur.

**Comment by iamdarkle** [comment]
Sorry for the delay. I have disabled animations and transparency, I have tried changing these settings but it doesn't seem to do anything with the problem.

**Comment by iamdarkle** [comment]
Fixed, it seems that with the latest Windows cumulative update it's finally fixed. I close the issue :)
