### ISSUE TITLE
Not all Font Awesome icons available?

### ISSUE THREAD

**Issue by apiening** [Eugeny/tabby#5117]
As far as I can see `tabby` uses a pretty current version of **Font Awesome** (5.15.4).
However, when I search for the term `linux` on the official **Font Awesome** site, I get 6 results:
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=linux&m=free

But none of them are available in the `Icon` property field of the `Profiles` dialog.

Is there a reason for that?
Can we make all of the icons available?

**Comment by Eugeny** [comment]
Which version are you on? `linux` works as a search query for me: 
![image](https://user-images.githubusercontent.com/161476/145690032-e1c241a7-c8a5-4a81-87f5-8af7ad6917c3.png)

**Comment by apiening** [comment]
I'm on **Mac OS X** with version **1.0.168**.
I've attached a screenshot how it looks on my install.

![Bildschirmfoto 2021-12-23 um 15 44 33](https://user-images.githubusercontent.com/2064875/147256065-8fab01b8-c450-4bea-b241-5306e9a241f2.png)
Using a search term:
![Bildschirmfoto 2021-12-23 um 15 47 23](https://user-images.githubusercontent.com/2064875/147256156-62175a41-bdae-4b1f-aa7b-cecb5ed9741a.png)

**Comment by Eugeny** [comment]
`linux` is an icon from the `fab` (fa-brands) set. Use `fab fab-linux` or just `linux` and let autocomplete find it.

**Comment by apiening** [comment]
Oh you're right.
User error, sorry.
