### ISSUE TITLE
Question: How does the config sync feature work

### ISSUE THREAD

**Issue by apiening** [Eugeny/tabby#5119]
I can't find any documentation for the `Config Sync` feature available in the `Settings`.
Is it possible to use `Config Sync` self hosted? If so, how to setup the end point?

Is there an option to save the `config.yaml` to a local path automatically when `Tabby` terminates and load from there if it is launched again? That would enable other back-ends like **Nextcloud**, **iCloud**, **DropBox** or other mounted file shares for the config synchronization.

**Comment by Eugeny** [comment]
There isn't documentation per se - "config sync" syncs to an instance of `tabby-web` which runs at https://tabby.sh by default, or to your own instance - see https://github.com/eugeny/tabby-web for setup help.
The config file is saved to the user's config directory (https://github.com/Eugeny/tabby/wiki/Config-file), but you can use the third party `sync-config` plugin, which has support for more backends.

**Comment by apiening** [comment]
Wow that's awesome!
Thank you very much!

**Comment by maveice** [comment]
Good morning, 
I like and appreciate Tabby very much. There is one thing I am still missing: I am still not able to sync my config in my self hosted setup. 
Please advice how to do it.
Many thanks and best regards!

**Comment by Eugeny** [comment]
@maveice once you have your self-hosted tabby-web working, copy your secret sync token from its Settings window and set the `Sync host` and `Sync token` fields in Settings -> Config sync page of the app: 
![image](https://user-images.githubusercontent.com/161476/147873317-13a07fa2-bdbf-4789-96c9-b5854fb11417.png)

**Comment by maveice** [comment]
@Eugeny Thanks a lot for your swift reply. In above mentioned case the "sync host" is not hosted by myself (it is "https://api.tabby.sh").

Do we have any different option to operate/install this "sync host" also on (my) prem?
Alternatively: If I go with the WebDAV-approach (as plugin for Mac-, Linux- and Windows-Client), is there any possiblity to also leverage the WebDAV-Plugin in the (self-hosted) Tabby-Web?

**Comment by Eugeny** [comment]
Yes, you can set up your own instance - follow the instructions here: https://github.com/Eugeny/tabby-web

The web version does not support plugins and hence you can't use the DAV sync (provided by the `sync-config` plugin) there.

**Comment by Citizen3rased** [comment]
Does this not work in the windows version? on the Confi Sync page in settings I can see the 'Secret sync token' area, but there is no box to input anything and nothing below it like I see in the pictures here.

**Comment by emoxam** [comment]
Can i make a symlink to some folder which is at the some cloud?
