### ISSUE TITLE
New tab at startup

### ISSUE THREAD

**Issue by karolskolasinski** [Eugeny/tabby#5121]
Version: 1.0.164
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

The application adds another tab at startup. It would be nice if the title of the tabs points to the last segment of the location and if app remembers last location (for example WSL location).

**Comment by Eugeny** [comment]
You can disable the automatic opening of a tab in Settings -> Terminal: 
![image](https://user-images.githubusercontent.com/161476/145690049-6d015363-394c-4ccf-9baa-dd1a59bdb518.png)

The tab title displays the shell's "window title", which you can set to the directory name: https://askubuntu.com/a/442663/12668 (an example for bash)

**Comment by karolskolasinski** [comment]
Thanks. 
Another question: is it possible to have active links in the terminal?

**Comment by Eugeny** [comment]
Yes, in the latest relese, the `clickable-links` plugin is bundled with the app itself.
