### ISSUE TITLE
Can't type on Restored Terminal Tabs

### ISSUE THREAD

**Issue by iambudi** [Eugeny/tabby#5122]
I use MacOS Monterey with zsh (as OS Default). 
1. Launch Tabby, add 2 terminal tabs.
2. Write any terminal command like `ls` or `cd Documents`
3. Quit Tabby and Relaunch. 
4. There would be 2 restored terminal tabs and I could not type any command nor paste something although the cursor keeps blinking.

**Comment by alexdevero** [comment]
I am experiencing the same issue on Windows 10.

Tabby version: 1.0.167
