### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by shaohaiyang** [Eugeny/tabby#5123]
I met the same problem again.  version: 1.0.167  and priviate key format was ssh-rsa.
![image](https://user-images.githubusercontent.com/2763056/145698424-cb034281-c286-4f2c-b82b-1b5a38f56bd5.png)

**Comment by WojtekRymarz** [comment]
HI, I have spotted this issue as well.
I just set up a new connection to my host and it's not connecting. (but I can connect via SSH from other host)
