### ISSUE TITLE
On app start, cannot type in initial tab

### ISSUE THREAD

**Issue by bstar** [Eugeny/tabby#5128]
When loading Tabby on Linux, the initial tab does not seem to accept text input.  Opening subsequent tabs works as expected.  I tried Xterm and Xterm GL with the same result.

If I close the tab that does not work, type characters in a new tab tab that does work, then close Tabby... upon returning the initial tab has my previous text but cannot accept new text input.

**Comment by Eugeny** [comment]
Fixed in the nightly.
