### ISSUE TITLE
when the terminal tab is still open

### ISSUE THREAD

**Issue by farhanreizha** [Eugeny/tabby#5129]
Version: 1.0.167
Platform: Linux x64 5.11.0-42-generic
Plugins: none
Frontend: xterm

when the terminal tab is still open and then restarts the terminal tabby, it cannot type so it must open a new tab.
I don't know if it's a feature or not but, it makes me uncomfortable using it.
And when my opacity changed, it had no effect on her background.
And i used operating system linux ubuntu btw

i hope this solve thanks

**Comment by Eugeny** [comment]
Fixed in the nightly.
