### ISSUE TITLE
sz error

### ISSUE THREAD

**Issue by c-wind** [Eugeny/tabby#5132]
Version: 1.0.164
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm-webgl

``` bash  
[tian@localhost ~]$ sz ump.sh 
 ZMODEM  Session started            
------------------------            
 Received  ump.sh            
 Error  PROTOCOL: Only thing after ZFIN should be “OO” (79,79), not: 27,93,48,59,116,105,97,110,64,108,111,99,97,108,104,111,115,116,58,126,7    
```

**Comment by magicmayu** [comment]
i have the same issue. The file can be completely tranfered, but error is printed on the console.

**Comment by DrayChou** [comment]
https://github.com/trzsz/tabby-trzsz/issues/2

**Comment by nchj** [comment]
same problem
maybe you dont need to install trzsz, you can just use `sz -b filename` instead
