### ISSUE TITLE
Feature: SSH connection multiplexing

### ISSUE THREAD

**Issue by RichardLS09** [Eugeny/tabby#5134]
I want to run "ssh -o ControlMaster=auto -o ControlPath=/save/path host:port" using tabby.
But, i don't know how to add ssh options.
Need help,please!

**Comment by Eugeny** [comment]
Tabby doesn't support connection multiplexing yet.

**Comment by jzuhone** [comment]
would love this feature.

**Comment by Eugeny** [comment]
Duplicate of #4795
