### ISSUE TITLE
there is no ssh in the new profile 

### ISSUE THREAD

**Issue by rattlesnakey** [Eugeny/tabby#5136]
Version: 1.0.164
Platform: macOS arm64 20.2.0
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
Please include more details.

**Comment by ReAlign** [comment]
Maybe you need enable it.

![image](https://user-images.githubusercontent.com/25849349/145950575-77ea6352-3e88-4a1b-b73e-1985dd0fca58.png)

**Comment by rattlesnakey** [comment]
Thx so much! I haven’t notice the ssh connection is belong to plugin section


| |
hengyuan_blcu
|
|
***@***.***
|
签名由网易邮箱大师定制


On 12/14/2021 ***@***.***> wrote：

Maybe you need enable it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
