### ISSUE TITLE
Sync Connections

### ISSUE THREAD

**Issue by kisonay** [Eugeny/tabby#5146]
Is it possible to sync connections across the site? I have config sync setup but my connections do not seem to sync

**Comment by rmagyar** [comment]
same issue here. Version 1.0.168. Syn setup successfully, but connections does not sync.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

Particularly when trying to upload/download the config manually in Settings -> Config sync

**Comment by rmagyar** [comment]
It seems the issue happens when I using encrypted config. In this case I can see the following in the console log:

`xhr.js:125 Refused to set unsafe header "Content-Length"`

After disabling config encryption, sync works perfectly.

**Comment by kisonay** [comment]
I'm seeing the same. How does one turn off encryption?

**Comment by Eugeny** [comment]
Please see https://github.com/Eugeny/tabby/issues/3164#issuecomment-995197756 for a workaround
