### ISSUE TITLE
Support command line connection

### ISSUE THREAD

**Issue by hanzixiaoshu** [Eugeny/tabby#5156]
Is command line connection supported?
for example：xshell
![image](https://user-images.githubusercontent.com/12489036/145968171-3a77db07-9bf0-483b-b600-9916f6626618.png)

**Comment by Eugeny** [comment]
Yes, but only for profiles: `tabby.exe profile <profile-name>`

**Comment by hanzixiaoshu** [comment]
Can I add this feature?
1、Occasionally, it is convenient to connect to a server temporarily through commands.
2、When connecting through the fortress machine, you need to select the local SSH client tool, and then pass the parameters to connect. You cannot select the profile.

**Comment by hanzixiaoshu** [comment]
Excuse me, by the way, Will this feature be added in the next version
