### ISSUE TITLE
row size bug

### ISSUE THREAD

**Issue by sepyeight** [Eugeny/tabby#5163]
Version: 1.0.168
Platform: Windows x64 10.0.19044
Plugins: altair
Frontend: xterm

![image](https://user-images.githubusercontent.com/20394603/146115222-f115b5dc-6901-4d50-b72c-09daafa772af.png)

**Comment by JC-ProgJava** [comment]
I think this is intentional (to highlight the more important settings).

**Comment by Eugeny** [comment]
Yes, this is intentional
