### ISSUE TITLE
is there a command history feature?

### ISSUE THREAD

**Issue by fuuulstack** [Eugeny/tabby#5167]
**Is your feature request related to a problem? Please describe.**
No, just a new feature.

**Describe the solution you'd like**
set a key to show a command history pannel.

**Describe alternatives you've considered**
i can't find the hotkeys options contains this one.

**Comment by Eugeny** [comment]
History completion is a feature of a shell that you run inside Tabby. Check out this comment (https://github.com/Eugeny/tabby/issues/1882#issuecomment-773696951) for some tips.
