### ISSUE TITLE
enter ~ . doesn't quit ssh session

### ISSUE THREAD

**Issue by elgs** [Eugeny/tabby#5169]
**Describe the problem**:
[A clear and concise description of what the bug is.]
Expected:
enter ~ . doesn't quit ssh session.

Actual:
It doesn't quit the ssh session in Tabby.

**To Reproduce**:
[Steps to reproduce the behavior]
1. login an ssh session;
2. press enter key;
3. hold shift key and press the ~ key;
4. press . key
5. the ssh session will quit in default terminal;
6. the ssh session doesn't quit in Tabby;

**Comment by Eugeny** [comment]
`Enter-~-.` is an OpenSSH specific shortcut. Use `Ctrl/Cmd-W` to end your session.

**Comment by elgs** [comment]
`Ctrl-Shift-W / Cmd-W` will kill the current tab. What if I don't want to quit the current tab? Let's say I have some bg jobs running. Well this is not the end of the world, but it seems every other terminal support it, including Hyper.

**Comment by Eugeny** [comment]
Hold on, do you mean you're starting `ssh...` from inside a local session and `~ Enter .` doesn't work? (it does for me)

**Comment by elgs** [comment]
I confirm it works when starting ssh from inside a local session, and it doesn't work when using a saved Tabby managed ssh session. This doesn't bother me, because I rarely use it. This is just FYI, in case you decided to do something with it. Thanks.

**Comment by Eugeny** [comment]
Don't get me wrong, I just don't understand the use case. If you have background shell jobs running, `Enter ~ .` will still kill them, won't it?

**Comment by elgs** [comment]
What I meant was the background shell jobs are running locally. But that was just an excuse for me to prove there is a use case for it. I myself never had this use case before. If there has to be a reason this is useful, that will be that I could press the up arrow key to run the ssh command to reconnect, rather than to open a new terminal to either type the ssh command from scratch or struggle to find the right ssh command from the shell history. But for managed Tabby sessions, this is not a problem at all. So please feel free to ignore it.

**Comment by Eugeny** [comment]
That was what bugged me. In Tabby managed sessions, there are no background jobs and no "up key" to go back to. And in local session + OpenSSH, `Enter ~ .` just works.
