### ISSUE TITLE
Font Ligatures causes hang and high cpu usage

### ISSUE THREAD

**Issue by ilhamazdi** [Eugeny/tabby#5188]
Version : 1.0.168 (Portable)
Platform : Windows 10 x64

I'm using Fira Code (https://github.com/tonsky/FiraCode) with ligatures enabled, Tabby works fine.

Recently, I updated the font to latest version (6.2) still with ligatures enabled and Tabby broke.
Whenever I'm **making SSH connection**, Tabby completely hangs and cannot be closed except from Task Manager. Also, it causes high cpu usage too when it hangs.

![image](https://user-images.githubusercontent.com/7246466/146379378-11126810-d3e4-4c80-af44-2d8de6feedb5.png)

There's no problem if font ligatures is disabled using the same font (Fira Code)

**Comment by Eugeny** [comment]
It would be extremely helpful if you could attach a native debugger (e.g. Visual Studio) to the process and get a stack trace of where it's hanging

**Comment by fy1231** [comment]
same thing on macOS

**Comment by nschloe** [comment]
Same on Linux (Ubuntu 22.04).
