### ISSUE TITLE
Using clickable-ips plugin causes error on start. 

### ISSUE THREAD

**Issue by pandeyshishir** [Eugeny/tabby#5190]
Version: 1.0.168
Platform: macOS x64 21.1.0
Plugins: workspace-manager, title-control, save-output, quick-restart, fit-screen, docker, clickable-ips
Frontend: xterm

If I disable the clickable-ips plugin, the error goes away.

**Comment by Eugeny** [comment]
It's a third-party plugin. Also, IPs should be already clickable with the built-in linkifier plugin.
