### ISSUE TITLE
No powerline fonts

### ISSUE THREAD

**Issue by getsueineko** [Eugeny/tabby#5191]
OS: Manjaro Linux
Tabby: 1.0.156
Env: zsh+powerlevel10k+MesloLGS NF Regular

I see 13 pre-installed fonts that do not display font icons, but I can't use my font Meslo.
My terminal look awful with squares instead of icons.

**Comment by Eugeny** [comment]
Please link the exact font file you're trying to use so that I can test.

**Comment by getsueineko** [comment]
Hi
I fix my problem with install font in global folder /usr/share/fonts/TTF instead local .local/share/fonts
Thnx for great soft!
19 дек. 2021 г., 20:15 +0300, Eugeny ***@***.***>, писал:

**Comment by maxreuben** [comment]
I face the same issue when trying to use vim-airline statusline plugin. I think this is the repo for [powerline-fonts package](https://github.com/powerline/powerline/blob/develop/font/PowerlineSymbols.otf). There's also a battery charging icon that's missing, which might be from Nerd Fonts icons which is part of my starship prompt, but it doesn't show up in tabby.
![image](https://user-images.githubusercontent.com/28548154/147541499-325f2f0a-e819-4ce8-83b3-e2224959c60b.png)
