### ISSUE TITLE
Send text to all tabs

### ISSUE THREAD

**Issue by rmasci** [Eugeny/tabby#5193]
Problem: I work with many servers, and there are many times that I have to connect to 2 or more servers and run the exact same command. 

Something similar to what iterm does, and that's to send to all tabs. So, when you type in one tab, the same thing is typed in another tab. When you've got to perform the same thing on 2 or more servers this really saves time.

**Comment by swtseaman** [comment]
use split   and  command+shift+i ???

**Comment by rmasci** [comment]
That works for when it's split, but sometimes I've got more terminals open
than you'd want to see in a split. I was hoping there would be something
that would do a broadcast to all tabs

Thanks!!

**Comment by orielz** [comment]
+1
I need to broadcast to all tabs as well

**Comment by ghislaindurand** [comment]
It would be great to have this function in tabby : I often use this function on my Linux (in KDE konsole terminal), but I would have it on Tabby on my Windows computer too

**Comment by ghislaindurand** [comment]
Thanks for the fast reply, I have tried your method (Explode/Combine), following your advice,
but when I install my software on new servers, I typically have 10 (more or less) open tabs at the same time to do all the installs in parallel and I need full-window size for each tab :
Panel splitting is not very convenient in my case, IMHO it would be better to have an option to "broadcast to all tabs"
(in the core program, or in a plugin).

**Comment by work-chausat** [comment]
+1

**Comment by bjornburrell-8451** [comment]
would love this feature!
