### ISSUE TITLE
Color scheme wrong color

### ISSUE THREAD

**Issue by gaetansnl** [Eugeny/tabby#5202]
**Describe the problem**:
When I select a color scheme, for example
![image](https://user-images.githubusercontent.com/8348807/146514015-5176de65-dfa1-46f3-9bd7-520776470e71.png)
And when I open a new tab (WSL Ubuntu on windows)
![image](https://user-images.githubusercontent.com/8348807/146514195-bab17add-d89b-4fbc-b966-9e2b6f6cd451.png)

It doesn't look like the color scheme I selected. I can't read the text. The text looks bold, aliased and is difficult to read. I just installed Tabby, and selected a font (Cascadia Mono Light)
**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by massimans** [comment]
it seems it doesn't care at all about the color on windows

**Comment by Eugeny** [comment]
The colorization shown under Settings is an example. Your shell decides which of the 16 colors are used to display stuff, the terminal just allows you to change these 16 colors. See https://askubuntu.com/questions/466198/how-do-i-change-the-color-for-directories-with-ls-in-the-console for more info
