### ISSUE TITLE
Can the label bar display a custom name first

### ISSUE THREAD

**Issue by hou-gaoping** [Eugeny/tabby#5204]
Version: 1.0.168
Platform: macOS x64 21.1.0
Plugins: none
Frontend: xterm

When I connect to many remote hosts, root@localhost is always displayed, so it is not convenient for me to distinguish between different hosts

The default shortcut ctrl+space conflicts with the input method switch

**Comment by Eugeny** [comment]
Tick "Disable dynamic tab title" in your profile's settings.
