### ISSUE TITLE
It would be nice if we could add remark or note on profiles

### ISSUE THREAD

**Issue by 1369521908** [Eugeny/tabby#5209]
**Is your feature request related to a problem? Please describe.**
as the title

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
none

**Additional context**
sometimes we want to add some note on the profiles , like this
![image](https://user-images.githubusercontent.com/32727597/146625914-053b2c58-011a-4f7c-b39e-a0eca90b9345.png)

**Comment by getpool** [comment]
Urgently need ssh remarks

**Comment by 1369521908** [comment]
i remarks like this now for handle :)   192.168.x.x_remarks

**Comment by Eugeny** [comment]
I think having a separate field for this is still a valid idea

**Comment by 1369521908** [comment]
thanks~

**Comment by 7934345** [comment]
Yes, note please, without note I cannot switch WindTerm to Tabby.

**Comment by sugarlesss** [comment]
I was torn between other software and tabby for a very long time because tabby doesn't support notes.

Please note that this is really important for user experience.
