### ISSUE TITLE
Is there any way to set link in terminal unclickable?

### ISSUE THREAD

**Issue by ez4lionky** [Eugeny/tabby#5210]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

By default, the link in terminal output will be clickable. However, it's not the preferable setting for anyone (like me).
Sometimes I just want to copy the link, but it's annoying when clicked the link the website was automatically opened.

**Describe the solution you'd like**
The option that disables clickable links.

**Describe alternatives you've considered**

**Additional context**

@Eugeny

**Comment by Eugeny** [comment]
You can disable the linkifier plugin, or set it to only work when a specific modifier key is held (Settings -> Terminal)
