### ISSUE TITLE
color scheme is not work

### ISSUE THREAD

**Issue by dsky1990** [Eugeny/tabby#5213]
**Describe the problem**:
color scheme is not work.
macos 11.2.3 (20D91)
**To Reproduce**:
![image](https://user-images.githubusercontent.com/1579516/146640708-2a1a89b9-925f-4997-ad0d-ec9a2e4040a4.png)
![image](https://user-images.githubusercontent.com/1579516/146640716-5903f698-70c3-4134-b470-77f719d0c5a6.png)

**Comment by Jas-Grace** [comment]
Well as you can see, it does not show the current directory and username in the same colour, also shows the files and folders when using 'ls' in same colour.

**Comment by Eugeny** [comment]
Please see https://apple.stackexchange.com/questions/33677/how-can-i-configure-mac-terminal-to-have-color-ls-output

**Comment by dxkrs** [comment]
@Eugeny The post link no help for these problem.

**Comment by nobleinventor** [comment]
I was able to resolve this issue by doing:
1. In  Tabby Appearance tab for "Terminal Background " option choose "From color scheme"
2. Goto color scheme tab and choose your scheme, it works :)

**Comment by arno0b** [comment]
My SSH profiles does not the display the specified color scheme. Only my background color matches the scheme. The texts, command prompts and icon colors dont match. If i dont use any profile, they work fine. But when using profiles they dont work. Any fix?

**Comment by Eugeny** [comment]
@arno0b see the pinned discussion

**Comment by ahmad-elkomy** [comment]
I have the same problem. What's worse is that there's no Terminal Background configuration any more so... :/
