### ISSUE TITLE
Color schemes not working properly

### ISSUE THREAD

**Issue by Jas-Grace** [Eugeny/tabby#5214]
<img width="1280" alt="Screenshot 2021-12-18 at 6 41 32 PM" src="https://user-images.githubusercontent.com/89769238/146642290-c6d2a0eb-80cf-4ec8-9a81-9ecd78176f36.png">

As you can see in the image above, the terminal is not showing much colours, as is shown in the cooler schemes - 

<img width="1280" alt="Screenshot 2021-12-18 at 6 43 07 PM" src="https://user-images.githubusercontent.com/89769238/146642315-9f01f76a-f000-4584-8f45-f7a4b9b62af2.png">

What should I do? Thanks in advance!

**Comment by Eugeny** [comment]
Please see https://apple.stackexchange.com/questions/33677/how-can-i-configure-mac-terminal-to-have-color-ls-output

**Comment by dxkrs** [comment]
I meet the same promble, and there no helpful info in the post link after I tried.

**Comment by dehengxu** [comment]
Nobody maintaince tabby any more ?

**Comment by Eugeny** [comment]
Read the pinned discussion

**Comment by hitzhangjie** [comment]
Why this closed? It hasn't been solved by this application.

**Comment by ahmad-elkomy** [comment]
Same same. color scheme isn't effective. No workarounds I can do.
