### ISSUE TITLE
Run command on startup/new tab

### ISSUE THREAD

**Issue by quantum9Innovation** [Eugeny/tabby#5217]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to any problem and is merely an enhancement suggestion.

**Describe the solution you'd like**
I would like to configure certain terminal profiles to run a command when a new instance of that profile is created.
For example, when I create a new profile, there could be a prompt that allows a certain command to be run every time a new instance of that profile is run.

**Describe alternatives you've considered**
Other alternatives would include creating a plugin to do this, which Hyper has.

**Comment by Eugeny** [comment]
a. You can set a _profile command_ other than your default shell - this will run the command instead of the shell
b. You can wrap your command in a mini-script, e.g. `zsh -c '<some command>; zsh -i'` and use that as the profile command.

**Comment by quantum9Innovation** [comment]
Thank you for the suggestion! It seems that both (a) and (b) solve the problem.

**Comment by Infinitybeond1** [comment]
on linux you could add the command you want to the bottom of your ~/.bashrc file
