### ISSUE TITLE
How should I install it on arm64?

### ISSUE THREAD

**Issue by Jas-Grace** [Eugeny/tabby#5218]
I am using Kali Linux arm64, though the .deb and .tar.xf files are for amd64. Is there any way I can install it on arm64?

**Comment by Eugeny** [comment]
There are no prebuilt binaries for arm64, but you can built one yourself as described here: https://github.com/Eugeny/tabby/blob/master/HACKING.md#getting-started

**Comment by mwinterstetter-io** [comment]
When I try to run 'yarn run build' I get the following error:

-# yarn run build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run" root® pilab)-[/home/./Desktop/tabby/build/linux]

What am I doing wrong?
