### ISSUE TITLE
Middle click pastes twice

### ISSUE THREAD

**Issue by lodrantl** [Eugeny/tabby#5219]
**Describe the problem**:

Similar to #4451 which I believe has been fixed already.
When pasting text into the terminal using middle mouse button the following two this happen:
* middlemousedown -  text from the clipboard (the same that would appear when pressing Ctrl-Shift-V) is pasted
* middlemouseup - text from the primary selection (the same that would appear when middle clicking in other applications) is pasted

Either of those texts being pasted would be ok, but not both.
![out3](https://user-images.githubusercontent.com/7591598/146676932-1cab0f68-918c-4fdc-bd8d-f9bb76475332.png)

**To Reproduce**:
Arch Gnome 41 - Tabby 1.0.168, xterm

**Comment by Eugeny** [comment]
Does disabling `terminal.pasteOnMiddleClick` help? It provides the manual handling of the middle click event, which I guess isn't necessary on Linux.

**Comment by lodrantl** [comment]
That helped. Thanks.

**Comment by emoxam** [comment]
Where to disable terminal.pasteOnMiddleClick ?

**Comment by emoxam** [comment]
It disabled at option but it still pasting..
is it OS setting works ?

**Comment by ABi233** [comment]
> Where to disable terminal.pasteOnMiddleClick ?

You can set it to config, like:
```yaml
terminal:
  pasteOnMiddleClick: false
```
restart the tabby and could be effected
