### ISSUE TITLE
No keyboard input in restored (saved) WSL2 tabs on Tabby start

### ISSUE THREAD

**Issue by merelin** [Eugeny/tabby#5228]
Version: 1.0.167
Platform: Windows x64 10.0.19043
Plugins: theme-windows10
Frontend: xterm

**Comment by merelin** [comment]
When I close Tabby it saves currently opened tabs. When afterwards I start Tabby again there is no reaction on keyboard in these re-opened tabs. Think it is a regression since it used to be fine on previous versions.

**Comment by merelin** [comment]
This seems to have been fixed in version 1.0.168.

**Comment by Eugeny** [comment]
Yep, it's fixed in v168
