### ISSUE TITLE
Whether SFTP is enabled to directly access the current ssh directory.Xshell software is ok

### ISSUE THREAD

**Issue by zxiaozhou** [Eugeny/tabby#5229]
**Describe the solution you'd like**
Whether SFTP is enabled to directly access the current shell directory.Xshell software is ok,This facilitates uploading files to the current SSH directory

**Comment by Eugeny** [comment]
Please see https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting

**Comment by zxiaozhou** [comment]
@Eugeny This setting is not valid, please note that this is an SSH remote server, not a local shell.Watch my video demonstration

**Comment by Eugeny** [comment]
@zxiaozhou it also works for remote hosts and SFTP, not just local. Have you restarted your SSH session after setting it up? Has this "tip" disappeared? 
![image](https://user-images.githubusercontent.com/161476/146746347-26116eb0-be44-4c88-96f0-f43bd037b251.png)

**Comment by zxiaozhou** [comment]
@Eugeny I rebooted my computer

**Comment by zxiaozhou** [comment]
@Eugeny You u need to set up remote server configuration, not local. However, xshell does not set up the remote server, any server support, and there is no need to configure environment variables on the remote server

**Comment by zxiaozhou** [comment]
@Eugeny Please note that there is no server configuration in my video demonstration, and each server needs to be set, do you think it is reasonable?? Xshell software does not require setting

**Comment by zxiaozhou** [comment]
@Eugeny Xshell software I just installed, configured the SSH link information, on the implementation. This software document requires the remote server to configure bash_profile
