### ISSUE TITLE
Import ssh config into tabby?

### ISSUE THREAD

**Issue by ShrimpLau** [Eugeny/tabby#5248]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when configuring the ssh profile, especially when the profile contains complicated flags. I really like tabby ssh function but I don't know how to configure something like:
```bash
Host myhost
    HostName aaa.bbb.ccc.ddd
    User root
    ProxyCommand ssh -p 2222 jump.server -W %h:%p
    StrictHostKeyChecking no
```

**Describe the solution you'd like**
I'm wondering whether tabby can read the config file in ~/.ssh/config and extract the profile information and integrate it into tabby ssh.

Hope I make my request clear, grateful for your work!

**Comment by Eugeny** [comment]
Duplicate of #1528
