### ISSUE TITLE
[linux][ubuntu] settings/plugins tab is gone after I disabled all plugins

### ISSUE THREAD

**Issue by guoqiao** [Eugeny/tabby#5257]
**Describe the problem**:
[A clear and concise description of what the bug is.]

I disabled all my plugins, and the plugins tab in settings is gone, I can not manage/enable any plugins any more.
On ubuntu 20.04/focal, tabby-1.0.168-linux.deb.

**To Reproduce**:
[Steps to reproduce the behavior]
In settings / plugins / installed, disabled any plugins if possible, restart tabby.
Go back to settings, you can not see plugins any more.

**Comment by Eugeny** [comment]
Well yes, the plugin settings tab is a plugin too. You can reenable it by removing it from the `pluginBlacklist` list in the [config file](https://github.com/Eugeny/tabby/wiki/Config-file) (or removing the `pluginBlacklist` option altogether)

**Comment by guoqiao** [comment]
@Eugeny  thanks for letting me know that tip. However, I don't think you should just close this issue.

I run into this issue when I was trying to report another bug. 
And in your issue template, we are required to disabled *all* plugins.
And once I did that, plugins manager is gone. 
Even terminal function is not usable any more, a blank panel will show, I can not do anything there.
I had to apt purge tabby from my system to try to take it back to normal.

This is not user-friendly at all, your tip should not be considered as an acceptable solution to this issue.

At least "plugin manager" should not be a plugin itself,  or user should not be allowed to disable it.

**Comment by Eugeny** [comment]
It's a good point - I've adjusted the issue template to explicitly mention *third-party* plugins. However I don't think that users should be prevented from disabling everything they don't need - it's perfectly fine to e.g. disable the local terminal plugin and keep the SSH plugin. I see how disabling the plugin manager causes confusion though and will add it to the "whitelist".
