### ISSUE TITLE
Hope to support custom highlight keywords

### ISSUE THREAD

**Issue by git10135405** [Eugeny/tabby#5264]
As shown in the figure below, xshell supports custom keyword highlighting, which is very convenient to capture key information, such as: mobile phone, email, ip, error messages, etc., which can be directly configured.
![image](https://user-images.githubusercontent.com/35558611/147207127-088ebb8c-4d1c-480f-bdba-d4537f80ddfd.png)

**Comment by Eugeny** [comment]
Duplicate of #632
