### ISSUE TITLE
SerialPort Parity option does not work

### ISSUE THREAD

**Issue by kukuk2010** [Eugeny/tabby#5267]
Since version 1.0.168 (Win10) changes on the parity option of a SerialPort seems to not have an effect. In version version 1.0.167 this option works as expected. 

Between the versions the serialport plugin changed from version 9.2.8 to version 10.0.0. Could be an issue there.

Best regards Matthias

**Comment by Eugeny** [comment]
which parity mode have you been using?

**Comment by kukuk2010** [comment]
I was waring with 'odd' parity

**Comment by kukuk2010** [comment]
Thanks for fast reacting. But I'm sorry to say to have the same issue with 1.0.169. 

I searched and found out that serialport library 10.0.0 has this bug. From Changelog it should be fixed in 10.0.1.

**Comment by Eugeny** [comment]
Good catch - my patch didn't apply on windows due to whitespace issues 😳  - I've now did a proper node-serialport upgrade: new nightly build incoming: https://github.com/Eugeny/tabby/actions/runs/1626553319
