### ISSUE TITLE
Can it support Duplicate SSH channel function like xshell

### ISSUE THREAD

**Issue by peitianwang** [Eugeny/tabby#5281]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangyulu** [comment]
That's exactly what I want. In some companies, we connect to servers through dynamic tokens like google authenticator. Without duplicating ssh channel, we have to input that dynamic tokens every time we start a new tab. Looking forward the  feature of duplicating ssh channel.

**Comment by Eugeny** [comment]
Duplicate of #4795

It's already available in the nightly builds (you need to enable it in the profile settings).
