### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by honglei-github** [Eugeny/tabby#5282]
Whether to enable automatic TRACING of SFTP directories by using shortcut keys？

**Comment by ryan7n** [comment]
![1646133549(1)](https://user-images.githubusercontent.com/44997334/156159952-8ad19fd4-c3a3-4571-ab4e-0873b8fb252d.png)


temp solution：
add login scripts :
if test -z "$(cat ~/.bash_profile|grep CurrentDir)"; then echo export "PS1=\"\$PS1\[\e]1337;CurrentDir=\"'\$(pwd)\a\]'" >>~/.bash_profile; fi

**Comment by Eugeny** [comment]
@honglei-github see https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting
