### ISSUE TITLE
Whether to jump to the SFTP panel by input a directory

### ISSUE THREAD

**Issue by zxiaozhou** [Eugeny/tabby#5285]
**Describe the solution you'd like**
1. Whether to jump to the SFTP panel by input a directory
2. SFTP takes you to the directory one by one. I know the directory address through PWD in shell, can I input the address directly? 
![image](https://user-images.githubusercontent.com/62740686/147319210-36bf164d-2357-4e1f-8406-a4aef4f729ea.png)

**Comment by Eugeny** [comment]
Click the lightbulb in the toolbar above

**Comment by zxiaozhou** [comment]
@Eugeny This position???，Can't enter directory address
![image](https://user-images.githubusercontent.com/62740686/147339501-4accf87a-fab6-474d-9f72-90137f46e688.png)

**Comment by Eugeny** [comment]
Yes, it will give you the instructions on how to set up your shell so that the SFTP panel automatically follows your current working directory.

**Comment by zxiaozhou** [comment]
@Eugeny But this needs to be configured on the remote server, and unlike Xshell does not require any configuration. And not being able to type in directory addresses is kind of anti-human. Other SFTP files allow you to enter directory addresses

**Comment by zxiaozhou** [comment]
@Eugeny XFTP, SecureFX, and so on can be entered with directory addresses. This eliminates input, and at the same time follows the current directory is troublesome, do not know why there is such a design
