### ISSUE TITLE
Can't scroll through the page with the mouse in “screen” 

### ISSUE THREAD

**Issue by cocollor** [Eugeny/tabby#5288]
when I use the command "screen",I can't use mouse wheel to scroll pages and the output is as follows

^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B

**Comment by eugenov** [comment]
echo "termcapinfo xterm* ti@:te@" > ~/.screenrc
did you try it?

**Comment by lanwenming** [comment]
> echo "termcapinfo xterm* ti@:te@" > ~/.screenrc did you try it?

It's ok, thank you!

**Comment by YossiCohen** [comment]
Thanks!!!

**Comment by frizib** [comment]
> echo "termcapinfo xterm* ti@:te@" > ~/.screenrc did you try it?

It doesn't help :(

**Comment by CSU-ZeyuZhong** [comment]
It helps!!! but it needed to quit screen first and return to it to take effect
