### ISSUE TITLE
set sftp in the current shell directory

### ISSUE THREAD

**Issue by ax7e** [Eugeny/tabby#5291]
**Is your feature request related to a problem? Please describe.
No.

**Describe the solution you'd like**
I want to be able to see my current shell working directory when pressing the sftp button.

**Describe alternatives you've considered**
No.

**Additional context**
For example, if I click the sftp button, I want to be in the .ssh directory.
![image](https://user-images.githubusercontent.com/53501747/147377866-fb33ee28-7c8c-449a-bc81-d101db0ffec5.png)

**Comment by DiaoWang** [comment]
> **Is your feature request related to a problem? Please describe. No.
> 
> **Describe the solution you'd like** I want to be able to see my current shell working directory when pressing the sftp button.
> 
> **Describe alternatives you've considered** No.
> 
> **Additional context** For example, if I click the sftp button, I want to be in the .ssh directory. ![image](https://user-images.githubusercontent.com/53501747/147377866-fb33ee28-7c8c-449a-bc81-d101db0ffec5.png)

Yes, me too. It's very very useful!

**Comment by DiaoWang** [comment]
Hey bro, see this can help you.
https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting
