### ISSUE TITLE
Accept path as command line positional argument

### ISSUE THREAD

**Issue by EternityForest** [Eugeny/tabby#5299]
**Is your feature request related to a problem? Please describe.**
Tabby doesn't work well as the default shell because opening it using file manager integration doesn't get you to the right folder.

**Describe the solution you'd like**
`tabby /folder/path` should open a new tab or window set to the specified working directory, as seems to be common with other shells.

**Comment by Eugeny** [comment]
`tabby open <path>`, see `--help`

**Comment by EternityForest** [comment]
Oh awesome! This works on KDE, but I'm not sure it will work on all desktop environments as well if they don't allow an arbitrary string as a default application setting.
