### ISSUE TITLE
support saving log in serial port

### ISSUE THREAD

**Issue by ganqiuye** [Eugeny/tabby#5315]
In embedded development, it often need to save log in the serial port, so it is necessary to add this function

**Comment by JiachengLi163** [comment]
这个功能已经有了，需要下载一下插件。

**Comment by ganqiuye** [comment]
ok，THX

**Comment by JiachengLi163** [comment]
![image](https://user-images.githubusercontent.com/65708339/147539559-f32f4d56-3b17-48c0-bdc1-c27b419df137.png)
安装一下 save output这个插件就可以使用 保存log

**Comment by ganqiuye** [comment]
get it, thx
