### ISSUE TITLE
deb install/update is broken

### ISSUE THREAD

**Issue by SavuBogdan** [Eugeny/tabby#5333]
i followed the instructuons from the deb install guide and ran the following command

**curl -s https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash**

this repo has broken url 

![image](https://user-images.githubusercontent.com/37210559/147722108-1b3ed8c9-775a-4ccf-bb94-26f7faf166b4.png)

also when i try the other command to do "**sudo apt-get install tabby-terminal=1.0.169**"

![image](https://user-images.githubusercontent.com/37210559/147722183-2ec0b49f-2e57-40b5-a7f8-3e91a88ce52b.png)

trying without the version gives a similar result

![image](https://user-images.githubusercontent.com/37210559/147722247-743ab0cd-207e-4963-9b44-39ca3cc139c9.png)

so nothing seems to work from deb repos

**Comment by Eugeny** [comment]
The repo only contains packages marked for `bionic` and `focal`. You can adjust your sources.list as a workaround - I'll look into it.
