### ISSUE TITLE
Can you support quick string pasting in the shortcut key function?

### ISSUE THREAD

**Issue by linsijia1002** [Eugeny/tabby#5336]
Can you support quick string pasting in the shortcut key function?
For example, press F2 to quickly enter the set string in the terminal, like:
```
ps -aux | grep
```
So I don't have to retype it every time

Please support this function, because it's very useful for Daily use.
Thanks!

**Comment by Eugeny** [comment]
The "quick commands" plugin should be able to do this I believe.

**Comment by linsijia1002** [comment]
> 

thank you
