### ISSUE TITLE
When will stable release come out?

### ISSUE THREAD

**Issue by Confucian-e** [Eugeny/tabby#5338]
Hello sir, I'm new here. I just want to ask when will stable release come out in your roadmap.
**Describe the problem**:
[A clear and concise description of what the bug is.]

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Eldritch-Hive** [comment]
This is not a bug, don't use issues to ask questions. You can head over to [Discussions](https://github.com/Eugeny/tabby/discussions) for that. FYI I'm not involved with the project.
