### ISSUE TITLE
Conflicts exist when multiple Tabby windows opened

### ISSUE THREAD

**Issue by GodricG** [Eugeny/tabby#5346]
Version: 1.0.169
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm

The first Tabby window is docked on right. When i open another Tabby window, all Tabby windows are hidden and cannot bring anyone back no matter how i try.

**Comment by Eugeny** [comment]
Disable "hide dock on blur" in Settings -> Window.
