### ISSUE TITLE
Are you considering adding highlight words support?

### ISSUE THREAD

**Issue by lucas-law** [Eugeny/tabby#5350]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use the terminal to view some keywords, I hope these words can be highlighted

**Describe the solution you'd like**
Add a plug-in to support terminal keyword highlighting

**Describe alternatives you've considered**
Like xhell 7， it can highlight words
Thank you

**Comment by lucas-law** [comment]
My friends and I, even my colleagues in the company, are using tabby a lot, but the lack of this highlighting function makes us very troubled.

**Comment by DanRoses** [comment]
Very unlikely. 
https://github.com/Eugeny/tabby/issues/632#issuecomment-1002938290

**Comment by Qiming-Liu** [comment]
Duplicate of #632

**Comment by lucas-law** [comment]
Duplicate
