### ISSUE TITLE
bug: i have to switch to the latest node version every time i open a new terminal window

### ISSUE THREAD

**Issue by anuraglol** [Eugeny/tabby#5351]
Hey
I'm using WSL running Ubuntu, and the problem I'm facing is, every time I open a new terminal window, the node version resets back to v10 something.. and I have to change it to v17 every time using nvm `nvm use v17.3.0`

What is the workaround for this?

**Comment by Eugeny** [comment]
See https://stackoverflow.com/questions/47190861/how-can-the-default-node-version-be-set-using-nvm?rq=1
