### ISSUE TITLE
Stop quake mode disappearing if other app loaded inside

### ISSUE THREAD

**Issue by MANICX100** [Eugeny/tabby#5356]
**Describe the problem**:
Occasionally I would like to load another program on windows from terminal.
Other examples would be switching to linux bash and loading .bashrc for this I use
C:\Windows\System32\bash.exe ~ -c /bin/bash
already configured as a wsl alias

**To Reproduce**:
load above command or another program and the terminal hides itself.

Essentially i would like a config to keep it persistent onscreen until I use the hotkey to hide and ONLY then hide. This might hopefully be already possible?

**Comment by Eugeny** [comment]
Is this what you're looking for? (Settings -> Window) 
![image](https://user-images.githubusercontent.com/161476/147882366-bcb63b81-6204-4250-aec0-cccc4e64dea7.png)

**Comment by MANICX100** [comment]
Perfect thank you.
