### ISSUE TITLE
Can't build packages on actions

### ISSUE THREAD

**Issue by Bearcatail** [Eugeny/tabby#5359]
I forked this repository and enable the workflows. And I tried many times to build packages but never succeed:

![pic](https://user-images.githubusercontent.com/80463781/147860919-94152a33-c1f6-43d8-9eca-a86de23d5807.png)

Or there are somthing I need to set up before build?

**Comment by Eugeny** [comment]
Have you changed any file permissions in your fork? `scripts/build-native.js` must be executable.

**Comment by Bearcatail** [comment]
I get it, thanks!
