### ISSUE TITLE
scrollback not working in SSH terminal

### ISSUE THREAD

**Issue by stylemessiah** [Eugeny/tabby#5362]
Running latest

Mousewheel scrolls back through and back to commands, but window does not 

What am i missing here? Be nice to scrollback to previous output...

**Comment by Eugeny** [comment]
Which OS and shell are you using? Was that in a Screen/tmux?

**Comment by stylemessiah** [comment]
Im on Win 10 and connecting to a Ubuntu 20.04 LTS box via SSH, and yes with screen enabled, because disconnections, and hating to try and figure out where i was if it all goes to poop :)

I have a working scrollbar in Clink in another tab :)

**Comment by Eugeny** [comment]
screen doesn't work like a normal terminal as it's rendering its contents via the alternate buffer and there just "isn't" any scrollback. See the second entry here (https://web.archive.org/web/20190411015146/https://www4.cs.fau.de/~jnweiger/screen-faq.html) for explanation and workaround.

**Comment by stylemessiah** [comment]
Cheers!

**Comment by stylemessiah** [comment]
fwiw the linked articles solution is off by an * :)

Q: | My xterm scrollbar does not work with screen.

A: | The problem is that xterm will not allow scrolling if the alternate text buffer is selected. The standard definitions of the termcap initialize capabilities ti and te switch to and from the alternate text buffer. (The scrollbar also does not work when you start e.g. 'vi'). 

You can tell screen not to use these initialisations by adding the line  termcapinfo xterm ti@:te@  to your ~/.screenrc file

The line in ~/.screenrc actually needs to be (for me at least):

termcapinfo xterm* ti@:te@  

Happy camper now, thanks

**Comment by Eugeny** [comment]
:+1: the FAQ is very old, Tabby's $TERM is `xterm256-color`
