### ISSUE TITLE
Setting Color defaults for the default profile settings does nothing

### ISSUE THREAD

**Issue by Thom-netexpo** [Eugeny/tabby#5395]
Version: 1.0.169
Platform: Linux x64 5.11.0-43-generic
Plugins: docker
Frontend: xterm

Steps to reproduce:

1. Go to Profiles & Connections
2. Go to Advanced tab
3. Edit one of the default profile settings, for example `Local`
4. Set any value for `Color`
5. Open a connection of that type from the built-in profiles selector

"Bonus bug": (more than likely related)
After following the above steps:
1. Go back to Profiles tab
2. Copy one of the build-in profiles
3. Note that in pop-up the `Color` is set
4. Save profile
5. Created profile has no visible color

Only by changing the color to an other color and then changing it back to the default color, the color will appear.

**Comment by Hypn0sis** [comment]
Hi, have the same issue on 1.0.215 deb x86-64
