### ISSUE TITLE
vim operation shows chaotic problems

### ISSUE THREAD

**Issue by whuizhe** [Eugeny/tabby#5401]
![图片](https://user-images.githubusercontent.com/14052911/148314846-b3e482b7-5788-4e01-83eb-f669f5cde032.png)
It doesn't clear the screen

**Comment by whuizhe** [comment]
mac os 12.0.1

**Comment by GustabMG** [comment]
windows版本上也出现了类似的乱码

**Comment by GustabMG** [comment]
我发现好像是对字体的支持不完善导致的。最新版本（170）使用consolas字体后未再出现这个问题。
不过那个版本换别的字体很容易导致死机。
