### ISSUE TITLE
Split window

### ISSUE THREAD

**Issue by EricMzky** [Eugeny/tabby#5406]
Hello, when we open multiple terminals, we can be broken down into two Windows, but I want to return to the initial state, no matter how I didn't move split window operation, can only choose close him, but this will affect the use of I, so I need to work, how can let him return to the initial state in a line, thank you

**Comment by kusrinivasan** [comment]
Yes I also would like this feature or bug to be addressed.

**Comment by EricMzky** [comment]
@Eugeny Hello, I have updated to version 1.0.170, but I still find that window drag does not work. Now I have two tabs, one of which contains three window terminals. I can't drag any of the three Windows into the tabs and turn them into three tabs. Is there something wrong with my operation? Thank you, if you can, you can send me email ericmzky@gmail.com, thank you for your help, thank you!

**Comment by Eugeny** [comment]
@EricMzky how are you doing it?

https://user-images.githubusercontent.com/161476/149730303-a6f21593-c0f5-4c49-bc5f-fb5fb0d19513.mov

**Comment by EricMzky** [comment]
https://user-images.githubusercontent.com/37823382/149963066-4d51b08c-5064-4ed3-9ac8-f7f677b885a7.mov

As the video shows, I want to put any of the tabs tabs on top of the new tabs. But the window in the TAB cannot be dragged out into a new TAB.
How can I implement this feature? thank you

**Comment by EricMzky** [comment]
I don't know how you operate at the moment of the third second. How can I move Windows the way you do

**Comment by Eugeny** [comment]
Hold the "rearrange panes" hotkey (Cmd-Shift / Ctrl-Shift).

**Comment by EricMzky** [comment]
> Hold the "rearrange panes" hotkey (Cmd-Shift / Ctrl-Shift).

wa oh ，so cool！ i get it ！

**Comment by EricMzky** [comment]
> Hold the "rearrange panes" hotkey (Cmd-Shift / Ctrl-Shift).

Thank you so much. Is that how Windows works? thank you

**Comment by Alex-duzhichao** [comment]
![image](https://user-images.githubusercontent.com/9667107/150458350-d3712362-327b-4504-8e61-d239983b0a57.png)

Hi @Eugeny, I am using Windows.  When I press `Ctrl-Shift` hotkey,  those widgets (like yours but on Windows) just appear a  little moment. So it's hard to choose the panes I want to  rearrange. Is this a bug on Windows?

**Comment by Eugeny** [comment]
@Alex-duzhichao hold `Ctrl-Shift` until you're done rearranging the panes.

**Comment by Alex-duzhichao** [comment]
> @Alex-duzhichao hold `Ctrl-Shift` until you're done rearranging the panes.

@Eugeny Yes, I keep holding `Ctrl-Shift`, but those widgets disappear after a little moment. 
I think those widgets should keep showing while I still hold `Ctrl-Shift`. So I think maybe it's a bug on Windows.
