### ISSUE TITLE
How to rename dynamic tab title in tabby terminal

### ISSUE THREAD

**Issue by chenbiaoyeting** [Eugeny/tabby#5408]
Version: 1.0.164
Platform: Windows x64 10.0.17763
Plugins: title-control, quick-cmds
Frontend: xterm

How to rename dynamic tab title in tabby terminal?  For example, change the tab title  to IP address.

**Comment by Eugeny** [comment]
You can set the tab title to static in any profile's settings, which will then use the profile name as tab title. 
![image](https://user-images.githubusercontent.com/161476/148404133-20f30a3a-bfa5-4605-838d-b6d853c50274.png)
