### ISSUE TITLE
SFTP Set up

### ISSUE THREAD

**Issue by centosliuhsuai** [Eugeny/tabby#5440]
How to set SFTP to open according to the server path, SFTP online editing how to specify the group custom editor (VScode)? @Eugeny

**Comment by Ningsir** [comment]
https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting

**Comment by centosliuhsuai** [comment]
How to edit the specified editor online?

**Comment by Ningsir** [comment]
I don't quite understand what you mean.

**Comment by centosliuhsuai** [comment]
Open sftp does not support online editing of the file, I want to select a specified editor to modify the file (function name (edit locally))
![image](https://user-images.githubusercontent.com/45585777/148874506-cd0b002d-3754-420d-a15d-4549487818e0.png)

**Comment by Eugeny** [comment]
It's using the application that's assigned to this file type in your OS. On Windows, you can download the file, right click, "open with" -> "other", select the new app and click "always use".
