### ISSUE TITLE
Cannot remove bold from font

### ISSUE THREAD

**Issue by cxaclaudio** [Eugeny/tabby#5444]
Is your feature request related to a problem? Please describe.
I couldn't move to Tabby yet because font characteristics aren't good. If I look over Xshell client, font DejaVu Sans Mono, with size of 9, and font type "normal", it looks ok, not to say perfect. If I try to set DejaVu Sans Mono on Tabby, I need change size to at least 12, and I cannot change font type, from bold to normal. By comparison, tabby appears to have font type set to "Bold" by default. and the characters do not look so clear comparing with Xshell.

Describe the solution you'd like
What I ask is for a clearer font, and ability to set it to normal, bold, italic, whatever.

Describe alternatives you've considered
Xshell gives me clear output.

Additional context
XShell output:
![xshell7-output](https://user-images.githubusercontent.com/77572140/149006023-09bb712d-4895-4ff1-8fb8-9b8e252228cd.PNG)

Tabby output:
![tabby-output](https://user-images.githubusercontent.com/77572140/149006039-3ee55f32-24c2-4f2d-bc6b-93904e902353.PNG)

**Comment by cxaclaudio** [comment]
I tried to set this.xterm.setOption('fontWeight', 400) , or 'normal' , among other things, did not work.

**Comment by Manuzor** [comment]
I noticed the same issue. @cxaclaudio did you continue investigating?

**Comment by iacob28** [comment]
Any update on this issue ?

**Comment by renraw** [comment]
same issue here, also noticed that on other monitors is clearer

**Comment by rmatte** [comment]
This is still a problem regardless of the font weight options being added. The default font is bold in Tabby and there's no way to disable bold. I opened https://github.com/Eugeny/tabby/issues/8164 to track this issue.
