### ISSUE TITLE
download finish status

### ISSUE THREAD

**Issue by tonycody** [Eugeny/tabby#5460]
Version: 1.0.169
Platform: macOS arm64 21.3.0
Plugins: sync-config
Frontend: xterm
![image](https://user-images.githubusercontent.com/6773121/149248210-84a129e6-5492-4dcb-ab54-bf4977ef2cef.png)

Why is it not done? What looks like a downloading state is actually finished downloading

**Comment by boonkerz** [comment]
Same Issue but should the popup be closed? or only the icon changed from x to an checked marker?
