### ISSUE TITLE
Reserve working directory when switch between different shell

### ISSUE THREAD

**Issue by Alex-duzhichao** [Eugeny/tabby#5467]
I use tabby (version: 1.0.169) on windows 10. 

Usually I am used  to switching shell between `Powershell`, `Cygwin` and `Git-Bash` using `switch-profile` hotkey. 
**I find sometimes the working directory is reserved between switch, and sometimes the working directory is not reserved.**

For example, suppose I am in the directory `C:\Users\vagrant\Downloads` using `Powershell`. 
If I switch to `Git-Bash` using `switch-profile` hotkey, I will be in the directory `/c/Users/vagrant/Downloads`. The working directory is reserved. 
But if i switch to `Cygwin`, I will always be in the home directory `/c/Users/vagrant`. The working directory is not reserved.

I made a table to illustrate all the switch combinations:

|From      |To        |Is working directory reserved|
|----------|----------|------------------------------|
|Cygwin    |Powershell|No                            |
|Powershell|Cygwin    |No                            |
|Cygwin    |Git-Bash  |No                            |
|Git-Bash  |Cygwin    |No                            |
|Git-Bash  |Powershell|Sometimes Yes, sometime No    |
|Powershell|Git-Bash  |Yes                           |

I think it's better that `switch-profile` can always reserve the working directory.

Thanks.

**Comment by Eugeny** [comment]
Done a bit of more exact testing (for later reference):

| Shell | Accepts WD | Reports CWD |
| - | - | - |
| PowerShell |  Yes |  Yes |
| Git-bash | Yes | Yes |
| cmd.exe (stock) | Yes | Yes |
| cmd.exe (clink) |   | Yes |
| MSYS2 | Yes |   |
| WSL | Yes |   |
| Cygwin |  No |   |

**Comment by Eugeny** [comment]
Tracking in #1703
