### ISSUE TITLE
Persist Zoom

### ISSUE THREAD

**Issue by OlaoluwaM** [Eugeny/tabby#5473]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could set the default zoom level for all tabs

**Describe the solution you'd like**
An option to set the default zoom of all tabs, with the shortcut working as is but based off the default zoom level

**Comment by Eugeny** [comment]
You can just change the font size, it has the same effect as zoom.

**Comment by OlaoluwaM** [comment]
Thank you!!
