### ISSUE TITLE
Can't input Chinese by Sougou IME

### ISSUE THREAD

**Issue by lanzhiquan** [Eugeny/tabby#5483]
Version: 1.0.171-nightly.0
Platform: Windows x64 10.0.22533
Plugins: none
Frontend: xterm

Sougou IME download link：
https://pinyin.sogou.com/

**Comment by Qiming-Liu** [comment]
Do other Chinese input tools have this problem for you? I'm using `xinshuru` and did not encounter this problem.

**Comment by lanzhiquan** [comment]
Microsoft Pinyin has no problem for input Chinese character.

**Comment by codingcai** [comment]
> Microsoft Pinyin has no problem for input Chinese character.

So do you try other IME (like Baidu) ? The Microsoft Pinyin works well but Sogou doesn't

**Comment by codingcai** [comment]
> Do other Chinese input tools have this same problem for you? I'm using `xinshuru` and did not encounter this problem.

You are right !! Good ! -:)
