### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [Eugeny/tabby#5493]
The Croatian translation is completly translated on [Crowdin](https://crowdin.com/project/tabby) and ready to be implemented.

Also, if you feel like it and if possible or necessary, you could set up a "Tabby website" and a "Tabby web app" translation projects at Crowdin.

**Comment by Eugeny** [comment]
Thanks a lot! v170 already includes the Croatian translation as seen a few days ago, and I'll pull the updates in the nightly shortly.

@allcontributors please add @milotype for translations.
