### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by pop-lee** [Eugeny/tabby#5499]
by password
![image](https://user-images.githubusercontent.com/7325728/149705405-59842b8c-3b8c-46a0-b7c8-dbef6d32dc09.png)

**Comment by pop-lee** [comment]
Tabby  Version 1.0.169 (1.0.169)
MacOS 12.0.1

**Comment by wgicio** [comment]
I have similar issue

**Comment by uuair** [comment]
useing "ssh-keygen -t ed25519" instead rsa

**Comment by utgpay2** [comment]
all bro,ubuntu have the problem,use centos is ok

**Comment by Eugeny** [comment]
Duplicate of #6804 - see that issue for more info.
