### ISSUE TITLE
FTP: change the directory to the current dir when start sftp

### ISSUE THREAD

**Issue by bigben0123** [Eugeny/tabby#5518]
I send my files to the different directories on a server, so I wish these several directories can be favorated or when I need to change directory, I can close sftp first, then when I reopen it, its default directory should be the directory same as my ssh current directory. Or I can paste the target directory on "show path" on sftp.
Thanks!

**Comment by centosliuhsuai** [comment]
https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting
