### ISSUE TITLE
No fingerprint warning for first login and ssh server changed fingerprint

### ISSUE THREAD

**Issue by BigStar0916** [Eugeny/tabby#5534]
For modern ssh,we do not care man in the middle attack? Even check base64 sha256 fingerprint.I also need my eyes to check every time for every login

**Comment by BigStar0916** [comment]
...

**Comment by TheAndrey** [comment]
@Eugeny Why does the application not remember the host key fingerprint and does not warn about it change? **This is an important security issue.** SSH doesn't use certificates and CA, authentication is carried out through memorizing the host key fingerprint.

**Comment by Eugeny** [comment]
Host key verification has been added in the nightly.
