### ISSUE TITLE
Vault 7 days to remember questions

### ISSUE THREAD

**Issue by tonycody** [Eugeny/tabby#5535]
![image](https://user-images.githubusercontent.com/6773121/150044565-f1dd211e-fd34-447a-8cca-4132df62f906.png)

Set to 7 days to remember, but sometimes open within 7 days still prompt for password

**Comment by Eugeny** [comment]
The "remember for" timeout does not apply if you close the app. Since the premise of the Vault itself is that your data is stored on disk encrypted, storing the passphrase alongside it somewhere renders it useless.
