### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by EricMzky** [Eugeny/tabby#5544]
Hello, I have the Monaco font installed in windows10, but I cannot set this font in tabby, and I find that the fonts in tabby are not supported very much. How can I support more fonts?  thank you

**Comment by Eugeny** [comment]
Please link the specific font file you're using.

**Comment by EricMzky** [comment]
<img width="648" alt="Snipaste_2022-01-20_11-46-45" src="https://user-images.githubusercontent.com/37823382/150269788-b942d442-8c08-45d5-bf88-725e72194dd7.png">
<img width="242" alt="Snipaste_2022-01-20_11-47-01" src="https://user-images.githubusercontent.com/37823382/150269796-c95cd808-f744-446c-b24c-08f26b8fe78c.png">
What should I do, thank you？

**Comment by EricMzky** [comment]
> Please link the specific font file you're using.

thanks！

**Comment by Eugeny** [comment]
Just post it here or mail it to e@ajenti.org

**Comment by 1JunGu** [comment]
> Please link the specific font file you're using.


I prefer `Fira Code` and `MesloLGS_NF` that are better than original fonts for me. Sorry for not understanding the solution. Could you please tell detailed procedures?

**Comment by Tim4497** [comment]
Also https://github.com/Twixes/SF-Mono-Powerline for all Apple Users

Origin: https://developer.apple.com/fonts/

**Comment by Eugeny** [comment]
For some reason, it's not considered monospace by `font-manager` - I've removed the monospace filter altogether.
