### ISSUE TITLE
Automatically detect light or dark mode based on system settings

### ISSUE THREAD

**Issue by MeerBiene** [Eugeny/tabby#5561]
**Is your feature request related to a problem? Please describe.**

It would be neat to have to option to choose a theme for light mode and one theme for dark mode - kinda like github did it

**Describe the solution you'd like**

- Switch to toggle "automatic mode" switching 
- Option to choose either only one theme or 2 themes when the automatic dark mode is activated

**Describe alternatives you've considered**

I thought about writing a plugin but this seems like it should be a core functionality

**Additional context**

**Comment by Arro** [comment]
+1 for this.  Would be nice.  Feels like a must-have feature these days.

**Comment by zhouzq-thu** [comment]
+1, maybe just check if
```
defaults read -g AppleInterfaceStyle
```
is 'Dark' or 'does not exist'.

**Comment by ysc3839** [comment]
On Windows, you can read registry `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` `AppsUseLightTheme` DWORD value to get dark mode setting for apps. When dark mode changed, there will be `WM_SETTINGCHANGE` message sent to top-level windows, with `lParam = wchar_t* "ImmersiveColorSet"`.

**Comment by OoguroxRyuuya** [comment]
Is there any progress on this issue?

**Comment by Sonicfury** [comment]
+1, really looking forward to using this feature

**Comment by Eugeny** [comment]
Coming to the nightly build in https://github.com/Eugeny/tabby/actions/runs/5592726182
