### ISSUE TITLE
通过sftp上传文件失败

### ISSUE THREAD

**Issue by newbieandroid** [Eugeny/tabby#5562]
Version: 1.0.170
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

![image](https://user-images.githubusercontent.com/25599357/150497907-8b043d16-032a-48db-b1c1-75df3a0542ec.png)
![image](https://user-images.githubusercontent.com/25599357/150497971-acf019dc-97ba-488b-9798-4ce8a0bdd603.png)

**Comment by Eugeny** [comment]
#5532
