### ISSUE TITLE
Option to log all session content to file by default

### ISSUE THREAD

**Issue by SolidState214** [Eugeny/tabby#5572]
Automatic recording of session output to file based on profile settings. Similar to the "save-to-file" plugin, but automatic based on profile settings.

**Is your feature request related to a problem? Please describe.**
Records of terminal sessions are useful :)

**Describe the solution you'd like**
The start of a session should create a new log file with support for variables; e.g. $profile_name-$date_stamp.log. This should be configurable in the profile.

**Describe alternatives you've considered**
The "save-to-file" plugin is close, but involves a manual process and manual file naming. This functionality would be great as a profile option.

**Additional context**
See the way SecureCRT has implemented this feature with filename variables and line timestamps.

**Comment by Eugeny** [comment]
The "save output" plugin has an option to save logs automatically - see `Settings -> Save output`
