### ISSUE TITLE
[Feature request] how to execute command simultaneously in multiply tabs or panes in one tab??

### ISSUE THREAD

**Issue by bingo4933** [Eugeny/tabby#5573]
as the subject description, what if tabby has this function??
scenario I, running command in multiple tabs
    - type command in one tab and press enter, this command are executed simultaneously in some other tabs.

scenario II, running command in multiple panes
    - in one tab, I've splitted some panes, type command in one pane and press enter to run it, other panes  run that command simultaneously as well.

or need download plugin to achieve it?

would some guy please help ??
thans a lot in advance.

**Comment by Eugeny** [comment]
You can do this with multiple panes, but not with multiple tabs - use the `Focus all panes` hotkey or context menu item.

**Comment by yanyujian** [comment]
Ctrl+Alt+Shift+I
