### ISSUE TITLE
Inline Suggestions?

### ISSUE THREAD

**Issue by kacperleague9** [Eugeny/tabby#5579]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
Like in title, inline suggestions like some linux terminals have (show you what will happen after tab)

**Comment by Eugeny** [comment]
This is something you set up within your shell - not the terminal app. If you specify your shell and OS, I could point you in the right direction.

**Comment by kacperleague9** [comment]
Thanks for the quick answer, im on windows 10 and i use ssh option so idk what terminal (probably command prompt)?

**Comment by Eugeny** [comment]
In that case the only thing that matters is the shell on the remote side.

**Comment by kacperleague9** [comment]
It is ubuntu server 20, default shell

**Comment by kacperleague9** [comment]
i resolved that myself, thanks
