### ISSUE TITLE
Editing .zshrc file does not enable Shell working directory reporting

### ISSUE THREAD

**Issue by jsuri5356** [Eugeny/tabby#5581]
Hi!

I'm on macOS Monterey, and by default the .zshrc file is not there so I had created one and pasted the command shown in [here](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting). After doing this, I am still unable to open my SFTP into the folder that the shell is in. Am I doing something wrong, or is this a bug? Thank you!

**Comment by Eugeny** [comment]
You need to edit .zshrc/.bash_profile on _the machine you're connecting to_.
