### ISSUE TITLE
Ability to click on links made with echo or printf

### ISSUE THREAD

**Issue by hazardousthingy** [Eugeny/tabby#5612]
When in shell you write out url strings, Tabby cant click on them. 

e.g.  
echo -e '\e]8;;http://example.com\aThis is a hyperlink\e]8;;\a'  

printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'

both provide a text in the shell which is not clickable (to take you to the URL behind the string).

**Comment by Eugeny** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1134

**Comment by jack1142** [comment]
FYI, a stable version of xterm.js 5.0 has now been released (just 10 minutes ago) and it brings support for hyperlink escape sequences among other things:
https://github.com/xtermjs/xterm.js/releases/tag/5.0.0
