### ISSUE TITLE
Add Translations to Crowdin

### ISSUE THREAD

**Issue by gOOvER** [Eugeny/tabby#5613]
Crowdin is a Translation platform with Github integration and it's free for OpenSource projects.

It would be nice, when you adding the translations to crowdin.

Homepage: https://crowdin.com/
Opensource Licence: https://crowdin.com/page/open-source-project-setup-request

**Comment by Eugeny** [comment]
Already done - see https://translate.tabby.sh/project/tabby

**Comment by TheAndrey** [comment]
Please add information about string usages (context). It is difficult to make a high-quality translation without understanding where this line is used.
Also there is no need to translate the names of languages. It's unnecessary. Use English names or in language self name.
