### ISSUE TITLE
MacOS Require a key to click links does not work for Ctrl and No modifier

### ISSUE THREAD

**Issue by max1c** [Eugeny/tabby#5616]
**Describe the problem**:
The 'Ctrl' and 'No modifier' for the Require a key to click links does not seem to work on MacOS. I tested the other options like command, shift, and alt, all work correctly.

**Comment by Eugeny** [comment]
Fixed the "no modifier" option in 9893fb51, but Ctrl won't work on macOS as OS captures it to reinterpret as a right click.
