### ISSUE TITLE
New tab and new tab with profile hotkeys

### ISSUE THREAD

**Issue by TimaGribanov** [Eugeny/tabby#5617]
**Describe the problem**:
Hello
I have set a hotkey to open a new tab as Ctrl-T, and at the same time, I've set another hotkey (Ctrl-T-1) to open a tab with a profile.
However, when I pres Ctrl-T-1, both tabs are opened. So, it seems the app is triggered by Ctrl-T as well.
Actually, I am not sure if it's a bug. Probably, I just don't quite understand how it should work.

**To Reproduce**:
Settings -> Hotkeys
Configure `New tab` and `New tab: <your_profile>` as the same hotkey prefix (e.g. Ctrl-T for `New tab` and Ctrl-T-1 for `New tab: <your_profile>`
![image](https://user-images.githubusercontent.com/48593815/151379407-352120c8-3c3f-4654-a5d7-54882a9ac2b6.png)

**Comment by Eugeny** [comment]
This (overlapping hotkeys) unfortunately won't work since the app can't know whether you are going to press the third key. 

The hotkeys are in fact triggered twice: once when you hold Ctrl and press T, and the other when you hold Ctrl and T and press 1.

**Comment by TimaGribanov** [comment]
Thank you for your comment
