### ISSUE TITLE
Tilde Character (~/.ssh/[file]) Not Recognized in Windows Built-In OpenSSH Config File

### ISSUE THREAD

**Issue by lahma0** [Eugeny/tabby#5627]
OS: Windows 11 (21H2) x64 Enterprise
Tabby Version: 1.0.170 (Portable)

**Describe the problem**:
Using the built-in OpenSSH client on Windows 10/11, config files support using a tilde (~) character to designate a user's home directory, just as it would on Linux. This makes your SSH config file easily portable between Windows and Linux. However, when using Tabby to try and open a profile that is automatically detected/imported from "C:\Users\[Username]\.ssh\config", I am getting the following error if my SSH config file contains a path that has a tilde character in it:

> SSH   !  Could not load private key ~/.ssh/id_ed25519: Error: Not found

In Windows, cmd prompt does not recognize tilde as a valid path character but both Powershell and Pwsh (Powershell 7) do recognize it as a valid character. Despite this, the built-in OpenSSH client works fine when run from command prompt or Powershell (when the OpenSSH config file contains a path using the tilde character). This makes me think it is likely that Tabby is using its own built-in SSH client which does not recognize the tilde as a valid path character on Windows. If it was using Windows' built-in OpenSSH client, it doesn't appear that this would be an issue.

Here is an example entry from my OpenSSH config located at "C:\Users\[Username]\.ssh\config":

> Host home
>     HostName MyHomeDomain.com
>     Port 2222
>     User john
>     IdentityFile ~/.ssh/id_ed25519
>     ServerAliveInterval 15
>     ServerAliveCountMax 3
>     ForwardAgent yes

**To Reproduce**:

- On Windows, create an OpenSSH config file at "C:\Users\[Username]\.ssh\config" and create an entry in it that uses a tilde character in the 'IdentityFile' path
- Install latest Tabby and it should automatically find and import this entry from your config file
- Try to open this profile in Tabby and you will receive an error about it not being able to load your private key

**Comment by aroldobossoni** [comment]
I have this error before connection:

ssh: Could not resolve hostname serv: Este host n**\343o \351** conhecido.
