### ISSUE TITLE
WSL2 tab name is always "C:\WINDOWS\system32\wsl.exe"

### ISSUE THREAD

**Issue by MoussaSak** [Eugeny/tabby#5629]
Version: 1.0.170
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm
WSL2 image:  

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

![image](https://user-images.githubusercontent.com/16084105/151639639-9f9b01a4-47cb-4fb2-a2b6-a7d688d03868.png)

**Comment by Eugeny** [comment]
To show the profile name instead:
* Tick "disable dynamic title" in the profile settings

To show the directory instead:
* You need to configure the shell you're using inside WSL to show the current directory in the window's title. Example for bash: `PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'`
