### ISSUE TITLE
question about “Ports” feature

### ISSUE THREAD

**Issue by firmianay** [Eugeny/tabby#5630]
Hello, I would like to ask a question. I have opened a simple service on 127.0.0.1 port 8000 and want to open it to other machines in the intranet, for example, use a browser to access http://10.248.156.19:8000. How do I achieve this through the “Ports” feature?

```
$ python3 -m http.server --bind 127.0.0.1 8000
Serving HTTP on 127.0.0.1 port 8000 (http://127.0.0.1:8000/) ...

$ ifconfig
enp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.248.156.19  netmask 255.255.252.0  broadcast 10.248.159.255
        inet6 fe80::56e8:7aa6:dc53:b213  prefixlen 64  scopeid 0x20<link>
        ether 6c:02:e0:64:88:bd  txqueuelen 1000  (Ethernet)
        RX packets 157212  bytes 26826717 (26.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20221  bytes 3194380 (3.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 10917  bytes 2521341 (2.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10917  bytes 2521341 (2.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by Eugeny** [comment]
This is not terminal specific - just use your IP (or 0.0.0.0 for "all addresses") instead of 127.0.0.1 in --bind.

**Comment by firmianay** [comment]
What if 127.0.0.1 is hardcoded and I can't change? So Ports is not for this, I have to use a reverse proxy like nginx?

**Comment by Eugeny** [comment]
Sure, you can also use a remote port forward for this (forward `10.248.156.19:8000` to `127.0.0.1:8000`)

**Comment by firmianay** [comment]
![image](https://user-images.githubusercontent.com/15265215/152731825-d251df3d-65d9-4ec2-b666-46f8ef13090a.png)

I did that but still can't access
```
$ curl 10.248.156.19:8000
curl: (7) Failed to connect to 10.248.156.19 port 8000: Connection refused
```

**Comment by Eugeny** [comment]
Just to clarify - is the :8000 service running on the remote machine, or on your local machine?

**Comment by firmianay** [comment]
I use tabby's ssh to connect to a linux server in the same intranet on windows, the 8000 service runs in the server, and then I want to access 10.248.156.19:8000 on windows.
