### ISSUE TITLE
SageMath terminal shell is not supported?

### ISSUE THREAD

**Issue by uncopyrightable** [Eugeny/tabby#5634]
Tabby opened a new terminal window instead of a new tabby tab.

Program:
D:\SageMath 9.2\runtime\bin\mintty.exe

Arguments:
/bin/bash
--login

working directory:
D:\SageMath 9.2\runtime\bin\

Env:
TERM=cygwin

Thanks. Best Regards.

**Comment by Eugeny** [comment]
`mintty` is the cygwin/msys's GUI terminal app itself - try using `runtime\bin\bash.exe` as the "Program" in your profile.

**Comment by uncopyrightable** [comment]
It works, 3Q very much, but there still another problem: sage-series commands are not available in such status.
