### ISSUE TITLE
Save Connection As missing on SSH tabs

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#5688]
### Discussed in https://github.com/Eugeny/tabby/discussions/5686

<div type='discussions-op-text'>

<sup>Originally posted by **ismaelbalkhi** February  7, 2022</sup>
Hello,

I love Tabby! Now that that is out of the way. I constantly SSH into hundreds of hosts, it would be nice if I could **'Right-Click'** on an established connection and **'Save-As'** a profile along with the login credentials I used. Right now, this easy method is not available. I have to go, one-by-one into Settings to create individual profiles which isn't feasible in the long run for so many connections. Also, does anyone know of a nice Sessions Manager within Tabby that could handle hundreds of saved profiles and be able to organize/sort them? 

Currently, I quickly connect via myName@10.10.10.10:22, but I don't see a way to save it efficiently.

Thanks!</div>

**Comment by randadinata** [comment]
Yes, it would be nice to connect first, save profile later as needed. In tabby you cannot do that. Either you save first and then connect. Or you connect first but save later by manually retyping the connection details. I see that the default terminal profile (clink) has **Save as profile** on the menu. But there's no such menu for SSH tabs.
