### ISSUE TITLE
Add commands to merge/split all tabs

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#5703]
* Merge all open tabs into split panes inside the current tab
* Split out all panes from current tab into separate tabs

**Comment by Whipplash** [comment]
Hey again! I had another thought whilst on the job. Would it at all be possible to define/select multiple split panes that I want to send text/input to:

By holding a key of my choice (let's say the hotkey bind had been set to ALT),

and then left-click each pane I wish to work on?

No rush on this by any means, I just thought of it while working and figured I'd write it down somewhere.

**Comment by Eugeny** [comment]
Yeah that should be generally possible although the current `SplitTabComponent` only allows either "all or nothing" approach to focusing.
