### ISSUE TITLE
ssh window can not show the theme

### ISSUE THREAD

**Issue by xdxiaoran** [Eugeny/tabby#5709]
**Describe the problem**:
local zsh can show the right theme on it,but ssh window is not available.
![image](https://user-images.githubusercontent.com/57976020/153201952-5004ea52-cbdb-4a3b-9c68-2678443e4408.png)
![image](https://user-images.githubusercontent.com/57976020/153202003-5c72bff9-71af-43b0-a03f-5a394e9c156d.png)

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Eugeny** [comment]
This depends on your shell, see https://github.com/Eugeny/tabby/discussions/5258
