### ISSUE TITLE
SSH: add static json file profile importer

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#5712]

**Comment by apiening** [comment]
This feature would be very much appreciated!

For those who don't know: This would behave similar to the **Dynamic Profiles** feature in **iTerm2**. You can easily populate a list of static profiles based on a simple JSON file this way.

**Comment by Eugeny** [comment]
This now works for a `ssh-profiles.yaml` file next to `config.yaml`. Example:

```yaml
- name: test
  options:
    host: 1.1.1.1
```

**Comment by apiening** [comment]
Wow you are incredible!

Can I test this already with the latest nightly from https://nightly.link/Eugeny/tabby/workflows/build/master?

Where can I look up the supported options?

**Comment by Eugeny** [comment]
The yesterday's build has failed but a new one should be up soon: https://github.com/Eugeny/tabby/actions/runs/1822722132

The options are all the same as in `config.yaml` - you can create a test profile in the UI and then copy over the options.
