### ISSUE TITLE
[BUG]: Scroll wheel behavior changes without warning 

### ISSUE THREAD

**Issue by h3n4l** [Eugeny/tabby#5720]
**Describe the problem**:
When I use **tabby(version: 1.0.169)** to remote my cloud hosting, the scroll wheel behavior changes **from turning pages to selecting history command**. At the same time, the scroll bar disappeared.

**To Reproduce**:
I can't reproduce with specific steps. But it always appear.

**Pics**:
Normal:
![图片](https://user-images.githubusercontent.com/87714218/153372258-bd9b45b2-c402-4c33-b075-9de429bcec59.png)
Bug appear:
![图片](https://user-images.githubusercontent.com/87714218/153372354-13a06d18-8439-4cb1-a402-bbbc6d17620f.png)
Check scroll bar in two situations described above.

**Comment by Eugeny** [comment]
This is usually the case when some program screws up terminal modes when exiting incorrectly or crashing. Doesn't this also happen for you in other terminals?

**Comment by h3n4l** [comment]
> This is usually the case when some program screws up terminal modes when exiting incorrectly or crashing. Doesn't this also happen for you in other terminals?

It doesn't appear in XShell and my default terminal ( cmd or powershell ).

**Comment by petrosschilling** [comment]
Any solutions for this? Still happening
