### ISSUE TITLE
Can't connect SSH via Socks5 Proxy when ip belongs to Private network

### ISSUE THREAD

**Issue by W0n9** [Eugeny/tabby#5730]
**Describe the problem**:
I have tried Alpha 171, it solved the major problem when connect SSH via socks5 proxy, but it still raise an error when target ip belongs to [Private network](https://en.wikipedia.org/wiki/Private_network), such as 10.0.0.0/8, 172.16.0.0/12 and fd00::/8 .

Error message:
```
 SSH  Connecting to 100.64.1.1
 SSH   Proxy  Using 127.0.0.1:10808
 X  Connection lost before handshake
```
```
[ssh-shell-100.64.1.1-22]  X  Remote rejected opening a shell channel: Error: Not connected
````
**To Reproduce**:
1. Create a new config which use socks5 proxy to connect SSH and its target ip belogs to Private network
2. Connect
3. Error Reproduced

**Comment by Eugeny** [comment]
Can you confirm that the proxy server works in general (e.g. using `nc` as a proxy command)?

**Comment by W0n9** [comment]
Yes, this proxy server works well and I can use tabby to connect Public Network Servers via this proxy server, and I have tried other terminal client, such as MobaXterm to connect Private Network Servers via this proxy server, but I can't use tabby to connect Private Network Servers via this proxy server.

**Comment by W0n9** [comment]
Problem solved! It is a bug of my proxy server.
