### ISSUE TITLE
Tabby not opens after closing

### ISSUE THREAD

**Issue by YarikDev2008** [Eugeny/tabby#5733]
Version: 1.0.171
Platform: Windows x64 10.0.18363
Plugins: none
Frontend: xterm

My problem: Tabby not opens after closing from window
Reason: Tabby's process stays after closing, but not shows new window when i try to start them from icon on Desktop
![2022-02-12_11-24-07](https://user-images.githubusercontent.com/65668478/153690764-9ebcc930-ff06-44fe-afc1-eed793d8ca6f.png)

**Comment by goophps** [comment]
I had the same problem on a linux system.

**Comment by Eugeny** [comment]
Fixed in 60a48ec2
