### ISSUE TITLE
Every time I use SFTP and want to view recent files, it takes a lot of time to drag the slider to the very bottom.

### ISSUE THREAD

**Issue by goophps** [Eugeny/tabby#5741]
Every time I use SFTP to view recent files, I have to drag the slider to the bottom for a long time. I hope this can be optimized.

**Comment by goophps** [comment]
anyone there?

**Comment by goophps** [comment]
no one cares about me

**Comment by goophps** [comment]
Come on people, how come no one pays attention to this demand!

**Comment by Eugeny** [comment]
Duplicate of #4180
