### ISSUE TITLE
In Color Scheme settings, preview more practical information

### ISSUE THREAD

**Issue by drone1** [Eugeny/tabby#5742]
**Is your feature request related to a problem? Please describe.**
Yes. I have to go to an active WSL/Ubuntu terminal to check each preview, because a simple ``ls`` command is often completely unreadable for many color schemes. Example:

![image](https://user-images.githubusercontent.com/6324796/153757439-e1a90cb7-da17-45f4-9627-b18569c90446.png)

Many color schemes display filenames from a ``ls`` command where the foreground color is literally almost the same as the background color:

![image](https://user-images.githubusercontent.com/6324796/153757558-6a23ef28-5543-4bf4-963f-40802d5e32f4.png)

I'm having to change color scheme, then click on an active tab in order to properly preview, and it seems that a lot of schemes are just broken.

**Describe the solution you'd like**
I'd like a preview that includes a full example of all cases, including highlighted text.

**Describe alternatives you've considered**
If it's easy/you have the data: Sort schemes by popularity, so the ones that have issues can sink to the bottom.

**Comment by Eugeny** [comment]
If you could capture a few examples, I can add them. See here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

**Comment by drone1** [comment]
Hey @Eugeny. Sorry about that, I missed your response here.

Was the issue resolved, or are you closing because you did not hear back from me?

If you need more data still, please give me a little time and I'll get back to you here. Thank you!

**Comment by Eugeny** [comment]
Sorry - I've added these two examples (black over green and grey) and closed the issue with a commit. GitHub should be showing this above the "closed" message. Let me know if there are other problematic color combos I should add to the preview

**Comment by drone1** [comment]
You’re right. Sorry, brain error. Thanks a lot.
