### ISSUE TITLE
SFTP can easily locate the target directory

### ISSUE THREAD

**Issue by ykgw-quliang** [Eugeny/tabby#5744]
![image](https://user-images.githubusercontent.com/66979744/153784352-534610e8-1a94-4309-84f9-2aa45758b287.png)
When selecting a file to download in the SFTP window, it is troublesome to find a directory when there are many root directories, 
I have to drag the slider to the bottom for a long time. I suggest adding a text box where can enter the path. I hope this can be optimized.

**Comment by Eugeny** [comment]
Duplicate of #5646

**Comment by ykgw-quliang** [comment]
thanks a lot, I see.
