### ISSUE TITLE
CTRL-C does not work, when connected over a proxy host

### ISSUE THREAD

**Issue by chefschaffner** [Eugeny/tabby#5753]
**Describe the problem**:
CTRL-C does not stop the running process. 
Im using ssh over a proxy. Everything works fine, but I'm not able to stop a running process via CTRL-C.

I tried with setting the shortcut for **intelligent CTRL-C /copy/abort)** to CTRL-C and tu NUL.

On a connection without proxy it works well.

**To Reproduce**:

- Open a ssh session via an proxy host
- tail a log file, e.g. `tail -f /var/log/syslog`
- Press CTRL-C
- I just get a printout of STRG-C (see picture), but taill will not end.
![image](https://user-images.githubusercontent.com/33776820/153876237-b78493de-820a-48a0-8f54-c1e85f4a26f3.png)
- This does not only occur with tail, but on all commands, I usually can quit via CTRL-C. (works on same server, over proxy, same command when using putty or kitty)

**Comment by chefschaffner** [comment]
I'm using a jump host at port 22.

**Comment by Eugeny** [comment]
Does Ctrl-C work on the jump host itself?

**Comment by chefschaffner** [comment]
Yes, it does.

**Comment by chefschaffner** [comment]
Hi  @Eugeny ,
I'm sorry - my last information was wrong.
I switched to connection without jump host this week and just now I found, that CTRL-C does also not work when using a direct connection.

I'm wondering, if there is a relation to 'tail', because today the problem occurs while using tail again....

Beg your pardon fpr misinformation

**Comment by Eugeny** [comment]
No problem. Can you run `showkey -a` and see what keycode ctrl-c is generating on the other side?

**Comment by chefschaffner** [comment]
^C        3 0003 0x03

**Comment by Eugeny** [comment]
Do other processes stop on ctrl-c? Is it about `tail -f` only?

**Comment by chefschaffner** [comment]
Sorry for the long time, but now I found the error: The problem sat in front of the Monitor....
I had a wrong prompt setting, where a unnecessary character lead to this error.

I cannot explain - but now it works.
Sorry for that!

**Comment by Eugeny** [comment]
No problem, thanks for posting a followup.
