### ISSUE TITLE
Unable to connect to SSH server via CyberArk proxy

### ISSUE THREAD

**Issue by rbukovansky** [Eugeny/tabby#5770]
Version: 1.0.172
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

Hi,
our company started to use CyberArk IAM software for the management of passwords to our servers.
With that, the connection string changed to this complicated thing:

`my_username@server_username@target_server_fqdn@cyberark_proxy_fqdn`

Unfortunately, this does not work with Tabby. In Putty, it works just fine.

Could anybody please take a look? I think it has to do something with that many @ in that string. Probably.

Thank you,
Richard Bukovansky

**Comment by rbukovansky** [comment]
Never mind, I have found out the workaround...
As a server I use the name of the proxy, then the username is the rest of the connection string.

Richard

**Comment by f3b377e** [comment]
hi @rbukovansky,

are u still using tabby & Cyberark? Im facing same issues and can't find the right setting.
Thanks
