### ISSUE TITLE
Style display issue under oh-my-zsh bullet-train theme

### ISSUE THREAD

**Issue by lyx10101010** [Eugeny/tabby#5774]
**Describe the problem**:
- At v1.0.172's tabby 
![image](https://user-images.githubusercontent.com/16348807/154191690-a76772fc-2bf6-4e4f-b6fd-bb96c3a6be56.png)

- At xshell 
![image](https://user-images.githubusercontent.com/16348807/154191471-50d6770f-c17e-40a7-9ccb-e724d157f20d.png)

**To Reproduce**:
- Install [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh)
- Use [bullet train theme](https://github.com/caiogondim/bullet-train.zsh)
- .zshrc profile is as follow
```
# If you come from bash you might have to change your $PATH.

source ~/app/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle fzf
antigen bundle ubuntu
antigen bundle urltools
antigen bundle git-flow
antigen bundle git-extras
antigen bundle tig
antigen bundle httpie
antigen bundle command-not-found
antigen bundle colored-man-pages
antigen bundle skywind3000/z.lua
antigen bundle sukkaw/zsh-proxy

# Search in the local tree of subdirectories for files(just files! No directories nor links)
#antigen bundle leophys/zsh-plugin-fzf-finder
#antigen bundle andrewferrier/fzf-z
#antigen bundle Aloxaf/fzf-tab

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting


# Load the theme.
#antigen theme robbyrussell
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
BULLETTRAIN_PROMPT_ORDER=(
  context
  time
  dir
  git
)

BULLETTRAIN_CONTEXT_BG=green

# Tell Antigen that you're done.
antigen apply
```

**Comment by Eugeny** [comment]
If your prompt contains Powerline characters, you should be using a font that includes them as well.

**Comment by lyx10101010** [comment]
Thanks for your quick reply! Can you tell me how to setup? I used the same font as Xshell, but I didn't see the effect.

**Comment by Eugeny** [comment]
Hey - it looks like Xshell is doing some magic to support Powerline characters (these triangle "junctions") even if the font you're using doesn't have them. For other terminals, you need to use a special patched version of a font with the characters added in, you can see if you can find yours at https://www.nerdfonts.com/font-downloads

**Comment by weifan01** [comment]
> Thanks for your quick reply! Can you tell me how to setup? I used the same font as Xshell, but I didn't see the effect.

set fallback font to "Hack Nerd Font Mono" can solve it

![image](https://user-images.githubusercontent.com/24838466/155253167-3344e47c-77d5-46ac-a1a3-73c9c42228fc.png)

![image](https://user-images.githubusercontent.com/24838466/155253222-b0b36036-0b32-4716-8c6c-25d5c4dc3a4c.png)

**Comment by Eugeny** [comment]
The nightly build now also includes Source Code Pro NF as the "2nd fallback" font
