### ISSUE TITLE
Tabby Can't remember ssh host key ? [configuration file not saved]

### ISSUE THREAD

**Issue by Mathieu-Coupe** [Eugeny/tabby#5797]
Version: 1.0.172
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

Each time I start Tabby and connect to SSH host, I get the dialog box asking for "Host Key verification".
Event if I select "accept and remember the key", I'll the same dialog on next start.

I also checked in the configuration file and it seems that the "ssh -> knownHosts" section is created but the configuration file itself is not saved when quitting. So, on next start, it ask again.

**Comment by Remonli** [comment]
I got same problem.

**Comment by astromasoud** [comment]
I had to disable "Verify host keys" under SSH in Settings

**Comment by thenicholas** [comment]
Same to me.
