### ISSUE TITLE
Default .bashrc not used on Manjaro Linux

### ISSUE THREAD

**Issue by piersandro** [Eugeny/tabby#5803]
Version: 1.0.172
Platform: Linux x64 5.15.21-1-MANJARO
Plugins: none
Frontend: xterm

Hi,

I use Tabby on my MacBook Air M1 at home and on a Manjaro Linux at work.

I noticed that using "bash" as default terminal on Mac it loads the `.profile` file but on Linux it ignore the `.bashrc` configuration. I need to manually execute `source ~/.bashrc` to use my configuration and aliases every time.

![tabby-bashrc](https://user-images.githubusercontent.com/19996309/154926998-e8b9b74a-9328-43e2-a3c6-f43f7a294c83.png)

I solved at the moment removing the `-l` option on a custom profile.

**Comment by erichlf** [comment]
This is because that is how those OSes do things. I don't think this is a bug in tabby.

**Comment by nuncio-bitis** [comment]
Mac is based on UNIX, which is not quite the same as Linux. Linux is GNU, and Apple didn't want to deal with the open-source licensing, so they went with a proprietary version.
Running 'man bash' on each system will open the documentation where you can learn how that flavor of bash operates.

**Comment by piersandro** [comment]
Hi @erichlf @nuncio-bitis as I wrote, I solved (on Linux) by removing the `-l` option used by default to launch a bash shell.
My "request" was to understand if the `-l` option it is mandatory or could be removed by default to solve this very small issue.

**Comment by piersandro** [comment]
Thank you @erichlf. I will use my _workaround_ because I prefer the "non login shell".
I close the issue.
