### ISSUE TITLE
Connect to a SSH URI from CLI

### ISSUE THREAD

**Issue by hanzixiaoshu** [Eugeny/tabby#5820]
Is command line connection supported?
for example：xshell
![image](https://user-images.githubusercontent.com/12489036/155250498-4ace50f9-ec10-48e3-ab39-2c105c768b48.png)

**Comment by ocin99** [comment]
Hello,

Indeed it would be nice to allow to create connections from the command line.
I think a lot of users use software like keepass (we need login/password not only for SSH/Telnet connections...) and allowing this interoperability would be a big advantage.
I'm just starting to use Tabby and I find it really fun!!!

Regards

**Comment by hanzixiaoshu** [comment]
Hello，You're right.

**Comment by duskst** [comment]
Exactly my thoughts.

I want to use tabby as a third-party tool. In my case, the URI is different each time, even though the hosts accessed are the same. So I can't add it directly in the Profiles&connections.
Hope to support SSH URI in CLI.

**Comment by ashneilson** [comment]
Hello 👋 

If PR https://github.com/Eugeny/tabby/pull/9383 is accepted and merged, that should provide the functionality you are looking for.
