### ISSUE TITLE
Can I sort profiles & connections by name？

### ISSUE THREAD

**Issue by ansoda** [Eugeny/tabby#5832]
Can I sort profiles & connections by name？

**Comment by EricYangHai** [comment]
my ways is rename all profiles with a prefix, the most popular profiles will have prefix "A-", the prefix for  second level profiles is "B-".
hope this can solve your problem

**Comment by ansoda** [comment]
Ok,thanks!

**Comment by Eugeny** [comment]
Duplicate of #3059
