### ISSUE TITLE
Zmodem download file problem

### ISSUE THREAD

**Issue by Lurking9527** [Eugeny/tabby#5845]
**Describe the problem**:
[A clear and concise description of what the bug is.]
Zmodem downloaded gz compressed file, but failed to extract it.

**To Reproduce**:
[Steps to reproduce the behavior]
1、gzip file (file.gz>100MB);
2、sz file.gz
3、Use 7z to extract the file
Error:  CRC check failed!
Unzipped files are not available.

**Comment by weiyijie-git** [comment]
I have the same problem,Zmodem downloaded success,but the file  is different from the original file.

**Comment by Lurking9527** [comment]
I use version 1.0.189 , The problem still exists ,
Use 7z to extract the file.gz , Display data error
@Eugeny

**Comment by hereTac** [comment]
The same here 1.0.200 , it still there. @Eugeny
