### ISSUE TITLE
Serial connection - Backspace not working

### ISSUE THREAD

**Issue by archtur** [Eugeny/tabby#5853]
## Steps to reproduce

1. Configure the serial port like in the pictures. Most relevant is IMHO the input mode `Normal`, because this is how I want to handle my shell that is on the connected device.

    - ![Serial settings 1](https://user-images.githubusercontent.com/10476509/156126398-864c7ff0-ba8f-49c2-9da8-f6b631e1f3eb.png)
    - ![Serial settings 2](https://user-images.githubusercontent.com/10476509/156126413-4b811222-cdae-4eb5-929d-96628a4f8c0f.png)

3. Write text
4. Press the `backspace` key.

The `backspace` key press does not delete the last written character, as expected.
I think `backspace` key (and possibly other relevant keys) are not send by tabby to the device. With other terminal emulators, this is working (e.g. `teraterm`). So the connected shell on the device can handle this.

**Comment by tmalaher** [comment]
Perhaps related to #5862

**Comment by Eugeny** [comment]
Tracking in #5862

**Comment by n3tax** [comment]
Had the same issue, here are a few steps that helped me to fix it: 
1. Press **Settings**
2. **Profiles & connections**
3. **ADVANCED**
4. In the "Default profile settings" menu, click on **Serial**
5. In the pop-up window, click on **INPUT**
6. In the "Backspace key mode", choose **Ctrl-H**
7. Save
