### ISSUE TITLE
How can I send a command to all active tables?

### ISSUE THREAD

**Issue by Syehunter** [Eugeny/tabby#5863]
Windows@1.0.173

I've seen the answer in issue#5822 but it doesn't work.

Is "ctrl-shift-i(pane-focus-all)  -> ls(command) ->  press[enter]"  in the right order?

**Comment by Eugeny** [comment]
Yes, but just to clarify: it focuses all _panes_, not _tabs_. For multiple tabs, in the latest release, you can merge them together first (merge-tabs hotkey), then focus-all-panes, and later split them into separate tabs again with the explode-tab hotkey.

**Comment by Eugeny** [comment]
Duplicate of #5193
