### ISSUE TITLE
Can't input with Sougou Pinyin

### ISSUE THREAD

**Issue by geekheitian** [Eugeny/tabby#5888]
Version: 1.0.173
Platform: Windows x64 10.0.22000
Plugins: theme-gruvbox
Frontend: xterm

Can not input with SougouPinyin ime，But it does works with  microsoft Pinyin or others input ime.
搜狗输入法无法录入，手心输入法和微软拼音均可。

**Comment by timnick-snow** [comment]
same problem~

**Comment by Eugeny** [comment]
Duplicate of #4999
