### ISSUE TITLE
Feature Request: Edit remote file with local editor like VS Code

### ISSUE THREAD

**Issue by FantaZZ** [Eugeny/tabby#5889]
Edit remote file with local editor like VS Code.

And update remote file when save in local editor.

**Comment by FantaZZ** [comment]
Like Xftp, It can download remote file that we want wdit in local disk as cache.
We can edit the file, and when file change, it will automatic upload and cover origin file.

**Comment by FantaZZ** [comment]
I found it ...

**Comment by iambudi** [comment]
When edit file locally it seems Tabby open with mac default app. Can we just use VSCode as default for anykind of text file?
