### ISSUE TITLE
last profile being opened for same host

### ISSUE THREAD

**Issue by nexional** [Eugeny/tabby#5900]
**Describe the problem**:
If there are two profile entries for the same user@host say profileA & profileB. They only different between them is LOGIN_SCRIPT part. If I open profileA and then in a new tab open profileB then profileA opens again & not profileB. This issue is there since version 1.0.171+. Still noticing it in latest version 1.0.173. I checked & version 1.0.170 seems to work fine in this regard.

**To Reproduce**:
Create two profiles profileA & profileB for the same user@host but with different LOGIN_SCRIPT part
Open profileA
Subsequently open profileB in new tab.
Ideally profileB should open in second tab but profileA is being reopened.

**Comment by Eugeny** [comment]
You're likely running into a connection being reused. You can disable this in the profile settings -> advanced -> connection multiplexing.
