### ISSUE TITLE
lost all data

### ISSUE THREAD

**Issue by NiuBlibing** [Eugeny/tabby#5904]
Version: 1.0.173
Platform: Windows x64 10.0.22000
Plugins: none
Frontend: xterm

When add some ssh profiles,all my data in the config is lost.Is there a solution?

**Comment by lolomin** [comment]
Hi, got the same exact thing with tabby v1.0.173 and my own hosted tabby-web and gw ... lost all profiles/connexions suddenly :(
don't even known how to reproduce

**Comment by NiuBlibing** [comment]
My profile was encrypted by vault, and gone when adding some ssh connections

**Comment by reimnm** [comment]
1.0.176 vault encrypted, all perfiles gone but still can access via tab->Recent

**Comment by Eugeny** [comment]
Duplicate of #5355
