### ISSUE TITLE
Whether all query results can be highlighted

### ISSUE THREAD

**Issue by mymach** [Eugeny/tabby#5940]
![image](https://user-images.githubusercontent.com/24400068/158503614-6a4437d5-8d71-4341-a0b4-0ba1826e9f1f.png)

As shown in the preceding figure, only one selected result can be displayed.

Is it possible to highlight all search results like xshell?

Here's the xshell display：

![image](https://user-images.githubusercontent.com/24400068/158716536-7b88173d-da38-4683-9483-3a038965edcc.png)

**Comment by konstantin83** [comment]
Hi, have you find the way to manage it?
Also is there a way to make search result more highlighted?
