### ISSUE TITLE
A little problem with the tab bar

### ISSUE THREAD

**Issue by xiaoxinda** [Eugeny/tabby#5946]
![image](https://user-images.githubusercontent.com/17923218/158546150-60e8ccb0-6e9b-42ed-929f-8582d479ba3b.png)

**Comment by xiaoxinda** [comment]
The first tab is blocked

**Comment by Eugeny** [comment]
Have you changed any window settings that caused this? Could you please post the config file?

**Comment by xiaoxinda** [comment]
version: 3
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  duplicate-tab: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  scroll-to-bottom: []
  settings-tab: {}
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
terminal:
  searchOptions: {}
  colorScheme:
    name: Zenburn
    foreground: '#dcdccc'
    background: '#3f3f3f'
    cursor: '#73635a'
    colors:
      - '#4d4d4d'
      - '#705050'
      - '#60b48a'
      - '#f0dfaf'
      - '#506070'
      - '#dc8cc3'
      - '#8cd0d3'
      - '#dcdccc'
      - '#709080'
      - '#dca3a3'
      - '#c3bf9f'
      - '#e0cf9f'
      - '#94bff3'
      - '#ec93d3'
      - '#93e0e3'
      - '#ffffff'
  profile: local:binzsh
  customColorSchemes: []
  fontSize: 15
  cursor: beam
  background: colorScheme
ssh:
  knownHosts:
    - host: 1.1.1.1
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 123213123123=
configSync:
  parts: {}
appearance:
  frame: native
profileDefaults:
  ssh:
    type: ssh
    options:
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      host: ''
      auth: password
      port: null
      privateKeys: []
      forwardedPorts: []
      scripts:
        - expect: ''
          send: ''
  local:
    type: local
    options:
      env: {}
pluginBlacklist: []
enableWelcomeTab: false
profiles:[]
clickableLinks: {}
hacks: {}
language: zh-CN

**Comment by Eugeny** [comment]
You need to restart Tabby after changing the `Window Frame` setting (as the UI suggests)
