### ISSUE TITLE
Sogou can't input Chinese again...

### ISSUE THREAD

**Issue by yzh1255245824** [Eugeny/tabby#5954]
```
Version: 1.0.173
Platform: Windows x64 10.0.22000 (win11)
Plugins: title-control, theme-hype
Frontend: xterm
```

As the title says, I can not input Chinese by Sougou again...The Sougou's version is `stable 11.8.0.5496`, you can [download](https://pinyin.sogou.com/) it at here.

Praise your work, and I look forward to your reply. Thank you!

**Comment by Eugeny** [comment]
Sogou input has been fixed in the nightly build - thanks!
