### ISSUE TITLE
hot key for deleting the entire line

### ISSUE THREAD

**Issue by yzliao-zip** [Eugeny/tabby#5959]
**Is your feature request related to a problem? Please describe.**
Currently, no hot key supports deleting the entire line. The existing hot keys only support deleting an entire word.

**Describe the solution you'd like**
A hot key (e.g., cmd + backspace) to remove the entire line of command

**Describe alternatives you've considered**
enable sending hex code to terminal and allow user to self-defined hot keys and hex code mapping

**Additional context**
none

**Comment by hntee** [comment]
+1, really need to send hex code on shortcuts
