### ISSUE TITLE
Tauri

### ISSUE THREAD

**Issue by boonkerz** [Eugeny/tabby#5964]
Any plan to migrate to tauri project?

https://tauri.studio
https://medium.com/geekculture/the-end-of-electron-is-near-310467d6415

**Comment by Eugeny** [comment]
There's very little reason to. The only upside is smaller binary size, while the downside is rewriting half of Electron's functionality in Rust and an inconsistent JS environment between OSes.

**Comment by feluelle** [comment]
>  The only upside is smaller binary size, [...]

I don't think that is entirely true. The startup time would probably be quite faster as well. Currently, having to wait a few seconds is a big disadvantage for using tabby in my opinion.
