### ISSUE TITLE
Bash profile

### ISSUE THREAD

**Issue by chris-daly** [Eugeny/tabby#5973]
Version: 1.0.173
Platform: Linux x64 5.4.0-104-generic
Plugins: none
Frontend: xterm

When using tabby, the default bash profile won't detect my .bashrc file. I have to manually source it, for it to work.

**Comment by mirelsol** [comment]
In the command line field of your profile remove the -l option
`/bin/bash -l` => `/bin/bash`

**Comment by Eugeny** [comment]
It's also a good idea to source .bashrc from .bash_profile: https://linuxize.com/post/bashrc-vs-bash-profile/#difference-between-bashrc-and-bash_profile
