### ISSUE TITLE
Translation request PT_BR

### ISSUE THREAD

**Issue by wellesximenes** [Eugeny/tabby#5986]
Greetings

I have completed the portuguese brazil translation, how should I proceed so that it can be implemented in the next release.

Thank you

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment]
Thanks! Will add them in a moment. How do I correctly name it in the language list - _Português do Brasil_?
