### ISSUE TITLE
Repeatedly enter the safe box password

### ISSUE THREAD

**Issue by xu98** [Eugeny/tabby#5992]
Version: 1.0.174
Platform: macOS x64 21.4.0
Plugins: workspace-manager, sync-config, quick-cmds
Frontend: xterm

You need to re-enter the  password every time you restart the app, so it doesn't make sense to store it for 7 days.
![image](https://user-images.githubusercontent.com/24386577/159617691-1864d707-46da-4124-ba9d-258fa0b68fda.png)

**Comment by Eugeny** [comment]
Correct - the "saving" only saves to RAM. If it would save the password to disk, there would be no reason to have Vault at all as all the information needed to decrypt it would be stored in the same place.
