### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by unic0rn9k** [Eugeny/tabby#5999]
On wayland compositors the reselution defaults to 1080p on hidpi displays.

**Comment by Eugeny** [comment]
Please elaborate

**Comment by unic0rn9k** [comment]
Wayland is a linux display protocol. Tabby does not support wayland, and thus only works using xwayland (a compatibility layer for running x apps on wayland).
This comes with some drawbacks, mainly bad performance and the reselution issue I mentioned.

**Comment by Eugeny** [comment]
Thanks. Can you check whether running Tabby with these flags works? https://wiki.archlinux.org/title/wayland#Electron

**Comment by unic0rn9k** [comment]
Doesn't seam to make a difference. 
Changing the frontend between xterm and xterm WebGL doesn't do anything either.

**Comment by proletarius101** [comment]
However, `GDK_BACKEND` is automatically set to `x11` if Tabby is open with `x11` and to `wayland` if Tabby is open with `wayland`. Consequently, in the former situation, Tabby can't open applications with x11 backend, whereas in the later situation, it can't open applications with wayland backend.

**Comment by unic0rn9k** [comment]
Running with the arguments sepcified above doesn't work and neither does setting the `GDK_BACKEND` variable to `wayland`.

**Comment by proletarius101** [comment]
> Running with the arguments sepcified above doesn't work and neither does setting the `GDK_BACKEND` variable to `wayland`.
> 
> Also tabby outputs some weird errors when i run it (although it does run, to be clear):
> 
> ```
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [5974:0410/220625.313651:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
> chown: changing ownership of '/opt/Tabby/chrome-sandbox': Operation not permitted
> chmod: cannot access '/opt/Tabby/chrome-sandox': No such file or directory
> ```

added a `--no-sandbox` parameter

**Comment by unic0rn9k** [comment]
Oh, sorry. That works.
