### ISSUE TITLE
Add a function to download and upload folders

### ISSUE THREAD

**Issue by alfred-hong** [Eugeny/tabby#6002]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alfred-hong** [comment]
Now there is only the function of uploading and downloading files. I want to add a function of uploading and downloading folders.I hope the author will consider it.

**Comment by Eugeny** [comment]
Duplicate of #4946
