### ISSUE TITLE
Built-In Profile Options

### ISSUE THREAD

**Issue by CandiceJoy** [Eugeny/tabby#6008]
Found one, but was a FAR more extensive request than what I have in mind.

**Is your feature request related to a problem? Please describe.**
When I want to use a built-in profile, it's very difficult to find the one I want in my huge list of profiles.

**Describe the solution you'd like**
I'd like to be able to rename and categorise built-in profiles.  I don't need any other fancy features like changing options or anything, just rename and categorise.  If you're feeling REALLY fancy, a color/icon option would be nifty, but not at all needed.

**Describe alternatives you've considered**
Only other alternative might be to be able to hide unused built-in profiles, but I think that's a much more extensive change than I really want or need.

**Additional context**
In the end, I'd just like to be able to find commonly used built-in profiles in the list of all my profiles more quickly, that's really all.  I'm perfectly happy with anything that facilitates that.

**Comment by Eugeny** [comment]
There's currently a workaround for this in form of hiding the built-in profiles by default: 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/161476/159869781-23fbbcd3-5db9-44ab-8d18-316ae7a419b2.png">

and then cloning and customizing the ones you want to keep.

The builtin profiles will then be excluded from the selector dialog and won't be searched against.

**Comment by hwdef** [comment]
> There's currently a workaround for this in form of hiding the built-in profiles by default: <img alt="image" width="444" src="https://user-images.githubusercontent.com/161476/159869781-23fbbcd3-5db9-44ab-8d18-316ae7a419b2.png">
> 
> and then cloning and customizing the ones you want to keep.
> 
> The builtin profiles will then be excluded from the selector dialog and won't be searched against.

Where is this option? I can't find it.

**Comment by Eugeny** [comment]
Settings -> Profiles -> Advanced

**Comment by Eugeny** [comment]
You need to have at least one custom profile before this option becomes available.

**Comment by hwdef** [comment]
> You need to have at least one custom profile before this option becomes available.

Thank you! It works.

**Comment by NJT145** [comment]
Are there any way to hide custom profiles? Not delete but only hide from menu?
And are there any way to hide built-in profiles on "Default profile" selection menu?
I believe that the better way to handle this issue is to add ability to hide profiles and restore default built-in profiles, and/or automatically copy built-in profiles as custom in order to edit them only without changing default values (which is much more error-safe).

**Comment by NJT145** [comment]
I created an issue for this, at #7727, which is more than a built-in profile issue.

**Comment by NJT145** [comment]
My issuue at #7727 closed but the problem still exist. Having the option to add custom profiles is not enough. We need to have a way to hide some of our custom profiles when we don't need them at some times. As a result, a HIDDEN parameter is requeired for custom profiles.

**Comment by Eugeny** [comment]
Fixed in #7727
