### ISSUE TITLE
Add Tabby To Right Click Menu In Windows

### ISSUE THREAD

**Issue by Mrahmani71** [Eugeny/tabby#6011]
Hello,
I'm really happy with Tabby but one feature is missing in my opinion. Tabby is not in the context menu of Windows and I would like you to add it.

To do this, you can create a key in the registry named "Tabby" in this path:

`HKEY_CLASSES_ROOT\Directory\Background\shell\`

Double click on "Default" and add "&Tabby" below the value data

You can add a new value named "Icon", and give it the following value

`%USERPROFILE%\AppData\Local\Programs\Tabby\Tabby.exe`

Add a new key under the "Tabby" folder. Rename it to "command"

Double-click on "Default" and add next value

`"C:\Users\mohammad\AppData\Local\Programs\Tabby\Tabby.exe" "%V"`

![1](https://user-images.githubusercontent.com/13013819/160019517-6efe7fec-98ce-4857-9b32-2554d9a4c5ef.png)
![2](https://user-images.githubusercontent.com/13013819/160019525-b1c9751f-4d77-437a-b3ac-4e381090095e.png)
![3](https://user-images.githubusercontent.com/13013819/160019840-00017bc7-5de0-443c-af82-e52a1ff6307e.jpg)

**Comment by Eugeny** [comment]
It's actually built-in - Settings -> Application -> Shell integration

**Comment by Mrahmani71** [comment]
thanks i didn't see it
