### ISSUE TITLE
[Feature Request] Sixel graphics in the terminal

### ISSUE THREAD

**Issue by BlueFalconHD** [Eugeny/tabby#6032]
**Is your feature request related to a problem? Please describe.**

I hate having to use graphical applications, and love any terminal utilities that try to replicate that. But they are limited. I want to be able to view images in the terminal, but every terminal emulator I find doesn't support sixel.

**Describe the solution you'd like**
I would love to see sixel graphics come to tabby.
**Describe alternatives you've considered**
Maybe a custom terminal image format, or  iTerm2's image format.

**Additional context**

**Comment by bdmorin** [comment]
Yep, this is a show stopper for me. I rely on imgcat, viu, and others in my workflow.
