### ISSUE TITLE
Port forwarding, remote address listening address cannot be changed.

### ISSUE THREAD

**Issue by YueLWish** [Eugeny/tabby#6036]
Version: 1.0.174
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm

Port forwarding, remote forwarding to the local, the remote end is always 127.0.0.1 and cannot be changed.

However, I set the address in the settings, and it is always 127.0.0.1 through ss -nltp | grep xx.

**Comment by Eugeny** [comment]
You need to enable the `GatewayPorts` option or equivalent on your SSH server.
