### ISSUE TITLE
SSH profile with same host do always use the first profile's scripts

### ISSUE THREAD

**Issue by mullerch** [Eugeny/tabby#6064]
**Describe the problem**:

When I create a new profile B connecting to a host for which another profile A already exists, that B profile will execute the A profile's scripts instead of its own.

**To Reproduce**:

- Create a SSH profile named 'A' to a remote server (use username, hostname and SSH keys) with a login script [$, echo Hello]
- Create another SSH profile named 'B' to the same server, with same configuration, and set login script [$, echo World]
- Open profile B

Expected : it shows `World` after login
Actual : it shows `Hello` after login

Note: script in GUI always look correct

**Comment by Eugeny** [comment]
Thanks for the report. A workaround is to disable "session reuse" in the advanced settings of both profiles.

**Comment by win0909** [comment]
> Thanks for the report. A workaround is to disable "session reuse" in the advanced settings of both profiles.

Thanks, this works!

**Comment by cypherbits** [comment]
Affected by this too.

**Comment by whyuds** [comment]
> Thanks for the report. A workaround is to disable "session reuse" in the advanced settings of both profiles.

Will this problem be fixed?

**Comment by Eugeny** [comment]
It's fixed in 1.0.175
