### ISSUE TITLE
New setting to customize new tab "+" button behaviour

### ISSUE THREAD

**Issue by Eclipsow** [Eugeny/tabby#6077]
_**Is your feature request related to a problem? Please describe.**_
This feature request is not related to any problem and is a small enhancement / QOL suggestion.

_**Describe the solution you'd like**_
I would like to configure a specific profile (or even maybe a custom layout) to be used when clicking on the "+" button in the tab bar.
I use Tabby mostly to interact with my WSL Ubuntu, but everytime I click on the new tab "+" button, it opens a default CMD terminal. I have to manually select the Profile each time. It would be very nice to have a Selectbox somewhere in the settings to customize what Profile/Layout this button will open (something along the lines of "Default terminal profile" for example).

_**Describe alternatives you've considered**_
Other alternatives would include creating a plugin to do this, I guess... But even that I'm not sure there is any way to alter this button behaviour from a plugin.

PS: Thank you for your amazing work on this tool btw. Tabby is by far my favorite for that kind of thing on Windows. The broadcasting option specifically is really useful, yet not very common for Windows terminal emulators.

**Comment by Eugeny** [comment]
You can select the default profile in Settings - Connections and Profiles

**Comment by Eclipsow** [comment]
Well. I must be blind, I completely missed that one... 
Thank you for the quick answer and sorry to make you loose your time. I still have another feature request (and I hope I didn't miss anything for this this time lol) but will make it in another thread to keep everything clean. 

Closing this one, thanks again.

**Comment by jwoodard80** [comment]
Would it be possible to make the new tab button prompt for the connection?? Actually just like the "profiles and connections" . Even if given the option to remove "new terminal" would be ok. 

I find myself constantly clicking on the "new terminal" hoping to select a SSH connection and then waste 4-5 clicks trying to clean it back up. I realize I'm probably the only person to ask this so I appreciate any consideration. :-)

**Comment by ahrooran-r** [comment]
> Would it be possible to make the new tab button prompt for the connection?? Actually just like the "profiles and connections" . Even if given the option to remove "new terminal" would be ok.
> 
> I find myself constantly clicking on the "new terminal" hoping to select a SSH connection and then waste 4-5 clicks trying to clean it back up. I realize I'm probably the only person to ask this so I appreciate any consideration. :-)

Is this feature available now?
