### ISSUE TITLE
MSYS2 environment $HOME is incorrectly pointed to /c/Users/<UserID>

### ISSUE THREAD

**Issue by lbmeng** [Eugeny/tabby#6079]
**Describe the problem**:
[A clear and concise description of what the bug is.]
MSYS2 environment $HOME is incorrectly pointed to /c/Users/\<UserID\>, but it should be pointed to /home/\<UserID\>

The native MSYS2 shell, as well as Windows terminal, maps $HOME correctly to /home/\<UserID\>.

Tried the latest tabby, the issue still exists.

**To Reproduce**:
[Steps to reproduce the behavior]

Install MSYS2 (https://www.msys2.org), and use tabby to open one of the MSYS2 supported configuration, for example, MSYS2 (MINGW64)

**Comment by Eugeny** [comment]
Don't you have to [set up the MSYS2 starting directory manually](https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/doc/user-docs/ThirdPartyToolProfiles.md#msys2) in Windows Terminal?

**Comment by lbmeng** [comment]
Ah, thanks for the quick update!

It looks like I did follow the [MSYS2 official guide](https://www.msys2.org/docs/terminals/#windows-terminal) to set up my Windows Terminal.

It seems there is no corresponding setting in tabby to configure MSYS2?

**Comment by lbmeng** [comment]
Reopening this, as this issue is partially fixed in 1.0.175

1.0.175 seems to only fix the starting directory so that it points to **/home/<UserID>**, but the $HOME environment variable still points to **/c/Users/<UserID>**

**Comment by lbmeng** [comment]
Oops, it looks like I don't have the privilege to reopen this issue. I will file a new issue then.
