### ISSUE TITLE
Should restore focus to active tab when cancelling ssh dialog

### ISSUE THREAD

**Issue by princemaple** [Eugeny/tabby#608]
clicking on the backdrop of the ssh dialog closes it, but the focus is not restored to the active tab.

Version: 1.0.68
Platform: win32 10.0.17763
Plugins: clickable-links, scrollbar

**Comment by martinzca** [comment]
When switching tabs the focus is also lost. You have to mouse click into the tab itself so you can start typing.

**Comment by princemaple** [comment]
seems to have been fixed
