### ISSUE TITLE
The Windows portable x86_64 nightly build does not start

### ISSUE THREAD

**Issue by lbmeng** [Eugeny/tabby#6081]
**Describe the problem**:
[A clear and concise description of what the bug is.]
I wanted to try the Windows portable x86_64 nightly build but it does not start. The main window never pops up.

I have to revert my version back to alpha 174.

https://nightly.link/Eugeny/tabby/workflows/build/master/Windows%20portable%20build%20%28x86_64%29

**To Reproduce**:
[Steps to reproduce the behavior]
Download https://nightly.link/Eugeny/tabby/workflows/build/master/Windows%20portable%20build%20%28x86_64%29
Extract it to a directory, create a data sub-directory inside it, and lauch tabby.

**Comment by zyitingftnt** [comment]
me too

**Comment by Eugeny** [comment]
Fixed! The new build will be ready soon: https://github.com/Eugeny/tabby/commit/95ae4b84a60f998ff0a764169d43ffc577e38e3e

**Comment by zyitingftnt** [comment]
@Eugeny is it released?

**Comment by Eugeny** [comment]
It is now.
