### ISSUE TITLE
Edited themes don't work

### ISSUE THREAD

**Issue by Buzzraider** [Eugeny/tabby#6090]
**Describe the problem**:
When I click on a theme: Settings->Color scheme, im greeted with bunch of themes, I can use one, then edit the color for it for example CU (Cursor Color) Then I pick color that I like, the color stays, I click save lets say agronauts22...aaaaand. default color  for CU is back. Am I doing something wrong here?

**To Reproduce**:
try to change any color for any theme (color scheme) save it and witness that nothing will actually change

changing CU color to orange:
![Screenshot 2022-04-04 at 20 39 21](https://user-images.githubusercontent.com/69143224/161614321-81148988-e084-4ac4-bfc8-4f793cdd037a.png)

saving and this is what I have after the change
![Screenshot 2022-04-04 at 20 39 49](https://user-images.githubusercontent.com/69143224/161614379-c67d08ca-9890-4620-8c4d-eb9de54226ba.png)

Editing the agronauts22 agin, no changes saved.
![Screenshot 2022-04-04 at 21 08 11](https://user-images.githubusercontent.com/69143224/161614841-3301e00b-c95b-4538-86d8-3b2a77686de8.png)

This is the cursor after picking up agronauts22 with saved CU color to orange. 🤷‍♂️
![Screenshot 2022-04-04 at 21 10 41](https://user-images.githubusercontent.com/69143224/161615141-398821e3-6ae4-402c-965d-67686651c9c6.png)

Tabby 1.0.174 on MacOS 12.3.1

**Comment by retsimx** [comment]
+1

**Comment by retsimx** [comment]
There is a temporary workaround that works for me. If you find the original colour in the theme editor, and have your new colour handy (you can also use the them editor for this), you can then find the original colour in the theme config inside `Settings -> Config File`. Replace it with your new colour and save and apply.

It's a roundabout workaround, but it does work.

**Comment by pfworks** [comment]
Once this is fixed, I'll probably start using tabby.

**Comment by sureshparimi** [comment]
+1
