### ISSUE TITLE
Is there any font weight option?

### ISSUE THREAD

**Issue by Sheey11** [Eugeny/tabby#6099]
I am using a composite font named `CascadiaCode Nerd Font` ([source here](https://github.com/ryanoasis/nerd-fonts)), and I didn't see any font weight option, or any font variant in font list.  
Here's a screenshot for that, which looks terrible
![image](https://user-images.githubusercontent.com/13375959/161753459-17393482-66ab-40d3-ad62-5cfcf1ed6a89.png)

---

I tried adding
```css
{ font-weight: 500; }
```
to custom css, but it makes no difference.

**Comment by retsimx** [comment]
+1
