### ISSUE TITLE
How To Bind Key To Send Escape Sequence

### ISSUE THREAD

**Issue by crh19970307** [Eugeny/tabby#6123]
Hi, I find that key binding can only be configed to do specific actions. What if I want to bind some keys to send escape sequence? Is there any way? Thanks!

**Comment by Eugeny** [comment]
There's a 3rd party plugin called `quick-cmds` that does this.

**Comment by crh19970307** [comment]
But I find that this plugin cannot bind specific key to the send escape sequence?
