### ISSUE TITLE
Animations on closing dynamic-sized tabs could be improved

### ISSUE THREAD

**Issue by simon-budin** [Eugeny/tabby#6147]
I am using the "Workspace manager" plugin which is awesome but sometimes I need to quickly clean up some random tabs and it is a bit tedious to close tabs quickly using mouse-wheel click because of :
- animations during tabs closings which you cannot disable, apparently
- those animations being started from the width of the "Fixed" tabs setting, making it hard to anticipate where the next tabs will be in a split second. 

I know there are options to close "other tabs" or "tabs to the right" but I generally find it less quick than clicking on them with the mouse-wheel. Moreover, I may want to close only some tabs in the middle for example. 

Please look at the video to understand this "clunky" behavior, preventing the whole operation to be performed reliably : 

https://user-images.githubusercontent.com/50825026/163034984-d698c711-5984-49e9-93d7-58b0e317765c.mp4

Suggestions : 
- animations should be configurable or simply disableable 
- tabs animations start width should be based on actual tab width, not fixed width
- css rules for animations timings should be easily accessible - I tried to inspect the tabs using the devtools and change the transition / animation timings, in vain.

**Comment by Eugeny** [comment]
Fixed the width jump and added an option to disable animations globally. I can't make the animation definitions accessible through CSS unfortunately as they're done via `@angular/animations` and are baked into the code.

**Comment by simon-budin** [comment]
Great thanks a lot for reactivity !
