### ISSUE TITLE
Command palette as in modern editors

### ISSUE THREAD

**Issue by mrjackphil** [Eugeny/tabby#6164]
**Description**
There are a lot of options and commands in tabby. I assume there will be only more. The only way to trigger most of them is a shortcut. So you should remember very big amount of shortcuts.

**Solution**
This would be cool to have a command palette as in Windows Terminal, VsCode, Sublime Text and Idea. This will allow to easily access commands. Even cooler if it will show current shortcut for a command. 

**Additional context**
There are a quick commands plugin which allows you to quickly use profile for your current terminal. I might would try to come with solution which will use this plugin as a base. But if there is something like that in progress/roadmap please let me know.

**Comment by Lockszmith-GH** [comment]
I came here to suggest this feature exactly, for the same exact reasons.

Just to add:
`F1` and `Ctrl-Shift-P` seem to be the common default shortcut keys for command palette - these also seem to be consistent across platforms.

**Comment by saif-abualkhair** [comment]
a command palette would actually a big improvement to tabby, I've been using it for month still don't know the shortcut to split terminals.

**Comment by Lockszmith-GH** [comment]
Absolutely fabulous. Thank you so much for this. [Ctrl]+[Shift]+[P] is my new favorite shortcut.

Now to start bugging you to add commands to that list 🤭 (just kidding)
I'm going to get familiar with the feature first, I'll bug you in a couple of weeks 😉 with suggestions.

**Comment by Eugeny** [comment]
Thanks! Currently the command list is just composed of all context menu items and toolbar buttons - but happy to add more. Eventually it should move in the direction of vscode where commands and hotkeys are unified among other things

**Comment by mrjackphil** [comment]
Instant upgrade! Thank you, very much!
