### ISSUE TITLE
Auto updating v1.0.174 -> v1.0.175 downloads wrong arch on Win10 x64.

### ISSUE THREAD

**Issue by designgears** [Eugeny/tabby#6196]
**Describe the problem**:
When clicking update in the GUI after a new version was discovered, the wrong arch was downloaded.

**To Reproduce**:
Install `tabby-1.0.174-setup.exe`
Check for updates
Goto `C:\Users\%username%\AppData\Local\tabby-updater\pending`
In the directory you'll find `tabby-1.0.175-setup-arm64.exe`
Proceeding with the install simply left me with `Uninstall Tabby.exe` under `C:\Users\%username%\AppData\Local\Programs\Tabby`

**Comment by cjerrington** [comment]
I too saw this. I was also able to download the right x64 bit version and everything was restored as well.

**Comment by joshuajeschek** [comment]
This happened to me too, on Win11. I went through with the update and now I don't have tabby installed at all

**Comment by Eugeny** [comment]
The latest release now uses Keygen and separate update channels per arch, so this won't come up again with the next update.
