### ISSUE TITLE
cannot search keywords with 1.0.175

### ISSUE THREAD

**Issue by junyicc** [Eugeny/tabby#6197]
Version: 1.0.175
Platform: macOS arm64 20.6.0
Plugins: none
Frontend: xterm

how to reproduce:
1. cmd + f to open search input box.
2. input some keywords that are already shown on terminal.
3. cannot hit the keywords.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/10704251/163908936-9aa2c783-f9ac-4d26-a30f-3cc590ade350.png">

**Comment by lijiachang** [comment]
me too.  cannot hit the keywords.

macos 12.3.1
tabby 1.0.175

**Comment by junyicc** [comment]
I try to reinstall tabby as follows:
1. uninstall tabby
2. download the 1.0.175 pkg and install it

However, I cannot open tabby again. It is jumping up and down on the dock, and then exits.

**Comment by aisatis** [comment]
also cannot hit the keywords.
Win10 and tabby 1.0.175.
when i revert to 1.0.174,it works.
