### ISSUE TITLE
Automatic link identification

### ISSUE THREAD

**Issue by halhu** [Eugeny/tabby#6214]
Hi, 
The product is very well done and appreciated, and there is a bit of advice I hope to adopt

The IP address and other text will be automatically recognized as a link, when i want to copy, it is easy to open the link by mistake, affects copying of some text. My current version is 1.0.174

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The feature of identify ip addresses, etc. as links can be turned off or on by allowing the user to choose in the settings

**Describe alternatives you've considered**
Auto identify addresses starting with http:// or https:// as links, do not automatically recognize ip as a link

**Additional context**

**Comment by Eugeny** [comment]
In the settings, you can set the links to only be clickable while holding a modifier key - this will prevent accidental clicking.

**Comment by halhu** [comment]
Oh...it can be set in the terminal, sorry for not noticing :-)
