### ISSUE TITLE
clickable links won't work with modifier ctrlKey

### ISSUE THREAD

**Issue by najib-houcine** [Eugeny/tabby#6221]
**Describe the problem**:
[A clear and concise description of what the bug is.]

**To Reproduce**:
[Steps to reproduce the behavior]
Change config.yaml clickableLinks {} section to the below
```yml
clickableLinks:
  modifier:  ctrlKey
```

Save and Apply 

Click Ctrl Key with any link the drop-down menu appear instead of link opening

**Comment by Eugeny** [comment]
Are you on macOS? Ctrl-Click is hardwired to right mouse button there.

**Comment by najib-houcine** [comment]
Yep , I see damn Apple , I will close this issue 

There another issue #6222 , plus there is no documentation on clickable links (had to dig in code )

**Comment by Eugeny** [comment]
Were you looking for some specific documentation? Clickable-links only has one config option, and it's exposed under Settings -> Terminal.

**Comment by najib-houcine** [comment]
Missed that sorry , Thanks anyway .

**Comment by 0xinit** [comment]
Im using linux, and went to Settings -> Terminal and changed "require a key to click links" to `ctrl`. Still couldnt click on the localhost links built by npm or yarn. any sugestions? @Eugeny
