### ISSUE TITLE
Will prevent the SSH greeting from showing up  does not work

### ISSUE THREAD

**Issue by bzw1204** [Eugeny/tabby#6227]
**Describe the problem**:
Will prevent the SSH greeting from showing up  does not work
![image](https://user-images.githubusercontent.com/9693637/164370822-3ff6e4bd-9805-4fa8-94b3-34f70b0c2eb6.png)
![image](https://user-images.githubusercontent.com/9693637/164370894-6d7dbea8-379a-4f4e-b748-e31d157d7265.png)

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Eugeny** [comment]
This options disables the SSH banner (as set by the e.g. `Banner` option in OpenSSH) - it can't prevent your remote .bash_profile from printing stuff.

**Comment by bzw1204** [comment]
> This options disables the SSH banner (as set by the e.g. option in OpenSSH) - it can't prevent your remote .bash_profile from printing stuff.`Banner`

![image](https://user-images.githubusercontent.com/9693637/164616090-0e7944d9-dd92-4017-9b5f-3447c2d48995.png)
Isn't this information from the tool?

**Comment by Eugeny** [comment]
Yes - this is Tabby's own connection log - I thought you meant the big "OpenWRT" banner

**Comment by bzw1204** [comment]
> Yes - this is Tabby's own connection log - I thought you meant the big "OpenWRT" banner

So, Is it supported to turn off the log?

**Comment by Eugeny** [comment]
No, the log can't be turned off.
