### ISSUE TITLE
Title display error

### ISSUE THREAD

**Issue by b0123456789** [Eugeny/tabby#6230]
![1](https://user-images.githubusercontent.com/21169660/164388375-387a95b7-51d2-416d-abaa-76df4c376ec4.png)
![2](https://user-images.githubusercontent.com/21169660/164388446-f0cd1037-1987-449f-9f5a-d034e71fbdfe.png)
![3](https://user-images.githubusercontent.com/21169660/164388458-05f99fbb-257d-4d92-8cd4-da12f21c3ad6.png)

"腾讯云" display correct.
"root@JadedEmotional-VM"   display error, should be "翻墙VPN"

**Comment by Eugeny** [comment]
You're seeing the dynamic title reported by the shell - you can disable it with this option: 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/161476/164394146-721e3f14-ca14-4b8c-a5a9-12e04279c8db.png">
