### ISSUE TITLE
Ctrl-/ doesn't work in Tabby.

### ISSUE THREAD

**Issue by mtbar131** [Eugeny/tabby#6235]
**Describe the problem**:
I am running emacs inside a Tabby tab and emacs uses `Ctrl-/` for undo. But It seems like Tabby doesn't forward (?) this key press over to emacs. If I run the same emacs inside Windows Terminal or a powershell terminal `Ctrl-/` starts working again. 

**To Reproduce**:
1. Get emacs for windows (or install emacs in WSL).
2. Start Tabby and run emacs in terminal mode with `emacs -nw` (or emacs can be started inside wsl tab with `emacs -nw`).
3. Make some changes in the emacs buffer.
4. Try to undo with `Ctrl-/` nothing happens.

Try the same steps above with a powershell windows and it works.

**Comment by sukiida** [comment]
Disturbed by this problem too.

**Comment by Saladestroyer** [comment]
![ObserveIcon](https://github.com/Eugeny/tabby/assets/103356679/4de5341f-c870-467b-97d7-a46f5b916024)
