### ISSUE TITLE
Tabby, Windows, cmd, vim, alt key not working

### ISSUE THREAD

**Issue by tex** [Eugeny/tabby#6249]
ALT key is ignored in vim / neovim under cmd.exe on Windows 10. When Alt is pressed, mouse pointer changes to cross instead of passing the ALT press to vim / neovim. It behaves like CTRL is pressed.

It prevents me from using ALT mappings in vim / neovim.

**Comment by pseudocc** [comment]
same.

**Comment by super-bunny** [comment]
There is a setting to disable this behavior, it's called "Use Alt as the Meta key" in the Terminal page of settings.
Source: https://github.com/Eugeny/tabby/issues/356
