### ISSUE TITLE
I am update the version from 1.0.174 to 1.0.176,the sftp can not automaticly enter user's current directory

### ISSUE THREAD

**Issue by gy-super** [Eugeny/tabby#6260]
**Describe the problem**:
[A clear and concise description of what the bug is.]
I am update the version from 1.0.174 to 1.0.176,the sftp can not automaticly enter user's current directory
**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by g-xu** [comment]
same issue， follow https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting， try with 1.0.176， not work

**Comment by WAY29** [comment]
I'm having the same problem
