### ISSUE TITLE
Sometimes ssh does not work.

### ISSUE THREAD

**Issue by PrajjwalS** [Eugeny/tabby#6263]
SSH   X  Remote rejected opening a shell channel: Error: (SSH) Channel open failure: open failed

Each time I open tabby and connect to a ssh session via. a ssh profile, it connects perfectly  up to  2 connections after that each time I open new SSH session it gives the above error.

Please help fix this.

**Comment by PrajjwalS** [comment]
I disabled "Reuse session for multiple tabs" and it works well now.
Please close this issue if this is supposed to be the default behavior.

**Comment by aran112000** [comment]
We just encountered the same issue and the above suggestion has resolved it for us too.

Running Tabby 1.0.173

**Comment by jgsun** [comment]
> I disabled "Reuse session for multiple tabs" and it works well now. Please close this issue if this is supposed to be the default behavior.

Great，thanks!

**Comment by shelmingsong** [comment]
> I disabled "Reuse session for multiple tabs" and it works well now. Please close this issue if this is supposed to be the default behavior.

I met the same issue and solved it after following your comment settings, thank you!

Tabby 1.0.179

**Comment by 675506026** [comment]
I met the same issue but I can`t fint  "Reuse session for multiple tabs" ,can you tell me where is it? Thank you
