### ISSUE TITLE
Inconsistent color

### ISSUE THREAD

**Issue by heiha7789** [Eugeny/tabby#6271]
Version: 1.0.175
Platform: Windows x64 10.0.22598
Plugins: workspace-manager, title-control, theme-windows10, theme-hype, theme-gruvbox, sync-config, search-in-browser, save-output, relaxed-theme, quick-restart, quick-cmds, plugin-fig-integration, fit-screen, fig, elastic-quick-commands, elastic-quick-cmds, docker, cloud-settings-sync, clippy, altair
Frontend: xterm

tabby，After the update, the colors of the upper and lower modules are inconsistent, which looks uncomfortable

![image](https://user-images.githubusercontent.com/57821098/165018988-9081810e-0ec2-4e7b-8e7f-9e3943e9277d.png)

**Comment by Eugeny** [comment]
The different color for the bottom bar is a deliberate design choice.
