### ISSUE TITLE
sftp opened according to the terminal's directory

### ISSUE THREAD

**Issue by linlih** [Eugeny/tabby#6324]
**Is your feature request related to a problem? Please describe.**
when using sftp, I need to mannual choosing the directlthat I want to download or update, but most time the terminal directory is the place I want to download or upload something. 

**Describe the solution you'd like**
for example, when terminal directory is : /var/log ，when open the sftp windows, it will directly go to the /var/log, not / directory

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment]
See https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting
