### ISSUE TITLE
Latest version following shell directory does not take effect

### ISSUE THREAD

**Issue by zxiaozhou** [Eugeny/tabby#6339]
**Describe the solution you'd like**
1. Latest version following shell directory does not take effect
2. I have followed the tutorial Settings
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/62740686/166403396-484d4ee9-f920-4268-b63d-14e4547346d6.png">

**Comment by Eugeny** [comment]
Duplicate of #6260
