### ISSUE TITLE
Can not back from hide window

### ISSUE THREAD

**Issue by wznmickey** [Eugeny/tabby#6346]
Version: 1.0.176
Platform: Linux x64 5.15.32-1-MANJARO
Plugins: theme-windows10, save-output, docker
Frontend: xterm

In Window->Docking, choose any option other than Off, and choose Hide window on focus loss. After losing the focus, it will hide the window but have no operation of let window back.

**Comment by UyCode** [comment]
same issue occurs on windows, I think this is an infinite loop

**Comment by Eugeny** [comment]
You can re-show the window either by launching the app again or using the "toggle window" hotkey.
