### ISSUE TITLE
Font Ligatures not working with "Comic Code Ligatures" in Garuda Linux

### ISSUE THREAD

**Issue by Noxdor** [Eugeny/tabby#6351]
**Describe the problem**:
I just installed tabby. I changed the font to "Comic Code Ligatures", a coding font with Ligatures. I enabled Ligatures in the settings. On the right in the example window it shows me the working ligature arrow, but it doesn't work inside the actual terminal. Is this a bug or am I doing something wrong?

**To Reproduce**:
1. Fresh install of tabby on Garuda (Arch) Linux with the pacman download
2. Install "Comic Code Ligatures" or possibly also any other Ligature font
3. Choose it in tabby and enable ligatures
4. See the behaviour I describe above

**Comment by HealsCodes** [comment]
I can reproduce this on tabby 1.0.223 / macOS 15.5 was there ever a solution for Arch Linux or is it a problem with the font in tabby?
