### ISSUE TITLE
Adding linux arm to CI workflows

### ISSUE THREAD

**Issue by Jai-JAP** [Eugeny/tabby#6355]
@Eugeny I have successfully got armv7l and arm64 compiled and working [here](https://github.com/jai-jap/tabby-arm-builds). What do you think about adding docker based build for arm linux builds as it is slow and takes ~ 1.5 - 2 hours to build.

**Comment by Jai-JAP** [comment]
I'll make a pr with changes required it you agree to add this.

**Comment by Jai-JAP** [comment]
Also the linux arm64 / armv7l must be uploaded to the packagecloud.io repo but idk how

**Comment by Eugeny** [comment]
Please do! I'll enable those builds for releases only to save time.

**Comment by Jai-JAP** [comment]
> Please do! I'll enable those builds for releases only to save time.

Also  we have to remove patch for builder-util package and update it on a new release of builder-util as I have made an PR upstream adding arm as an alias for armv7l which is now merged. See https://github.com/electron-userland/electron-builder/pull/6845

**Comment by Jai-JAP** [comment]
@Eugeny do you have an idea how to upload new arm builds to packagecloud repo

**Comment by Jai-JAP** [comment]
Also i tried making changes but it gives some errors and fails. See patch-1 branch in my fork

**Comment by Eugeny** [comment]
@Jai-JAP I suspect that `bsdtar` might be missing in the ARM image - `electron-build` needs it. Re packagecloud I'll check it once the build is working, should be straightforward.

**Comment by Jai-JAP** [comment]
I do install libarchive-tools on arm images 
https://github.com/Jai-JAP/tabby/blob/8f79b043eedc613720f5b662e9114ddf73b7fbb6/.github/workflows/build.yml#L187
https://github.com/Jai-JAP/tabby/blob/8f79b043eedc613720f5b662e9114ddf73b7fbb6/.github/workflows/build.yml#L164

**Comment by Jai-JAP** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v23.0.9
My fix for Unsupported arch arm is now merged amd released time to update electron-builder , builder-utiland app-builder-lib.
Also to remove the patch file for builder-util

**Comment by Eugeny** [comment]
Fantastic! Let me know when it's clear for merge :)

**Comment by Jai-JAP** [comment]
its ready but still needs testing the build artifacts
(Most probably will  be working as minimum changes made to build process)

i cant test as my pi is broken

**Comment by Jai-JAP** [comment]
also i was also reported by some users that they are getting errors 
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```
on the arm build artifacts after the commit that moved ./scripts/build-native.js to postinstall

however manually including scripts/build-native.js to workflow fixed the issue

**Comment by Jai-JAP** [comment]
@Eugeny

**Comment by Eugeny** [comment]
Yes, the PR looks good to me, but I'll need a confirmation that the builds work on real hardware before merging & releasing.

I was referring to the error in https://github.com/Eugeny/tabby/issues/6355#issuecomment-1157535794 - is it happening in the builds from your PR?

**Comment by Jai-JAP** [comment]
i dont know whether the issue is present in the builds from the PR as i haven't tested them

**Comment by Jai-JAP** [comment]
testing needed

**Comment by nerohmot** [comment]
@Jai-JAP I have an aarch64 machine available, if you tell me what to do I will test for you ;-)

**Comment by Jai-JAP** [comment]
@nerohmot can you try the linux arm64 artifact [here](https://github.com/Eugeny/tabby/suites/6942341761/artifacts/270619725)

**Comment by Jai-JAP** [comment]
Also test the armv7l build from the same workflow run [here](https://github.com/Eugeny/tabby/suites/6942341761/artifacts/270619726) if possible.
