### ISSUE TITLE
My color scheme doesn't work

### ISSUE THREAD

**Issue by R-juzi** [Eugeny/tabby#6358]
Version: 1.0.176
Platform: macOS arm64 21.4.0
Plugins: none
Frontend: xterm
 remote window:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/59160257/167074249-93c4876f-42e2-40fe-a81d-3b447c21adcf.png">
 local window
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/59160257/167074346-fc1c28d7-2dd3-4d0a-92f7-2c2a62dd47de.png">

When I open the local and remote shell Windows, the color scheme doesn't work, just grey and white. Strangely enough, it works again when I switch the remote window user to root, and it also works again when I switch back to normal user. This does not work for the local shell. I did not find any relevant configuration and documentation on the official website and GitHub. Is this a bug?

**Comment by Eugeny** [comment]
https://github.com/Eugeny/tabby/discussions/5258

**Comment by R-juzi** [comment]
I followed the instructions and turned on the default Settings on the MAC, and now it works, but that doesn't solve the problem I had on the remote Ubuntu system (when I first connected to the terminal, the color match didn't show, but when I switched the user, it did)?
