### ISSUE TITLE
SFTP directory can't change automatically

### ISSUE THREAD

**Issue by DachunKai** [Eugeny/tabby#6360]
I have tried the wiki https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting. I add the command to my profile, but it doesn't work.

**Comment by Eugeny** [comment]
Have you added it to your _remote_ profile?

**Comment by DachunKai** [comment]
![image](https://user-images.githubusercontent.com/66354783/167245426-4bda74c1-a3ed-4be6-8ab9-53716cffe335.png)

Of course, I have addded it, and i use zsh shell.

**Comment by DachunKai** [comment]
> Have you added it to your _remote_ profile?

![image](https://user-images.githubusercontent.com/66354783/167245455-00f91887-88c9-495c-a815-84b40751bcb7.png)

Of course, I have added it, and i use zsh shell.
