### ISSUE TITLE
Hide Recent Connections in New-Connection-Selection-Hover

### ISSUE THREAD

**Issue by pthoelken** [Eugeny/tabby#6362]
Maybe a way to configure and disable / enable "showing recent connections" in the new-connection-selector which comes over when I click on the plus-sign? 

For configuration I think it's a good idea to configure - if it's enabled - how many recent connection are displayed.

**Comment by Eugeny** [comment]
You can configure this (or disable recents altogether) in Settings - Profiles - Advanced.
