### ISSUE TITLE
Explode tab not working as expected

### ISSUE THREAD

**Issue by kkellysci** [Eugeny/tabby#6365]
**Describe the problem**:
When using the "explode tab" keyboard shortcut, panes in the current tab remain panes, and a new tab is opened with the default session. This differs from the expected behavior (each pane becoming its own tab).

**To Reproduce**:
1. Start two ssh tabs
2. Drag one tab into the other to make it a pane
3. Press the keys for the "explode tab" keyboard shortcut

**Comment by Eugeny** [comment]
Could you please double-check that the same hotkey isn't assigned to "new tab"? :)

**Comment by kkellysci** [comment]
Ah-ha!! That was it -- unassigned the hotkey for new tab and it works fine now. Thank you!
