### ISSUE TITLE
Make installed plugins searchable

### ISSUE THREAD

**Issue by MagicLike** [Eugeny/tabby#6367]
**Is your feature request related to a problem? Please describe.**
When I search my installed plugins I sometimes can't find them right away and have to look closer. (For example when something isn't working properly)

**Describe the solution you'd like**
It would be a very nice feature to make the installed plugins - like the available plugins, searchable.

**Comment by Qiming-Liu** [comment]
For PR https://github.com/Eugeny/tabby/pull/6713

![image](https://user-images.githubusercontent.com/68600416/177045061-23e8727a-3223-46e9-947f-f6944701c8c1.png)

Any advice or better solution feel free to let me know

**Comment by MagicLike** [comment]
@Qiming-Liu Thanks for your PR! 😊
