### ISSUE TITLE
replace the default name of tabs to config name

### ISSUE THREAD

**Issue by shadow-yuan** [Eugeny/tabby#6374]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a lot of windows open because all tabs all have very similar names, just like root@node62 or root@localhost. These names confuse me.

**Describe the solution you'd like**
I would like to be able to replace its name with the name of the configuration. Because when I configure an ssh connection, i will  configure a special name and a group name, this special name means something to me.

![image](https://user-images.githubusercontent.com/25924234/167539791-984a59cb-21f5-4666-b515-c12094233d06.png)

**Comment by Eugeny** [comment]
Tick this checkbox in your profile's settings: 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/161476/167539940-ee36a010-7c8f-4968-ba54-6940197b4f23.png">
