### ISSUE TITLE
tabby becomes lighter when taking screenshots

### ISSUE THREAD

**Issue by dylandee** [Eugeny/tabby#6397]
When I take a screenshot, tabby terminal  becomes much lighter than usual

![image](https://user-images.githubusercontent.com/13831247/168198957-a809bdbc-74e4-4fd1-b80d-8d03b19610bc.png)

can i fix this with any setting options?

**Comment by Eugeny** [comment]
`Cmd-Shift` is the default "rearrange tabs" shortcut, which you can change in Settings -> Hotkeys.
