### ISSUE TITLE
何时supports simultaneous operation of multiple machines, what I mean is that after connecting multiple machines, the machines can be operated at the same time. is a synchronous operation

### ISSUE THREAD

**Issue by zheng2010** [Eugeny/tabby#6412]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment]
You're looking for the "focus all panes / broadcast" hotkey in Settings -> Hotkey.

**Comment by zheng2010** [comment]
建议集成到右键菜单里面

**Comment by zheng2010** [comment]
谢谢
