### ISSUE TITLE
Always show connecting status

### ISSUE THREAD

**Issue by yg2008432** [Eugeny/tabby#6449]
Version: 1.0.177-nightly.0
Platform: macOS arm64 21.5.0
Plugins: none
Frontend: xterm

When the serial port is opened for the first time, the connection status is normal. When the serial port is opened again, the connection status is always displayed
<img width="798" alt="image" src="https://user-images.githubusercontent.com/17795353/168937957-188dead2-bcc9-4b86-af76-00ce79a07fea.png">

**Comment by Eugeny** [comment]
Could you please elaborate?

**Comment by x1systems** [comment]
I'm seeing what might be the same issue. Whenever I connect to a serial port, in this case, /dev/ttyUSB0, I see "Connecting" flashing the entire time even though the port is open and displaying data. I think that might also be causing some display issues with the serial data itself.

v1.0.177 on Ubuntu 22.04 LTS. This was working perfectly until the update to this version. I think I was a couple versions behind prior to this update. Same behavior on multiple computers.

![image](https://user-images.githubusercontent.com/95955913/169211957-46514e2d-cd22-4b99-80ba-bd7ec9ea312b.png)

**Comment by x1systems** [comment]
I rolled back to v1.0.176 and it no longer displays 'Connecting' and serial data is displayed properly.
