### ISSUE TITLE
Copy the ip of the current host

### ISSUE THREAD

**Issue by DreamPWJ** [Eugeny/tabby#6467]
![image](https://user-images.githubusercontent.com/16730031/169442081-342d74ba-aee0-42f1-9bbc-a71080e1d6eb.png)
We often need to get the ip of this machine, but this just shows that it cannot be copied for other places

**Comment by Shivam-jainn** [comment]
Hey , i want to contribute to this project but since this is my first time , can i please get guidance on this?

**Comment by Eugeny** [comment]
Hey @Shivam-jainn this is a great idea for a plugin - check out https://github.com/Eugeny/tabby/blob/master/HACKING.md and https://docs.tabby.sh/classes/TabContextMenuItemProvider.html

**Comment by NightBrownie** [comment]
@Eugeny will pick this up
