### ISSUE TITLE
Tabby not recognizing IdentityAgent in .ssh/config

### ISSUE THREAD

**Issue by Xosten** [Eugeny/tabby#6480]
**Describe the bug**
I use 1Password as IdentityAgent as it stores all my SSH keys. I did all the necessary steps in their [documentation](https://developer.1password.com/docs/ssh/get-started#step-3-turn-on-the-1password-ssh-agent) to enable the IdentityAgent. When using the macOS terminal, it loads the key information and prompts me with TouchID before establishing the SSH connection. 

But when I try to connect with Tabby, it throws me the following error. From my guessing, it's not picking the IdentityAgent information from my `.ssh/config`.

```
 SSH  Connecting to REDACTED
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-REDACTED= 
 X  All configured authentication methods failed
 SSH   X  Remote rejected opening a shell channel: Error: Not connected
```

Profil configuration
![image](https://user-images.githubusercontent.com/11696836/169707214-cc5fd292-7369-464d-bb0e-218f2a9035ac.png)

.ssh/config
```
Host *
  IdentityAgent "~/Library/Group Containers/XXXXXXXXXX.com.1password/t/agent.sock"
```

**To Reproduce**
Steps to reproduce the behavior :
1. Have your SSH key information stored in 1Password
2. Configure 1Password to be your IdentityAgent
3. Add a connection profile in Tabby
4. Select Agent in the connection profile
5. Initiate the SSH connection

**Expected behavior**
 It should load the key information from 1Password and prompts me with TouchID before establishing the SSH connection.

**Environment**
Installed version: 1.0.117
macOS: 12.3.1
1Password version: 8.7.0

If you need any additional information, please let me know.
Thanks in advance for helping!

**Comment by nljackson2020** [comment]
I know this is closed but did you ever find a solution?

**Comment by alekslyse** [comment]
I would also know if you found a solution?

**Comment by Skyfay** [comment]
Any news?

**Comment by rh363** [comment]
> This helped for me thanks: [#5939 (comment)](https://github.com/Eugeny/tabby/discussions/5939#discussioncomment-2980766)

hi guys i'm sorry i didn't found a way to make it work with a custom ssh-agent socket, can you give me more infos about it?

i already try to configure .ssh with a specific IdentityAgent
i already try to export SSH_AUTH_SOCK: `export SSH_AUTH_SOCK=my-agent-path.sock; tabby`

i'm stuck...

**Comment by ArtemYurov** [comment]
https://github.com/ArtemYurov/tabby-ssh-auth-socket#readme

<blockquote><img src="https://opengraph.githubassets.com/1d284a3562532d8583576abfd04cf7c4b0728b804356c963c8b986832ce97334/ArtemYurov/tabby-ssh-auth-socket" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/ArtemYurov/tabby-ssh-auth-socket">GitHub - ArtemYurov/tabby-ssh-auth-socket</a></strong></div><div>Contribute to ArtemYurov/tabby-ssh-auth-socket development by creating an account on GitHub.</div></blockquote>
