### ISSUE TITLE
How set tab name via shell start

### ISSUE THREAD

**Issue by emikg777** [Eugeny/tabby#6481]
Hi, I trying integrate Tabby with GNS3. GNS3 just send command to shell to start telnet session with virtual router in specific terminal. I  find how establish telnet session with some IP from shell. Something like:
`/opt/Tabby/tabby run telnet %hostname% %port%`

But how I can give name to the tab which create after execute this command? I can't find any information about that.

**Comment by Eugeny** [comment]
Tabs opened with `tabby run` will show the dynamic title, which the program can set using a special escape sequence: https://superuser.com/a/1527233/311689
