### ISSUE TITLE
Telnet can not work. Always in Connecting status...

### ISSUE THREAD

**Issue by charlesginger** [Eugeny/tabby#6489]
![Screenshot from 2022-05-23 10-57-25](https://user-images.githubusercontent.com/3732714/169879268-5669334a-799a-429b-a6d8-1952e252f3b3.png)
![Screenshot from 2022-05-23 10-57-03](https://user-images.githubusercontent.com/3732714/169879274-d3138f26-4246-4cd7-a2c9-dc46aa8913de.png)

**Describe the problem**:
establish telnet connection, it does not work.

**To Reproduce**:
[Steps to reproduce the behavior]
establish telnet connection, it does not work. If from local termal, then telnet works. OS is Ubuntu 22.04

**Comment by nanedi** [comment]
I have same problem.
