### ISSUE TITLE
After the screen command is executed, the scroll bar disappears, so you can't scroll up and down through the scroll wheel.

### ISSUE THREAD

**Issue by Jonnyan404** [Eugeny/tabby#6520]
Version: 1.0.179
Platform: Windows x64 10.0.22000
Plugins: fit-screen, elastic-quick-commands
Frontend: xterm

**Comment by Jonnyan404** [comment]
After executing the screen command, the progress bar will disappear.

**Comment by Eugeny** [comment]
Yes, GNU screen runs on the alternate buffer, which has no scrollbars by design.

**Comment by Jonnyan404** [comment]
> 是的，GNU 屏幕在备用缓冲区上运行，该缓冲区在设计上没有滚动条。

That is to say, this is a normal phenomenon, not a bug. Can it be further optimized?
If not, you can close this issue!
Thanks for the answer!

**Comment by Eugeny** [comment]
No, this is just how Screen behaves. You can scroll within a Screen pane by pressing Ctrl-A, then Esc and then arrow keys.

**Comment by Jonnyan404** [comment]
> 不，这就是 Screen 的行为方式。您可以通过按 Ctrl-A、Esc 和箭头键在屏幕窗格中滚动。

Ok, got it
