### ISSUE TITLE
Specify path for port forwarding

### ISSUE THREAD

**Issue by pierre-leonard** [Eugeny/tabby#6523]
In Putty, it's possible to specify a path behind the port when configuring a tunnel. So for instance you can tell that localhost:33306 should be forwarded to xxx:3306/yyy

Would it be possible to have the same in Tabby?

**Comment by pierre-leonard** [comment]
Hi,

I meant here, at the end of destination

![image](https://user-images.githubusercontent.com/2114903/181756405-10488d07-b042-4f30-a325-c4c4ddacd030.png)

**Comment by Eugeny** [comment]
I might be missing something, but I've tried it, and the path part is simply ignored: 
![image](https://user-images.githubusercontent.com/161476/181783698-7d1d962f-2e4b-4cb3-b95a-3f4905bcb470.png)

Also, the SSH protocol doesn't include any provisions for "paths" or HTTP for what it's worth, port forwarding always happens from one ip:port to another ip:port.

**Comment by pierre-leonard** [comment]
Hi,

you're correct, I did the test in putty and indeed I can remove the path part. I assumed this was the issue because one of my port forwards was working with it in putty and I couldn't get it to work on tabby but it looks like I misconfigured something somewhere else. Thanks for taking time to check this out.

**Comment by Eugeny** [comment]
No problem and glad you've sorted it out
