### ISSUE TITLE
Love-shell plugin not in plugins available list

### ISSUE THREAD

**Issue by jiaxiangl** [Eugeny/tabby#6535]
**Describe the problem**:

I wrote a plugin recently called [love-shell and publish it to npm](https://www.npmjs.com/package/love-shell) . However I am not able to see this plugin available in tabby (screenshot shows below).
<img width="1666" alt="Screen Shot 2022-06-01 at 2 16 08 PM" src="https://user-images.githubusercontent.com/22890806/171484376-1b3a15bd-40f2-48ae-a79d-5910e3dfeb3e.png">

I already have `tabby-plugin` keyword added in package.json. Could you help me figure out why it is not in available list?
<img width="1574" alt="Screen Shot 2022-06-01 at 2 24 00 PM" src="https://user-images.githubusercontent.com/22890806/171485627-ae5250ee-a041-4da5-81f5-4cacae537170.png">

**To Reproduce**:
1. download tabby latest version 
2. go to settings => plugins
3. search `love-shell`

**Comment by alphahot1** [comment]
> **Describe the problem**:
> 
> I wrote a plugin recently called [love-shell]

Hi, I couldn't understand how is it supposed to work...

**Comment by jiaxiangl** [comment]
> > **Describe the problem**:
> > I wrote a plugin recently called [love-shell]
> 
> Hi, I couldn't understand how is it supposed to work...

you don't understand the love-shell plugin or you don't understand how to write plugin in general?  @alphahot1 ?

**Comment by alphahot1** [comment]
I made some step forward: I noticed the api key field in the prefernces, and I binded the love-shell popup on a key. However I still don't understand how is it supposed to be used...
If I try the demo on the openia website it shows better results.
I'm using this model: text-davinci-002

<img width="576" alt="Schermata 2022-07-11 alle 15 40 34" src="https://user-images.githubusercontent.com/984906/178277618-1d360b9b-d63c-491e-a175-d801d98d5d37.png">
.

**Comment by Eastegg** [comment]
> > > **Describe the problem**:
> > > I wrote a plugin recently called [love-shell]
> > 
> > 
> > Hi, I couldn't understand how is it supposed to work...
> 
> you don't understand the love-shell plugin or you don't understand how to write plugin in general? @alphahot1 ?

I don't understand the love-shell plugin too, do you have instructions or somethings?
