### ISSUE TITLE
[Question] Startup parameters

### ISSUE THREAD

**Issue by lpaulusLohr** [Eugeny/tabby#6540]
Hi,

Would like to know if it is possible to start Tabby with parameters like WinSCP ?

i. e
```cmd
winscp.exe sftp://{login}:{password}@{hostname}
```

Thanks guys

**Comment by Eugeny** [comment]
Yes:

```
tabby [command] [arguments]

Commands:
  Tabby open [directory]       open a shell in a directory
  Tabby run [command...]       run a command in the terminal       [aliases: /k]
  Tabby profile [profileName]  open a tab with specified profile
  Tabby paste [text]           paste stdin into the active tab
  Tabby recent [index]         open a tab with a recent profile

Options:
      --version  Show version number                                   [boolean]
  -d, --debug    Show DevTools on start                                [boolean]
      --hidden   Start minimized                                       [boolean]
      --help     Show help                                             [boolean]

```

**Comment by bumbummen99** [comment]
@Eugeny This does not seem to work on Linux. Is that intended?

**Comment by Eugeny** [comment]
Which distro are you on and which package did you use? Some maintainers make /usr/bin/tabby a wrapper script that swallows arguments.

**Comment by bumbummen99** [comment]
> Which distro are you on and which package did you use? Some maintainers make /usr/bin/tabby a wrapper script that swallows arguments.

Fresh ubuntu 22.04 installed with https://packagecloud.io/eugeny/tabby/install#bash-deb

**Comment by rootvip** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lpaulusLohr** [comment]
> Yes:
> 
> ```
> tabby [command] [arguments]
> 
> Commands:
>   Tabby open [directory]       open a shell in a directory
>   Tabby run [command...]       run a command in the terminal       [aliases: /k]
>   Tabby profile [profileName]  open a tab with specified profile
>   Tabby paste [text]           paste stdin into the active tab
>   Tabby recent [index]         open a tab with a recent profile
> 
> Options:
>       --version  Show version number                                   [boolean]
>   -d, --debug    Show DevTools on start                                [boolean]
>       --hidden   Start minimized                                       [boolean]
>       --help     Show help                                             [boolean]
> ```


Is this working on Windows ?

**Comment by bumbummen99** [comment]
> > Yes:
> > ```
> > tabby [command] [arguments]
> > 
> > Commands:
> >   Tabby open [directory]       open a shell in a directory
> >   Tabby run [command...]       run a command in the terminal       [aliases: /k]
> >   Tabby profile [profileName]  open a tab with specified profile
> >   Tabby paste [text]           paste stdin into the active tab
> >   Tabby recent [index]         open a tab with a recent profile
> > 
> > Options:
> >       --version  Show version number                                   [boolean]
> >   -d, --debug    Show DevTools on start                                [boolean]
> >       --hidden   Start minimized                                       [boolean]
> >       --help     Show help                                             [boolean]
> > ```
> 
> Is this working on Windows ? @[Eugeny](https://github.com/Eugeny)

Yes, it is the output of `Tabby.exe --help`
