### ISSUE TITLE
bug: File transfer window of sftp disappears unexpectedly.

### ISSUE THREAD

**Issue by Drincann** [Eugeny/tabby#6621]
**Describe the problem**:
[A clear and concise description of what the bug is.]

The file transfer window disappears after reopening the sftp.

**To Reproduce**:
[Steps to reproduce the behavior]

When i am uploading the file, tabby looks like this.The file transfer window is displayed normally.

![image](https://user-images.githubusercontent.com/53897259/174079735-74b01951-e30e-4c96-b14c-9a962a815d6f.png)

When I click outside the sftp , the sftp window will collapse and the file transfer window will also disappear at this time.

Looks like this:
![image](https://user-images.githubusercontent.com/53897259/174079890-4cfa9152-5bf0-4330-b0dc-dec9e0933a79.png)

When I re-click sftp to re-invoke the sftp window, the file transfer window disappears, but the file transfer continued, because I observed that the size of the previously uploaded file gradually increased after repeated opening of sftp.

![image](https://user-images.githubusercontent.com/53897259/174080022-73136c67-ce5a-446a-9a50-8c13ba6340dd.png)

**Comment by Eugeny** [comment]
You can click the Transfers button to show the window again: 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/161476/174760086-ead2e8f1-dff1-4400-a354-88497b3e233a.png">

**Comment by Drincann** [comment]
ty.
