### ISSUE TITLE
Downloading a large file with the SZ command will cause the MD5 value to change

### ISSUE THREAD

**Issue by LWF53** [Eugeny/tabby#6639]
Transferring files (>50M) using the SZ command changes the MD5 value, causing file corruption, but uploading with RZ command is normal, this seriously affects the use.

windows 11 x64 22000.675
tabby version 1.0.181
lrzsz-0.12.20-36

**Comment by Qiming-Liu** [comment]
I have also encountered this issue, and it is recommended to use SFTP to transfer files.

Possible bug solutions:
1. Fix this
or
2. Arlert not allowed to transfer >50M files using SZ

**Comment by ZScai** [comment]
sz -8be  filename   is ok
