### ISSUE TITLE
Add option(s) in tab context menu to kill running process and/or restart the tab

### ISSUE THREAD

**Issue by Totalus** [Eugeny/tabby#6653]
**Is your feature request related to a problem? Please describe.**

I sometimes run a command that I am unable to stop, even with `Ctrl+C` multiple times, it just keeps running. The only way I can stop it is to close the tab.

**Describe the solution you'd like**

I would like to be able to force kill the process running in a tab without having to close my tab and open a new one.

**Describe alternatives you've considered**

Currently I use the _Duplicate_ option to duplicate my tab, which copies most of my context (title, color, path, etc.) to a new tab, and then I close the original tab.

**Additional details**

This could be easily implemented with an additional option in the tab's context menu. We could have one or possibly event both of the following:
- `Restart` : Would restart the tab (similar to duplicating + closing original tab). This would keep most of the context (color, title, path), but would reset the environment variables.
- `Kill process` : Would only force kill the running process. This would keep the context and the environment variables intact.

**Comment by Qiming-Liu** [comment]
For PR https://github.com/Eugeny/tabby/pull/6709

![image](https://user-images.githubusercontent.com/68600416/176991936-1e2178b0-20a9-4d22-b958-f8a22b5f0aef.png)

Any advice or better solution feel free to let me know

**Comment by Totalus** [comment]
Looks good to me 👍

**Comment by Qiming-Liu** [comment]
> Looks good to me 👍

Thanks!
As here https://github.com/Eugeny/tabby/pull/6709#issuecomment-1175339271
This will become a configurable hotkey function.

**Comment by Qiming-Liu** [comment]
This issue can be closed.

**Comment by Remonli** [comment]
Can not find such restart tab in context menu.

env:  1.0.182 x64 portable on Win10 x64 2021 LTSC

<img width="357" alt="1659273375413" src="https://user-images.githubusercontent.com/9067053/182028241-3f4952f6-0aa4-4798-a0a5-4379aeaf0926.png">

**Comment by Totalus** [comment]
This feature was added as a hotkey instead of a context menu item ([reference](https://github.com/Eugeny/tabby/pull/6709#issuecomment-1175771106)). Not sure in which version it is released.

**Comment by Qiming-Liu** [comment]
> This feature was added as a hotkey instead of a context menu item ([reference](https://github.com/Eugeny/tabby/pull/6709#issuecomment-1175771106)). Not sure in which version it is released.

Thank you. That is true. It's in Alpha 182.
![image](https://user-images.githubusercontent.com/68600416/182059020-ad94bba1-fa93-44b8-b009-4521523ed58f.png)

**Comment by Remonli** [comment]
I found this note, thanks.
