### ISSUE TITLE
SSH Profile key and interactive

### ISSUE THREAD

**Issue by qiqizjl** [Eugeny/tabby#6685]
Our current authentication method is key+2FA. 2FA authentication is required after key authentication. After I added SSH to the profile and set the key, it prompted 'X All configured authentication methods failed'. The server log shows that the key authentication is successful, and you need to enter 2FA.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/7540584/175999086-eb2efe12-ac16-4277-ba3c-88e6c9bf7486.png">
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/7540584/175999160-c2608c15-5775-4ba8-a898-37589d31da36.png">

when i set it to auto. And id_rsa is after connecting to publickey. can be connected. Prompt to enter 2FA. After authentication, the input can be completed
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/7540584/175999272-0dce916a-f206-482b-b022-6a02ed2a9fc3.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/7540584/175999324-6fc686d7-2124-47b8-985f-8818ed3df35f.png">
Does the coexistence of key and MFA not currently supported?

**Comment by qiqizjl** [comment]
Must be present in the following cases
1. Configure the `key`, `password` login in the profile
2. The server has MFA enabled, etc. that require `keyboard-interactive` interactive authentication

cause
In ``tabby-ssh/src/session/ssh.ts`` L145-L185, the appropriate AuthMethods will be selected according to the configuration in the profile. But MFA authentication needs to add `keyboard-interactive` AuthMethods.

Temporary solution:
Select `Auto` in Profile. Because ``Auto`` will append all ``AuthMethods`` to ``remainingAuthMethods``

solution:
Add a switch in Profile to support `keyboard-interactive` can coexist with key, password, etc.?

**Comment by Eugeny** [comment]
Using Auto is the correct solution here - why are you considering it a "workaround"? When auto is selected, Tabby tries all authentication methods (same as OpenSSH without explicit configuration), and you can still select specific keys and a password.

**Comment by qiqizjl** [comment]
Thanks .It works fine after using Auto
