### ISSUE TITLE
Failed to retrieve identities from agent

### ISSUE THREAD

**Issue by mmdjiji** [Eugeny/tabby#6690]
**Describe the problem**:
When I try to connect my server which is Ubuntu 20.04 Server:
```bash
SSH  Connecting to 10.0.0.6
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  9Zc13Hbt2L**********P9AhEyY0qL9Q= 
 X  Failed to retrieve identities from agent
```
Then the process is stoped.

But connect to the server with tabby is normal last days, and it's abnormal with this error since today.

**To Reproduce**:
1. A Ubuntu 20.04 Server, with SSH username and password;
2. Use tabby to SSH;
3. One day you cannot login with the error.

**Comment by mmdjiji** [comment]
Solved by upgrading to the latest version, issue closed.

**Comment by L-Block-C** [comment]
I'm having this problem again.

**Comment by MrTalon63** [comment]
I'm also experiencing the same problem on 1.0.204
```
 SSH  Connecting to 104.*.*.*
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  KaSOCTHL3qPxQ***************dreNMKqH58FY= 

 SSH  Connecting to 104.*.*.*
 SSH  Trying saved password
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  KaSOCTHL3qPxQ***************dreNMKqH58FY= 
 X  Failed to retrieve identities from agent
 SSH  Trying saved password
```

```
OpenSSH_8.4p1 Debian-5+deb11u2, OpenSSL 1.1.1w  11 Sep 2023
```

**Comment by icecliffs** [comment]
I also experiencing the same problem on 1.0.204, How can I solve it?

```bash
 SSH  Connecting to 1
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  O= 

 SSH  Connecting to 1
 SSH  尝试已保存的密码
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  O= 
 X  Failed to retrieve identities from agent
 SSH  尝试已保存的密码
```

**Comment by max64mode** [comment]
I have found a way to fix this problem (if signing in with password)
- 1: Go to SSH profile settings
- 2: Set auth type to "Password" instead of "Auto"
This worked for me

**Comment by 75re** [comment]
> I have found a way to fix this problem (if signing in with password)
> 
>     * 1: Go to SSH profile settings
> 
>     * 2: Set auth type to "Password" instead of "Auto"
>       This worked for me

It worked!
