### ISSUE TITLE
直连堡垒机失败：X  All configured authentication methods failed  SSH   X  Remote rejected opening a shell channel: Error: Not connected

### ISSUE THREAD

**Issue by Reallyone** [Eugeny/tabby#6704]
问题：链接堡垒机的时候需要输入其他的因子认证

![image](https://user-images.githubusercontent.com/40932714/176857060-2065e8be-7c37-4272-886d-227731f475a2.png)

![image](https://user-images.githubusercontent.com/40932714/176857406-a1bd399c-1d4c-4c60-a538-7ba846e6b4fc.png)

在xshell中是可以的，我已经确保自己输入的账号和密码一致
![image](https://user-images.githubusercontent.com/40932714/176858163-02f0d2cf-3406-4e8d-8689-3fa9c7d269e1.png)

**Comment by XHxin** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by mineary** [comment]
I have the same problem, too.

**Comment by yananma** [comment]
I have the same problem too.
