### ISSUE TITLE
Dynamic tab title on local/ssh connection

### ISSUE THREAD

**Issue by alphahot1** [Eugeny/tabby#6706]
**Is your feature request related to a problem? Please describe.**
I mostly use ssh from my local prompt to remote hosts. My tabs title doesn't reflect user@host where I'm connected to.

**Describe the solution you'd like**
I would like the tab title to change accordingly to the user@host I'm connected to. The same could apply even if I use an ssh profile, then ssh to another host.

**Describe alternatives you've considered**
I'm aware that I can set the title with shell escape sequence but it's not an option since I can't update my bashrc.

Thanks,  and I love the program!

**Comment by ouyangxudu** [comment]
yes, I'd like the tab title showing the profile name but not user@host

**Comment by Eugeny** [comment]
By default, Tabby shows the window title as reported by the remote shell. You can disable this in the profile settings: 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/161476/177282762-c3dab63a-ea33-4139-9005-1e173ccc4233.png">

**Comment by Eugeny** [comment]
No - you can also disable this through the checkbox as shown, and the title will display the connection name instead.

**Comment by Eugeny** [comment]
If you launch OpenSSH from within your local shell, there's little I can do that wouldn't be pure heuristics on the terminal side. If you insist on using the local openssh client, the best way would be to alias `ssh` to a wrapper that changes the window title before and after handing off the connection to `ssh`.

**Comment by alphahot1** [comment]
Thanks, I've done something similar (through a script called sshrc). I would like to use the ssh profile provided by Tabby, I'm liking it very much, however I have  hundreds of systems and it's not practical to configure a session for each one, also with the openssh client I have tab completion for the hostname.
I've seen other apps doing that, presumably by parsing the command prompt, do think is there any other way around that?

**Comment by Eugeny** [comment]
Are these configured in your `.ssh/config`? In that case, they should automatically show up in the profile list.

**Comment by stevenmunro** [comment]
I'm also wanting the hostname to be displayed in the tab. I have as many as 10 terminals open and I'm struggling to keep tab of them all.

**Comment by Showfom** [comment]
Solved with adding the following on `~/.bashrc`

```
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```
