### ISSUE TITLE
Cursor delay

### ISSUE THREAD

**Issue by TantalusZzz** [Eugeny/tabby#6710]
Version: 1.0.181
Platform: Windows x64 10.0.22000
Plugins: none
Frontend: xterm

Hello, i love tabby because its much pretty than other ssh clients.
But i found a bug these days..
Whenever i open tabby,which makes feel cursor delay when i drag a application window and try to move it to another location.That means, i feel cursor cant follow my hand and even when i stop move mouse,cursor will still move by previous tracks.
Thanks!

**Comment by bes-internal** [comment]
Looks like poor performance on your computer. If so, then try:
Setting - Terminal - Frontend - xterm (webgl)
Setting - Window - Acrylic background - off
If this is not what I wrote about, then record a video of your problem

**Comment by TantalusZzz** [comment]
> 

I close Acrylic background then problemed solved

**Comment by TantalusZzz** [comment]
> Looks like poor performance on your computer. If so, then try: Setting - Terminal - Frontend - xterm (webgl) Setting - Window - Acrylic background - off If this is not what I wrote about, then record a video of your problem

I closed Acrylic background then problem sloved
Thanks a lot!
