### ISSUE TITLE
[Question] How to detect that the current session is local in SessionMiddleware?

### ISSUE THREAD

**Issue by lonnywong** [Eugeny/tabby#6730]
If it is a local session ( e.g., `cmd`, `PowerShell` ), I want to do some special processing. How to detect that?

```js
export class MySessionMiddleware extends SessionMiddleware {
  constructor(
    private config: ConfigService,
    hostWindow: ElectronHostWindow,
    electron: ElectronService,
    terminal: BaseTerminalTabComponent
  ) {
    super();
    // Here, I want to know if the current session is local.
  }
}
```

**Comment by lonnywong** [comment]
## Another question

If I drag some files into the tabby terminal, it shows the absolute paths.

Can I subscribe the dragging files event in `SessionMiddleware`? 

I can process the terminal input, check if it's some absolute paths. But I'm looking for a better solution.
```js
feedFromTerminal(data: Buffer): void {
}
```

**Comment by Eugeny** [comment]
You can't override `PathDropDecorator`, but you could work around it by attaching the dragover/drop event handlers to a more deeply nested element, e.g. the `canvas` inside `.xterm`.

As for the type, you could check the `profile.type` on the current tab: https://docs.tabby.sh/interfaces/Profile.html#type

**Comment by lonnywong** [comment]
Can I get the current `Profile` in `BaseTerminalTabComponent` or `BaseSession` ?

**Comment by Eugeny** [comment]
Yes - the `TerminalTab` class from `tabby-local` is not exported, but it has a `profile` property: https://github.com/Eugeny/tabby/blob/master/tabby-local/src/components/terminalTab.component.ts#L18 

Sessions don't know about profiles however.

**Comment by lonnywong** [comment]
I'm not familiar with rxjs. Can I make my subscribe on `drop$` run first?

**Comment by Eugeny** [comment]
No, but you if you `addEventListener` to a more deeply nested element and call `stopPropagation()` inside, you'll catch the event before `PathDrop` does

**Comment by Eugeny** [comment]
Yep - looks good!

**Comment by lonnywong** [comment]
@Eugeny Thanks for your help.
