### ISSUE TITLE
Use shortcuts to switch diffent tab in one terminal which be splited many tabs

### ISSUE THREAD

**Issue by huawang400** [Eugeny/tabby#6740]
Hello author:
I open a terminal ,as the same time ,in one terminal ,i split many tabs ,Can i  use shortcuts to switch these tabs? 
Thank you very much 

![微信截图_20220707161322](https://user-images.githubusercontent.com/75016485/177726864-ba8015c5-5121-488c-aef7-56f46ced4cc5.png)

**Comment by Eugeny** [comment]
Yes - search for "pane" on the Hotkeys settings page: 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/161476/177734033-e90e0226-762c-411f-a5b0-9069d7839464.png">
