### ISSUE TITLE
The color scheme is not displayed correctly

### ISSUE THREAD

**Issue by mongoliaredmountain** [Eugeny/tabby#6747]
更换配色方案后，终端界面上不能正确的显示，特别是背景不变

**Comment by guodongxiaren** [comment]
设置里面选择：外观 -> 终端背景 -> 选择【取自配色方案】。你的设置可能是【取自主题】

Appearance -> Terminal Background -> Selcect [From color scheme]

**Comment by toxyl** [comment]
I think this is the same issue I have: when using the setting "Appearance -> Terminal background -> From theme" Tabby will use the terminal background color for background _and_ foreground which breaks, for example, the `nano` interface. When using  "Appearance -> Terminal background -> From color scheme" foreground and background colors are used correctly, but I am unable to change the opacity of the terminal. Whatever opacity I choose, it never changes and yes, I did restart Tabby.

**Comment by Anubisxcw** [comment]
nonono，it‘s a bug.just in the preferences windows .just turn off the bright 。then，the terminal backround color will right
