### ISSUE TITLE
Config synced without typing passphrase.

### ISSUE THREAD

**Issue by gaelthas** [Eugeny/tabby#6752]
**Describe the problem**:

Config synced without typing passphrase.

**To Reproduce**:

1. Turn vault lock on.
2. Goto config sync, click upload on any config.
3. Do not input passphrase, but config uploaded.

Is is nessary to type passphrase before upload config? Maybe I can fix it someday.

**Comment by Eugeny** [comment]
No, configs are uploaded in their encrypted state, so a vault unlock isn't necessary

**Comment by gaelthas** [comment]
> No, configs are uploaded in their encrypted state, so a vault unlock isn't necessary

So when upload clicked, passphrase dialog is unexpected?

**Comment by gaelthas** [comment]
Nevermind
