### ISSUE TITLE
profile loss, sync loss because of font change.

### ISSUE THREAD

**Issue by Tlntin** [Eugeny/tabby#6776]
### what happend ?
When I modify the "font" of the "appearance" interface, all configurations are lost.
And when "font" modifying, the font will be automatically filled, so I can't select the desired font.

### what i do ?
I tried to use the "configure synchronization" function to recover files, but it didn't seem to work.
Later, I tried the plugin tool "cloud settings sync" to restore the old configuration. As a result, neither dav nor gists can be restored.

### how to recovery ?
Finally, I found the directory of the configuration file by clicking "configuration file" - "display configuration file".
Thankfully, there are many backups of configuration files in this directory. The naming format is similar to “config.yaml.new.2e5f4b33-c7be-4d10-befb-837e88227550”

I closed tabby and deleted config Yaml, and then copy an old  `config.yaml.newxxx` and rename it to `config.yaml`, and then reopened tabby. The interface seemed to recover for a while. As a result, it cleared again after 10 seconds. I think the plugin "cloud settings sync" is making trouble, so I uninstalled it and repeated the copy and rename operation in the previous step. Thank goodness, my configuration is back.

**Comment by Tlntin** [comment]
> Please report it to the plugin's repo: https://github.com/niceit/tabby-cloud-sync-settings
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/157548c7bb51e75d1b8274f860b6b4301e0439ef4ef392b383e81b1c6bdd7cd2/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f303237373762666130343730313234643137643030323038663034386530396239663161383430646262333236336465323534393061633337636662313236662f6e69636569742f74616262792d636c6f75642d73796e632d73657474696e6773"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - niceit/tabby-cloud-sync-settings: Official Tabby plugin for syncing settings across device platforms. https://github.com/Eugeny/tabby](https://github.com/niceit/tabby-cloud-sync-settings)**Official Tabby plugin for syncing settings across device platforms. https://github.com/Eugeny/tabby - GitHub - niceit/tabby-cloud-sync-settings: Official Tabby plugin for syncing settings across de...

Although plugins have a certain impact on it, the same problem will occur when there is no plugin.

**Comment by nguyen-dhn** [comment]
I've faced the same issue when changing the font size.
