### ISSUE TITLE
auto delete host key

### ISSUE THREAD

**Issue by rsidhaarth** [Eugeny/tabby#6788]
Hi,

Consider we are login in to the server for the 1st time. And it stores the host key.

Now, when we reinstall the server and try to log in, it throws an error because the host key already exists. So we have to remove them manually and then only able to log in again.

Can this be automated by asking whether to replace like it usually asks in FileZilla and other apps?

**Comment by Eugeny** [comment]
In the host key mismatch warning dialog, there's actually a button to force the connection anyway, which will store the new host key.
