### ISSUE TITLE
SSH public key Remote reject to Ubuntu 22.0.4

### ISSUE THREAD

**Issue by loriszigliani** [Eugeny/tabby#6791]
Version: 1.0.181
Platform: Windows x64 10.0.22000
Plugins: sync-config, cloud-settings-sync
Frontend: xterm

Hello
I created an ssh connection profile in the settings tab.
I open the connection and tabby reports this error:
```
SSH  Loading private key: id_rsa
 X  Failed to connect to agent
 SSH   X  Remote rejected opening a shell channel: Error: Not connected``
```
Always from tabby but opening the windows terminal and typing the command ssh user @ host connects perfectly using the public key and the private key

![Screenshot (2)](https://user-images.githubusercontent.com/29120210/179356536-234e7f83-7f12-4965-a5ec-bbb608d152c0.png)
![Screenshot (3)](https://user-images.githubusercontent.com/29120210/179356538-04f4da4f-a1e7-4323-8fc0-a1047f2f9ad3.png)

**Comment by rabauss** [comment]
Use a more modern and secure type of key such as `ed25519` .

If you don't want to replace your RSA key now, a temporary workaround on the target server could be:
```
nano /etc/ssh/sshd_config
...
PubkeyAuthentication yes
PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Comment by alanhg** [comment]
same issue with https://github.com/mscdex/ssh2/issues/989

I think ssh2 module should fix the issue.
