### ISSUE TITLE
SSH: can't connect to OpenSSH 9 / Ubuntu 22

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/tabby#6804]
Tabby currently lacks support for rsa-sha2-256/512 private key auth (through node-ssh2).

OpenSSH 8 has [deprecated](https://www.openssh.com/releasenotes.html) the old ssh-rsa private key auth algorithm in 9.0 since rsa-sha2-256 offers better security with the same key, however Tabby as an SSH client doesn't support it yet.

The error shown in Tabby is All configured authentication methods failed.

As a workaround, you can reenable ssh-rsa auth on the server by adding PubkeyAcceptedAlgorithms +ssh-rsa to your /etc/ssh/sshd_config and reloading the SSH service.

**Comment by orangeSi** [comment]
My first ssh connect is ok, but got this error when duplicate it. Then I close the whole tabby and restart it, all is ok now~

**Comment by mc36** [comment]
the issue is still there... :( i'm running debian sid, that is, the ssh agent is also from ssh9.0p1 right now, and it cannot connect 127.0.0.1:22.. doing ssh localhost connects fine without asking for a thing...

**Comment by cayenne17** [comment]
> the issue is still there... :( i'm running debian sid, that is, the ssh agent is also from ssh9.0p1 right now, and it cannot connect 127.0.0.1:22.. doing ssh localhost connects fine without asking for a thing...

What are the connection conditions?
by password or by key?
what kind of key ?

what is the error message in the SSH server logs at the time of SSH connection in `/var/log/auth.log` ?

**Comment by Eugeny** [comment]
@mc36 are you on v1.0.182?

**Comment by Phil57** [comment]
Had to rollback to 181, could not connect anymore.

ecdsa-sha2-nistp256

Ubuntu 20.04.4 LTS
OpenSSH 8.2p1-4ubuntu0.5

**Comment by mc36** [comment]
> @mc36 are you on v1.0.182?
yesss, the build from 2 days ago...

**Comment by mc36** [comment]
> What are the connection conditions?
> by password or by key?
> what kind of key ?
so i try to use the agent to authenticate with my key... it's an old 2kbits rsa key...
the key, and a lot more, present in ssh-add -L.. moreover, ssh 127.0.0.1 opens fine...

**Comment by Aterfax** [comment]
X-post.

https://github.com/Eugeny/tabby/issues/5023#issuecomment-1230657424

**Comment by tennox** [comment]
Same here
![image](https://user-images.githubusercontent.com/2084639/200173083-09af3673-7bd7-46bc-a0ef-37816c4658a1.png)

**Comment by Aterfax** [comment]
Still having this problem under Ubuntu 22.04 with Tabby 1.0.186 - is this related to issues in the ssh2 package? 

https://github.com/mscdex/ssh2/issues/989
