### ISSUE TITLE
Bug in hotkeys

### ISSUE THREAD

**Issue by frizib** [Eugeny/tabby#6843]
*Describe the problem:*

> I wanted to set up new buttons to move down\up. There are 2 duplicate fields for entering the down key, but no up.

*To Reproduce:*

>1. I go to Hotkeys
>2. I'm trying to find an opportunity to change the UP key
>3. I don't see...
![image](https://user-images.githubusercontent.com/28644006/180974359-408514d3-729e-4d75-83b5-c34363b31fba.png)

**Comment by Eugeny** [comment]
Duplicate of #194
