### ISSUE TITLE
add delimiter for mouse double left click to choose which strings to copy 

### ISSUE THREAD

**Issue by orangeSi** [Eugeny/tabby#6849]
add delimiter for mouse double left click to choose which strings to copy , reference as Xshell as below:
![image](https://user-images.githubusercontent.com/12126846/181221015-47f9471f-d253-42fb-9478-a16928fbb217.png)

**Comment by Eugeny** [comment]
You can find it in Settings -> Terminal: 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/161476/181223125-c1fb91d4-5739-4071-a98d-ac85a694d3cc.png">

**Comment by orangeSi** [comment]
> You can find it in Settings -> Terminal: <img alt="image" width="635" src="https://user-images.githubusercontent.com/161476/181223125-c1fb91d4-5739-4071-a98d-ac85a694d3cc.png">

Thanks! Find it now！
And if is possible to add a  search function like ```<input value="keyword for search" />``` to search the whole Settings content by keyword ? beacause if had that, will search  the keyword ```separator``` then can find it !
