### ISSUE TITLE
Plugins not show the last update

### ISSUE THREAD

**Issue by Paulpatou** [Eugeny/tabby#6854]
Version: 1.0.181
OS: Ubuntu 20.04

**Describe the problem**:
I want to update "Cloud-settings-sync"  but the latest version is not available from the tabby plugin panel.
I tried to uninstall it completely but no change

![image](https://user-images.githubusercontent.com/33478981/181441783-8e04b2f2-3059-4cdb-8597-baba9a47d6f2.png)

The last update is 1.5.0 => https://github.com/niceit/tabby-cloud-sync-settings/releases

**Comment by z0ow** [comment]
I have the same problem : (

**Comment by z0ow** [comment]
After the test, tabby uses npms.io to fetch the plugins' version, but the npms.io returns an older version of trzsz. Is there any way to solve this problem?

**Comment by z0ow** [comment]
I guess it will be better if tabby has an offline plugin install interface

> After the test, tabby uses npms.io to fetch the plugins' version, but the npms.io returns an older version of trzsz. Is there any way to solve this problem?

**Comment by LacazeThomas** [comment]
Yes this bug seems to be present since 2017, I think there is no hope to fix it : https://github.com/npms-io/npms/issues/18

**Comment by LacazeThomas** [comment]
I tried to find a new API to replace npms. But the official registry.npm doesn't support keywords in the full text search. 
See [here](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search)

And libraries.io seems to work with an API Key and doesn't support keywords in full text search

**Comment by LacazeThomas** [comment]
Hi, 

Good news, this issue will be solved in the next release. Feel free to close this problem afterwards.
