### ISSUE TITLE
I can't update and download a folder in tobby's sftp?

### ISSUE THREAD

**Issue by nullscode** [Eugeny/tabby#6879]
![图片](https://user-images.githubusercontent.com/110315835/182006415-a6cd6772-251c-4e4b-895c-2b79257628e4.png)

**Comment by Remonli** [comment]
There are so many issues about this , but looks like there is no answer or any plan on this.

**Comment by Eugeny** [comment]
I would like to remind everyone that I'm working on this project in my free time, and cleanly implementing folder uploads/downloads is a particularly big chunk of work.

**Comment by Remonli** [comment]
@Eugeny Yes, completely understand . You may pin a issue on top to avoid receiving such issues again and again .

**Comment by nullscode** [comment]
ok i see,I'm so sorry for distrubed you
