### ISSUE TITLE
Any plane for "Config sync by Webdav"?

### ISSUE THREAD

**Issue by nullscode** [Eugeny/tabby#6880]
for decentralization
I want safekeeping my config by myself, and i need webdav to do that.
Please help me,thanks!
i'll donate for this!

**Comment by mc36** [comment]
i did similar with nfs... what works here is symlinking ~/bin/tabby/data/config,yaml[.backup] to a central place...
fortunately it even works on readonly to mounts... only one drawback, the keys are still stored locally...

**Comment by Bloopps** [comment]
@nullscode tout Can truc this plugin for webdav => https://github.com/niceit/tabby-cloud-sync-settings

**Comment by nullscode** [comment]
> @nullscode You can try this plugin for webdav => https://github.com/niceit/tabby-cloud-sync-settings

it's work! thanks!
