### ISSUE TITLE
SFTP does not synchronize command line PWD

### ISSUE THREAD

**Issue by chengpeng2015** [Eugeny/tabby#6908]
**Describe the problem**:
What should I do if I want my SFTP directory to follow the directory where pwd is located on the command line? At present, I have to click to the specified directory layer by layer. I think this is very unfriendly!

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Eugeny** [comment]
https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting
