### ISSUE TITLE
sudo not work on last tabby update

### ISSUE THREAD

**Issue by ahmedmoselhi** [Eugeny/tabby#6913]
I'm on tabby 1.0.81.1 on arch linux but i got sudo suddenly not working and shows this:
```
sudo pacman -Sy

sudo: The "no new privileges" flag is set, which prevents sudo from running as root.

sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
```

previous versions of tabby was ok

**Comment by ngmisl** [comment]
what was the fix? got the same issue

**Comment by sokushi-git** [comment]
same error here

sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.

on linux mint, normal terminal works just fine, but not tabby
