### ISSUE TITLE
Settings > Window: options not visible

### ISSUE THREAD

**Issue by nexional** [Eugeny/tabby#6914]
Don't see any toggle for options like "Show Profile icon on tab". It's there & I see cursor changing if I hover just that it's not visible.
See attached ss.
![image](https://user-images.githubusercontent.com/19317423/182674574-b1339d97-2604-4032-ba63-b7bc35883b20.png)

**Comment by Eugeny** [comment]
You seem to be using a custom theme that make toggle switches invisible
