### ISSUE TITLE
Upgrading Tabby is actually uninstalling Tabby on Windows 10

### ISSUE THREAD

**Issue by limuyuan** [Eugeny/tabby#6915]
**Describe the problem**:
[A clear and concise description of what the bug is.]
After upgrading Tabby, the Tabby was gone, there's only an Uninstall Tabby.exe under C:\Program Files\Tabby
**To Reproduce**:
[Steps to reproduce the behavior]
Windows 10
Open Tabby, click on the present icon on the upper-right, and proceed upgrade.

**Comment by limuyuan** [comment]
Same issue as #6203

**Comment by limuyuan** [comment]
{"fileName":"tabby-1.0.183-setup-arm64.exe","sha512":"KtxTIq+WMf7oIZ4cLpqOrsi7xQNCol+WVPaQYudzAmfOxpToxBbs5jBVgP856tNPLeNQTVgRLC19ODx75qFK+A==","isAdminRightsRequired":false}

**Comment by uaustudio** [comment]
Happened the same to me upon updating to Alpha 183 today.

**Comment by uaustudio** [comment]
I figured out what's going on. 
I found the file tabby-1.0.183-setup-arm64.exe in the folder %USERPROFILE%\AppData\Local\tabby-updater\pending
This means that clicking on Update from the settings the programs downloads the ARM version instead of x64 version, then fails the installation.

**Comment by Eugeny** [comment]
FIxed in the latest release
