### ISSUE TITLE
IS there any way to set the line endings on the serial terminal?

### ISSUE THREAD

**Issue by stickben** [Eugeny/tabby#6928]
My serial output only has '\n' line endings.  It doesnt look right.  Is there any way to set the line endings?

Version: 1.0.183
Platform: macOS x64 21.4.0
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
Yes, you can change them in the profile's setting or globally in profile defaults (Settings -> Profiles -> Advanced)
