### ISSUE TITLE
Argument "--directory" does not open given path reliably

### ISSUE THREAD

**Issue by vnc0** [Eugeny/tabby#6953]
**Describe the problem**:
The `--directory` argument does not work reliably. 
If Tabby is already running, the folder is opened correctly. If Tabby is not already running, the following behavior occurs: Tabby is opened, but it does not navigate to the folder.

**To Reproduce**:
Tabby 1.0.183 on MacOS.
Run `open -na tabby --args --directory ~/Downloads`.

**Comment by Eugeny** [comment]
Tabby doesn't have a `--directory` option, I guess you're running `open` from inside Downloads? Tabby will pick up CWD as the directory for a new tab. To reliably open a tab in a specific directory, use `--args open <dir>`, see `--help`
