### ISSUE TITLE
Document advertised features

### ISSUE THREAD

**Issue by Gaibhne** [Eugeny/tabby#6966]
**Is your feature request related to a problem? Please describe.**
The website advertises many amazing features such as file transfer via SFTP in SSH sessions, progress bars, split tabs/panes and 'simultaneous multi-pane input', whatever that may be, none of which I found any documentation on how to use them at all for.

**Describe the solution you'd like**
While I understand that providing documentation is both hard and boring, I would appreciate at least a single sentence per feature on how to accomplish the basic task of accessing said feature at all. With all of the above, for example, I have no idea how they work, nor how I would go about figuring them out at all, short of learning JS and looking at the source code.

**Describe alternatives you've considered**
Not using said features :(

**Comment by Eugeny** [comment]
Hey, thanks for the feedback! I know Tabby lacks docs badly, as I'm very low on time that I can dedicate to the project. I've compiled some of the ideas here: https://github.com/Eugeny/tabby/discussions/5259

99% of the features are directly discoverable either as always-visible buttons or in the context menu - to answer your questions directly:

- SFTP: UI button in the top toolbar when in an SSH tab
- progress bars: shown automatically when a shell/program outputs percentages of any kind
- split tabs: either via context menu or hotkeys
- simultaneous multi-pane input: via hotkeys ("focus all panes")

**Comment by Gaibhne** [comment]
Thanks! I found especially all the tab/pane stuff to be very unintuitive to stumble across via experimentation/self discovery, maybe it's more obvious for someone coming from Mac/OSX ? Like I said, I would think if you highlight a feature, a single sentence on how to access it would make sense, because even something as simple as the context menu is hidden behind a key/mouse combo you have to guess at (I still haven't quite figured out what exactly makes it appear instead of me pasting - seems to be based on how long a hotkey is held ?)

**Comment by Eugeny** [comment]
Yes - long-holding mouse button overrides "RMB to paste". IMO if you're coming from macOS, it's easier to just let RMB be used for context menu and paste with Cmd-V.

**Comment by Eugeny** [comment]
I've also just made those menu items accessible through the tab header menu and added a button to make the menu more easily discoverable
