### ISSUE TITLE
No colors on my terminal

### ISSUE THREAD

**Issue by heitorthewizard** [Eugeny/tabby#6971]
Version: 1.0.183
Platform: Linux x64 5.15.0-46-generic
Plugins: none
Frontend: xterm
(Zorin Linux, btw)

It's not showing any colors, only when I enter some program like vim, nano, htop it starts to show, but when I do some "ls", the folders and files are all whie, which gets hard to identify if it is a file or a folder. ( I tried disabling GPU acceleration, nothing happened)

**Comment by Eugeny** [comment]
Please see https://github.com/Eugeny/tabby/discussions/5258
