### ISSUE TITLE
update question

### ISSUE THREAD

**Issue by Dan-Essin** [Eugeny/tabby#6974]
**Describe the problem**:
I previously installed tabby-terminal-1.0.156-1.x86_64 on Fedora
I undoubtedly used the rpm.
Today tabby notified about an update so I downloaded 
tabby-terminal-1.0.183-1.x86_64

when running rpm -i tabby-1.0.183-linux-x64.rpm
I get dozens of conflict messagaes like:
file /usr/share/applications/tabby.desktop from install of tabby-terminal-1.0.183-1.x86_64 conflicts with file from package tabby-terminal-1.0.156-1.x86_64

I'm still learning linux and I don't know  the best way to resolve this.

Dome guidance would be appreciated

**To Reproduce**:
ditto

**Comment by Eugeny** [comment]
Use `rpm -U`
