### ISSUE TITLE
“Delete“ & “Backspace“ cant work normally in some Terminal

### ISSUE THREAD

**Issue by TanY0Y0** [Eugeny/tabby#6983]
Version: 1.0.183
Platform: Windows x64 10.0.22000
Plugins: save-output
Frontend: xterm

in some Terminal, Backspace doesnt work, and Delete work as like this: "~", the real Backspace is "Shift + Backspace"
how can modify the keyboard config to fix it?

**Comment by Eugeny** [comment]
Tracking in #5862
