### ISSUE TITLE
Tabby Update in settings always download arm64 installer but it should be x64

### ISSUE THREAD

**Issue by TigerBeanst** [Eugeny/tabby#7001]
**Describe the problem**:
I am using x64 version, download from release.(tabby-1.0.181-setup-x64.exe)
But using Update in Tabby Setting, it always download arm64 version.(tabby-1.0.183-setup-arm64.exe)

![image](https://user-images.githubusercontent.com/3889846/185202488-f165475f-7dd6-4422-a93d-b6cd6390c013.png)

And then....yeah, the installer works fine and I didnot realize that it is arm64 installer.
Now my Tabby Program files looks like that:

![image](https://user-images.githubusercontent.com/3889846/185203114-3263d307-7d32-4f9b-93ab-eae11efccd4d.png)

**I have to go to Github and manally download the latest x64 installer....**
Fortunately, this does not affect the configuration file.

I update Tabby twice and it happen twice.

`C:\Users\<username>\AppData\Local\tabby-updater\pending\update-info.json`
```json
{"fileName":"tabby-1.0.183-setup-arm64.exe","sha512":"KtxTIq+WMf7oIZ4cLpqOrsi7xQNCol+WVPaQYudzAmfOxpToxBbs5jBVgP856tNPLeNQTVgRLC19ODx75qFK+A==","isAdminRightsRequired":false}
```

**Comment by Eugeny** [comment]
Fixed in the latest release
