### ISSUE TITLE
color schema not effect while using ohmyzsh

### ISSUE THREAD

**Issue by clearcodecn** [Eugeny/tabby#7024]
**Describe the problem**:
I am use ohmyzsh on macos. they are all default config. 
and I change color schema on tabby, but it looks like worse. 
Do you have any idea?

![image](https://user-images.githubusercontent.com/34591322/185828891-b36a211b-6ad5-4213-b9e3-6e1b48d996d5.png)

**Comment by mukangt** [comment]
@clearcodecn 
Appearance -> Terminal background, choose "From color scheme"
