### ISSUE TITLE
lrzsz downloading .tar.gz files, the file will be broken. Tabby: v1.0.183

### ISSUE THREAD

**Issue by QG-phy** [Eugeny/tabby#7053]
**Describe the problem**:
when using the version v1.0.183. I use the sz  command to download xxx.tar.gz file. it says succefully downloaded. but when i open the downloaded file. it is either broken or some files lost.

**Comment by leonpenn** [comment]
The same problem has bothered me for a long time

**Comment by QG-phy** [comment]
> The same problem has bothered me for a long time
Yeah. hope it can be fixed soon. @Eugeny

**Comment by LWF53** [comment]
@Eugeny
