### ISSUE TITLE
Support for `Sixel` terminal graphics

### ISSUE THREAD

**Issue by curio-sitas** [Eugeny/tabby#7063]
Many terminals support graphics printing, like bitmap images and even gif image.
This kind of feature may have many interests when working with images, and to have custom ouputs in scripts.

Some of terminals supporting this feature : 
* macOS: [iTerm2](https://iterm2.com/), [contour](https://github.com/christianparpart/contour) and [mlterm](https://sourceforge.net/projects/mlterm/)
* Linux: [mlterm](https://sourceforge.net/projects/mlterm/), [contour](https://github.com/christianparpart/contour), [xterm](https://invisible-island.net/xterm/)
* Windows: [contour](https://github.com/christianparpart/contour), [mintty](https://github.com/mintty/mintty), [msys2](https://www.msys2.org/) and [mlterm](https://sourceforge.net/projects/mlterm/)

One could use this library : [libsixel ](https://github.com/saitoha/libsixel) to implement it.

**Comment by jerch** [comment]
What about this:
![grafik](https://user-images.githubusercontent.com/6193135/187534108-2afe3dde-f90a-4dda-874a-b95d8b0aa06a.png)
Not working for you?

**Comment by curio-sitas** [comment]
I did not find this option, but it was activated. I tested with the Julia REPL and their [Sixel packages](https://github.com/JuliaIO/Sixel.jl). But it does not work for me.

**Comment by jerch** [comment]
And what does not work? What did you try / expect and what did you get instead? Also note that sixel does not work on windows/WSL currently due to windows/ConPty issues.

**Comment by curio-sitas** [comment]
I run the Julia console using Tabby. Wich is a windows executable (i created a profile for it). I then use the package mentioned before to show a png image in the terminal. It is supposed to convert the file into a Sixel output. But there is nothing printed, it does not work. But the problem may come from them.

**Comment by jerch** [comment]
If you are on windows - nope sixel does not work there currently due to window's incompatible console driver (called ConPty).

**Comment by curio-sitas** [comment]
Ok my bad then, im on windows. You or i may close the issue then
