### ISSUE TITLE
Update wrong version

### ISSUE THREAD

**Issue by sOUTHeRYF** [Eugeny/tabby#7065]
**Describe the problem**:
I have installed x86 version,but when it update itself,there will download a  arm64 version,and obsolute wrong

**To Reproduce**:
1.install x86 version
2.wait a new version
3.try update
4.install failed, a arm64 install package downloaded in C:\Users\XXXXX\AppData\Local\tabby-updater\pending\

**Comment by Eugeny** [comment]
The latest release now uses Keygen and separate update channels per arch, so this won't come up again with the next update.
