### ISSUE TITLE
Window moving and resizing utterly lagging and unusable

### ISSUE THREAD

**Issue by Earu** [Eugeny/tabby#7074]
This issue has been around for a very long time for me, strangely enough it didnt exist when I was using "Terminus" instead of the current version. I looked a bit online about what could be the issue I found some stuff related to mouse polling where the polling rate is too high, so I tried lowering my mouse polling rate to 125hz, it helped a bit but Tabby is still lagging way behind.

[See this video for an example of what happens](https://streamable.com/g2x802)

I'm not doing anything particular, I just open Tabby and this starts happening.

**Comment by Eugeny** [comment]
Disable the "fluent" window background style. Tabby, not being an UWP app is using a hack to enable it and on _some_ machines it causes lag when moving/resizing the window.

**Comment by Earu** [comment]
Sorry for the late response, that fixed it thanks !

**Comment by coderunway** [comment]
I'm facing the same issue and it's honestly very laggy. I tried this option but I'm still facing the same issue.  Please see the screenshot of the setting, I did. Hope I'm doing it correctly. 

![image](https://github.com/Eugeny/tabby/assets/22704812/6d17b08e-bdae-45c3-8ff8-2c085b5bfb68)
