### ISSUE TITLE
Strange color scheme issue

### ISSUE THREAD

**Issue by Gaibhne** [Eugeny/tabby#7077]
**Describe the problem**:
My Tabby, which picked up my dark theme from my Windows 10 installation (I think), has various unreadable parts:

![](https://i.imgur.com/MXiix4x.png)

Not pictured here is pasted text, which also looks like the key info - very light gray on white, I think ? Other things also appear unreadable, such as the hotkeys in the `nano` editor or certain search results.

I have no idea what caused this and/or how to change it. Any help please ?

**To Reproduce**:
I'm not sure what caused it or where that behavior would be configured.

**Comment by Eugeny** [comment]
Have you tried a different color scheme already?

**Comment by Gaibhne** [comment]
I don't think I ever changed from the default, but trying now, I see them taking effect, but not the background - if I select a non-dark theme, I end up barely being able to read anything anymore, the background stays dark. Something overriding the themes background, maybe ?

**Comment by Eugeny** [comment]
Yes - see Settings -> Appearance -> Terminal Background

**Comment by Gaibhne** [comment]
Ah, cheers! I'm not sure if I changed that or it was set like that, but everything works as intended now! Thank you!
