### ISSUE TITLE
UI lags when opening or closing a tab

### ISSUE THREAD

**Issue by Arichy** [Eugeny/tabby#7081]
**Describe the problem**:
[A clear and concise description of what the bug is.]
UI lags when opening or closing a tab, very not smooth.
SoC: Apple M1 pro
**To Reproduce**:
[Steps to reproduce the behavior]
1. open Tabby
2. open a new tab
3. close a new tab
![Kapture 2022-08-31 at 21 28 48](https://user-images.githubusercontent.com/29599723/187690359-19590394-ad86-499c-ab20-5d1e99f15f70.gif)

**Comment by Larissa-Kravtsova** [comment]
Having same issue on Windows 11

**Comment by Satellite-Galaxy** [comment]
Same here on Fedora 36
