### ISSUE TITLE
AutoUpdate Error

### ISSUE THREAD

**Issue by lingting** [Eugeny/tabby#7082]
After using the program's own update, all the files in the tabby program installation folder disappeared.

os: win 11 21H2 22000.856
tabby : 1.0.181

Click here to update
![image](https://user-images.githubusercontent.com/59352063/187838764-b9ebfcf9-9cb0-49d3-b1ae-6cba0433b26d.png)

install all
![image](https://user-images.githubusercontent.com/59352063/187838829-a70bc27b-9d6b-462e-a7f3-dad71221c7a3.png)

result
![image](https://user-images.githubusercontent.com/59352063/187838863-ad48d66b-5795-4a73-9c58-bace06a2e207.png)

![image](https://user-images.githubusercontent.com/59352063/187838900-dc2e1cfe-fc6a-4e92-97ea-baed482485b5.png)

![image](https://user-images.githubusercontent.com/59352063/187838914-c031568b-47d5-43c9-ac4d-5d79ef49f1d4.png)

![image](https://user-images.githubusercontent.com/59352063/187838952-48e7703c-aab7-48fa-a46b-f1c16d859267.png)

**Comment by jc-fun** [comment]
I also met the same problem
