### ISSUE TITLE
Text merges with background in some places

### ISSUE THREAD

**Issue by konstantin83** [Eugeny/tabby#7088]
Hi, Eugeny.
On am attahed screenshot you can see the simple nano interface, where no shortcuts and topline text are visible because of text merging with it's background. 
Changing Color themes in Tabby settings changes only some elements, but not background for example.
Some time ago I used to change something in settings file (but don't remember what exactly). So it can easilly be me the one to blame))
But I really want to make colors and themes controlled as they supposed to.
Maybe you can understand the reason of this issue and explain how to fix it?

![1](https://user-images.githubusercontent.com/13274062/188323119-09f158ca-a2a1-4927-97a2-13007fdb3874.png)

**Comment by Eugeny** [comment]
This is an existing issue in the WebGL renderer and one of the reasons it's still marked as experimental. Switching back to the normal xterm frontend will do the trick.
