### ISSUE TITLE
Display images in terminal 

### ISSUE THREAD

**Issue by lokize** [Eugeny/tabby#7097]
Hi i really loving tabby, is there any way to show images in the terminal? for example:

I'm using zsh with neofetch and when I try to display images with w3m nothing appears

**Comment by Eugeny** [comment]
You can enable Sixel support in Settings -> Terminal, but keep in mind that there are caveats if you're on Windows: #6988

<img width="290" alt="image" src="https://user-images.githubusercontent.com/161476/193661911-d1319414-13a6-4d46-8ede-324a6f711ebf.png">
