### ISSUE TITLE
Splitting the window is not user friendly

### ISSUE THREAD

**Issue by atiris** [Eugeny/tabby#7116]
**Is your feature request related to a problem? Please describe.**
I need to split tab to two terminals and as many others who uses tabby I ends with this comment: https://github.com/Eugeny/tabby/issues/49#issuecomment-800159732

**Describe the solution you'd like**
First place where I search for "Split horizontally" and "Split vertically" or possibly "Split and open profile" is right menu on tab. I think this is the ideal place (image 1) for people to look first if they want to achieve a split window. 

**Describe alternatives you've considered**
Since the division of the window would be appropriate to combine with the possibility of connecting another profile, I think it would be appropriate to place (dynamically displayed) icons when selecting a profile, which will allow the profile to be opened left, right, top, bottom. Kind of like image 2.

**Additional context**
Image 1:
![image](https://user-images.githubusercontent.com/10474618/189600877-f6db8be6-4545-46ad-99a9-a33dd4036c1f.png)

Image 2:
![image](https://user-images.githubusercontent.com/10474618/189602092-c5791bf1-0c0c-423d-a233-673d7e8f0a8c.png)

**Comment by Eugeny** [comment]
Please try the nightly build - the tab menu now includes the missing items that were previously only available in the terminal context menu

**Comment by atiris** [comment]
Fixed
