### ISSUE TITLE
Show saved password like edge

### ISSUE THREAD

**Issue by zzdts** [Eugeny/tabby#7128]
Is any way to view the saved password ?

**Comment by Eugeny** [comment]
Passwords are saved in your OS' keychain (Keychain.app / Credential Manager / gnome-keyring)

**Comment by zzdts** [comment]
> Passwords are saved in your OS' keychain (Keychain.app / Credential Manager / gnome-keyring)

I use win11

**Comment by Eugeny** [comment]
https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0

**Comment by wtlovzjj** [comment]
> 

hello, How can you retrieve your password through the Accessing Credential Manager？
