### ISSUE TITLE
Add the posibility to paste from clipboard using mouse right-click

### ISSUE THREAD

**Issue by kCyborg** [Eugeny/tabby#7132]
**Is your feature request related to a problem? Please describe.**
I work a lot with terminals, always copying and pasting here and there, in other terminals (suchs as Termius and MobA) you can paste your clipboard's content using the right-click on your mouse.

**Describe the solution you'd like**
Allow paste clipboard's content using the mouse's right-click 

**Describe alternatives you've considered**
None

**Additional context**
As you can see I went to the `Hotkeys` section (which is super nice to interact with) but I can't use the mouse to use shortcuts. I have a mouse with a couple of extra buttons and I will like to use some of them in this action and in others too.

![not letting me use the mouse buttons](https://user-images.githubusercontent.com/37458643/190279596-e414e186-97b9-422a-a37d-1fb5eebf4b3f.png)

**Comment by amajauskas** [comment]
This is already implemented:

![image](https://user-images.githubusercontent.com/82594881/190329371-c9017b09-e5a6-4fb6-80ea-bd9486df52a6.png)

**Comment by kCyborg** [comment]
Holy moly! I did't say it! Thanks!!!!
