### ISSUE TITLE
[feature request] add option for Tresor unlock timeout

### ISSUE THREAD

**Issue by F3000** [Eugeny/tabby#7165]
at the moment every time I start an SSH session I have to enter my password for the Tresor again . Even if the program is not closed between the sessions .

Would be useful to have a setting that sets a timeout e.g. 3 hours . After that user have to input the password again

**Comment by Eugeny** [comment]
What OS are you on? Generally there's no way for Tabby to influence how the OS keychain is handling remembering its password

**Comment by F3000** [comment]
@Eugeny  im using Windows 10/11. 

where is the tresor stored ? 

the goal should be to reduce the time the user have to enter the password again

**Comment by Eugeny** [comment]
I think there's been a misunderstanding - do you mean Tabby's _Vault_ or the OS keychain where passwords are stored by default? (Tabby uses the Windows Credential Manager for this)

**Comment by F3000** [comment]
No I mean the tabby vault . When I t possible to have there an option "unlock for 3 minutes" etc.. would be fine

**Comment by Eugeny** [comment]
You mean this?... 
![image](https://user-images.githubusercontent.com/161476/192886239-d75fc3e2-f852-4c56-9711-f5317029b172.png)

**Comment by Eugeny** [comment]
It's right where you're typing in the vault password when unlocking it.
