### ISSUE TITLE
[Feature request] edit "Tab " Name

### ISSUE THREAD

**Issue by F3000** [Eugeny/tabby#7198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

As a user I want to have the possibility to edit the tab title .
Instead of seeing the whole path (which is often to long ) where the cmds.exe is saved a simple "Command prompt" or "Powershell" would be 

**Describe alternatives you've considered**
Tried the plug-in for that . But it is updated . 

**Additional context**

**Comment by Eugeny** [comment]
Disable "dynamic tab title" in the profile settings.
