### ISSUE TITLE
All connection profiles are gone

### ISSUE THREAD

**Issue by denysbondar2002** [Eugeny/tabby#7234]
Version: 1.0.184
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

I added about 50 profiles. But the last one was through jumphost.    And after I connected to the last one from the settings, all the profiles disappeared. Only the built-in ones were left.

**Comment by luchare-hash** [comment]
> I got a sync problem now.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3195031/194200281-13125fdc-2f61-4a50-bd5e-7262c0944602.png)
> 
> 

In my case there was no mention of synchronization, you have the wrong issue
