### ISSUE TITLE
Dragging the window so  weird

### ISSUE THREAD

**Issue by Anekys** [Eugeny/tabby#7255]
Version: 1.0.184
Platform: Windows 11 x64 10.0.22000
Frontend: xterm
![gif](https://user-images.githubusercontent.com/53458682/194571495-fd72e2a3-74c9-4d78-94b9-e76420a6ded6.gif)

**Comment by Anekys** [comment]
Animation is always delayed

**Comment by chaoo-fish** [comment]
This is my solution to this problem
![image](https://user-images.githubusercontent.com/59482475/194581251-c9422b4b-62bb-4ea1-8399-fb3fec3c3f4f.png)

**Comment by Anekys** [comment]
> This is my solution to this problem ![image](https://user-images.githubusercontent.com/59482475/194581251-c9422b4b-62bb-4ea1-8399-fb3fec3c3f4f.png)

It's work， Thanks
