### ISSUE TITLE
copy not working when editing a file with vim

### ISSUE THREAD

**Issue by thudjx** [Eugeny/tabby#7266]
**Describe the problem**:
I have turned `copy on select` on and want to copy multilines when editing a file using vim.
If interaction using mouse is diabled, `copy on select` works fine, although I have to suffer from the copied linenumbers(I have `set number; set relativenumber` in vim) when copying multilines at once:
![image](https://user-images.githubusercontent.com/32637321/194810532-422e6a16-d7cf-49aa-8a40-2008f2346e11.png)

If the mouse interaction is turned on, I can select multilines of pure text without the linenumbers, but I cannot copy the text. I have tried the `copy` in the menu but it doesn't work(the paste button in the menu works as expected).
![image](https://user-images.githubusercontent.com/32637321/194810771-80623079-712f-4544-ba3a-180d378622b6.png)

**To Reproduce**:
Vim configuration:
```
set number
set relativenumber
set mouse=a
```
I am editing files in a remote server. Not sure whether this will make things more complicated.

**Comment by Eugeny** [comment]
Not a vim user, but the vim's own selection (on the right) is not "selection" in terms of terminal state, but rather just gray background. It's very likely that vim also has its own "copy" command somewhere that would use this selection.

**Comment by Eugeny** [comment]
Check out https://github.com/ojroques/vim-oscyank

**Comment by Eugeny** [comment]
Also if that doesn't work, as a workaround, you can hold Alt when selecting text to use rectangular selection

**Comment by thudjx** [comment]
Thanks for your kind reply. I have compromised to use tmux clipboard in remote server. This solved most of the problem as the majority of text copying and clipping happens inside the server itself. Besides, the problem of copying from remote to local is solved by using the plugin you mentioned.
Thanks again and I am closing the comment.
