### ISSUE TITLE
reconnect ssh sessions cause mouse action abnormal

### ISSUE THREAD

**Issue by cloud-yu** [Eugeny/tabby#7267]
**tabby version: 1.0.184**
**windows version: win11 22h2**

## [Steps]
1. ssh session closed due to bad net connections. (**passively closed**)
2. click `reconnect` button, to reconnect session
3. mouse click or scrolling mouse on the windows will make some unreadable inputs
![image](https://user-images.githubusercontent.com/8436078/194835759-299bce9d-0427-47c7-b165-6f7db36c3b08.png)

**Comment by HiFiPhile** [comment]
Brand-new 1.0.188 also has this issue, connecting to a Debian 11 machine from Windows 10 22H2.

**Comment by cloud-yu** [comment]
according this [QA](https://apple.stackexchange.com/questions/329785/when-i-click-on-my-terminal-strange-characters-appear)
reconnect action somehow cause iterm active [mouse tracking mode](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking)
running the `reset`command should work
