### ISSUE TITLE
Smart zooming in the font size

### ISSUE THREAD

**Issue by Mr-Zhang-Cn** [Eugeny/tabby#7277]
现在程序上有放大字号和缩小字号的快捷键，但是我觉得不是很方便，我希望增加ctrl+滚轮 智能修改字号的功能

**Comment by stritti** [comment]
See also: https://github.com/Eugeny/tabby/issues/6793

**Comment by Mr-Zhang-Cn** [comment]
解决了.https://github.com/Eugeny/tabby/issues/7277#issuecomment-1186514866
