### ISSUE TITLE
Tabby keeps opening a new tab every time it launches 

### ISSUE THREAD

**Issue by louis-kiyus** [Eugeny/tabby#7300]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/75559366/196056449-bdbcde04-ca6e-4bed-967a-5cadcd51c2d3.png">

Version: 1.0.183
Platform: macOS arm64 21.6.0
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
You can disable this "Auto-open a new tab on start" in Settings
