### ISSUE TITLE
Option "Hide Window on focus loss" do not work

### ISSUE THREAD

**Issue by Manriel** [Eugeny/tabby#7309]
Version: 1.0.184
Platform: Windows x64 10.0.19044
Plugins: workspace-manager
Frontend: xterm

I use Quake-style docking. And option "Hide Window on focus loss" do not work. It became broken since version Alpha 178
Probably related with issue #6812, but it does not work for me regardless of "Warn on multi-line paste" option value.

Also do not work "Focus follows mouse" option. Might be related with mouse events?

**Comment by taniadaniela** [comment]
Version: 1.0.184
Platform: MacOS 11.6 
having the same issue

**Comment by Eugeny** [comment]
Can't reproduce unfortunately - with these settings, focusing another application hides the window: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/161476/197864537-383f828a-1728-41b1-8b9b-f8455e35db79.png">

**Comment by taniadaniela** [comment]
@Eugeny that's actually helpful, I was using primary display, when switching to current focus works correctly, so the issue is with the primary display setting.

**Comment by tkirkland** [comment]
Version: 1.0.187
Platform: Windows x64 10.0.19044
Plugins: theme-windows10
Frontend: xterm-webgl

Add me to the list of 'not working.'  I've tried several different combos to no avail.  Docked to all sides, current/primary, transparent/non, and nothing.  The terminal sits there quite stubbornly, I might add.

**Comment by luckydye** [comment]
Version: 1.0.188
Platform: Windows 11 22H2 and MacOS 13
Frontend: xterm-webgl

I have the same problem on my Windows 11 and MacOS 13. It seems that as soon as I turn on Config encryption it stops working.

**Comment by ralleal** [comment]
Version: 1.0.188
Platform: Ubuntu 22.10
Frontend: xterm-webgl

I have the same problem on Ubuntu 22.10. Changing monitor to "Current" doesn't fix, nor disabling config encryption.
