### ISSUE TITLE
A shell script error which not occured in putty

### ISSUE THREAD

**Issue by EatonLin** [Eugeny/tabby#7326]
Version: 1.0.184
Platform: win10
Plugins: quick-cmds
Frontend: xterm-webgl

I use ssh to log into my ubuntu server and execute my script(test.sh):
`
#!/bin/sh
function test_func()
{
    echo "Test func"
}
echo "Test"
`

In tabby, i got this error: **./test.sh: 2: Syntax error: "(" unexpected**, and i found that it cause by the key word "function". It never occured in putty. Any suggestion?

**Comment by Eugeny** [comment]
Scripts are executed on the remote side and are not affected by the terminal app. Make sure you're actually running the same thing on both cases.
