### ISSUE TITLE
Opacity for words

### ISSUE THREAD

**Issue by louis-kiyus** [Eugeny/tabby#7348]
I love the option to adjust the opacity of Tabby, but I think it would also be even more beneficial to allow users to retain the text's opacity while decreasing the window's opacity. Currently, the texts fade along with the window, which makes it hard to read the texts. 

Version: 1.0.183
Platform: macOS arm64 21.6.0
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
On macOS, this is only possible with the "vibrancy" window option under Settings
