### ISSUE TITLE
Disable White shade when pressing ctrl+shift

### ISSUE THREAD

**Issue by John98Zakaria** [Eugeny/tabby#7381]
**Is your feature request related to a problem? Please describe.**
Feature Request
When I press ctrl+shift, tabby shows a transparent white overlay with the names of the tabs.
This annoys me while copying and pasting items as the white overlay is distracting

![image](https://user-images.githubusercontent.com/30316353/198305442-0b5b8dc0-570c-4765-8ef4-b01ebdec6ad9.png)

**Describe the solution you'd like**
An option not to have this white overlay showing up

**Describe alternatives you've considered**
Tried looking in the config file for a mapping that solely binds to ctr+shift, but found nothing.

**Comment by Eugeny** [comment]
You can change or disable it in Settings -> Hotkeys -> Show pane labels.
