### ISSUE TITLE
Request: full text manipulation of the command line including text selection/highlighting and Ctrl+X for *cutting* text

### ISSUE THREAD

**Issue by dizzy-egg** [Eugeny/tabby#7389]
**Is your feature request related to a problem? Please describe.**
The killer feature which made me instantly love Tabby was the fact that you can manipulate text on the command line almost like you do in a text editor, using hotkeys such as `Ctrl+Backspace`, `Ctrl+Left`/`Ctrl+Right`, and the *Intelligent Ctrl+C* command.

However, I desperately miss being able to *highlight* text using `Shift+Left` or `Ctrl+Shift+Left` and then being able to *cut* text using `Ctrl+X`.

**Describe the solution you'd like**
I would like typing on the command line to feel more like using any other native text input:
* Enable text on the command line to be selected/highlighted using common shortcuts such as `Shift+Left`/`Ctrl+Shift+Left`.
* Add *Intelligent Ctrl+X* functionality which cuts the selected text when in a command line context, much like the existing *Intelligent Ctrl+C* functionality does for copying text.

**Describe alternatives you've considered**
Currently I manually highlight parts of the command line using the mouse, and manually delete parts using `Backspace` or `Ctrl+Backspace` but this is slow and tedious compared to native text manipulation.

**Additional context**
I have seen similar discussions involving other terminal emulators with developers saying this is not possible because the input is processed on the server and therefore can't be directly manipulated in this way; however this functionality **is** present in *SmarTTY*, for example.

One solution could be to process all input locally first and *then* send the processed line to the server instead of sending the input to the server character-by-character (unless that's what Tabby does already).

**Comment by bijoy26** [comment]
This is a much-needed feature! 👨‍💻

**Comment by dizzy-egg** [comment]
Any thoughts on this feature @Eugeny ? Or how it might be added?

**Comment by Eugeny** [comment]
This opens an awful can of worms and is not in the scope of this project. As you said, line editing happens on the shell side / remote side in case of SSH, and just doing it on the client side means you don't get things like tab completion.

This is totally doable as a plugin though.
