### ISSUE TITLE
ANSI escape code not working?

### ISSUE THREAD

**Issue by 8exBCYJi5ATL** [Eugeny/tabby#7402]
**Describe the problem**:
ANSI escape code that works with Alpha 184 may not work with Alpha 185.

**To Reproduce**:
1. I use Windows 11 Home 22H2.
2. Download Tabby Alpha 184 & Alpha 185.
   [tabby-1.0.184-portable-x64.zip](https://github.com/Eugeny/tabby/releases/download/v1.0.184/tabby-1.0.184-portable-x64.zip)
   [tabby-1.0.185-portable-x64.zip](https://github.com/Eugeny/tabby/releases/download/v1.0.185/tabby-1.0.185-portable-x64.zip)
3. Create "test.bat".
```bat
@echo off
for /f %%i in ('cmd /k prompt $e^<nul') do set ESC=%%i
echo %ESC%[38;5;231m%ESC%[4m%ESC%[48;5;33m1234%ESC%[0m%ESC%[24m%ESC%[0m
```
4. Execute "test.bat".

**Tabby Alpha 184（Expected Results）**
![image](https://user-images.githubusercontent.com/83834253/199250349-3e962caa-dcd3-44c1-a9e9-4b0d7127d943.png)

**Tabby Alpha 185**
![image](https://user-images.githubusercontent.com/83834253/199253103-b40b3472-3a76-4165-93ba-a10cc10db2db.png)
![image](https://user-images.githubusercontent.com/83834253/199256029-bd15525c-4834-44b7-ba30-98c01f757a16.png)

**Comment by Eugeny** [comment]
Does switching Settings -> Terminal -> Frontend back to `xterm (canvas)` help?

**Comment by 8exBCYJi5ATL** [comment]
@Eugeny
Thanks for your reply🙇

**Tabby Alpha 185 & xterm (canvas)**
Underline color as expected.
But text color is not what I expected.
![image](https://user-images.githubusercontent.com/83834253/199274173-abab78d6-79ea-40bf-bc2c-78411fcb0eab.png)

**Tabby Alpha 184 (Expected Results)**
![image](https://user-images.githubusercontent.com/83834253/199275891-8feebf73-dea2-467e-92de-a208f4dd6e2d.png)

**Tabby Alpha 185 & xterm (WebGL)**
![image](https://user-images.githubusercontent.com/83834253/199273988-ec66ec9e-91e9-484f-adc0-86d143065f49.png)

**Comment by 8exBCYJi5ATL** [comment]
#7926
