### ISSUE TITLE
Using tmux in a remote server through ssh causes weird UI issues - new line every 1 minute

### ISSUE THREAD

**Issue by sandeepchittilla** [Eugeny/tabby#7413]
**Describe the problem**:
[A clear and concise description of what the bug is.]

As mentioned in the title this is how my screen looks after several minutes of tmux-ing into a remote server. Below is a screenshot. I have split the screen vertically inside a tmux session. The right pane is currently active. Notice the cursor is several lines below the actual line where i input text. If i leave this for several minutes, it keeps "adding" another green line / terminal screen "shifts up". **Check the timestamp.** Happens every 1 minute so time roll over causes this somehow?

NOTE : The white boxes are for censoring some info

![image](https://user-images.githubusercontent.com/62606281/199479148-f746509c-30fd-4fd9-9b2f-44da9640ded4.png)

**To Reproduce**:
[Steps to reproduce the behavior]

1. Open tabby with Gitbash backend
2. SSH into a remote mahcine and start a tmux session
~~3. Split the tmux session into horizontal panes~~ This happens even if you don't split the panes. 
4. Wait

**Comment by sandeepchittilla** [comment]
@Eugeny is this going to be fixed in the next release or isn't a priority? Thanks for the reply

**Comment by Eugeny** [comment]
Unfortunately I'm unable to reproduce this - would appreciate any info about your setup.

**Comment by sandeepchittilla** [comment]
I believe this could be a tmux issue .. too many variables to figure out what is causing it. I have opened an [issue]( https://github.com/tmux/tmux/issues/3381 ) in the tmux repo. So i can close this issue for now
