### ISSUE TITLE
I tried to change the weight of the font, but failed

### ISSUE THREAD

**Issue by ZhangqyTJ** [Eugeny/tabby#7449]
Tabby version: 1.0.186

My Custom Css:
`
body {
 font-weight: 100;
}

body > app-root > div > div.content > tab-body.content-tab.ng-tns-c0-0.ng-star-inserted.content-tab-active.active > split-tab > ssh-tab > div.content { 
   background-color:rgba(0,0,0,1.5) ;
   margin-top:15px;
   margin-left:0px;
   padding-left:8px;  
   font-weight: 100;
}
`
font-weight does not take effect
![微信图片_20221107155605](https://user-images.githubusercontent.com/95729803/200257669-5cb5013d-76b9-4e6c-adfe-d8e7b5342eb2.jpg)

**Comment by Eugeny** [comment]
You can change the font weight in Settings -> Appearance.
