### ISSUE TITLE
profiles and connections

### ISSUE THREAD

**Issue by bibinvargheset** [Eugeny/tabby#7451]
I am using tabby on ubuntu 20.04.
The ssh configs are imported into the Built-in group in profiles after the other default options and other after 32 serial options.
is there a way to group the ssh config parsed as a separate group and before the default options and not removed on disabling the default options?

**Comment by Eugeny** [comment]
The only way to modify built-in or imported profiles is to duplicate them. You can duplicate the profiles you want and then disable all built-in profiles in Settings -> Profiles -> Advanced
