### ISSUE TITLE
Add an option to copy by right click

### ISSUE THREAD

**Issue by qazwsxedckll** [Eugeny/tabby#7476]
**Is your feature request related to a problem? Please describe.**

It happened many times that I selected something unconsciously and it overwrote the clipboard.

**Describe the solution you'd like**

I think the right way to copy is by right click once just like other tools, not select or right click menu.

It should be select, right click to copy, right click again to paste.

**Comment by Eugeny** [comment]
Settings -> Terminal -> Right click -> Right click to copy

**Comment by qazwsxedckll** [comment]
It is Right click to PASTE, not copy

**Comment by qazwsxedckll** [comment]
@Eugeny It is Right clict to PASTE, not copy.

**Comment by Eugeny** [comment]
That's also an option:
![image](https://user-images.githubusercontent.com/161476/201487722-43c74342-3797-4a62-a8e0-ba4673ea9090.png)
