### ISSUE TITLE
Tabby not saving history between sessions

### ISSUE THREAD

**Issue by rarahim75** [Eugeny/tabby#7482]
Tabby is not saving its own command history between sessions. 

Open a bash terminal on Tabby, type some commands, close Tabby. Re-open Tabby, previously opened terminal is restored and message 'History restored' is printed.. However, when I clicked the up arrow key to cycle through previously typed commands, none were saved. The only available commands from the history list were the ones entered in the built-in Terminal program. All commands entered in Tabby terminal were not saved. 

I'm using the latest version Tabby 1.0.186 on Ubuntu 22.04. I have installed Tabby using the instructions given [here](https://linuxhint.com/install-terminus-modern-age-terminal-ubuntu-22-04/).

Thanks in advance.

**Comment by Eugeny** [comment]
Terminals don't control your command history. Check out https://askubuntu.com/questions/499376/bash-history-not-saved-after-closing-terminal
