### ISSUE TITLE
Background color change not working in Windows

### ISSUE THREAD

**Issue by USMANHEART** [Eugeny/tabby#7505]
Version: 1.0.186
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

The terminal is really great and I like to use it. But there is small issue that my eyes have problem with bright colors.
I am not sure about Linux, but as per my experience based in Windows, it is only changing Font colors. Background or many color changing settings are not working
Kindly have a look if it's possible to fix.

![image](https://user-images.githubusercontent.com/46762805/202331765-6a80bb45-ffcb-4d74-a6ac-39ff611a3007.png)
![image](https://user-images.githubusercontent.com/46762805/202331373-9103220f-6262-458e-bf7e-f0f6e01976d9.png)

**Comment by 1301536601** [comment]
Yes, I have the same problem. Can this be fixed?

**Comment by zjttfs** [comment]
![QQ截图20221122135912](https://user-images.githubusercontent.com/24729880/203236515-300815df-3cf4-4038-9d69-e9a196646889.png)
在这里

**Comment by 1301536601** [comment]
> > The translator bot has detected that this issue body's language is not English, and has translated it automatically.
> 
> ![QQ screenshot 20221122135912](https://user-images.githubusercontent.com/24729880/203236515-300815df-3cf4-4038-9d69-e9a196646889.png) it's here

Very good. This solved my problem
