### ISSUE TITLE
SFTP edit locally executable file will make the file  non-executable

### ISSUE THREAD

**Issue by Alexpham1130** [Eugeny/tabby#7522]
**Describe the problem**:
Select SFTP and select executable file (shell, python, ....) and then **Edit locally**. After made change and saving, the change is reflected . However the edited file is no longer executable. 

**To Reproduce**:
- Create executable
```
% touch demo.sh
% chmod +x demo.sh 
% stat -c '%A %a %n' demo.sh 
-rwxrwxr-x 775 demo.sh
```

- Make a chance and save

- Observe the file property has been unexpectedly changed

```
% stat -c '%A %a %n' demo.sh 
-rw-rw-r-- 664 demo.sh
```

**Comment by molinacarlos** [comment]
+1
