### ISSUE TITLE
How to remove black background of character like this?

### ISSUE THREAD

**Issue by pengshp** [Eugeny/tabby#7542]
I don't like Color scheme like this,how to change it?
![image](https://user-images.githubusercontent.com/13529131/203296297-cf09eae7-57fb-4bad-8270-434316aa421c.png)

Tabby version: 1.0.187
Color scheme: ayu

**Comment by Canary233** [comment]
> It's my zsh theme,not tabby!sorry

Hi,bro.I'm also having this issue with zsh using the powerlevel10k theme,but other SSH clients don't have this issue, such as JuiceSSH and Termius.How did you solve this one?
