### ISSUE TITLE
The tab close icon is not visisble on verticle tab layout

### ISSUE THREAD

**Issue by rahulsinghk** [Eugeny/tabby#7543]
steps to repro. 
1) configure the tab to the left screen.
2) the tab cross icon is not visible only the options icon is visible

<img width="404" alt="image" src="https://user-images.githubusercontent.com/42302337/203458684-18817047-bbc5-424d-b1bb-58507e7f632d.png">

the expected behaviour is to have the close icon visible, 

Version:- 1.0.187 (1.0.187)

**Comment by Eugeny** [comment]
Temporary workaround: disable the tab menu button in Settings -> Window

**Comment by rahulsinghk** [comment]
hi @Eugeny 
could not find the tab menu button in Settings -> Window 
but one more workaround is to set  Tab width to Dynamic
