### ISSUE TITLE
Disable port forwarding

### ISSUE THREAD

**Issue by bar1bar1** [Eugeny/tabby#7571]
Hi,

I keep getting this error :
 SSH   X  Could not set up port forward on 
 SSH   X  Could not set up port forward on 
 SSH   X  Could not set up port forward on 
 X  (SSH) Channel open failure: open failed

I don't really have the time or energy to check if the port is in use or what....the auto port forwarding is a cool feature.
but can we disable it?

**Comment by Eugeny** [comment]
Tabby doesn't have auto port forwarding. These are the forwards you've set up in your Profile > Ports.
