### ISSUE TITLE
[Feature Request] Add Telnet functionality 

### ISSUE THREAD

**Issue by LordBoBCUP** [Eugeny/tabby#760]
Hi, 

I would love to see the addition of telnet to terminus. Working in the network field I still have a bunch of old equipment on the network that isn't ssh friendly. I would love to see a option in the SSH connection manager to select telnet when saving the connection as well!

Thanks

**Comment by Testato** [comment]
+1

**Comment by nhjeffh** [comment]
+1

**Comment by shaqaruden** [comment]
+1

**Comment by JiHanHuang** [comment]
+1

**Comment by NerDante** [comment]
+1

**Comment by tritamk14** [comment]
+1

**Comment by Qetesh** [comment]
+1

**Comment by haneefdm** [comment]
+1

or netcat
