### ISSUE TITLE
i cant change theme

### ISSUE THREAD

**Issue by thompson0012** [Eugeny/tabby#7621]
Version: 1.0.187
Platform: macOS arm64 22.1.0
Plugins: relaxed-theme, docker, altair
Frontend: xterm-webgl

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/51963680/206417185-ebef9e63-e3b3-4ed5-a8ad-f2330df0cd4d.png">

as you can see, the theme dropdown menu is disappear from the application tab

anyone can tell me how can i change theme?

**Comment by Eugeny** [comment]
It's on the Window tab.

**Comment by thompson0012** [comment]
ohhh, thanks Eugeny

i saw documentation, thought it is still in application.

big thanks

**Comment by Eugeny** [comment]
Where did you see it? (So that I can update the doc)
