### ISSUE TITLE
 Jump out of an animal and scare me

### ISSUE THREAD

**Issue by Axe-l** [Eugeny/tabby#7623]
Where did it come from and how to turn it off.

- [ ] @1. > ### [`_****_`](url)
![顶顶顶顶顶顶顶顶顶顶顶顶顶](https://user-images.githubusercontent.com/45731066/206461179-c45ecd6f-bb85-4c0d-9691-1b0e0a11a503.jpg)

**Comment by Eugeny** [comment]
This happens if you install every plugin from the list without reading the description. It's the tabby-clippy, the demo plugin.
