### ISSUE TITLE
Tab list when moved to bottom has separator miss-aligned 

### ISSUE THREAD

**Issue by hellozyemlya** [Eugeny/tabby#7637]
**Describe the problem**:
When tab list moved to bottom, separator between tab list and tab content is missaligned, see screenshot.
<img width="1104" alt="Screenshot 2022-12-11 at 17 08 30" src="https://user-images.githubusercontent.com/53153547/206911771-59c707f7-41b5-4376-9ce1-88946bcd70a8.png">
**To Reproduce**:
* install latest tabby on mac os 12.6.1
* "Tabs location" - bottom
* "Dock the terminal" - top

**Comment by hellozyemlya** [comment]
Hi. Any update for this issue? This still happens. Thanks a lot for a nice terminal app, btw.

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/53153547/223408750-77feda0b-1bd7-46ad-bf4f-8abde8a78065.png">

**Comment by Eugeny** [comment]
Thanks! Fixed in the nightly (there's also a new default theme there).

**Comment by hellozyemlya** [comment]
@Eugeny many thanks, sir, going to try nightly builds.
