### ISSUE TITLE
SSH Connection Color settings

### ISSUE THREAD

**Issue by DevUrbi** [Eugeny/tabby#765]
Hello, 
I have been proving it a little bit and has been nice expirence.
The only thing i miss to be my primary option is a setting to put different scheme color options to each ssh connection. For me it is very important because many times i have differente enviroment connections opened and i like to know what I´m using  to avoid posible errors.

Thanks, and nice work.

**Comment by ericiper** [comment]
This would really be useful, same need here !

**Comment by sburkett** [comment]
I was just about to post a request for this as well. It would extremely helpful to be able to assign a color to a each host setting so you wouldn't have to do it manually each time you open a new session for that connection.

Last night I almost made a pretty serious production mistake by being in the wrong tab :)

**Comment by Eugeny** [comment]
Not a "fix", but you can now assign tab colors to SSH connections

**Comment by XenHat** [comment]
> 
> 
> Not a "fix", but you can now assign tab colors to SSH connections

I'm struggling to make this feature work. Any pointers?

**Comment by sburkett** [comment]
> Also would like the ability to assign themes to saved SSH connections.
> 
> > Not a "fix", but you can now assign tab colors to SSH connections
> 
> I'm struggling to make this feature work. Any pointers?

What is happening for you? You basically just right click on an open session tab and choose the option to change the color.

Again, I think it would be pretty awesome to be able to save a pre-defined color for each server entry, but the above is how it works currently.

**Comment by Eugeny** [comment]
@sburkett I meant the per-connection color setting (Settings -> SSH -> Advanced -> Tab color), and I think @XenHat means the same. It used to be broken a few previous versions but has since been fixed.

**Comment by chrismyers81** [comment]
This would be a fantastic addition.
