### ISSUE TITLE
Some characters inserted with AltgGr don't work

### ISSUE THREAD

**Issue by vvollaro** [Eugeny/tabby#768]
Version: 1.0.73
Platform: win32 10.0.17134
Plugins: none

On azerty keyboard, some additional characters can be inserted using a AltGr+Key (in fact the Alt key on the right). See this [image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/500px-KB_France.svg.png) for details for the french azerty layout for example.

In my case two keys are not correctly inserted, the characters ~ and  `. For example when pressing the AltGr+é keys, the ~ should be displayed, but the é char is inserted instead. If I press space bar, the ~ is finally inserted. 

When testing with the basic git bash window, the behavior is when pressing first the AltGr+é key, nothing is displayed, pressing bar space displays the "~" char. This the same behavior  in Linux terminals:

![tild_bug](https://user-images.githubusercontent.com/7499305/56273785-be776980-60fd-11e9-9020-bbdc24fe0a1b.png)

**Comment by bahamut45** [comment]
+1 I have the same problem

**Comment by gdlx** [comment]
This is the same issue I opened on VScode: https://github.com/Microsoft/vscode/issues/68262

**Comment by bcxpro** [comment]
Same thing on the Spanish keyboard with Alt-Gr

**Comment by gdlx** [comment]
Same issue with the ` character with AltGr + 7

**Comment by bcxpro** [comment]
Still happens to me on the Spanish keyboard

**Comment by vvollaro** [comment]
I see that the microsoft terminal has the same problem and has a potential fix: https://github.com/microsoft/terminal/issues/521

**Comment by bcxpro** [comment]
Still happens to me on the Spanish keyboard

**Comment by gdlx** [comment]
Still relevant on 1.38.1 with French keyboard 😿

**Comment by fle108** [comment]
same problem on 1.0.91

**Comment by Renji-FR** [comment]
Me too on 1.0.103.3882.

**Comment by mr-potato-head** [comment]
Same problem on a french keyboard.

**Comment by Renji-FR** [comment]
A workround is to use Microsoft Keyboard Layout Creator to create a custom layout with tilde ~ configured without option "dead key". Under MSKLC, select ALTGR and make right click on ~ to unselect "Set as dead key"

**Comment by roonie007** [comment]
@Renji-FR Dude you are the best, I have been struggling with this since the problem started on VsCode

**Comment by bertrandp** [comment]
Still have this issue with French keyboard ...

**Comment by Raton-Laveur** [comment]
Reproduced on VS Code 1.50.1 Win10 20H2. Regional settings are Windows display US, keyboard Azerty France.

**Comment by Eugeny** [comment]
I've just pushed a potential fix for these dead key related issues - would love to hear your feedback as soon as the nightly is built

**Comment by enodr** [comment]
Just downloaded the windows portable version and unfortunately the fix does not work for me.

**Comment by bcxpro** [comment]
The last insiders version available to me is from two days ago so it could
be that there is not a build with the fix yet.
My version is:
Version: 1.60.0-insider (user setup)
Commit: 89bbd372f459ce72e9c0b60eb3b26b924f64f62d
Date: 2021-08-20T17:51:50.560Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Eugeny** [comment]
@enodr dang. The fix isn't in xterm yet, but it's in tabby's fork.

**Comment by enodr** [comment]
In fact on a AZERTY layout only two keys don't behave correctly: the tilde "~" and the backtick "`"

The key "2" on a FR layout is:
2 (upper)
é (lower)
~ (need to press ALT-GR + space or ALT-GR + letter for ñ, õ, ã, etc)

![image](https://user-images.githubusercontent.com/10436257/130664340-bff8d616-f512-47a0-936d-f0b72f35b9ba.png)

When typing a ALT-GR + 2, Tabby outputs "é" and then after space press it outputs "~" and you now have "é~" in the term instead of just "~". Same for backtick (key 7), you will end up with "è`".

Unfortunately these two chars are keys used very often on linux terminal. Could that be yet another bug in xterm.js?

**Comment by bcxpro** [comment]
Just tested with this tabby-1.0.156-nightly.0-portable and my Spanish keyboard. AltGr+4 and then SPACE should display ~. It displays 4~

**Comment by Eugeny** [comment]
Build ready: https://github.com/Eugeny/tabby/actions/runs/1177141278

**Comment by bcxpro** [comment]
Everything looks good to me now.

**Comment by enodr** [comment]
Works perfectly now, thanks.

**Comment by Bloopps** [comment]
Hi,
Sorry but for me the last nightly build does not fix the issue.   #4433
