### ISSUE TITLE
support for ubuntu kinetic

### ISSUE THREAD

**Issue by holiq** [Eugeny/tabby#7697]
**Describe the problem**:
i install with follow this command
`curl -s https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash`
but i can't find repo for kinetic
![Screenshot from 2022-12-26 16-37-21](https://user-images.githubusercontent.com/30729921/209533110-95b156ea-598d-4cf0-82e4-babd58a9a8ea.png)

it available only to jammy, so i must change repo kinetic to jammy on gpg list `/etc/apt/sources.list.d/eugeny_tabby.list` 
![Screenshot from 2022-12-26 16-38-51](https://user-images.githubusercontent.com/30729921/209533131-9798f798-08a5-427e-b8b3-97d195db5389.png)

**Comment by Eugeny** [comment]
Thanks, I've updated the build scripts and the next release will be uploaded for kinetic as well.
