### ISSUE TITLE
unable to config sync keep getting error message server error 500 app.tabby.sh

### ISSUE THREAD

**Issue by keep57** [Eugeny/tabby#7703]
Version: 1.0.187
Platform: macOS x64 21.6.0
Plugins: trzsz, title-control, theme-windows10, theme-hype, theme-gruvbox, sync-config, search-in-browser, save-output, relaxed-theme, quick-restart, quick-cmds, plugin-fig-integration, love-shell, fit-screen, fig, elastic-quick-commands, elastic-quick-cmds, cloud-settings-sync, clippy, altair
Frontend: xterm-webgl

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by chunheisiu** [comment]
I am also seeing the same error after logging in on app.tabby.sh.

**Comment by keep57** [comment]
I simply uninstall, then reinstall works fine.
Daryl N.

**Comment by et304383** [comment]
@Eugeny this is still happening for many users, including myself, on multiple computers.  Please address this asap!
