### ISSUE TITLE
Run user command in SSH session

### ISSUE THREAD

**Issue by nabaco** [Eugeny/tabby#7706]
**Is your feature request related to a problem? Please describe.**
I want to be able to start an ssh session that runs a command upon SSH connection.
From the command line, I would do this: `ssh user@host -t command`

**Describe the solution you'd like**
I think the best solution is to add an option in the profile configuration. I'd assume the option should be added somewhere here afterward: https://github.com/Eugeny/tabby/blob/master/tabby-ssh/src/session/ssh.ts#L318

**Describe alternatives you've considered**
I've tried adding `ForceCommand` and `RequestTTY` to my ~/.ssh/config, but it didn't help, though it worked from the command line.
I could possibly change my `~/.bashrc`/`sshd_config`/`/etc/passwd` on the host to ensure that I automatically enter TMUX upon login. I don't have root access on all destinations, and it messes up other use-cases where scripts/apps run commands in a subshell. Either way, I'm looking for a flexible solution and not to resolve this specific use-case.
Alternatively, if Tabby passes some custom environment variable to the destination, via `SetEnv`, it might be useable but adding a condition for this variable on the destination.

**Additional context**
My main use-case is for reconnections when the internet connection is faulty. I have a custom profile in Microsoft Terminal that runs SSH command in a loop, so that I get automatic reconnections and TMUX re-attachments. I'd like to see the same here. My command is `ssh user@host -t tmux -L nabaco attach || tmux -L nabaco new`

**Comment by Eugeny** [comment]
You can use a "login script" with an empty "expect" value in the profile settings

**Comment by nabaco** [comment]
Didn't work for me, I'll try again

**Comment by nabaco** [comment]
It works, thank you. Probably I did something wrong the first time around.
