### ISSUE TITLE
Log in with Google returns Server Error (500)

### ISSUE THREAD

**Issue by longhtran91** [Eugeny/tabby#7707]
**Describe the problem**:
https://app.tabby.sh/api/1/auth/social/login/google-oauth2/ returns Server Error (500)

**Comment by Killerherts** [comment]
It appears something is wrong with the oauth backend as my cookies still work but all SSO is broken when it calls the API. 

Are people who are self hosting the web app having this issue. I was just using tabby.sh

**Comment by hrryt** [comment]
I seem to also be getting this issue for all SSO endpoints. 

I'm using Firefox v108.0.1 & LibreWolf v108.0.1

**Comment by lachiefish** [comment]
+1, is happening with all SSO endpoints, tried Firefox and Chrome

**Comment by Flaam** [comment]
+1, hope this will get fixed soon, I've been trying to login with GitHub SSO for the past week and it's not working, atp it's 100% sure that the login server is having problems

**Comment by red0orange** [comment]
+1, is happening with all SSO endpoints, tried Edge and Chrome

**Comment by ljwtorch** [comment]
+1,log in with Google returns Server Error 500 (use Chrome)

**Comment by aayushus** [comment]
+1, sometimes the GitHub login page shows up if you are not logged in to GitHub.

**Comment by Eugeny** [comment]
Should be back up!

**Comment by Flaam** [comment]
Login with GH is still not working
