### ISSUE TITLE
Mac command + 2 can't work

### ISSUE THREAD

**Issue by lingtaolf** [Eugeny/tabby#7722]
**Describe the problem**:
When I use `command + 2` to switch tab 2 , tabby do nothing.

tabby version: 1.0.184 (1.0.184)
OS version: macOS Monterey 12.1

**To Reproduce**: Open multiple tab then use command+2 to switch tab 2

**Comment by MuhtasimTanmoy** [comment]
Tabby Version: 1.0.203 (1.0.203)
OS: macOS Sonoma 14.1.1 

I could not regenerate. Working as expected.

**Comment by Eugeny** [comment]
Fixed in v1.0.204
