### ISSUE TITLE
Profile Options -> Hide

### ISSUE THREAD

**Issue by NJT145** [Eugeny/tabby#7727]
**Describe the problem**:
1. There is no option to hide any custom profile.
2. There is no option to hide any profiles from "Default profile" selection menu.
3. There is no option to restore default settings of a built-in profile.

**Describe the solution you'd like**:
1. Add option to hide custom profiles. You can add a bool value of HIDDEN status to each profile which is False as default, and hide the profiles with HIDDEN=True.
2. Add an option to hide built-in profiles from "Default profile" selection menu. You can add another bool value to each built-in profiles for that, or you can add an option to "Advanced" tab to hide hidden built-in profiles from "Default profile" selection menu, or you can hide all hidden profile from "Default profile" selection menu (if you do my next suggestion).
3. Copy all built-in profiles as custom profiles (if you cannot get default values for each settings later). Stop showing built-in profiles and make the copies of the built-in profile locked to delete, but allow to edit. Add on option to restore these copies of built-in profiles, which will get the values from built-in profiles.

**Comment by Eugeny** [comment]
Settings -> Profiles -> Advanced -> "Show built-in profiles"

**Comment by Eugeny** [comment]
I don't think so - but wouldn't just duplicating the built-in profiles that you need and then hiding all of them be an acceptable workaround?

**Comment by NJT145** [comment]
> I don't think so - but wouldn't just duplicating the built-in profiles that you need and then hiding all of them be an acceptable workaround?

no, not at all. I don't want to see all profiles in my custom profiles at menu. I want to keep some of them as hidden. That's NOT A SOLUTION.

**Comment by NJT145** [comment]
This is not only hiding built-in profiles, but also hiding some custom profiles when we don't need them. Don't want to create each profile again, just wnt to hide them when I need to hide them.
