### ISSUE TITLE
[feature] Add option to prevent tab from closing when shell/ssh exits

### ISSUE THREAD

**Issue by jpbochi** [Eugeny/tabby#7751]
**Is your feature request related to a problem? Please describe.**

Sometimes, I close a session by accident (e.g. too many ctrl-c's), or kicked off an ssh session. When that happens, the tab closes, and I can't lose all the logs.

Sometimes, I want to finish a session on purpose, but keep the screen log open for reference. That is not currently possible with Tabby, since the tab will be closed.

**Describe the solution you'd like**

I propose that Tabby adopts a similar feature to that iTerm2 has. There, you can choose for each profile, what you want to happen when a session ends, with 3 options:

1. Close tab, which is the default.
2. Kepp tab. A last "session ended" line is printed, no more prompt is asked, but I can still scroll through the logs.
3. Restart session. A "session ended" line is printed, and a fresh shell (or ssh) session starts immediately below it.

Some docs about iTerm2's feature at https://iterm2.com/documentation-preferences-profiles-session.html

Here's an screenshot of their preferences window:

![image](https://user-images.githubusercontent.com/96475/210965001-18d986ca-ab78-40e9-9d21-d7730a51e7e4.png)

**Describe alternatives you've considered**

The only alternative I considered was to configure in my `.bashrc` to prevent bash from closing. This is possible, but it's flimsy and not trivial to do. I don't know if it's possible to do for ssh sessions.

Adding support directly on the terminal app is a far superior option.

**Comment by rusty-lr** [comment]
I'd like to see this also.  There are many advantages to Tabby, but I pop back to mac terminal when I know I'm going to need to review what I was looking at in the ssh session.
