### ISSUE TITLE
Enh: click on custom profile should open connection (instead of edit)

### ISSUE THREAD

**Issue by gitgt** [Eugeny/tabby#7754]
After we create custom profiles, we can click on them (unlike built-in profiles that only react on icons).
Click should *open* that connection, unlike edit it like it does now. Reason: once you make a profile, you will most likely frequently use it to make a connection and rarely to change it. 
I think this change is acceptable for all, so I ask for a change, an option would be redundant, but could also be a solution.

I didn't find a similar issue.

**Comment by Eugeny** [comment]
> Reason: once you make a profile, you will most likely frequently use it to make a connection and rarely to change it.

The setting page is there to mostly change settings. You can pull up a clickable list of profiles with the `profile-selector` hotkey or the corresponding button in the toolbar above (next to "new tab")

**Comment by gitgt** [comment]
Thanks for a speedy response. That's a logic I have to embrace. I just started using it, still need to figure out more. 
I see about the profile-selector hotkey but I didn't figure out this "put the corresponding button in the toolbar".

**Comment by Eugeny** [comment]
No problem, it's this one: 
<img width="226" alt="image" src="https://user-images.githubusercontent.com/161476/211054016-a388a405-2b08-413c-b153-87049e5df870.png">

**Comment by Eugeny** [comment]
You can assign hotkeys to profiles in Settings -> Hotkeys. There are no default hotkeys to launch any of the profiles.
