### ISSUE TITLE
when HotKey setting in actived and using other terminal tab,CPU is too high,usually no response

### ISSUE THREAD

**Issue by TanY0Y0** [Eugeny/tabby#7771]
Version: 1.0.188
Platform: Windows x64 10.0.22000
Plugins: save-output
Frontend: xterm-webgl

![image](https://user-images.githubusercontent.com/51318636/211440534-76c14a4e-3d04-4f5b-ad46-eb2ea28cc4ea.png)
![image](https://user-images.githubusercontent.com/51318636/211440613-6bd58eef-6a7c-4543-94df-bc1323ba9b6d.png)

**Comment by rainbowflesh** [comment]
Same in Ubuntu 22.10

Version: 1.0.188
Frontend: xterm-canvas

**Comment by Eugeny** [comment]
This is fixed in the nightly and I'll make a full release soon
