### ISSUE TITLE
update Tabby new version, all ssh connect config disappear

### ISSUE THREAD

**Issue by itgoyo** [Eugeny/tabby#7782]
**Describe the problem**:

MacOS ：big sur 11.6
version 1.0.164->1.0.188
all my mac ssh connect files disappear

All configuration can only be redone

**Comment by Gary1567** [comment]
me too

**Comment by gexxx05** [comment]
Same here, all connections and configurations are gone.

**Comment by ManuelReschke** [comment]
Has this something to do with that? https://github.com/Eugeny/tabby/issues/5370

**Comment by Eugeny** [comment]
Duplicate of #5355
