### ISSUE TITLE
Unable to open tabby in the current path

### ISSUE THREAD

**Issue by LHabc-me** [Eugeny/tabby#7856]
**Describe the problem**:
there are no relevant options in the settings

**Comment by Eugeny** [comment]
Please elaborate

**Comment by LHabc-me** [comment]
> Please elaborate

I installed tabby via the deb package, and when I open tabby with the "Open terminal in current location" option in the right mouse button, tabby does not recognize the current path correctly, but opens in the ~ directory. The option is not found in the settings.
I would truly appreciate it if you can give me a hand.
