### ISSUE TITLE
Incomplete language translation

### ISSUE THREAD

**Issue by fenglangjunzi** [Eugeny/tabby#7870]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/5000975/215999234-da297a72-161c-4444-ac71-f4f78ffb453b.png">

**Comment by Eugeny** [comment]
Feel free to contribute :) https://translate.tabby.sh/translate/tabby/75/en-zhtw?filter=basic&value=0#q=tabs%20in%20fullscreen
