### ISSUE TITLE
Can we develop a version suitable for Android tablets

### ISSUE THREAD

**Issue by chenjj100419** [Eugeny/tabby#7880]
Can we develop a version suitable for Android tablets
For operation and maintenance, the existing Android ssh tool is not beautiful enough, and its function is not as powerful as this one. I hope it can be transplanted to Android tablet, thank you. I use termux to run it in a virtual machine, but it is not easy to use.

**Comment by Eugeny** [comment]
Not planned

**Comment by LokeYourLord** [comment]
> Can we develop a version suitable for Android tablets
> For operation and maintenance, the existing Android ssh tool is not beautiful enough, and its function is not as powerful as this one. I hope it can be transplanted to Android tablet, thank you. I use termux to run it in a virtual machine, but it is not easy to use.

If you need something for mobile and cross-platform of all types like me, use Termius for now. I hope Tabby one day comes around to Android like Termius did :)
