### ISSUE TITLE
How to dynamically log to text?

### ISSUE THREAD

**Issue by larkzhang** [Eugeny/tabby#7900]
How to dynamically log to text?
It's kind of like Crt logging, right?
Start logging while connected: The session option starts logging when connected. 
 
Append to file: If the log file exists, the new log is appended to the original log file. 
 
Overwrite file: If the log file exists, the new log overwrites the original log. 
 
Original record: Only original data is recorded, not custom data. 
 
Record only user-defined data: Records only user-defined log data.

**Comment by Eugeny** [comment]
You can do this with the `tabby-save-output` plugin
