### ISSUE TITLE
I get a black screen like this when in a VIM file. All the texts vanishes but the file remains open. 

### ISSUE THREAD

**Issue by dhanvin-k** [Eugeny/tabby#7914]
Version: 1.0.188
Platform: Windows x64 10.0.1
9044
Plugins: none
Frontend: xterm-webgl

![Capture](https://user-images.githubusercontent.com/46697688/218013230-96b96757-7593-46a2-8290-295b93d23fbe.PNG)

**Comment by windflowerly** [comment]
how did to resolve it?
