### ISSUE TITLE
sftp does not support pasting path strings

### ISSUE THREAD

**Issue by yangyongyongyong** [Eugeny/tabby#7928]
sftp不支持粘贴路径字符串 

如果路径特别长  需要耗时很久去找到文件

**Comment by Eugeny** [comment]
Double-click the breadcrumbs to make them editable, then you can paste the path there.

**Comment by huih99** [comment]
as you said, i follow this operation, but it didnt work
version: 1.0.188

**Comment by Eugeny** [comment]
Maybe this would help?

https://user-images.githubusercontent.com/161476/220079147-d00b047d-b76b-4c82-a65d-7f169924d280.mov

**Comment by huih99** [comment]
![record](https://user-images.githubusercontent.com/36914167/220080858-a9f04d50-a847-430a-99e1-ac2e6057fb86.gif)
emmm, why difference

**Comment by Eugeny** [comment]
Oh my bad, it's actually only available in the nightly right now 😅

**Comment by huih99** [comment]
got it , thanks！
