### ISSUE TITLE
The color scheme does not take effect

### ISSUE THREAD

**Issue by AgentZh0u** [Eugeny/tabby#7930]
版本: 188
设备: M2 pro

配色方案选择了,  外观也设置了取自配色方案, 效果上只是修改了背景色,其余颜色都没修改
<img width="507" alt="image" src="https://user-images.githubusercontent.com/24451759/218634247-ff1cb274-776f-4649-8ee8-8dd397e9ce23.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/24451759/218634279-4bf44f71-ef53-4477-906b-11db11495eb1.png">

**Comment by Eugeny** [comment]
https://github.com/Eugeny/tabby/discussions/5258

**Comment by Sora-dcliu** [comment]
> #5258
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b4f5bed4e2db77ffd03ac1cccb0dc400d714aaecb0a09da0a4a1f48a66c918f2/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f626364373839663065323737313034306366333532323037303736663734626534313437326635666334613461663130326366393763373333373036623065312f457567656e792f74616262792f64697363757373696f6e732f35323538"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[No colors in `ls`, etc. · Discussion #5258 · Eugeny/tabby](https://github.com/Eugeny/tabby/discussions/5258)**What is happening? Color themes can only change colors of colored text that is printed to the terminal, not colorize text that is originally black and white. How to make sure that a color scheme wo...

This method can only make the file names displayed by "ls" command appear in color, but the characters before the "%" symbol will still be displayed in black and white. Like:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/54578027/230554049-3f6a7d7e-c9e9-4284-812d-999a9b49fb9d.png">

**Comment by Eugeny** [comment]
If you want a colorful prompt, you need to install one. There are many available, the one I'm using is https://ohmyz.sh/
