### ISSUE TITLE
Setting the tab title using the shell

### ISSUE THREAD

**Issue by fhackenberger** [Eugeny/tabby#7935]
I'm using tabby on Linux and I'd like to be able to set the title of the Tabs using the shell (bash in my case). For e.g. Konsole as a terminal, it uses the current directory as a title.

The respective shell command is `echo -ne "\033]30;test change title\007"`.

See also [Stackoverflow](https://stackoverflow.com/questions/19897787/change-konsole-tab-title-from-command-line-and-make-it-persistent).

Thank you for making this great project happen!

**Comment by Eugeny** [comment]
You can already do this, running your `echo` command changes the title. Your .bashrc might be overriding this tough, reverting back to the current dir name after every command.

**Comment by fhackenberger** [comment]
@Eugeny I was hoping it would, but it doesn't on my Ubuntu 20.04 with the current package version from your deb repository. Is there maybe a setting that I missed? It keeps the title at "User default" (name of the profile).

**Comment by fhackenberger** [comment]
Connecting via SSH does change the title to the remote prompt though.

**Comment by fhackenberger** [comment]
@Eugeny Shall I open a new issue for Linux/Ubuntu specifically?

**Comment by fhackenberger** [comment]
Thank you for your reply! Not sure it was on [SO](https://stackoverflow.com/a/25175079) and I just used it for testing. I tried it as you suggested and it did set my prompt, so I guess it's somehow an incompatibility with something in by .bash_rc. I'm using [git_svn_bash_prompt.sh](https://gist.github.com/woods/31967), might be that.

**Comment by fhackenberger** [comment]
Okay I experimented a bit more and it seems some part of my PS1 is not supported by tabby, but does work in bash. Here's my current setting:
`$ echo "$PS1"

\[\033[0;32m\]\u@\A \[\033[1;33m\]\w\[\e[0m\] \[\033[0;31m\]\[\033[1;31m\](fhackenberger/angular-io-upgrade)↑\[\e[0m\] \[\e[0m\]\[\033k\033\\\]
$`
