### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by wjwei-handsome** [Eugeny/tabby#7980]
Version: 1.0.189
Platform: macOS x64 22.3.0
Plugins: none
Frontend: xterm-webgl

In the Setting-Shortcut key , the chinese translation of `scroll-to-top` not should be `滑动中断到顶端`, it should be `滑动终端到顶端`

Thanks！

**Comment by Eugeny** [comment]
Hi, you can contribute corrections on https://translate.tabby.sh/project/tabby - thanks!
