### ISSUE TITLE
Pane GUI issues on windows moving around and top bar coming in the way. 

### ISSUE THREAD

**Issue by krusion** [Eugeny/tabby#8028]
Version: 1.0.189
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm-webgl

Hello, 

I recently started using tabby mainly for multiple panes. Love the UI but having some quirks here and there. I tried replicating this on another machine with windows 11 and had the same issues.

What I did was I had multiple SSH sessions running, I dragged one tab onto the current tab to create multiple panes. However, the main pane can be moved from the move icon (top left), but the added tab won't move. The button doesn't show. This happens with multiple panes too. See video below of the issue. 

 

https://user-images.githubusercontent.com/23137586/222873466-4c0f8146-fe18-4090-91cf-c465cd3f4aa8.mp4

I saw another issue where the solution was to hold ctrl+shift. Would've preferred to have an all mouse solution, but even with that solution, I get an issue where I end up getting ghost pains that show up and are empty. There's nothing in them. I'm not even sure how to close these as there's no close button. Am I missing a close button or has it not been implemented yet?
Weirdly though, after those ghost panes show up, I get a move button for all the panes. I can also move them into a new tab and close them from there separately. 

https://user-images.githubusercontent.com/23137586/222873566-c41258c7-108a-4734-b7f1-c29f9d4bddfb.mp4

I moved all panes out and ended up with the two empty panes in that window. 

![image](https://user-images.githubusercontent.com/23137586/222873798-6e6cc495-a2c6-4ffc-bd8c-b05a9c246d91.png)

Lastly, I can see a there's a wrench button at the top left behind the top bar (title bar?) for each session. I unpinned this bar to show the wrench button. I assumed this might be a close session option. However, I can't reach the wrench because every time I come close, the bar will drop down and cover it. 

https://user-images.githubusercontent.com/23137586/222873747-8ee3f7a5-7a33-42fe-9fe3-0eaf05d537b9.mp4

Again, these issues were repeated on another computer. I'm unsure if this is a new bug or things that are known already. Couldn't find the exact issues on here.   

EDIT: I just realized that after adding multiple panes. As I said, the move button disappear. If I close and reopen tabby, then they show up. Also, the ghost panes will also show up properly if I restart. Having said that, I found another bug related to the fact that after unloading the panes to tabs, the text in the tabs remain "squeezed" to fit the old pane size and will only spread out if I reconnect the SSH session.

**Comment by krusion** [comment]
Yes of course! I'll repeat the tests once it's ready and verify that all is good! 

Thank you!

**Comment by krusion** [comment]
Hello!
Just tested it now! Works perfectly as expected. Non of the things that happened before are happening now!

**Comment by Eugeny** [comment]
Thanks for checking
