### ISSUE TITLE
Cannot change theme

### ISSUE THREAD

**Issue by MaxAlekseyev** [Eugeny/tabby#8047]
Looks like simple issue, go to Settings -> Color scheme, click on theme, theme marked but nothing had happened

Lasr tabby
Win 10 LTSC

![image](https://user-images.githubusercontent.com/10415908/223188513-ece05a18-b4b3-4f08-8c78-6314742bf550.png)

**Comment by Eugeny** [comment]
These are terminal color schemes, not app themes. Open a terminal tab to see the changes.

**Comment by MaxAlekseyev** [comment]
Can you exlain me step by step how apply 3024 Night theme to CMD to example or Ubuntu/WSL?

![image](https://user-images.githubusercontent.com/10415908/223241215-12e627ee-382e-4aac-8634-fbc7c66a47f3.png)

**Comment by Eugeny** [comment]
It seems to be already applied to me. If you're referring to the window theme background still being used, you can switch it in Settings -> Appearance -> Terminal Background

**Comment by MaxAlekseyev** [comment]
Yes, great this is working well but what about the fonts color like the first screen.

This style is perfect

![image](https://user-images.githubusercontent.com/10415908/223280513-6fcafa42-2d45-4cc8-9432-69cdf8698258.png)

**Comment by max1c** [comment]
> It seems to be already applied to me. If you're referring to the window theme background still being used, you can switch it in Settings -> Appearance -> Terminal Background

This setting doesn't appear to exist anymore. How can this be enabled now?
