### ISSUE TITLE
Show saved password for SSH profile

### ISSUE THREAD

**Issue by huaiyizhao** [Eugeny/tabby#8056]
**Describe the problem**:
I cannot see my saved password for a SSH profile. The only option is to forget. 

**To Reproduce**:
Open any saved SSH profile
![image](https://user-images.githubusercontent.com/29160164/223643086-86ee7ce8-111e-41fb-97dd-09869029174c.png)

**Comment by Eugeny** [comment]
You can see it in your OS keychain (Keychain.app / Seahorse / Windows Credential Manager)

**Comment by MrLoading** [comment]
![image](https://github.com/Eugeny/tabby/assets/33680247/df1839bc-a400-4830-92e8-b98dbe1ba5e9)

I use win11，there's no "show" option here, so I can't see my secret. 

The "Edit" option can only modify the password, but cannot view the password. 

I think this is a bug, once I forget my password I won't be able to use sudo to set a new password, stuck in a dead end?

**Comment by muava12** [comment]
put password on encrypted tabby's password would be great.. i don't really trust MacOs to not sending this password to their server
