### ISSUE TITLE
SFTP bug

### ISSUE THREAD

**Issue by njzyxiong** [Eugeny/tabby#8093]
**Describe the problem**:
the exit button is too large in stfp

**To Reproduce**:
click stfp, then you can see

**Comment by njzyxiong** [comment]
![Snipaste_2023-03-19_15-31-06](https://user-images.githubusercontent.com/32593161/226160735-d0ebaf4f-2b33-438d-9b72-b4031d7a9a89.png)

**Comment by Eugeny** [comment]
Which theme are you using?

**Comment by njzyxiong** [comment]
> Which theme are you using?

Cobalt Neon, but this happens with all themes

**Comment by Eugeny** [comment]
I mean in Settings -> Window -> Theme

**Comment by njzyxiong** [comment]
follow the color scheme. but this also happens with all themes
