### ISSUE TITLE
Copy on select is no longer working

### ISSUE THREAD

**Issue by victor-vc** [Eugeny/tabby#8096]
After updating to 1.0.192 the selected text is not automatically copied to clipboard. I cannot copy any text neither by selecting it nor by using the `Ctrl-Shift-C` shortcut.

**Comment by Eugeny** [comment]
Fixed in 1.0.193

**Comment by victor-vc** [comment]
I have just updated to the 1.0.193 version, and selecting the text doesn't copy it to clipboard, as `Copy on select` should do. However, `Ctrl-Shift-C` works.
