### ISSUE TITLE
Unable to copy text

### ISSUE THREAD

**Issue by FireloliZZ** [Eugeny/tabby#8098]
Version: 1.0.192
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

**Comment by chaolinhan** [comment]
Same for me. Just updated form 192 to 193 and it fixed.

**Comment by FireloliZZ** [comment]
thanks

**Comment by brunolabozzetta** [comment]
unable to copy text in ubuntu 22.04 also...

**Comment by Eugeny** [comment]
Fixed in 1.0.193
