### ISSUE TITLE
The search input box is not the normal size

### ISSUE THREAD

**Issue by pengan95** [Eugeny/tabby#8100]
Version: 1.0.191
Platform: macOS arm64 22.3.0
Plugins: none
Frontend: xterm-webgl

![WX20230320-152815@2x](https://user-images.githubusercontent.com/10327949/226273883-edd30f69-73ba-4dba-8d2e-0c73efbabac9.png)

**Comment by fenglangjunzi** [comment]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/5000975/226538600-80de427b-99cf-4193-a774-16f25b9d6ab5.png">

**Comment by fenglangjunzi** [comment]
Upgraded to version 1.0.194, the problem still exists.

**Comment by Eugeny** [comment]
Should be fixed in 1.0.196 now

**Comment by fenglangjunzi** [comment]
Bug was fixed, great!
