### ISSUE TITLE
Hotkey settings freezing

### ISSUE THREAD

**Issue by Jeluxe** [Eugeny/tabby#8102]
Version: 1.0.192
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

hello when i'm going into the hotkeys settings when i click on other section it is still showing the hotkeys setting window
![Tabby_c2WVudNkzg](https://user-images.githubusercontent.com/59278268/226344883-7e12c10f-6ec1-443e-959d-48cf39409401.png)

**Comment by Jeluxe** [comment]
also alot of hotkeys not showing anymore in the hotkey section
like duplicate tab or move pane, etc...

**Comment by lawweiliang** [comment]
@Jeluxe 
Try to update your tabby to the latest version `1.0.196` and check whether the problem is still exist or not. 
From my side, I couldn't not regenerate the problem. 

![image](https://user-images.githubusercontent.com/34936929/228401803-b44d8db4-fd99-40cf-8dfe-1d2fe559abda.png)

**Comment by Jeluxe** [comment]
so i reinstalled entirely including restarting all the configs and then it works
