### ISSUE TITLE
copying no longer works

### ISSUE THREAD

**Issue by SullyvanCrow** [Eugeny/tabby#8103]
Hello, 
since i updated to the latest version,
copying no longer works either from the context menu or on the fly when I select text.
pasting it works fine.

Version: 1.0.192
Platform: Windows x64 10.0.19045
Plugins: workspace-manager
Frontend: xterm-webgl

**Comment by MvrckTheBald** [comment]
Same here.

Version: 1.0.192
Platform: Ubuntu 22.04.2. LTS
Plugins: quick-cmds-1.0.2
