### ISSUE TITLE
welcome page button no response

### ISSUE THREAD

**Issue by X3vvv** [Eugeny/tabby#8119]
Version: 1.0.194
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm-webgl

i just installed Tabby, click "New terminal" or "Profile & connections", nothing happened. then when i click other buttons, nothing works. But if after open Tabby, click "Settings", it can be opened.

**Comment by kentooo** [comment]
Version: 1.0.194
Platform: Windows x64 11 22624.1465
Plugins: none

> Version: 1.0.194 Platform: Windows x64 10.0.19044 Plugins: none Frontend: xterm-webgl
> 
> i just installed Tabby, click "New terminal" or "Profile & connections", nothing happened. then when i click other buttons, nothing works. But if after open Tabby, click "Settings", it can be opened.

same as you
but settings button doesn't work on my system
