### ISSUE TITLE
Context Menu does not show

### ISSUE THREAD

**Issue by InanisOmnia** [Eugeny/tabby#8127]
**Describe the problem**:
When right clicking or using the menu button on tabs, the context menu does not show

**To Reproduce**:
1. Update to Tabby 1.0.189
2. Open tab
3. Right click in terminal (or click on tab menu button)
4. No context menu shows

OS: Windows 10

Note: I downgraded to 1.0.188 and the context menu works just fine again so it may have been caused by the additional menu option that was shipped in 1.0.189

**Comment by Dan-Essin** [comment]
now on 1.2.200
no rt-click menu

**Comment by zygfrydw** [comment]
I have the same issue on Ubuntu 22.04 with 1.0.201

**Comment by Eugeny** [comment]
Fixed in v1.0.204
