### ISSUE TITLE
After updating to the latest version, some buttons cannot be seen clearly

### ISSUE THREAD

**Issue by Suery** [Eugeny/tabby#8128]
After upgrading to version 1.0.196, some buttons cannot be seen clearly.

OS: Windows 10
Tabby Version: 1.0.196

Note: After the 1.0.190 version started, there was this problem, but the 1.0.189 version did not have this problem

The following is a comparison chart.

#### Version 1.0.196

![image](https://user-images.githubusercontent.com/55574045/226774793-7086f338-7da0-40b8-a4d7-acf1fbd97fd8.png)

#### Version 1.0.189

![image](https://user-images.githubusercontent.com/55574045/226775255-d92d1b8b-4e8c-4d69-84ea-48e0a8153700.png)

**Comment by MartinLau7** [comment]
+1

**Comment by AethLi** [comment]
same problem
