### ISSUE TITLE
Ability to permanent disable Cmd (clink)

### ISSUE THREAD

**Issue by catalin87** [Eugeny/tabby#8131]
A big problem with CMD Clink is that "Tabby\resources\extras\clink\clink_x64.exe inject" trigger an antivirus alert and this is a NO GO for everybody in our organization.

A good solution will be ability to permanent disable Cmd (clink) from settings, to avoid accidental opening of Cmd (clink).

This will be a huge update for corporate users where antiviruses software cannot be personalized and where security policies are strict.

**Comment by Eugeny** [comment]
Clink is only started when you open a tab that uses a clink based profile. You can change the default profile in Settings - Profiles & Connections

**Comment by catalin87** [comment]
I know about that option, but we installed Tabby for 3 users and all of then pressed CTRL+SHIFT+E and started the 1st cmd option from the list (witch is cmd clink).
So the security team requested us to delete Tabby from our machines because they got lot of AV alerts.

That is why will be a nice improvement to have an option to remove clink from everywhere.

Thanks a lot for your fast reply!

**Comment by Eugeny** [comment]
To be honest it sounds like the security team could manually review this case and make an exception for an obvious false positive.

Alternatively, you can make a copy of your preferred built-in profile, so that it shows up on top of the list

**Comment by catalin87** [comment]
Yes, security team can treat this as a false positive because is clear that this is false positive.
But in our company security policies are so strict and they cannot allow any exception.

Anyway! Great software, this is really the best terminal!
Keep on the good work.
