### ISSUE TITLE
Close button misalignment

### ISSUE THREAD

**Issue by capricornxl** [Eugeny/tabby#8141]
Tabby verion: alpha 1.0.190
My operate system: windows 11 x64

When i config tabby:  Settings ---> Window ---> Spaciness，window close button misalignment...
![image](https://user-images.githubusercontent.com/40738379/227541332-2dcf0231-422e-4d52-8258-f75e4ddc99c4.png)

**Comment by Eugeny** [comment]
Fixed in the latest release
