### ISSUE TITLE
^H for backspace and ability to change termtype

### ISSUE THREAD

**Issue by ray73864** [Eugeny/tabby#8186]
Have a need to be able to tell tabby that backspace should send ^H and also be able to change the termtype for an SSH session.

Finding tabby really nice to work with, on 1 of my work computers I use MobaXterm and CryptoTerm, MobaXterm for all the general ssh sessions since it natively supports X11 forwarding, and CryptoTerm for the WYSE-60 support.

However I installed Tabby onto another computer and love the fact that it natively works with both X11 forwarding and WYSE-60 (at least so much as in if I bring up our old character-based point of sale, it just, works, something neither MobaXterm or Putty are capable of).

Unfortunately, the database we use, for its procedure editor, it only supports so many different termtypes, and the default Tabby one of xterm-256-color isn't supported, so I need to be able to change the termtype to 'xterm', but not always, some SSH sessions where I will never use it, the default is fine, for the ones where I do, I need it to be that (same SSH login and IP).

For that procedure editor, I also need backspace to send ^H, otherwise instead of deleting the character to the left, it deletes the character to the right.

With MobaXterm, backspace by default deletes to the left, and if I want to delete to the right, I hold down the shift key + backspace.

Otherwise, I am so in love with this software, even the SFTP browser works 1000x better than MobaXterms one, which doesn't download properly if I change something in the directory and forget to refresh, and opening lots of files causes it to bug out and stop working completely.

**Comment by Eugeny** [comment]
Tracking in #5862
