### ISSUE TITLE
HotKey for quick command dropdown

### ISSUE THREAD

**Issue by j4l-Shvn** [Eugeny/tabby#8192]
I may be missing this in about 13K issues -- but would really appreciate if there is a hotkey to activate the quick command dropdown

**Comment by Eugeny** [comment]
It's `Show command selector` in Setting -> Hotkeys

**Comment by j4l-Shvn** [comment]
Actually I meant the quick command selector that shows up after the the "quick command" option is selected from the "Show command selector" -> dropdown .. Is there any way to skip the selection of the "quick command" option first from the main command selector and jump straight to the quick command selector

**Comment by Eugeny** [comment]
Oh not sure, you might wanna ask in https://github.com/minyoad/terminus-quick-cmds

**Comment by j4l-Shvn** [comment]
Thanks a lot .. Will ask!!
