### ISSUE TITLE
stucking there once I click the dialog selecting "profiles&connections".

### ISSUE THREAD

**Issue by y8gao** [Eugeny/tabby#8257]
Version: 1.0.196
Platform: Windows x64 10.0.22621
Plugins: theme-windows10, theme-hype, theme-gruvbox, save-output, relaxed-theme, fig, altair
Frontend: xterm-webgl

Actually I am using windows 11. When I open the "profiles & connections", the window is stucking there once I click the dialog selecting "profiles&connections".

**Comment by rmatte** [comment]
I'm running 1.0.196 on Windows 11 and I don't have the problem that you are describing.

**Comment by y8gao** [comment]
I uploaded one video recording my operations.  When I open the "profiles&connection", the UI seems have one light grey cover on the top. at that time, only keyboard input may be used, once clicked by mouse, nothing can be input, and the only operation is I stop it by force.

[cannot-input-or click-anything.webm](https://user-images.githubusercontent.com/5154290/233529567-25b59c88-735e-45dc-9187-53358e7b67b6.webm)
