### ISSUE TITLE
paper clip?

### ISSUE THREAD

**Issue by zazi0001** [Eugeny/tabby#8259]
version:1.0.196

A paperclip pops up in the bottom right corner of the terminal
never see it before
can anyone tell me why

![20230419122052](https://user-images.githubusercontent.com/28730221/232966293-ce919c5a-b568-4b2a-96d1-028a4c6587ba.png)

**Comment by Clem-Fern** [comment]
It's the clippy plugin.
You can disable it throught Settings > Plugins > Installed

**Comment by zazi0001** [comment]
ty it works
