### ISSUE TITLE
search box become large

### ISSUE THREAD

**Issue by chenwenchao1201** [Eugeny/tabby#8291]
Version: 1.0.196
Platform: macOS arm64 22.3.0
Plugins: none
Frontend: xterm-webgl
When I open the search box, the search box becomes very large.like this
![image](https://user-images.githubusercontent.com/30336621/233935748-8a5f3097-f1ae-4b38-8ff9-d023be34c5bc.png)

**Comment by Eugeny** [comment]
This should already be fixed in the nightly, feel free to reopen if it isn't
