### ISSUE TITLE
Request for synchronization function between local folder and remote server folder

### ISSUE THREAD

**Issue by zhiha** [Eugeny/tabby#8293]
Excuse me, I was wondering if there is a simple way to sync the contents of a local folder to a specific folder on a remote server using your terminal tool? This would eliminate the manual upload steps required every time the folder is updated. Your terminal tool is excellent and I appreciate your hard work and open-source spirit. Thank you very much in advance! ^_^

**Comment by Eugeny** [comment]
Thank you, but this is not in the scope for this app at this time. I would recommend using `rsync`
