### ISSUE TITLE
keep colors and logos when tabby resarts

### ISSUE THREAD

**Issue by c-0ne** [Eugeny/tabby#8313]
**Is your feature request related to a problem? Please describe.**
When restarting tabby with opened tabs, the colors and logos are not visible until i click them & open it 1 time

**Describe the solution you'd like**
it would be great, if at start of tabby the colors and the logos of my opened tabs are loaded and visible.

**Describe alternatives you've considered**
i just never close tabby i just hide it with CTRL Space, but sometimes i need to exit it or i forget to hide it and close it anyways.

**Additional context**
tabby is REALLY great!! i use it at work and home every day. thank you! very great software!

**Comment by c-0ne** [comment]
nice one thank you, do you know when this will be in a release?

**Comment by Eugeny** [comment]
Not yet, but you can install the nightly build
