### ISSUE TITLE
Some characters inside the private use area not displayed correctly

### ISSUE THREAD

**Issue by pseudocc** [Eugeny/tabby#8314]
Version: 1.0.188
Platform: Linux x64 6.1.0-1009-oem
Plugins: none
Frontend: xterm-webgl

Nerd fonts are using the [private use area](https://www.unicodepedia.com/groups/private-use-area/) to store some vectors,
but tabby cannot display some of them correctly.

All characters behind U+E635 (inclusive) are affected.

![image](https://user-images.githubusercontent.com/85104110/234758453-f3aadf9a-b94e-40ca-ba49-614c37fa47c9.png)

**Comment by Eugeny** [comment]
Could you please attach the specific font version you're using?

**Comment by pseudocc** [comment]
> Could you please attach the specific font version you're using?

Sure, I am using [Cascadia Code](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/CascadiaCode.zip).
Neither CaskaydiaCove Nerd Font nor CaskaydiaCove Nerd Font Mono could work.

**Comment by pseudocc** [comment]
@Eugeny Sorry, this is not a valid case actually. It is actually an issue about fc-cache, and the way chromium and gnome load the font are different.

I have a very outdated version of the nerd font at ~/.local/share/fonts/ (legacy) and a latest version at ~/.fonts/truetype/ (controlled by my dotfiles repo).
Chrome and Tabby loads the legacy one by default, and gnome desktop apps loads the latest one by default.
