### ISSUE TITLE
How to send commands to multiple windows at once

### ISSUE THREAD

**Issue by lsnme** [Eugeny/tabby#8323]
How to send commands to multiple windows at once

**Comment by RANJITHROSAN17** [comment]
To send commands to multiple windows at once, you can use a terminal multiplexer like tmux or screen. These tools allow you to create multiple terminal windows within a single session and send commands to all windows simultaneously.
For example, in tmux, you can create multiple windows with the new-window command and send commands to all windows with the send-keys command. Here's an example:
1. Start a new tmux session 

>tmux new-session

2. Create two new windows

>tmux new-window -n window1

>tmux new-window -n window2

3. Select both windows with tmux 

>tmux select-window -t 0 \; select-window -t 1

4. Send a command to both windows with

tmux send-keys "ls" Enter

This will send the ls command to both window1 and window2 simultaneously

**Comment by Eugeny** [comment]
See https://github.com/Eugeny/tabby/discussions/5259
