### ISSUE TITLE
Hide serial port connections

### ISSUE THREAD

**Issue by yarkovaleksei** [Eugeny/tabby#8337]
**Is your feature request related to a problem? Please describe.**
Every time I have to select an SSH connection, I have to scroll through a long list of serial connections I don't need.

**Describe the solution you'd like**
I'd like to be able to hide unwanted connections from the list.

**Describe alternatives you've considered**
I don't know how to do it now.

**Additional context**
![image](https://user-images.githubusercontent.com/6022892/235340055-066e0a8e-78ee-4bce-9e7c-3dd0d94f2be3.png)

**Comment by Eugeny** [comment]
Settings -> Profiles -> Advanced -> Show built-in profiles

**Comment by yarkovaleksei** [comment]
Thanks )) But in this case, everything is turned off, but I would like to leave the rest, just hide the serial ports. Is it really impossible to do without creating your own profiles?

**Comment by Eugeny** [comment]
Unfortunately not, you can either hide all builtin profiles or none. If you're not using the serial port functionality at all, you can disable the serial plugin in Settings -> Plugin.

**Comment by yarkovaleksei** [comment]
Thank you! This is exactly what I needed.
