### ISSUE TITLE
The size of the search box is abnormal

### ISSUE THREAD

**Issue by 839514831** [Eugeny/tabby#8371]
Version: 1.0.196
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

搜索框特别大，遮挡屏幕内容，影响正常使用

**Comment by 839514831** [comment]
![image](https://user-images.githubusercontent.com/52354170/236607724-a8189c2c-e0d9-4933-80bc-b493791c9386.png)

**Comment by ifndf** [comment]
any update?

**Comment by joxhehe** [comment]
有解决的办法吗？

**Comment by mickdewald** [comment]
I got the same issue.
I am not sure when it will happen. Usually, it is suddenly huge and there is no way to reverse it apart from restarting tabby.
<img width="1510" alt="Screenshot 2024-06-05 at 00 24 58" src="https://github.com/Eugeny/tabby/assets/278107/618c2e0b-2712-40ce-a630-d4a6f7ea72c1">
