### ISSUE TITLE
The title background color is abnormal

### ISSUE THREAD

**Issue by MartinLau7** [Eugeny/tabby#8373]
**Describe the problem**:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/5416852/236635591-0d1f48df-b7b9-4a3f-a9f7-400691d098a0.png">
Since the 1.0.196 (macOS) version, the wrong background color in the location of the screenshot marks resulted in the button not being visible. Before this version, it was a dark color and the button was very visible.
Whether this is intentional by the new version?

**Comment by Eugeny** [comment]
Which terminal color scheme are you using? As a workaround, you can go back to the old theme in Settings -> Window -> Theme

**Comment by MartinLau7** [comment]
> Which terminal color scheme are you using? As a workaround, you can go back to the old theme in Settings -> Window -> Theme

I'm currently using the ayu_light theme. Any other 'light' I try will affect the background of the Title. Versions up to 1.0.189 are not affected

**Comment by Eugeny** [comment]
Could you please verify on the nightly build? This is what is looks like for me: 
<img width="813" alt="image" src="https://github.com/Eugeny/tabby/assets/161476/57ee4461-b537-4157-a288-d573ee45af00">

**Comment by MartinLau7** [comment]
> Could you please verify on the nightly build? This is what is looks like for me: <img alt="image" width="813" src="https://user-images.githubusercontent.com/161476/238471535-57ee4461-b537-4157-a288-d573ee45af00.png">

@Eugeny , I'm not familiar with source builds, how do I get the dmg file for each night's build?

**Comment by Eugeny** [comment]
You can always grab a nightly build from https://nightly.link/Eugeny/tabby/workflows/build/master (the link from readme)

**Comment by MartinLau7** [comment]
<img width="916" alt="螢幕截圖 2023-05-17 00 42 09" src="https://github.com/Eugeny/tabby/assets/5416852/928d9e10-270a-4f86-9d73-45074a46ff61">

I tried installing the nightly build (**macOS-arm64-1.0.198**), and things didn't get any better. The font color was still inconspicuous. 
The test topics include: 
- **ayu_light**
- **3024 Day**
- **AtomOneLight**

**Comment by MartinLau7** [comment]
@Eugeny I found the problem by reinstalling Tabby, and once I changed the Windows theme and rebooted, the background color and text color of the title bar became inconspicuous.
<img width="410" alt="image" src="https://github.com/Eugeny/tabby/assets/5416852/fcaf1aea-8725-431c-ae91-8dcd26bcb3c4">
