### ISSUE TITLE
Huge box for the `Search`

### ISSUE THREAD

**Issue by jason19970210-senao** [Eugeny/tabby#8402]
Version: 1.0.194
Platform: Linux x64 6.2.0-20-generic
Plugins: none
Frontend: xterm-webgl

OS: Ubuntu 23.04
Gnome 44.0

As mentioned in title, how big is that !!?

![](https://i.imgur.com/bXpaGXw.png)

**Comment by Eugeny** [comment]
Already fixed in the latest release
