### ISSUE TITLE
Connect to esxi and report an error

### ISSUE THREAD

**Issue by lutinglt** [Eugeny/tabby#8429]
X  Timed out while waiting for handshake

All the encryption methods in the connection configuration are turned on, and other setting options are also tried, and this error is prompted

**Comment by Olgerd96** [comment]
Win11: password or ssh-key autentification to esxi fails

**Comment by Olgerd96** [comment]
Try to downshift to some old protocol: FAIL
enabled diffie-hellman-group-exchange-sha256:
- Timeout during handshake
- 
disable diffie-hellman-group-exchange-sha256:
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  nY77Bh7TfiBGGPE4boAxYSFCxWQcrjkbhIYi+ggqKZ0= 
 SSH  Loading private key: file://C:\Users\olgerd\.ssh\id_ed25519
 X  All configured authentication methods failed
 ---
 open new tab with  Clink - and succesefully connect using: SSH command
 windows command line - SSH: works
 git bash - ssh: works
powershell - ssh: works

**Comment by undefinedid** [comment]
As a workaround with Vmware ESXi (v8 here), I found those settings work with Tabby:

```
vi /etc/ssh/sshd_config

- PasswordAuthentication no
+ PasswordAuthentication yes
+ ChallengeResponseAuthentication yes

/etc/init.d/SSH restart
```

**Comment by csphoenix1** [comment]
Hi, same problem :(

**Comment by tarocjsu** [comment]
https://github.com/Eugeny/tabby/issues/6233#issuecomment-1509722236

Problem solved temporary
