### ISSUE TITLE
Error: Permission denied, cannot open /dev/ttyUSB0

### ISSUE THREAD

**Issue by Namedqianli** [Eugeny/tabby#8511]
**Describe the problem**:
[A clear and concise description of what the bug is.]
OS: Ubuntu 22.04
Tabby: 1.0.197
I want to open serial port in tabby, but i got this error
```
Error: Permission denied, cannot open /dev/ttyUSB0
```
How can i use root to open serial port
**To Reproduce**:
[Steps to reproduce the behavior]
Profiles -> Serial

**Comment by kmanwar89** [comment]
Hello,

I see this was closed as completed, but there's no resolution posted? I'm encountering this exact error on Linux Mint (Ubuntu derivative) while trying to connect devUSB0 to a Cisco Layer 3 switch.

Could you please share a solution as to how you resolved this bug?

**Comment by KameiKojirou** [comment]
In Ubuntu you need to add the following groups to your user. Then reboot.

`sudo usermod -a -G tty yourusername
sudo usermod -a -G dialout yourusername`
