### ISSUE TITLE
The settings button doesn't respond sometimes

### ISSUE THREAD

**Issue by shankru5** [Eugeny/tabby#8534]
Version: 1.0.197
Platform: Windows x64 10.0.22000
Plugins: save-output
Frontend: xterm-webgl

I have noticed that the settings button stops responding or doesn't open the settings tab as expected sometimes when I click on the gear icon on the top right. I am not exactly sure I have found a way to reproduce the issue consistently. But it does happen from time to time.

**Comment by steberk** [comment]
I found a way to reproduce (maybe there is other one too)
- Start Tabby
- Open a SSH connection
- Split to the bottom (you can drag and drop other connection too)
- Save the layout from the tab context menu 
- Now the settings tab cannot be open (gear icon, setting menu from the main page, hotkey...)

As I remember when I played with multiple panes in multiple tabs this problem appeared without saving layout. But I could not reproduce this time...

**Comment by shankru5** [comment]
> I found a way to reproduce (maybe there is other one too)
> 
> * Start Tabby
> * Open a SSH connection
> * Split to the bottom (you can drag and drop other connection too)
> * Save the layout from the tab context menu
> * Now the settings tab cannot be open (gear icon, setting menu from the main page, hotkey...)
> 
> As I remember when I played with multiple panes in multiple tabs this problem appeared without saving layout. But I could not reproduce this time...

You are right. I followed your steps and it is reproducible now for me as well.

**Comment by steberk** [comment]
Hello,

I've attached the log. The first exceptions were raised when I saved the
layout. The last exception was raised when I pressed the settings button.

Eugene ***@***.***> ezt írta (időpont: 2023. júl. 4., K,
15:28):
