### ISSUE TITLE
Please add extra padding for space for close and options button on tabs

### ISSUE THREAD

**Issue by saudiqbal** [Eugeny/tabby#8542]
There is no space if dynamic width is selected for tabs. Please add an extra space for close and options button.

![Peek 2023-06-07 22-38](https://github.com/Eugeny/tabby/assets/6971514/d1ee7603-cec5-4188-a3b3-03aa313ba18b)

**Comment by Eugeny** [comment]
Both of them can be disabled in Settings -> Window if you'd prefer to use that space for the tab title.
