### ISSUE TITLE
Support command line calling

### ISSUE THREAD

**Issue by WindowsRegedit** [Eugeny/tabby#8556]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when tabby is not supporting command line calling.I have a program which need a Modern-UI SSH Client, but using terminal and putty is a little bit old-fashioned.I want to be able to call tabby through a command.

**Describe the solution you'd like**
Make tabby able to be calling from a command.Like putty: putty root@1.1.1.1

**Describe alternatives you've considered**
Add support of overriding custom ssh client(like putty).

**Additional context**
maybe we can just 'copy' the putty's command line usage :=)

**Comment by ashneilson** [comment]
Hello @WindowsRegedit 👋 

If PR https://github.com/Eugeny/tabby/pull/9383 is accepted and merged, that should provide the functionality you are looking for.
