### ISSUE TITLE
No GUI component for hiding custom profiles

### ISSUE THREAD

**Issue by NJT145** [Eugeny/tabby#8588]
**Describe the problem**:
1. The problem is the lack of UI component for editing the hidden custom profiles, added with #7727 . There should be some area at advenced settings for that.
2. Any way to hide buit-in profiles at new profile creator list?

**To Reproduce**:
I opened my fresh install of Tabby, copied two built-in profiles, disabled "Show built-in profiles in selector". And I cannot hide some of my custom profiles by usig GUI. And I cannot hide built-in profiles on profile templates list at Profiles -> "New Profile" section.

**Comment by Eugeny** [comment]
Individual built-in profiles can be hidden in the nightly build

**Comment by NJT145** [comment]
Okay, and there is a GUI way to do that at this build, right? And what about hiding built-in profiles at "New Profile" section, or anyway to mark them "built-in" so that it wont be mixed with copies of them ?

**Comment by NJT145** [comment]
I am actually using version 1.0.197

**Comment by Eugeny** [comment]
Yes, the option is in the "..." overflow menu of each profile. 

They weren't hidden in the "new profile" selector - fixed it now

**Comment by Eugeny** [comment]
(you can install a nightly build like a normal build, through the link in the README, a stable build will be released at some point, there's no fixed release schedule)
