### ISSUE TITLE
Cannot connect to Ubuntu via Win11

### ISSUE THREAD

**Issue by CHENBIN99** [Eugeny/tabby#8595]
Thanks for your great work! 

**Describe the problem**:
I try to connect to my remote host via ssh on local win11, but I get the error of **All configured authentication methods failed on tabby**, I have confirmed that my account password is correct, and the same account password can be done through the terminal of win11.

![image](https://github.com/Eugeny/tabby/assets/30487978/52e1abb0-28b7-4643-92b9-b2d11e7e71b3)
![image](https://github.com/Eugeny/tabby/assets/30487978/45915bcb-61df-46ea-96c8-28dd77b08164)

**Environment**:
Host: Win11 22H2
Remote: Ubuntu 22.04.2 LTS
Tabby: 1.0.197

This problem is bugging me and I hope I can find a way to fix it, thanks☺️

**Comment by Cengls** [comment]
我也遇到了同样的问题，幸运的是我解决了！或许尝试在ubuntu的配置文件中允许root账号开启ssh登陆

**Comment by CHENBIN99** [comment]
I have already solved this problem. I found that this problem will occur if you directly enter ssh user@host_ip here. 
![image](https://github.com/Eugeny/tabby/assets/30487978/e6512d54-8586-4a50-ac8d-eca9a93e7855)

Maybe there is a problem with the default configuration template. You need to enter the settings to manually add this host and it will be fine.

Thanks
