### ISSUE TITLE
Highlight tab title when there is output

### ISSUE THREAD

**Issue by TC-yWu** [Eugeny/tabby#8598]
**Is your feature request related to a problem? Please describe.**
It's often I have multi tabs for multi ssh connections to server, and  I'm always frustrated when I try to find out in which tab the log is printed out?

**Describe the solution you'd like**
Highlight the tab title in which the log is printed out.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Eugeny** [comment]
Tabs with new output have a small highlight at the bottom

<img width="468" alt="image" src="https://github.com/Eugeny/tabby/assets/161476/7f52ed33-c1bd-4830-bfef-a5c7ec582b90">
