### ISSUE TITLE
Where is the entrance to choose the public key for ssh login

### ISSUE THREAD

**Issue by feida2021** [Eugeny/tabby#8631]
Where is the entrance to choose the public key for ssh login ? I can't find where it is. Why does the software only use the private key for ssh login? Securecrt and xshell, both softwares use public keys for ssh login. Is the author of this software mistaken? This software makes me confused.
![1](https://github.com/Eugeny/tabby/assets/77482360/f30800f3-140b-41b3-a55a-4280a07b2f7d)

**Comment by Eugeny** [comment]
It's because it's the _private key_ that is used for signatures in _public key SSH authentication_
