### ISSUE TITLE
Windows - add 'Minimize to SysTray' option

### ISSUE THREAD

**Issue by SomwareHR** [Eugeny/tabby#8657]
Great tool, thanks!

**Is your feature request related to a problem? Please describe.**
No problem. Just increased usability for some type of users.

**Describe the solution you'd like**
"Minimize and/or close to SysTray" on Windows.

**Describe alternatives you've considered**
Windows Terminal

**Additional context**
n/a

BR

**Comment by Eugeny** [comment]
It already exists (the "toggle window" hotkey)

**Comment by ethanpil** [comment]
But need an option to prevent from closing window when click the X in the corner. Besides the hotkey its a "Minimize to Tray" option even for the close button. Here is a nice discussion of various ways to implement in Electron: https://stackoverflow.com/questions/37828758/electron-js-how-to-minimize-close-window-to-system-tray-and-restore-window-back
