### ISSUE TITLE
Font has too much jaggedness when using light theme

### ISSUE THREAD

**Issue by WanliZhong** [Eugeny/tabby#8659]
**Describe the problem**:

Terminal.app will smoothen the font then make it look like normal. 
![image](https://github.com/Eugeny/tabby/assets/49567307/d7ca394a-8d2f-4ca8-b11b-fbdf129abb4f)

But Tabby.app will not smoothen the font in light theme. I can't use any light theme in Tabby. Does no one like light themes?

![image](https://github.com/Eugeny/tabby/assets/49567307/832d701f-5f27-49f4-9847-4bac12ededde)

**To Reproduce**:
macOS, 3440x1440, light theme, any font or just default font.

**Comment by sjerdmann** [comment]
Hi,
I also have this problem on Windows 11. However, it seems it was introduced in a recent version of Tabby, as it doesn't happen with the `1.0.183` for instance. I don't know which exact version introduced the bug, but I can search if it is useful.

**Comment by Aimerny** [comment]
Same issue here on MacOS 13.5.1

**Comment by nyatorch** [comment]
You can try to change front end from WebGL to canvas
in settings -> Terminal -> Rendering -> front end
then restart tabby, For me, It solved problem.

**Comment by WanliZhong** [comment]
@nyatorch Thanks! It works for me.

**Comment by NJNataren** [comment]
@nyatorch thanks, that fixed it for me, I was having the same issue on Ubuntu 22.04.4!

**Comment by CangHaiQingYue** [comment]
@nyatorch thanks!

**Comment by Le0v1n** [comment]
@nyatorch And you, my friend, are a true hero.

**Comment by 213221486** [comment]
Same issue in Windows 11 VScode.

**Comment by dscham** [comment]
MacOS 15.3.1; Hack Nerd Font 14pt; Very weird oversharpened look in light themes ☹
