### ISSUE TITLE
How to restore tabs on another computer? 

### ISSUE THREAD

**Issue by gitgt** [Eugeny/tabby#8662]
I used Tabby in Windows as portable.
Now I transfered config.yaml to Linux Mint, I see my connections, but tabs session is not restored. 
Where is that written? Did not find it in issues. No luck with random copying of files or folders from Data.

Thank you for Tabby and for help here. 
Maybe it would be good to add Question in addition to Bug and Feature categories for issues here.

**Comment by Eugeny** [comment]
Tabs are saved into LocalStorage - try copying the entire Tabby folder from %APPDATA% to ~/.config - but it's not guaranteed to work between platforms.

**Comment by gitgt** [comment]
It works, thanks.
