### ISSUE TITLE
Cannot use CTRL+V to paste into ssh session.

### ISSUE THREAD

**Issue by muddenhed** [Eugeny/tabby#8668]
Hi

Seems that CTRL-V is not working when trying to paste into an ssh session, but right click with mouse works.

CTRL+C to copy seems to work just fine.

Version: 1.0.197
Platform: Windows x64 10.0.22621
Plugins: SSH
Frontend: xterm-webgl

![ssh_tabby](https://github.com/Eugeny/tabby/assets/8309791/41a9ffa8-a64a-406f-ad42-6cc2b32349d6)

**Comment by Eugeny** [comment]
The default paste shortcut on Windows is Ctrl-Shift-V, but you can change it in Settings -> Hotkeys
