### ISSUE TITLE
Feature request: border around active pane

### ISSUE THREAD

**Issue by et304383** [Eugeny/tabby#8687]
**Is your feature request related to a problem? Please describe.**
I find it difficult to know which pane is active, other than the colours being slightly more bold.

**Describe the solution you'd like**
It would be nice if the active pane could be coloured with a box or something so we know exactly where we're typing when working with multiple panes.

**Describe alternatives you've considered**
Custom CSS, but I don't know where to begin to do this.

**Comment by Eugeny** [comment]
This is relatively easy with custom CSS:

```css
terminaltab.focused {
    border: 3px solid red;
}
```

**Comment by et304383** [comment]
@Eugeny thanks!
