### ISSUE TITLE
Support for editing built-in

### ISSUE THREAD

**Issue by heyline** [Eugeny/tabby#8738]
**Is your feature request related to a problem? Please describe.**

As shown in the picture, there are three `WSL`. I want to delete the redundant options, and I don’t want git bash to appear here. It would be great if we can support editing

![图片](https://github.com/Eugeny/tabby/assets/51351113/9b5ecb28-5656-4d89-8fa8-dee539cc3da5)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment]
In the nightly build, you can hide the options you don't need via the "..." menu.

**Comment by heyline** [comment]
Thank you for your quick response, this is what I was looking for, looking forward to an early release
