### ISSUE TITLE
Hard to locate tab when multiple ones are open using same profile

### ISSUE THREAD

**Issue by nsrosenqvist** [Eugeny/tabby#8767]
**Is your feature request related to a problem? Please describe.**
It's really hard to tell what tab is running what process when having multiple ones open under the same profile.
![Screenshot 2023-07-31 at 11 36 14](https://github.com/Eugeny/tabby/assets/1303475/47479e76-6f80-4b76-8718-b8e1d93fe68e)

**Describe the solution you'd like**
An option to show the working directory or running process instead of the profile name. To make it clear what profile is used one could also support choosing an icon for each profile so that is shown on the tab as well.

**Describe alternatives you've considered**
No other solution comes to mind.

**Comment by Eugeny** [comment]
Tabby does support shells changing the window title - you just need to set it up: https://github.com/olets/zsh-window-title

**Comment by nsrosenqvist** [comment]
@Eugeny oh wow, sorry, I had missed that. Now it works great! Thanks!
