### ISSUE TITLE
Restore all ssh sessions on all tabs on tabby launch

### ISSUE THREAD

**Issue by williamblair333** [Eugeny/tabby#8768]
I'm not certain if a way to do this already exists.  Apologies if so.  

I have over 20 tabs connecting via ssh keys to servers.  How can I have them automatically connect when Tabby launches?

**Comment by Clem-Fern** [comment]
Hi, by ticking `Remember` on the keyphrase popup, it should reconnect without asking you anything the next time.

**Comment by williamblair333** [comment]
I enabled `Restore terminal tabs on app start` restarted Tabby, ssh'ed into my multiple terminal sessions and have yet to see any popups saying `Remember` or anything else.

**Comment by Clem-Fern** [comment]
Don't you have this prompt on connection ?
![image](https://github.com/Eugeny/tabby/assets/20025949/ba6b65ab-de8e-4a99-8e5d-774f9d467bd6)

**Comment by williamblair333** [comment]
I don't know where that setting is.  I've never seen it pop up. 

After some digging, it turns out what I really want is a way to launch all profiles under a specific group automatically.  I saw this:  https://github.com/Eugeny/tabby/issues/6650
