### ISSUE TITLE
When modifying the font size, the text is being obscured.

### ISSUE THREAD

**Issue by yuluod** [Eugeny/tabby#8777]
**Describe the problem**:
When modifying the font size, the text is being obscured.

**To Reproduce**:
![CleanShot 2023-08-03 at 11 35 15@2x](https://github.com/Eugeny/tabby/assets/9930784/485e71a5-fda5-4fcf-957b-24470dff14e0)

**Comment by Eugeny** [comment]
Duplicate of #8753
