### ISSUE TITLE
Font size field cut off

### ISSUE THREAD

**Issue by thdoan** [Eugeny/tabby#8782]
**Describe the problem**:
In Windows 10, the font size field is cut off:

![image](https://github.com/Eugeny/tabby/assets/4110567/19e8db97-0c25-4f39-b7dd-3cfec944d1bc)

**To Reproduce**:
[Steps to reproduce the behavior]
1. Open Settings / Appearance in Windows 10

**Comment by Eugeny** [comment]
Fixed in the nightly
