### ISSUE TITLE
The output text on the interface will be cleared after ssh reconnecting, version 1.0.197

### ISSUE THREAD

**Issue by Saigut** [Eugeny/tabby#8812]
OS: macos monterey m2
Tabby version: 1.0.197

**Describe the problem**:
The output text on the interface will be cleared after ssh reconnecting, version 1.0.197

**To Reproduce**:
Reconnect  ssh

**Comment by Clem-Fern** [comment]
Hi, you should be able to avoid this behavior by disabling the option `Clear terminal after connection` in `Settings > SSH`

**Comment by Saigut** [comment]
> Hi, you should be able to avoid this behavior by disabling the option `Clear terminal after connection` in `Settings > SSH`

It works, thank you!
