### ISSUE TITLE
cursor move with left click inline

### ISSUE THREAD

**Issue by aevans0001** [Eugeny/tabby#8822]
**Is your feature request related to a problem? Please describe.**
When in TAbby i would like the ability to click in the terminal current line and have the cursor move with it. 
**Describe the solution you'd like**
i want cursor to move inline as i left click on command line

**Comment by Eugeny** [comment]
Not possible https://superuser.com/questions/1081310/how-to-move-the-commandline-cursor-on-bash-using-the-mouse

**Comment by savoygrizzly** [comment]
Actually, you can (on Mac at least). 
On Mac you can hold down Opt and click where you want your cursor set on your current line.
