### ISSUE TITLE
bug: serial port display garbled code

### ISSUE THREAD

**Issue by FangXS-github** [Eugeny/tabby#8855]
Opening the serial port with tabby, when I copy a command that is longer than one line, the command is garbled when I press the space bar or right arrow key.
I've tried shrinking the window and that doesn't fix it either.
When the window is larger, copying longer commands overwrites the command on the current line instead of displaying it on a new line.
![image](https://github.com/Eugeny/tabby/assets/70793339/93e5eb28-84ec-4b02-984b-e7bdc834d071)
when I press the space bar :
![image](https://github.com/Eugeny/tabby/assets/70793339/e368f15d-426c-4e50-8347-ac436116a32d)
when I paste 3times "When the window is larger, copying longer commands overwrites the command on the current line instead of displaying it on a new line." in a larger window:

**Comment by shun-int** [comment]
![image](https://github.com/Eugeny/tabby/assets/70793339/93a4ec25-a1ec-40e4-b0b7-426c779fce8a)
and press a key:
![image](https://github.com/Eugeny/tabby/assets/70793339/6ce025d8-5b98-4a24-8b10-c719cc6438a8)

**Comment by shun-int** [comment]
Version : V1.0.198-nightly.0
env : Win10 22H2

**Comment by shun-int** [comment]
No，I recommend using SSH.



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 3, 2023 20:40 PM
To: ***@***.***&gt;;
Cc: "Fang ***@***.******@***.***&gt;;
Subject: Re: [Eugeny/tabby] bug: serial port display garbled code (Issue#8855)




 
I encountered the same problem, has this bug been resolved?
