### ISSUE TITLE
Changing Color scheme seems to deactivate up and down buttons

### ISSUE THREAD

**Issue by gitmatters** [Eugeny/tabby#8876]
Version: 1.0.198
Platform: Windows x64 10.0.19045
Plugins: sftp-tab
Frontend: xterm-webgl

Somehow my up and down buttons are deactivated in tabby, even though I never actually deactivated them. 
After I updated Tabby to the latest version, the up and down button worked again as expected, but with the installation came the default light scheme. 
So I than changed the color scheme ( I tried dozens ) and it seems like by overwriting the default scheme the up and down buttons cannot be used anymore. Even switiching back to the default light scheme, than doesnt reactive the functionality. 
So the only way I found is reinstallation, which doesnt help, since I cannot work on the light scheme. 

Anyone expierenced something similar? Or is this even reproducable?

**Comment by Eugeny** [comment]
Fixed in 1.0.200
