### ISSUE TITLE
The new terminal will be automatically created

### ISSUE THREAD

**Issue by Ericwln** [Eugeny/tabby#8879]
After opening Tabby, move the mouse to the new terminal + sign, but do not click, the new terminal will be automatically created. This is a serious bug

1.0.198 
ubuntu 20.04

**Comment by Clem-Fern** [comment]
Hi, according to the release notes, the option `Auto-open a terminal on app start` in `Settings > Terminal > Startup` has been enabled by default. Could you try to disable it ?

**Comment by Eugeny** [comment]
It should open immediately though, not on hover.
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Ericwln** [comment]
https://github.com/Eugeny/tabby/assets/37823382/1bc9495e-fc76-44e8-8f94-63f268273ed4

**Comment by Ericwln** [comment]
The mouse hovers over the + sign but does not click down

**Comment by Ericwln** [comment]
disable all？

**Comment by Ericwln** [comment]
disable all。does it have no effect or is it created automatically

**Comment by Ericwln** [comment]
hello ？> Can you try it again with the third-party plugins disable

**Comment by Ericwln** [comment]
> Can you try it again with the third-party plugins disabled?
hello
