### ISSUE TITLE
The window stayed black after opening the new version

### ISSUE THREAD

**Issue by hunterlodge** [Eugeny/tabby#8885]
Version: 1.0.198
Platform: Windows x64

After I upgrade tabby to version 1.0.198 and opened it, it could start, but after displaying the logo, I could only see a black window.
Now I have reinstalled it with the previous version, everything comes back.

**Comment by Foolian2** [comment]
I have the same problem what version did you reinstall?

**Comment by Eugeny** [comment]
Duplicate of #8868
