### ISSUE TITLE
Can't change Color schemes

### ISSUE THREAD

**Issue by belieberly** [Eugeny/tabby#8889]
1.  only have three color schemes to choose : From system, Always dark, Always light
2.  nothing happens after clicking scheme button
3. can not change to other settings page after clicking on Color schemes

using 1.0.199 version

**Comment by runkecheng** [comment]
same issue

**Comment by Eugeny** [comment]
Fixed in 1.0.200

**Comment by jdwebsphere** [comment]
using 1.0.202-nightly. It seems it is still not fixed
