### ISSUE TITLE
Clicking on the color scheme will get stuck

### ISSUE THREAD

**Issue by YogurtLY** [Eugeny/tabby#8891]
Version: 1.0.199
Platform: Windows x64 10.0.22621
Plugins: workspace-manager, title-control, sftp-tab, serial-timestamp, search-in-browser, quick-restart, quick-cmds, love-shell, docker, clippy
Frontend: xterm

![image](https://github.com/Eugeny/tabby/assets/74954367/336d56d6-bcd4-447e-823e-ba345b215626)
![image](https://github.com/Eugeny/tabby/assets/74954367/e0da7766-97b1-436d-9877-ab987043bf9e)

**Comment by smartlin** [comment]
Macos has the same problem

**Comment by YogurtLY** [comment]
我已收到您的邮件,我会尽快恢复的!祝您身体健康，工作愉快！

**Comment by Eugeny** [comment]
Fixed in 1.0.200
