### ISSUE TITLE
Win10/Win11 client , session group sync issue

### ISSUE THREAD

**Issue by Razcall** [Eugeny/tabby#8909]
**Describe the problem**:
Group id / name is swapped between synced my wind10 client and win11 client

**To Reproduce**:
be on 1.0.198
1. use a win 10 client (work) and a win 11 client (home)
2. Set all your session and group em carefully (over 100) from the wind10 client
3. Switch to your win11 client
4. All group names have been swapped with its matching uuid...
5. Swap all uuid with group names  on the win 11 client.
6. Switch back to your w10 client to findout all your client ungrouped...
7. lay down on floor
8. roll over
9. cry in silence because you really want to love this soft 😮‍💨 

**remark**
On win10 client conf file group are mentionned with name  
on win11 client conf file groups are mentionned with uuid (defined later in conf file)

**Comment by Eugeny** [comment]
Sorry to hear that... This just means that you're using two different versions on both sides. We've only recently made a change to the config format that allows changing profile settings on the entire group, and that required giving groups UUIDs. If you still have a config copy where you see UUIDs instead groups, that's the good one, just make sure you're on v1.0.200 on both sides

**Comment by Razcall** [comment]
I suspected that !
I will test and update this right away

**Comment by Razcall** [comment]
I confirm that sync issue is solved once updated to 1.0.200 issue is no longer occuring between both client
If I missed a warning in release note on this risk please accept my sincere apology.
If not maybe add a warning  in release note this is a really frustrating which might infuriate people like me that already adopted your awesome client for big files, and consider issue solved.

For any user facing this :
I used obsidian templater plugin to clean my file and  replace all group name with uuid which you can recover from your config file and it saved my day.

**Comment by Eugeny** [comment]
That's a great idea - added the warning!
