### ISSUE TITLE
Funny but annoying Backspace issue in Profiles & connections

### ISSUE THREAD

**Issue by konstantin83** [Eugeny/tabby#8915]
Hey, Eugeny. 
My Tabby version is 1.0.196 (the last actual version from apt repository).
In Profile & connection popup you can start typing a name of the profile to quickly connect to it. But if you made a mistake and want to delete everything, you hold the Backspace key expecting it to stop at the end of the line, when all characters are deleted. But it's not.
If you press or hold Backspace key It doesn't stop and instead somehow pastes a name of a recent profile and continues to delete it, until reaches the last characted, and then it happens again infinitely.

Here's the video with keypresses indicator at the bottom for clearity.

https://github.com/Eugeny/tabby/assets/13274062/1f65fa70-79d3-4663-8ebe-8cedfa56efcd

**Comment by Clem-Fern** [comment]
Hey, I agree. It can be quite annoying. It is cause by the edit feature which insert the quick connect string of the selected profile when Backspace key is pressed. 

I think it could be a great idea to prevent entering edit as long as the Backspace key is pressed.
I will submit a PR about this in the next few days.

**Comment by konstantin83** [comment]
@Clem-Fern Thanks for the reply. Have you already submitted a PR about this issue?
Can I somehow track such changes this to know if they are in a new version?

**Comment by Clem-Fern** [comment]
Hi @konstantin83, 
Just opened PR about this, I didn't get the time to do it before sorry.

You can watch the project to be aware of a new release:
![image](https://github.com/Eugeny/tabby/assets/20025949/f4eca723-5e62-43cf-94c4-d1969b60d412)
Nightly build will also contain this fix once PR merged, you can used it in wait of a the next release.
