### ISSUE TITLE
Shortcut for hiding tabs panel at the left

### ISSUE THREAD

**Issue by konstantin83** [Eugeny/tabby#8916]
Hey, Eugeny. Thanks again for this piece of art!
I use Tabby for a couple of years now, and always use left tabs placement. It's much more readable for me then classical tabs placement at the top.

And when I sometimes make Tabby window narrow this left tabs panel may take a lot of window space. And I am searching for a shortcut to toggle this pannel visibility. So I could hide it when it's not needed and show when it's needed again.

Can you please make this feature?

![image](https://github.com/Eugeny/tabby/assets/13274062/2a70fd70-8eef-404f-94c1-2cb4a4f2fad6)

## Funding this issue
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We only receive your pledge once the issue is resolved & you've verified it.

<a href="https://polar.sh/Eugeny/tabby/issues/8916">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/Eugeny/tabby/issues/8916/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/Eugeny/tabby/issues/8916/pledge.svg">
</picture>
</a>

**Comment by konstantin83** [comment]
Hey, @Eugeny. Can you please tell me if this enhancement could possibly be implemented in future, and if yes then maybe you could define when (plus/minus)? Or maybe there's already a way to hide this panel by a shortcut or somewhere in the settings?

**Comment by Eugeny** [comment]
Hi @kostantin unfortunately I have very little time to work on this project as I have a day job. So if you want to encourage contributors to work on this issue, consider pledging on polar.sh and someone might pick this up.

Alternatively you could build a plugin to do this (toggle a CSS style on a hotkey press) - check out the HACKING.md file for an introduction

**Comment by konstantin83** [comment]
@Eugeny thank you! Ok! )
