### ISSUE TITLE
Always print “SSH  Host key fingerprint:”

### ISSUE THREAD

**Issue by panhongyin** [Eugeny/tabby#8934]
When I use ssh to connect to my server, logging in with the key is normal, but logging in with the password will prompt the following message every once in a while:
"
SSH  Host key fingerprint:
SSH   ssh-rsa  JaIr1C364nDL2Lv+UTT7ehpfvMlos76z3Hc2EZLVhik=
"

Version: 1.0.197
Platform: Windows 11
Frontend: xterm-webgl

**Comment by panhongyin** [comment]
@Eugeny  this is a bug in "tabby-ssh/src/session/ssh.ts":
![image](https://github.com/Eugeny/tabby/assets/23182057/08f4ac36-edf0-4832-954c-8ef82d0232f4)

Should be:
![image](https://github.com/Eugeny/tabby/assets/23182057/e84fb3b5-c82b-4772-9034-68387dc58f2b)

**Comment by cfs4819** [comment]
> @Eugeny this is a bug in "tabby-ssh/src/session/ssh.ts": ![image](https://private-user-images.githubusercontent.com/23182057/266191710-08f4ac36-edf0-4832-954c-8ef82d0232f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDY0OTMsIm5iZiI6MTcxMDUwNjE5MywicGF0aCI6Ii8yMzE4MjA1Ny8yNjYxOTE3MTAtMDhmNGFjMzYtZWRmMC00ODMyLTk1NGMtOGVmODJkMDIzMmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEyMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjg1OTM1MTA4Mzc2MjM3ZWM5OGJhZjgwMjc4MTJhNzZjNDY5MWQ3YTExMDk0YWVmNzJiOTk2MTk5YTc3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5sNot4hE_9AThcT-eFDQamczZcxK2MxRHpKSLdMihE)
> 
> Should be: ![image](https://private-user-images.githubusercontent.com/23182057/266191938-e84fb3b5-c82b-4772-9034-68387dc58f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDY0OTMsIm5iZiI6MTcxMDUwNjE5MywicGF0aCI6Ii8yMzE4MjA1Ny8yNjYxOTE5MzgtZTg0ZmIzYjUtYzgyYi00NzcyLTkwMzQtNjgzODdkYzU4ZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEyMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NTQzYjU0MDg0ODM4ZWVlMjY5YTNhNDkzZjY1Zjk0ZmRiYjA0MDc3MDM2YTdkYzlmMzY5ODAzZDNiNzMyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MV1CB-9wE3RZdj8dT2_6Af9kIDjQw42D4i7p_ANcHjs)

Did you commit this change? I meet this bug again in Release Alpha 207.
