### ISSUE TITLE
Add build instructions to readme

### ISSUE THREAD

**Issue by sebdanielsson** [Eugeny/tabby#8941]
**Is your feature request related to a problem? Please describe.**
I would like to try to build tabby for a FreeBSD desktop. I'm not very familiar with building Electron apps so a short walkthrough for what to do after cloning the repo would be helpful.

**Describe the solution you'd like**
Add build instructions to the readme

**Comment by Eugeny** [comment]
Check out https://github.com/Eugeny/tabby/blob/master/HACKING.md
