### ISSUE TITLE
Broken on Debian testing

### ISSUE THREAD

**Issue by Glucy-2** [Eugeny/tabby#8967]
**Describe the problem**:
Interface broken on Debian testing (KDE, X11)
![screenshot](https://github.com/Eugeny/tabby/assets/53287753/837d84b6-1ced-4a3b-81be-07b76ad1e1ff)
And it is not possible to reinstall:
```
sudo apt install ./Downloads/tabby-1.0.200-linux-x64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'tabby-terminal' instead of './Downloads/tabby-1.0.200-linux-x64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tabby-terminal : Depends: gconf2 but it is not installable
                  Depends: gconf-service but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**To Reproduce**:
1. Install Debian 12 (bookworm)
2. Install tabby
3. Upgrade to Debian testing
4. See the bug

**Comment by Glucy-2** [comment]
solved after another system upgrade

**Comment by thobonho** [comment]
I've the same issue on a freshly installed Ubuntu 23.10

**Comment by andreasklostermaier** [comment]
Same error message here on a freshly installed Ubuntu 23.10. Tried all versions back to v1.0.194.

**Comment by notfixingit3** [comment]
gconf2 and gconf-service where removed in Ubuntu 23.10 and Debian 13
