### ISSUE TITLE
X11 Forwarding massivly damaged since version 1.0.198

### ISSUE THREAD

**Issue by gitmatters** [Eugeny/tabby#8968]
Version: 1.0.198 + 
Platform: Windows x64 10.0.19045
Plugins: sftp-tab
Frontend: xterm-webgl

Here is the thing the X11 forwarding in a ssh session under version 1.0.198 is slow and lagging (so slow that practically you cannot use GUI programs anymore, since the simpliest mouse clicks will take seconds to be proceeded). Whats even worse, that the version also affects alternative terminals like Putty (so they than have the exact same problem). Switching tabby back to version 1.0.197 resolves the issue, so it seems like the update made to xterm in 198 has caused the damage.   

The issue is reproducable, a colleague of mine verified (on Windows 11).

**Comment by gitmatters** [comment]
Could anybody reproduce? 
Its still an issue for me with v205...

**Comment by YaPaY** [comment]
weird, still no solution

**Comment by Eugeny** [comment]
Is likely fixed in 209+
