### ISSUE TITLE
invisible characters in short sequences

### ISSUE THREAD

**Issue by kylernocturnalnerd** [Eugeny/tabby#8995]
**Describe the problem**:
On a Fresh windows 10 install as well as fresh win11
Regardless the shell the characters show invisible sometimes.

This is not this issue: https://github.com/Eugeny/tabby/issues/510
Included transparency to show it's not the color issue
![image](https://github.com/Eugeny/tabby/assets/84939608/97177fad-39d8-4612-a028-2d9a62291532)

**To Reproduce**:
In a fresh windows installation, or an old one (not sure of the cause I don't experience this on an existing machine)
Install tabby version 1.0.200 and don't modify any settings.
Try typing into any shell various inputs and see what renders

**Comment by gfactor** [comment]
A similar issue occurs on Ubuntu 23.04, although I haven't been able to test with a fresh install.

Here's a video showing me typing numbers in Tabby. The numbers start invisible and become visible in batches.
[Screencast from 2023-09-19 11-22-50.webm](https://github.com/Eugeny/tabby/assets/1611947/70dd4731-2377-4d1e-9e04-79ce3fe96340)

**Comment by Clem-Fern** [comment]
Hey @kylernocturnalnerd,

As workaround, you can try to switch to `xterm (canvas)` in `Settings > Terminal > Rendering > Frontend`.
