### ISSUE TITLE
Unable to select custom default profile

### ISSUE THREAD

**Issue by matejkostros** [Eugeny/tabby#9022]
Version: 1.0.200
Platform: Windows x64 10.0.22621
Plugins: none
Frontend: xterm-webgl

Hello, I am running into an issue, where I cannot select the custom profiles as defaults. They do not appear in the menu. Tabby is a fresh installation. 

![image](https://github.com/Eugeny/tabby/assets/75608792/2c7f3c07-b544-4ac6-926d-12f950882e2d)

**Comment by Clem-Fern** [comment]
Hey @matejkostros ,

Thank's for reporting this. I will take a look at that and submit a PR soon.

**Comment by ThinkSalat** [comment]
Same here. I can only select from built in profiles.

**Comment by patleeman** [comment]
Just chiming in here with the same issue on Windows.

**Comment by Ranhiru** [comment]
I accidentally selected OS default and now I cannot switch back to my one

Also related: https://github.com/Eugeny/tabby/issues/9068

**Comment by Clem-Fern** [comment]
Thank you @Ranhiru for opening a PR about this issue! I didnt get the time to look at it sooner :/
