### ISSUE TITLE
Constantly opening Clink rather than 

### ISSUE THREAD

**Issue by c0fe** [Eugeny/tabby#9035]
The issue is that for some reason on version 200 of Tabby Clink keeps being opened up even though no plugins were installed, so basically when you launch Tabby you get this screen:

https://images2.imgbox.com/7f/c3/p0b1MXYm_o.png

Instead of the default welcome screen which it did open in the past versions:

https://images2.imgbox.com/95/f0/cgBgQx0s_o.png

The ideal version is that the welcome screen shows up instead of Clink.

**Comment by Clem-Fern** [comment]
Hi @c0fe ,

The option `Auto-open a terminal on app start` in `Settings > Terminal > Startup` has been enabled by default in the latest release. 

You should get the welcome screen back on tabby stratup if you disable it.
