### ISSUE TITLE
History is cleared after ssh disconnects and reconnects?

### ISSUE THREAD

**Issue by aSimpleSheep** [Eugeny/tabby#9036]
Why After ssh disconnects and reconnects, the previous interface record is cleared, but I cannot see the history record when I want to view it.

I remember in the previous version, the scene didn't seem to clean up.

**Comment by Eugeny** [comment]
This is configurable via the "Clear terminal after connection" setting in either your profile's setting or the global defaults in Settings -> Profiles -> Advanced.
