### ISSUE TITLE
font disaspear + open cmd at start

### ISSUE THREAD

**Issue by 13y87t** [Eugeny/tabby#9055]
hello, 

letters dissapear when I write.

+ how disable CMD tab when I open tabby ? 

thanks

Version: 1.0.200
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

**Comment by Clem-Fern** [comment]
Hey @13y87t ,

The option `Auto-open a terminal on app start` has been enabled by default in the latest release. You can disable it in in `Settings > Terminal > Startup`.


An issue is already open about charactets which are not displayed (#8884).
The current workaround is to Switch to `xterm (canvas)` in `Settings > Terminal > Rendering > Frontend`.

**Comment by 13y87t** [comment]
it's seems good, thanks you
