### ISSUE TITLE
Some letters in terminal are not seen in some cases.

### ISSUE THREAD

**Issue by rockyzhz** [Eugeny/tabby#9063]
**Describe the problem**:
In some cases, some letters in commandline are not seen.
For example, in a new powershell window, input a word : `exit`
the end 3 letters 'xit' are not seen.
![image](https://github.com/Eugeny/tabby/assets/3292710/e76c36ce-44a8-4a08-82ec-0f4eb52b8589)
I've tried to change the color scheme and theme, no changes.

In other cases, for example, ssh to a debian system. Still input `exit` in the commandline,
Some letters would disappear in some unknown rules.
![image](https://github.com/Eugeny/tabby/assets/3292710/789c59d8-5eab-44f5-a8f3-2565073aa6a0)
In upper case, I typed 'exitexi', until I typed another letter 't' (any other letter would result in the same situation.),
all the letters shown as the following. I don't know what's wrong with it.
The debian system is normal, because I've ssh to it many times with MobaXterm.
![image](https://github.com/Eugeny/tabby/assets/3292710/e4927389-645a-4552-8550-b915e590dfb7)

I use tabby portable version ([tabby-1.0.200-portable-x64.zip](https://github.com/Eugeny/tabby/releases/download/v1.0.200/tabby-1.0.200-portable-x64.zip)) on Win 11.
**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Clem-Fern** [comment]
Hi @rockyzhz 

Duplicated of #8884.
The current workaround is to switch to `xterm (canvas)` in `Settings > Terminal > Rendering > Frontend`.
