### ISSUE TITLE
can't use custom profile to change default profile on new tab

### ISSUE THREAD

**Issue by Leezed525** [Eugeny/tabby#9096]
**Describe the problem**:
[A clear and concise description of what the bug is.]

I want to set custom profile on new tab ,it has been worked before ,but now I can't change it ,and only built-in profile to choose 

![image](https://github.com/Eugeny/tabby/assets/53244472/cdd5278e-3154-4a34-b6b9-c71554fb13c1)

**Comment by Eugeny** [comment]
This is already fixed in the nightly build
