### ISSUE TITLE
Tabs not displayed when Mac is full screen

### ISSUE THREAD

**Issue by CubFE** [Eugeny/tabby#9106]
Version: 1.0.200
Platform: macOS arm64 23.0.0
Plugins: workspace-manager, love-shell, docker
Frontend: xterm-webgl

<img width="1035" alt="image" src="https://github.com/Eugeny/tabby/assets/143997481/1c989b7d-0df0-419e-b749-ce45f62397e4">
<img width="1115" alt="image" src="https://github.com/Eugeny/tabby/assets/143997481/ffd5785c-59e9-4cbc-b63d-3fe87e194af9">

**Comment by Eugeny** [comment]
Settings -> Window -> Tabs -> Show in fullscreen
