### ISSUE TITLE
Unable to synchronize configuration remotely code 401

### ISSUE THREAD

**Issue by good-ideal** [Eugeny/tabby#9120]
**Describe the problem**:
同步配置文件失败
version：1.0.201
![1697425426277](https://github.com/Eugeny/tabby/assets/41094378/10a3a60b-16fa-4e8f-b0f8-64e3f927795b)
![image](https://github.com/Eugeny/tabby/assets/41094378/2b5f6edc-d4e8-43a4-aaf2-80305742ab58)
![1697425698446](https://github.com/Eugeny/tabby/assets/41094378/777b4de3-d5e0-4b67-b606-b5c1e3f612b9)

**Comment by Eugeny** [comment]
app.tabby.sh has been discontinued

**Comment by EkkoG** [comment]
Does there have any alternative service? Or how to self-host the api service?

**Comment by Eugeny** [comment]
Yes, you can self-host it: https://github.com/Eugeny/tabby-web
