### ISSUE TITLE
Settings Sync / AxiosError: Request failed with status code 401

### ISSUE THREAD

**Issue by dennismetz** [Eugeny/tabby#9131]
**Describe the problem**:
Thanks for the great work/genius tool!
I just updated to version 1.0.201 (from 1.0.200) and noticed in the settings that the sync no longer works.

https://app.tabby.sh/ shows:
Error: Forbidden
Your client does not have permission to get URL / from this server.

**Comment by fr00sch** [comment]
I have the same Problewm with the same version.

**Comment by Eugeny** [comment]
app.tabby.sh has been discontinued

**Comment by Asthaknes** [comment]
It's a shame, it was really practical!
Is it going to be replaced by another system?
If not, what can we replace it with? 
Can we set up a server at home?

**Comment by Eugeny** [comment]
I've just ran out of money to host it, but you can set up your own instance: https://github.com/Eugeny/tabby-web

**Comment by asmpg** [comment]
@Eugeny  can you  make it  to be a paid service ?  i think many users will pay for it . 

You can do a survey to see how many people are willing to use this service, then decide to do it or not .

**Comment by EkkoG** [comment]
> I've just ran out of money to host it, but you can set up your own instance: https://github.com/Eugeny/tabby-web
> 
> > <img alt="" width="48" src="https://opengraph.githubassets.com/77fab4176d86a9335746eb6e512d0cadf37f31219af9caf2d6f53d4c05353e69/Eugeny/tabby-web"><img alt="" height="14" src="https://github.githubassets.com/favicons/favicon.svg"> GitHub**[GitHub - Eugeny/tabby-web: Tabby Web - an SSH/Telnet/Serial client in your browser.](https://github.com/Eugeny/tabby-web)**Tabby Web - an SSH/Telnet/Serial client in your browser. - GitHub - Eugeny/tabby-web: Tabby Web - an SSH/Telnet/Serial client in your browser.

Sorry to hear that, could you please split the API to independent project? It's too big if use as a sync API.

**Comment by TalhaMoazSarwar** [comment]
@Eugeny I left other platforms and moved to Tabby for its cloud sync functionality. Please bring it back as I don't want to use a third-party plugin.

**Comment by Lujnjie** [comment]
This is a very useful feature，You can allow users to set up their own synchronization services

**Comment by Clem-Fern** [comment]
Hey,

I published [rtabby-web-api](https://github.com/Clem-Fern/rtabby-web-api) some days ago. It was initially private as I made it to learn and train my self, so it's far from perfect...
With app.tabby.sh being discontinued, I through it could be useful to those who want to setup their own settings sync service without having the full Tabby web part.

However, you have to keep in mind that it is not an official tabby/Eugeny project.

**Comment by Eugeny** [comment]
@knightian write me an email to inbox@null.page from the same email that your account is linked to and I'll send you your config back.

**Comment by knightian** [comment]
> @knightian write me an email to [inbox@null.page](mailto:inbox@null.page) from the same email that your account is linked to and I'll send you your config back.

All good thanks, I found it was in the Roaming folder so I recovered it out of a device backup from just the other day. I think I will set up my own syncing server like you advise, thanks again.

**Comment by knightian** [comment]
@Eugeny do you know you can get a free 4 core 24GB RAM server on Oracle Cloud? https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm

**Comment by Eugeny** [comment]
I didn't know that, but unfortunately I don't have the time to be a devops in addition to being a developer - tabby-web used to run as an autoscaling container app on Google Cloud Run. Besides, Oracle's offering is capped at 1 MB/s traffic at the balancer.

**Comment by DeadZeta** [comment]
> I didn't know that, but unfortunately I don't have any time to be an unpaid devops in addition to being an unpaid developer - tabby-web used to run as an autoscaling container app on Google Cloud Run. Besides, Oracle's offering is capped at 1 MB/s traffic at the balancer.

Hello, what kind of traffic was there on api.tabby.sh?
What virtual machine configuration was used?

**Comment by Eugeny** [comment]
It was running as a container service on Google CloudRun, and consumed ~500 CPU-hours and 355 GB of outbound traffic plus 330 GB of outbound traffic from Google Cloud Storage per month.

**Comment by DeadZeta** [comment]
In theory, I can rent a virtual machine, run a docker container with tabby web or tabby api and make it public for all users who want to synchronize?
or will there be a problem with the security of data storage?

**Comment by EkkoG** [comment]
> Hey,
> 
> I published [rtabby-web-api](https://github.com/Clem-Fern/rtabby-web-api) some days ago. It was initially private as I made it to learn and train my self, so it's far from perfect... With app.tabby.sh being discontinued, I through it could be useful to those who want to setup their own settings sync service without having the full Tabby web part.
> 
> However, you have to keep in mind that it is not an official tabby/Eugeny project.
> 
> https://github.com/Clem-Fern/rtabby-web-api

I have added support for third-party login support https://github.com/Clem-Fern/rtabby-web-api/pull/10, and deployed to my own server, here is the address https://tabby-sync.imciel.com/

So, you guys can get a token by login at the home page and test the config sync now.

Welcome any suggestion.

**Comment by zzduci** [comment]
> @Eugeny I left other platforms and moved to Tabby for its cloud sync functionality. Please bring it back as I don't want to use a third-party plugin.

me too

**Comment by DeadZeta** [comment]
in theory, you can return synchronization, but for a nominal fee per month and payment in cryptocurrency

**Comment by winkelement** [comment]
@Eugeny I could offer hosting at full scale for one year either at Digital Ocean or Azure + take care of VM Maintenance if someone else takes care of the application itself.

**Comment by zzduci** [comment]
you can try Sync Config plugin ,it is very nice

**Comment by Eugeny** [comment]
I still have the backup, the last recovery request was only a month ago. Realistically I'll probably delete it on the anniversary of this ticket. If you want your data removed, it's no problem at all - just write me an email from the address you used for signing in.
