### ISSUE TITLE
The portable version configuration file cannot be placed in the software directory on the C drive

### ISSUE THREAD

**Issue by fszok** [Eugeny/tabby#9148]
How to put the configuration file into the software directory in the portable version? Only in this way can it be truly portable and convenient to put on a USB flash drive for portable use.

**Comment by mizzuri** [comment]
Just last week, the author closed a similar issue, #9114, with a reason, "not planned". I'd also like to know why it's not possible at the moment.

**Comment by lsdxfs** [comment]
i have the same question
do you solve it?
