### ISSUE TITLE
At "https://api.tabby.sh/" login with GitHub account then report "Error: Forbidden" 

### ISSUE THREAD

**Issue by kshq1996** [Eugeny/tabby#9152]
Request to sync setting：https://app.tabby.sh/

Error: Forbidden

Your client does not have permission to get URL / from this server.

<img width="1712" alt="image" src="https://github.com/Eugeny/tabby/assets/25955989/8aab2fe9-98b5-4862-9234-782e3ae8a550">

**Comment by qhlai** [comment]
#9131

**Comment by kshq1996** [comment]
When can the team fix this bug? I have reinstalled the system and urgently need to restore my server configuration to complete my work, please help!

**Comment by Eugeny** [comment]
Searching existing issues first would reveal that I had to discontinue app.tabby.sh due to prohibitive costs. Contact me at inbox@null.page from the email your account is linked to and I'll mail you your config back.

**Comment by kshq1996** [comment]
> Searching existing issues first would reveal that I had to discontinue app.tabby.sh due to prohibitive costs. Contact me at [inbox@null.page](mailto:inbox@null.page) from the email your account is linked to and I'll mail you your config back.

thanks I just send mail to [inbox@null.page](mailto:inbox@null.page)

**Comment by tarocjsu** [comment]
They already out of budget to support this feature....this feature EOL already....
