### ISSUE TITLE
Unable to install any plugin

### ISSUE THREAD

**Issue by matthiscock** [Eugeny/tabby#9157]
**Describe the problem**:
On attempting to install any plugin, this error appears
![image](https://github.com/Eugeny/tabby/assets/5795004/17f591e9-627b-4933-86aa-c8aa26fa2078)

**To Reproduce**:
Install Version 201 from scratch (never installed on this laptop before)
Settings -> plugin -> Choose plugin - Get.

Please note, this did not happen on another computer - same version.

Windows 11.

**Comment by matthiscock** [comment]
Log:

error: Unable to authenticate, need: Basic, Bearer {"body":null,"code":"E401","headers":{"access-control-allow-origin":["*"],"connection":["keep-alive"],"content-length":["68"],"content-type":["application/json; charset=utf-8"],"date":["Tue, 24 Oct 2023 10:46:44 GMT"],"etag":["W/\"44-SXlsQwgZ1CDvv/v5WN8xew1ZhJY\""],"server":["nginx"],"vary":["Accept-Encoding"],"www-authenticate":["Basic, Bearer"],"x-fetch-attempts":["1"],"x-powered-by":["verdaccio/4.8.1"]},"method":"GET","name":"Error","pkgid":"crypto-js@^4.0.0","stack":"Error: Unable to authenticate, need: Basic, Bearer\n    at C:\\Users\\matt\\AppData\\Local\\Programs\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\npm-registry-fetch\\check-response.js:107:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":401,"uri":"https://node.senses.co.uk:443/crypto-js/-/crypto-js-4.1.1.tgz"}

**Comment by matthiscock** [comment]
npm is global, and in path

Version is up to date 9.5.0

**Comment by Clem-Fern** [comment]
Hey @matthiscock,

From what I see in the log you send above, it seems that your network proxy or custom repo requires authentication:
```
error: Unable to authenticate, need: Basic, Bearer
...snip
"statusCode":401
...snip
```

**Comment by Jonson-zhang** [comment]
I have same problem, how to solve？

**Comment by Clem-Fern** [comment]
@Jonson-zhang You should try to contact your network administrator to know the authentication modalities.

As workaround, you could also use a different internet access while installing plugin (usb tethering with your phone?).
