### ISSUE TITLE
Question/Feature Request: CLI for opening tabby and directly execute a command

### ISSUE THREAD

**Issue by 0PandaDEV** [Eugeny/tabby#9160]
I would like to have a CLI that I can use system-wide in any terminal to open tabby and give a command as argument, for example tabby -c "yt-dlp \<yt-link>" to directly open tabby and start a command.

**Comment by ashneilson** [comment]
Hello @0PandaDEV 👋 

Have you tried the `run` cli argument for tabby?

#### Run Example
```bash
tabby run <command>
```

<img width="607" alt="image" src="https://github.com/Eugeny/tabby/assets/35913512/7774aaf5-5c04-4ad2-96aa-d0d080a41c88">

**Comment by 0PandaDEV** [comment]
tanks that is exactly what i was looking for
