### ISSUE TITLE
bad open source project

### ISSUE THREAD

**Issue by AnkoGo123** [Eugeny/tabby#9161]
This open source project in win10 by the anti-virus software 360 security guard for many times to detect remote injection code, we are still careful, no wonder I logged in the server always someone is constantly attacking my server, quickly shield this project.

**Comment by mizzuri** [comment]
I don't know if you're just trolling.. but the following are the results from VirusTotal:

[tabby-1.0.201-setup-x64.exe](https://www.virustotal.com/gui/file/ea3284f154fc917a964244e241c461e102564286037a3c1d8ba87e9c71a72501)

[tabby-1.0.201-portable-x64.zip](https://www.virustotal.com/gui/file/53824b19c8baf2820647dd523b954d2909d842c67a85bc4097d98e2f15a9dd72)
