### ISSUE TITLE
Use the plus sign to add a new TAB to select the ssh link you added

### ISSUE THREAD

**Issue by PonyZJH** [Eugeny/tabby#9206]
Now I can't see the ssh link I added by using the plus sign. I can only use the icon on the right of the plus sign to add a TAB. How to add ssh link in the plus sign。

**Comment by PonyZJH** [comment]
![1699085880689](https://github.com/Eugeny/tabby/assets/149866631/2bf54fa1-07d3-4e49-bd95-37c50346c36a)

**Comment by PonyZJH** [comment]
and I have added some SSH links like this ,but I cannot use + to choose them
<img width="603" alt="image" src="https://github.com/Eugeny/tabby/assets/149866631/38ecb142-f7cc-4069-bbaa-b2c321bc6928">

**Comment by PonyZJH** [comment]
thanks!

**Comment by Clem-Fern** [comment]
Hi @PonyZJH 

Duplicated of #9096
There is a fix for this issue in nightly build.

**Comment by PonyZJH** [comment]
> Hi @PonyZJH
> 
> Duplicated of #9096 There is a fix for this issue in nightly build.

Hi！
So we can use this function in the next version！
😀

**Comment by Clem-Fern** [comment]
Yup ! In wait of the next release, you can download nightly build from the url in the readme.

https://nightly.link/Eugeny/tabby/workflows/build/master

**Comment by Eugeny** [comment]
I'm trying to make a new release right now but the Github macOS CI workers are constantly freezing up during the build - I've already reported it.
