### ISSUE TITLE
the web-app entry missed in https://tabby.sh

### ISSUE THREAD

**Issue by GrayFull** [Eugeny/tabby#9216]
the web-app entry missed in https://tabby.sh , which casue i cannot sync my local config to cloud side

**Comment by Clem-Fern** [comment]
Hi @GrayFull 

app.tabby.sh has been discontinued.
Detail in #9131

**Comment by GrayFull** [comment]
got it . will try to  set up my own instance instead or use 'Settings Srync' plugin . thx @Clem-Fern
