### ISSUE TITLE
api.tabby.sh returning 403 forbidden

### ISSUE THREAD

**Issue by knightian** [Eugeny/tabby#9217]
Hello,

I have a fresh install of tabby and I want to retrieve my synced config file, however I cannot, because https://api.tabby.sh is returning 403 forbidden and I cannot even get my API key.

**Comment by xieccc** [comment]
#9210

**Comment by xieccc** [comment]
#9120

**Comment by et304383** [comment]
It's pinned:
https://github.com/Eugeny/tabby/issues/9131
