### ISSUE TITLE
Support request for ubuntu 23.10

### ISSUE THREAD

**Issue by onensensy** [Eugeny/tabby#9219]
**Support request.**
Please add support for ubuntu 23.10

**Comment by swyphcosmo** [comment]
I followed [these instructions](https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5) to install gconf2 which was deprecated in 23.10. After this, I was able to install the deb package like normal.

**Comment by Spl0itable** [comment]
> I followed [these instructions](https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5) to install gconf2 which was deprecated in 23.10. After this, I was able to install the deb package like normal.

Yesss thank you! This worked.

**Comment by nabheet** [comment]
The package does not exist in the repostiory for Ubuntu Mantic on packagecloud.io. I get a 404 when trying to install it via apt/apt-get. Can this package please be added to the repo?
