### ISSUE TITLE
How to ignore the sync error 

### ISSUE THREAD

**Issue by GrayFull** [Eugeny/tabby#9221]
Version: 1.0.201
Platform: macOS arm64 21.3.0
Plugins: quick-cmds, cloud-settings-sync
Frontend: xterm-webgl

<img width="287" alt="image" src="https://github.com/Eugeny/tabby/assets/102778169/1133dec4-319e-4943-a334-45b94f8094a6">

the error will appear often. actually i have used settings sync plugin to sync my config so i no need to use the tabby sync

**Comment by tarocjsu** [comment]
What kind sync service you used ? you are not point out this issue information....
