### ISSUE TITLE
tabby 1.0.203 The system default tab cannot be closed after the update

### ISSUE THREAD

**Issue by ThreadGitHub** [Eugeny/tabby#9229]
Version: 1.0.201
Platform: macOS arm64 23.1.0
Plugins: none
Frontend: xterm-webgl

**Comment by MartinLau7** [comment]
same problem

**Comment by likecreep** [comment]
same problem

**Comment by ZheCheng** [comment]
I also encountered the same issue

**Comment by xDong2781** [comment]
I also encountered the same issue

**Comment by Eugeny** [comment]
Fixed in v1.0.204
