### ISSUE TITLE
can not close tab

### ISSUE THREAD

**Issue by Nick742037091** [Eugeny/tabby#9231]
Version: 1.0.203
Platform: macOS arm64 22.5.0
Plugins: none
Frontend: xterm-webgl

I can't close the tab，it is no response when i click the  close button.
![image](https://github.com/Eugeny/tabby/assets/20139399/3a263db0-1fab-4ed8-9b9a-4f0875941f0c)

**Comment by MuhtasimTanmoy** [comment]
Same as https://github.com/Eugeny/tabby/issues/9230

**Comment by Eugeny** [comment]
Fixed in v1.0.204
