### ISSUE TITLE
Context menu does not open on right-click (Ubuntu20.04)

### ISSUE THREAD

**Issue by ksypassion** [Eugeny/tabby#9240]
I use on Ubuntu 20.04 and right click on a pane does not show the context.

Tabby Version: 1.0.201
OS: Ubuntu20.04
Platform : Linux 5.15.0-69-generic

**Comment by tinywolf3** [comment]
I had the same problem.
Try going into Settings -> Terminal and changing the rendering frontend from webgl to canvas.

**Comment by ksypassion** [comment]
@tinywolf3 
I changed the rendering frontend form webgl to canvas and then resolved issues.

Thanks.
