### ISSUE TITLE
1.0.203, tabby can not close tab and window by click ❌ button on macos

### ISSUE THREAD

**Issue by nchj** [Eugeny/tabby#9244]
**Describe the problem**:
close X button on tab or window do not work, i can only close a tab by type exit in shell, and exit tabby by right click tabby icon in task bar.when i double click the X button on tab, it always pop up a rename tab input box. 

**To Reproduce**:

**Comment by binary-sh** [comment]
Fixed in newly released 1.0.204.

**Comment by nchj** [comment]
> Fixed in newly released 1.0.204.

thanks greatly
