### ISSUE TITLE
default profile for new tabs can't chose ssh

### ISSUE THREAD

**Issue by HereHaveAnPeople** [Eugeny/tabby#9259]
default profile for new tabs can't chose ssh

<img width="826" alt="image" src="https://github.com/Eugeny/tabby/assets/54338257/fd53af85-eb71-4419-baeb-a9914de477f5">

why ?

**Comment by Eugeny** [comment]
Fixed in the latest release

**Comment by HereHaveAnPeople** [comment]
my version is v1.0.205，Already the latest
