### ISSUE TITLE
MacOS 11. Why does the color scheme work normally inside the docker container, but does not take effect in the system terminal?

### ISSUE THREAD

**Issue by LTaooo** [Eugeny/tabby#9265]
**/bin/zsh**
![image](https://github.com/Eugeny/tabby/assets/28125259/9f7ef939-33a0-452a-a322-1587a6e1d803)

**docker container**

![image](https://github.com/Eugeny/tabby/assets/28125259/b1502b63-1388-488f-be72-10b34bc3b4bb)

**Comment by Eugeny** [comment]
Read the pinned discussion please

**Comment by LTaooo** [comment]
> 请阅读固定讨论

It works, thanks!

**Comment by LTaooo** [comment]
https://github.com/Eugeny/tabby/discussions/5258
