### ISSUE TITLE
How to quickly close a split pane?

### ISSUE THREAD

**Issue by sober-wang** [Eugeny/tabby#9270]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/Eugeny/tabby/assets/35804630/6cda9007-74ad-4ddf-bb4e-298c2fcafc41)

I like create more splite pane. sometimes I should close those splite pane , only save a pane.

**Comment by Eugeny** [comment]
Right click -> close, of focus and Ctrl-D (exit shell)

**Comment by junchaw** [comment]
It's configurable now under `hotkeys.close-pane`
