### ISSUE TITLE
can't use ssh root@<computer-name>.local

### ISSUE THREAD

**Issue by bj121212** [Eugeny/tabby#9273]
Version: 1.0.205
Platform: macOS arm64 23.1.0
Plugins: none
Frontend: xterm-webgl

**Comment by Eugeny** [comment]
Tabby as a terminal doesn't affect commands running in your shell.

**Comment by bj121212** [comment]
![QQ20231123-174215](https://github.com/Eugeny/tabby/assets/12067274/ba82c914-0a65-4788-86f8-a107ee9f5446)

 X  connect EHOSTUNREACH fe80::37ac:5713:cefd:47a9:22 - Local (:::59703)

**Comment by xuxuejin** [comment]
我也遇到同样的问题，怎么解决的

**Comment by bj121212** [comment]
> 我也遇到同样的问题，怎么解决的

没法解决，我用回ip了
