### ISSUE TITLE
Pasted content always highlighted.

### ISSUE THREAD

**Issue by wupengcheng6819** [Eugeny/tabby#9277]
**Describe the problem**:
All pasted text under an Ubuntu 22 bash shell will be highlighted, either by shift-insert or right click. By highlight I mean black text on white background (just like doubleclick in Vim would do) on a dark scheme.

**To Reproduce**:
That's the tricky part. My other remote connection doesn't have this problem. Even if I copied everything from this other connection to the Ubuntu 22 (just changing the ip and username), the problem persists. Even if I removed all startup scripts (~/.bashrc, .profile, /etc/bashrc etc) of this machine, the problem persists.

**Terminal configuration**:
Copy on select : yes
Right click : Paste

**Comment by Eugeny** [comment]
It's bracketed paste. It's your shell's feature that ensures pasting multiple lines won't execute them immediately. You can turn it off in your shell or in Settings -> Terminal.

**Comment by wupengcheng6819** [comment]
Thank you!!!
