### ISSUE TITLE
[feature] support automatically complete  when select with the mouse

### ISSUE THREAD

**Issue by hello-soon** [Eugeny/tabby#9292]
In the terminal, enter "dec" and press the Tab key to list "decode1", "decode2", "decode3", and "decode4". 
Support for selecting a command directly with the mouse. 
For example, if you select "decode3", it will automatically complete as "decode3".

macos

**Comment by Eugeny** [comment]
This "UI" is presented by your shell and there's nothing the terminal app can do about it. Tabby already reports mouse events to programs running inside it, so the shell would have to implement it.
