### ISSUE TITLE
Don't "duplicate" ssh terminal when adding new pane

### ISSUE THREAD

**Issue by Nemric** [Eugeny/tabby#9306]
Version: 1.0.205
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

Love tabby and "multi pane" view but ...
When using ctrl-shift-s (or d or else) from a ssh profile (from .ssh/config), actual pane seems to be duplicated with same ssh connection
After that, when I close the connection (ctrl-d) the pane is closed

I would prefer that tabby let me choose which connection to use for new pane or just open a "cmd" or "powershell" default pane letting me enter "ssh xxx@server.ip" to be able to use "focus all tab" to send commands to multiple server at once

Thanks for great work !
Nemric

**Comment by Eugeny** [comment]
This is by design as "splitting" an existing session is the most common action with panes. You still can switch a pane to a different profile (Right click -> switch profile), or instead open your other profile in a new tab and drag n drop that tab onto your original tab, creating a pane.
