### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by GrayFull** [Eugeny/tabby#9310]
Version: 1.0.205
Platform: macOS arm64 22.6.0
Plugins: quick-cmds, cloud-settings-sync
Frontend: xterm-webgl

Why do window prompts pop up multiple times when pasting multiple lines? This is very unfriendly.

**Comment by Clem-Fern** [comment]
Hey @GrayFull 

You can disable the warning in Settings > Terminal > Clipboard > Warn on multi-line paste.

**Comment by Clem-Fern** [comment]
Duplicated #8161
