### ISSUE TITLE
Can't modify profiles created via "Save as profile"

### ISSUE THREAD

**Issue by decryptedchaos** [Eugeny/tabby#9323]
**Describe the problem**:

You can't save profiles if the profile is created via  "Save as profile"  from an active tab that was just a one-off ssh session. 

To be specific,  the profile is saved the first time when you right click the tab and Save as profile, but if you then go into settings to make modifications to the new profile you are unable to save the changes,  clicking the save button does nothing and the profile dialog stays open.

**Comment by slanglade** [comment]
In addition, @Eugeny : the newly created profile can't be updated just after being created and as long as you stay in Tabby.

But if you exit Tabby and relaunch the application, then you are free to update it.

**Comment by jdelrue** [comment]
still exists

**Comment by Clem-Fern** [comment]
I'm working on a fix. I'll submit a PR soon
