### ISSUE TITLE
在macos下，用它连接ubuntu server 22.04，使用命令sz下载zip文件，包zip文件错误。

### ISSUE THREAD

**Issue by zdhsoft** [Eugeny/tabby#9334]
**Describe the problem**:
在macos下，用它连接ubuntu server 22.04，使用命令sz下载zip文件，包zip文件错误。

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by xinkunZ** [comment]
绝了，我就是来找这个bug的，已经转向terminus了
