### ISSUE TITLE
Installation failing due to missing dependency - gconf2

### ISSUE THREAD

**Issue by apudiu** [Eugeny/tabby#9340]
Installation failing in Ubuntu 23.10.1

following is the log
```log
sudo apt install ./Downloads/tabby-1.0.205-linux-x64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'tabby-terminal' instead of './Downloads/tabby-1.0.205-linux-x64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tabby-terminal : Depends: gconf2 but it is not installable
                  Depends: gconf-service but it is not installable
E: Unable to correct problems, you have held broken packages.
```

To Reproduce:
Try to install in a fresh installation of ubuntu 23.10.1 (Tabby ver: [abby-1.0.205-linux-x64.deb](https://github.com/Eugeny/tabby/releases/download/v1.0.205/tabby-1.0.205-linux-x64.deb))

FYI: After googling found this: https://www.reddit.com/r/Kalilinux/comments/15rxyir/unable_to_install_gconf2/
Somebody is saying that this package (gconf2) is gone & apps using htis need to be updated.

**Comment by apuatcfbd** [comment]
I'll test this & let know, Even it works now it's a workaround. Is there any plan to remove this dependency?

**Comment by GokulSamraj** [comment]
> Need to install gconf2 using deb. i personally did this in one line
> 
> ```shell
>  wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && rm -rf *conf*.deb
> ```
> 
> **Hope it helps**

`dpkg: dependency problems prevent configuration of gconf2:
 gconf2 depends on gconf-service (= 3.2.6-8); however:
  Package gconf-service is not installed.

dpkg: error processing package gconf2 (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.11.2-3) ...
Errors were encountered while processing:
 gconf2`


got this error and still unable to install

**Comment by apudiu** [comment]
Tested on my machine & having same issue s @GokulSamraj.  So, it's unusable in new version of Ubuntu :(

**Comment by neda-d-tg** [comment]
I have the same error

` # sudo apt-get install mdatp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mdatp : Depends: mde-netfilter but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by H-FTM** [comment]
Hi guys try this fix and let me know if it works for you

```bash
wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
```

**Comment by H-FTM** [comment]
Hi guys try this fix and let me know if it works for you

```bash
wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
```

@apudiu @GokulSamraj @apuatcfbd

**Comment by blair2020** [comment]
> Hi guys try this fix and let me know if it works for you
> 
> ```shell
> wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
> ```
> 
> @apudiu @GokulSamraj @apuatcfbd

====================================================================================
ubuntu 18.04 LTS
```
Selecting previously unselected package gconf-service.
(Reading database ... 287855 files and directories currently installed.)
Preparing to unpack gconf-service_3.2.6-8_amd64.deb ...
Unpacking gconf-service (3.2.6-8) ...
dpkg: dependency problems prevent configuration of gconf-service:
 gconf-service depends on libc6 (>= 2.34); however:
  Version of libc6:amd64 on system is 2.28-10+deb10u2.
 gconf-service depends on libldap-2.5-0 (>= 2.5.4); however:
  Package libldap-2.5-0 is not installed.

dpkg: error processing package gconf-service (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 gconf-service
```

**Comment by GokulSamraj** [comment]
> Hi guys try this fix and let me know if it works for you
> 
> ```shell
> wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
> ```
> 
> @apudiu @GokulSamraj @apuatcfbd


![image](https://github.com/Eugeny/tabby/assets/73090987/e3fc4530-3837-4fde-802c-ae082c02376c)


this is what i got!

**Comment by H-FTM** [comment]
Hi guys try this fix and let me know if it works for you _(Just added apt install libldap)_

```bash
 sudo apt install libldap-2.5-0 && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
```

@GokulSamraj @apudiu @blair2020 @apuatcfbd

**Comment by apudiu** [comment]
Installation of gconf2 conflicts with other packages. Please get rid of this package from depency. It's better to leave dead things,

**Comment by mateobelanger** [comment]
> Tested on my machine & having same issue as @GokulSamraj. So, it's unusable in new version of Ubuntu :(

You can find the instructions to retrieve (from the debian ftp server) and install the missing librairies with dpkg.

https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5

Hope this helps :)

**Comment by Seb1plaz** [comment]
> > Need to install gconf2 using deb. i personally did this in one line
> > ```shell
> >  wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && rm -rf *conf*.deb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Hope it helps**
> 
> ![image](https://private-user-images.githubusercontent.com/73090987/295198658-f2d3a4b6-9662-4dc6-bf73-d7a94368762b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYwODYsIm5iZiI6MTcxODg2NTc4NiwicGF0aCI6Ii83MzA5MDk4Ny8yOTUxOTg2NTgtZjJkM2E0YjYtOTY2Mi00ZGM2LWJmNzMtZDdhOTQzNjg3NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MmE5MzY1NWRmOWFmYWY4MDM2NmI5MTBjZWM3MjczMmVkYzQ0YWJiNzY5NDg5M2ZmMTVjMGM2NTk4MWYyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7V4K1bRawwmnrLNoqovAAY7Z21HLb7UvMX_dCAAOHzg)
> 
> got this error and still unable to install

Install this deb and it should work, it worked for me 
```
  http://security.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.5-0_2.5.16+dfsg-0ubuntu0.22.04.2_amd64.deb
``` 
@GokulSamraj

**Comment by erjvarela** [comment]
> Need to install gconf2 using deb. i personally did this in one line (Edited with fix)
> 
> ```shell
> wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb && wget http://ftp.de.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2-common_3.2.6-8_all.deb && sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb && sudo dpkg -i gconf-service_3.2.6-8_amd64.deb && sudo dpkg -i gconf2_3.2.6-8_amd64.deb && rm -rf *conf*.deb
> ```
> 
> **Hope it helps**

Thanks :smile: It works on Debian 12 (Unstable 6.8.12-amd64)
