### ISSUE TITLE
Releases after 1.0.197 not starting on Win7

### ISSUE THREAD

**Issue by marekm72** [Eugeny/tabby#9404]
**Describe the problem**:
New releases can be installed but fail to start on Windows 7 64-bit - reports an error message about DiscardVirtualMemory in kernel32.dll - which seems to indicate it is no longer compatible with Win7.  Last version still working on Win7 is 1.0.197 even though I don't see which specific change in 1.0.198 broke Win7 support.  Yes I know Win7 is not supported by M$ anymore - now with Win10 support ending soon as well, I'll probably move to Linux instead.  Still many people use Win7 as it is mature and does the job.

**To Reproduce**:
Install 1.0.198 or later (up to 1.0.205 latest as of this writing) by running tabby-1.0.198-setup-x64.exe as usual.  It can be installed (the installer shows no warning about any Win7 incompatibility) but fails to start with the error message.  Downgrade to 1.0.197 or earlier and it works (as a new user I haven't yet tested all features, but at least it can be started for sure).

**Comment by JKHSDTV** [comment]
I can confirm that, also Win7, 64 bit. 197 still works, anything beyond doesn't.

**Comment by Eugeny** [comment]
Windows 7 is no longer supported by the underlying Electron version that Tabby uses.

**Comment by marekm72** [comment]
Please consider using https://github.com/win32ss/supermium-electron to keep Win7 compatibility.
