### ISSUE TITLE
please do not warn/alarm when paste with multi-lines

### ISSUE THREAD

**Issue by volcanochen** [Eugeny/tabby#9422]
Version: 1.0.205
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

it's anoying when a window is prompt when multi-lines is pasted, and i have to move mouse to choose....
how to disable this?
and please do not warn/alarm when paste with multi-lines, in later version.

**Comment by Eugeny** [comment]
Settings -> Terminal -> Clipboard -> Warn when pasting
