### ISSUE TITLE
There is a typo in locale/ko-KR.po for "Increase vertical split size" hotkey

### ISSUE THREAD

**Issue by pacho-h** [Eugeny/tabby#9444]
https://github.com/Eugeny/tabby/blob/ed5ff1113c0cde309462db011fdaaaac4d534e16/locale/ko-KR.po#L1097-L1099

It should be `msgstr "세로 분할 크기 크게"`.
The value currently set is the opposite of the actual.

**Comment by Eugeny** [comment]
Hi, translations are managed through https://translate.tabby.sh/ - feel free to directly change it there, thanks!
