### ISSUE TITLE
Why does tabby.sh appear in the app authorization of my Google account

### ISSUE THREAD

**Issue by toyo2333** [Eugeny/tabby#9455]
Tabby appeared in my Google account app authorization, and the authorized webpage is tabby.sh.

I usually only use the Windows version of Tabby to log in and manage my server, and I don't remember ever doing this authorization.

I just went to the official website of tabby and didn't see the authorization function entry that requires Google login.

Did I do something wrong? Or did you have this feature before but now it's removed?

**Comment by Eugeny** [comment]
You probably had used the app.tabby.sh config sync service in the past, which used Google auth. It's been shut down since then.
