### ISSUE TITLE
Problems with installation due to gconf-service and gconf2 deprecated in ubuntu 23.10

### ISSUE THREAD

**Issue by SagieSH** [Eugeny/tabby#9457]
When I attempt to install the software, I get the following error:
![image](https://github.com/Eugeny/tabby/assets/72133323/056e4429-0ffa-401d-8426-c6200437a7c7)
And after some research I found that this is due to deprecation of these packages.
Is there a way to install this anyway? apt install for gconf2 and gconf-service doesn't work....

**Comment by chrisVdd** [comment]
Exact same issue for me

**Comment by tobagin** [comment]
same issue for me.

**Comment by zhao-core** [comment]
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb

wget http://ftp.it.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb

wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb

wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb

wget http://ftp.it.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13%2bdfsg-5_amd64.deb

sudo apt install ./gconf2_3.2.6-8_amd64.deb \
  ./gconf-service_3.2.6-8_amd64.deb \
  ./libgconf-2-4_3.2.6-8_amd64.deb \
  ./gconf2-common_3.2.6-8_all.deb \
  ./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb

**Comment by zhao-core** [comment]
This worked.

**Comment by nowave7** [comment]
> wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb
> 
> wget http://ftp.it.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb
> 
> wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb
> 
> wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb
> 
> wget http://ftp.it.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13%2bdfsg-5_amd64.deb
> 
> sudo apt install ./gconf2_3.2.6-8_amd64.deb ./gconf-service_3.2.6-8_amd64.deb ./libgconf-2-4_3.2.6-8_amd64.deb ./gconf2-common_3.2.6-8_all.deb ./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb

This doesn't seem to work anymore?
```
sudo apt install ./gconf2_3.2.6-8_amd64.deb                                                                                                                                                                                           
./gconf-service_3.2.6-8_amd64.deb
./libgconf-2-4_3.2.6-8_amd64.deb
./gconf2-common_3.2.6-8_all.deb
./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gconf2' instead of './gconf2_3.2.6-8_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gconf2 : Depends: gconf-service (= 3.2.6-8) but it is not installable
E: Unable to correct problems, you have held broken packages.
zsh: permission denied: ./gconf-service_3.2.6-8_amd64.deb
zsh: permission denied: ./libgconf-2-4_3.2.6-8_amd64.deb
zsh: permission denied: ./gconf2-common_3.2.6-8_all.deb
zsh: permission denied: ./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb


```

**Comment by maxiaogood** [comment]
same

**Comment by RayneScofield** [comment]
> This worked.

Why it does not work on my kaili-linux machine after I installed the missing dependencies? 
The installation process is ok now, but the tabby-terminal just hang there when I launch it....

**Comment by Rubix982** [comment]
This is the order of the installation of the individual `.deb` files that @zhao-core shared that needs to be followed to successfully install all the packages,

1. sudo dpkg -i gconf2-common_3.2.6-8_all.deb // Install gconf2-common first
2. sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb // Then libgconf
3. sudo dpkg -i libldap-2.5-0_2.5.13+dfsg-5_amd64.deb // Then libldap
4. sudo dpkg -i gconf-service_3.2.6-8_amd64.deb // Then the gconf service
5. sudo dpkg -i gconf2_3.2.6-8_amd64.deb // Finally gconf.

Finally install Tabby with `sudo dpkg -i`.

This order has worked for me.

CC: @RayneScofield, @nowave7, @maxiaogood,

**Comment by ankit-thealchemist** [comment]
> This is the order of the installation of the individual `.deb` files that @zhao-core shared that needs to be followed to successfully install all the packages,
> 
> 1. sudo dpkg -i gconf2-common_3.2.6-8_all.deb // Install gconf2-common first
> 2. sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb // Then libgconf
> 3. sudo dpkg -i libldap-2.5-0_2.5.13+dfsg-5_amd64.deb // Then libldap
> 4. sudo dpkg -i gconf-service_3.2.6-8_amd64.deb // Then the gconf service
> 5. sudo dpkg -i gconf2_3.2.6-8_amd64.deb // Finally gconf.
> 
> Finally install Tabby with `sudo dpkg -i`.
> 
> This order has worked for me.
> 
> CC: @RayneScofield, @nowave7, @maxiaogood,

Thanks it works for me as well

**Comment by SchrodingersCpp** [comment]
> 5\. sudo dpkg -i gconf2_3.2.6-8_amd64.deb

I get this:
```
Setting up gconf2 (3.2.6-8) ...
/usr/bin/update-gconf-defaults:86: SyntaxWarning: invalid escape sequence '\['
  if re.search('^\[(?:\d+,?)+\]$', value) == None:
/usr/bin/update-gconf-defaults:86: SyntaxWarning: invalid escape sequence '\['
  if re.search('^\[(?:\d+,?)+\]$', value) == None:
```

**Comment by lukylbc** [comment]
> This is the order of the installation of the individual `.deb` files that @zhao-core shared that needs to be followed to successfully install all the packages,
> 
> 1. sudo dpkg -i gconf2-common_3.2.6-8_all.deb // Install gconf2-common first
> 2. sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb // Then libgconf
> 3. sudo dpkg -i libldap-2.5-0_2.5.13+dfsg-5_amd64.deb // Then libldap
> 4. sudo dpkg -i gconf-service_3.2.6-8_amd64.deb // Then the gconf service
> 5. sudo dpkg -i gconf2_3.2.6-8_amd64.deb // Finally gconf.
> 
> Finally install Tabby with `sudo dpkg -i`.
> 
> This order has worked for me.
> 
> CC: [@RayneScofield](https://github.com/RayneScofield), [@nowave7](https://github.com/nowave7), [@maxiaogood](https://github.com/maxiaogood),

you are an angel!!!!! THANK YOU SO MUCH!!!!!
