### ISSUE TITLE
The sftp folder can be synchronized with the console path

### ISSUE THREAD

**Issue by qq350039774** [Eugeny/tabby#9469]
The sftp folder can be synchronized with the console path，thanks

**Comment by qq350039774** [comment]
希望sftp的文件夹可以和控制台进入的文件夹路径保持同步，参考下finalshell可以。求求了，我同事给你们打钱可以！

**Comment by qq350039774** [comment]
![GIF 2024-2-21 11-53-35](https://github.com/Eugeny/tabby/assets/14347427/b99b9617-c832-445a-b7dd-0858edd31357)

**Comment by Eugeny** [comment]
Click the blue lightbulb icon in the toolbar.
