### ISSUE TITLE
下载任何插件提示报错

### ISSUE THREAD

**Issue by stefanie6** [Eugeny/tabby#9473]
Version: 1.0.205
Platform: macOS arm64 23.2.0
Plugins: none
Frontend: xterm-webgl

![1708943606035](https://github.com/Eugeny/tabby/assets/40618318/037af000-cca3-4a4d-b07d-566ceb7f5b8b)

**Comment by saul-goodman-lja** [comment]
有办法解决了吗

**Comment by sunchunfeng** [comment]
解决了吗？最新版的安装也是这样
<img width="251" alt="image" src="https://github.com/user-attachments/assets/c6ff6794-6bba-416d-93ae-5dd287409942">

**Comment by TobyIcetea** [comment]
我也是一样的报错，不知道怎么解决
