### ISSUE TITLE
Left pane text disappears when using split window

### ISSUE THREAD

**Issue by nyaong902** [Eugeny/tabby#9482]
Version: 1.0.205
Platform: Windows x64 10.0.22631
Plugins: terminal-charset, sftp-tab, quick-cmds
Frontend: xterm

This occurs when you run Tabby and split the window and leave it still.
Please refer to the video below.

https://github.com/Eugeny/tabby/assets/7732059/bb38eb6f-9a75-4ab7-aa79-42b57b425e72

**Comment by elekou** [comment]
Same happens on horizontal split, the bottom pane text disappears.
I'm on version 1.0.203.

**Comment by pesaventofilippo** [comment]
Same issue, in every orientation (sometimes it's the left panel, sometimes the right one)

**Comment by pesaventofilippo** [comment]
@Eugeny tagging you so you see it.
I think I've found the issue: opening the dev console, I inspected both the working pane and the pane whose text disappeared. Here's what happens:

<img width="745" alt="image" src="https://github.com/Eugeny/tabby/assets/32228386/82f3ac91-8774-4bca-bfb9-2ab3c12658b7">

This is the working tab. See the highlighted line and the one above it (specifically, the width and height)


<img width="690" alt="image" src="https://github.com/Eugeny/tabby/assets/32228386/93f6b26d-24cb-4fbd-925c-167d5e94a3cf">

This is the "ghost" tab. The width and height for some reason get both set to zero. If I go and manually edit those values, the text reappears successfully.

**Comment by Eugeny** [comment]
Fantastic investigation @pesaventofilippo - the fix is in.

This was due to the pane going to "sleep" since its invisibility status didn't wasn't updated after getting dragged into an active tab

**Comment by nyaong902** [comment]
Thank you for processing it quickly.  :)

**Comment by pesaventofilippo** [comment]
Just a heads up - I tried the latest nightly build and this is fixed!
Now there is a similar issue: when opening a saved layout (e.g. two terminals side by side) from the beginning, meaning you don't start with separate tabs and combine them, the text now disappears from both panels after a while lol.

If I had to guess it could be the same cause as the old problem, maybe it's a quick fix?

**Comment by DreamGallery** [comment]
I'm using the latest version right now, because I need control few servers together, and some windows will often disappear after some time, and I need to drag them to reappear.
