### ISSUE TITLE
search-panel so large 

### ISSUE THREAD

**Issue by Ox0400** [Eugeny/tabby#9483]
**Describe the problem**:
The search panel so large. size is `598px * 490px`
![image](https://github.com/Eugeny/tabby/assets/5310853/cff560f2-c665-4cd1-ba33-59504958b276)
![image](https://github.com/Eugeny/tabby/assets/5310853/b15dd782-861f-4ab3-8867-fa46bd1458ca)

normal size is `598px * 35px`
![image](https://github.com/Eugeny/tabby/assets/5310853/835147ee-ccd5-4de2-9c8a-bd0aa671634e)
![image](https://github.com/Eugeny/tabby/assets/5310853/45f10342-27d4-44aa-9512-d669f3bef67a)

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by biboc** [comment]
Got the same

![image](https://github.com/Eugeny/tabby/assets/4921425/66b1a088-7a94-40db-8c45-0a0e0469f313)

I don't know how to reproduce yet, it happens randomly but frequently
