### ISSUE TITLE
Weird character codes when scrolling/mouse clicking

### ISSUE THREAD

**Issue by Snuupy** [Eugeny/tabby#9522]
**Describe the problem**:

Weird character codes show up when trying to scroll after the app has been open for some time

**To Reproduce**:

Leave app open for awhile, try to scroll in the window, get weird character codes for some reason on scroll and mouse click

https://github.com/Eugeny/tabby/assets/964538/64182c5c-a927-4404-8608-8da7875263e9

**Comment by artu-ole** [comment]
`reset` should work as a workaround. I think this depends on the shell on the remote pc that you run or a command that you run it that it starts capturing mouse events. This is not specific to Tabby it seems:
https://askubuntu.com/questions/1150617/clicking-in-ssh-terminal-causes-junk-characters-08332m0-after-tmux
https://apple.stackexchange.com/questions/326266/in-terminal-scrolling-prints-weird-characters

**Comment by Snuupy** [comment]
Yes this happens after a network drop where the connection gets interrupted, there is an auto reconnect but when that happens these characters show up. `reset` fixes it!

**Comment by webloft** [comment]
This bug still exists (and also happens on re-connect). Why is this closed?
