### ISSUE TITLE
Option to not clear screen after ssh reconnect

### ISSUE THREAD

**Issue by fellrider2** [Eugeny/tabby#9536]
**Is your feature request related to a problem? Please describe.**
My VPN times out periodically and thus I have to reconnect, and it would be less intrusive if the screen contents weren't lost.

**Describe the solution you'd like**
An option to not clear the pane screen when reconnecting to ssh

**Additional context**
Thanks for the hard work on this program in general, I use it a lot.

**Comment by Eugeny** [comment]
You can find it in Profiles -> Advanced -> Defaults -> SSH -> Clear after on connection 👐
