### ISSUE TITLE
One-time connection

### ISSUE THREAD

**Issue by marcalath** [Eugeny/tabby#9541]
**Is your feature request related to a problem? Please describe.**
During live / shared sessions, when asked to connect to some machine (on the go / instantly / for just a minute) there's no "direct connection" feature.

**Describe the solution you'd like**
Add the native (Built-in) 'SSH Connection' and 'Telnet session' profiles to the 'Profiles & Connections' tab direct link at the top (not under 'Settings' - under the top shortcut tab), which will open a dialog for inserting one-time (instant) connection parameters (host, auth, etc.) and allow for an instant connection (without the need to configure a profile just for that one-time connection).

**Describe alternatives you've considered**
The Tabby alternative is to pre-configure a connection and only then clicking it the tab.
Other alternatives is to use other clients / session managers (e.g. PuTTY).

**Additional context**

There's no accessing the predefined built-in SSH / Telnet profiles from the top:

![top](https://github.com/Eugeny/tabby/assets/125604796/836b4426-f86f-4c2c-ad1d-2712f78ca845)

There's a way to configure default settings for connection types:

![settings](https://github.com/Eugeny/tabby/assets/125604796/eba5932c-649a-43c2-b251-8f999a567154)

Kindly consider adding the default built-in connection setting as a template for one-time connections - similar to how PuTTY would:

![putty](https://github.com/Eugeny/tabby/assets/125604796/932df9a8-a071-4326-86e0-0ee5d009bb7b)

**Comment by artu-ole** [comment]
It might help that there is a way to connect right away by entering username and ip in the profile selection list. This of course does not allow selecting private key on the fly, but works for servers that accept password authentication
![image](https://github.com/Eugeny/tabby/assets/15938416/0eaeece5-0e6c-4e6e-81b6-2884e13023a7)

**Comment by msacharewicz** [comment]
And there also are the Defaults that should allow you to not only configure they keys for an on-the-fly connection (which uses same shortcut as profiles, default Ctrl+Alt+E), but would preconfigure these settings for new profiles:

![obraz](https://github.com/Eugeny/tabby/assets/34579814/2371b346-9fd5-4b38-8db5-cedee869ce2f)

**Comment by marcalath** [comment]
@artu-ole, @msacharewicz - thanks 😃 
I guess the suggested feature somewhat includes aspects from the two: Defaults would provide the startup template, and connection via the list (for example, by providing user and host) would set such connection on the go.

We can expand this, for example: assuming one can connect right away from the profile selection list, a small configuration button would appear next to unknown connections - allowing on-the-fly customization of that connection
