### ISSUE TITLE
termux proot-distro ubuntu installation failed deprecated dependency gconf

### ISSUE THREAD

**Issue by jozhuare99** [Eugeny/tabby#9555]
im trying to install this in android device via termux proot-distro ubuntu
but got an error dependency

root@localhost:~# ls                                          
tabby-1.0.207-linux-arm64.deb                                 
tabby_arm64.deb

root@localhost:~# dpkg -i tabby-1.0*
(Reading database ... 16988 files and directories currently installed.)
Preparing to unpack tabby-1.0.207-linux-arm64.deb ...
Unpacking tabby-terminal (1.0.207) over (1.0.207) ...
dpkg: dependency problems prevent configuration of tabby-terminal:
 tabby-terminal depends on gconf2; however:
  Package gconf2 is not installed.                            
 tabby-terminal depends on gconf-service; however:
  Package gconf-service is not installed.
 tabby-terminal depends on gnome-keyring; however:
  Package gnome-keyring is not installed.
 tabby-terminal depends on libnotify4; however:
  Package libnotify4 is not installed.
 tabby-terminal depends on libsecret-1-0; however:              
Package libsecret-1-0 is not installed.
 tabby-terminal depends on libxtst6; however:
  Package libxtst6 is not installed.                           
tabby-terminal depends on libnss3; however:
  Package libnss3 is not installed.                           
dpkg: error processing package tabby-terminal (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:                      
tabby-terminal

do you have other build that will support installation in arm64 system for proot-distro ubuntu system?

**Comment by Eugeny** [comment]
Fixed in the latest release
