### ISSUE TITLE
Why does clicking the SFTP button not open the current path directory of the server

### ISSUE THREAD

**Issue by ncdxliu** [Eugeny/tabby#9568]
**Describe the problem**:
Why does clicking the SFTP button not open the current path directory of the server

**To Reproduce**:
![1712044538879](https://github.com/Eugeny/tabby/assets/28562769/3d2ae4fd-5baa-44ca-9380-f239de9b920c)

**Comment by Eugeny** [comment]
<img width="499" alt="image" src="https://github.com/Eugeny/tabby/assets/161476/30cccf3b-8b8c-456c-baf2-be00f8b87244">
