### ISSUE TITLE
Tabby Vault password protection do not work right 

### ISSUE THREAD

**Issue by icexlab** [Eugeny/tabby#9579]
Version: 1.0.207
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

Hi, Tabby dev team.

There is an issue when you activate Vault password protection. The time period to remeber the password do not work, if you select 7 days, and restart Tabby, the password box shows again every time you start Tabby. I think this happen with every time period option.

Thanks for your support.

![imagen](https://github.com/Eugeny/tabby/assets/114962837/384ee3b1-48d3-425d-81de-b74683f7d3d9)

**Comment by gitthangbaby** [comment]
Reproduced 100% of the time, it's also reported in #6547.

**Comment by Eugeny** [comment]
Vault can't protect your data if the password is "remembered" on disk next to the vault itself, just think about it
