### ISSUE TITLE
Hello~tabby official development author

### ISSUE THREAD

**Issue by godaizhan** [Eugeny/tabby#9594]
Hello~tabby official development author

I came across a new requirement and I wonder if you can consider improving it
Just linking to a terminal tab can currently be done by splitting multiple windows, which is no problem. But at this time, multiple windows can only link to the current server. At this time, we encounter a problem. When we solve the problem, we hope to be able to link to multiple servers in one tab to solve the problem at the same time. If we use multi-tab login There is actually no problem with the server, but we need to switch frequently, which results in very low efficiency.

for example
![image](https://github.com/Eugeny/tabby/assets/103105164/7a17e1d9-4fe1-4366-ac97-81de01bcb322)

For example, if I take a screenshot of the window, it is connected to a server. I split multiple windows, but the multiple windows can only connect to the server. At this time, I want to mark "2" in the picture, and I want to link The local system CMD window or Powersheel can only create new tabs, but cannot be linked in the sequence "2" in the first picture of my screenshot. Some local windows need to execute some commands locally because they need to update files, so that they do not need to switch frequently. window, so that work efficiency can also be improved

![image](https://github.com/Eugeny/tabby/assets/103105164/45a0d959-e9d6-4787-ad14-6c84e3fc6cd5)

I hope tabby can consider this need
If you already have this function, can you tell me how to use it? Thank you very much.
Taking up public time

**Comment by Eugeny** [comment]
Right-click a pane -> Switch profile.

You can even save the resulting combined tab as a profile itself.

**Comment by godaizhan** [comment]
![image](https://github.com/Eugeny/tabby/assets/103105164/47b66236-233c-48f6-b472-b8a9b0b364f6)
Hello, I tried~, but it doesn’t seem to work. Example: Take this screenshot of mine

I split many windows, in this window, in one of the windows I want to link the local bash environment,

![image](https://github.com/Eugeny/tabby/assets/103105164/e442fc58-044f-453a-afe4-7dcddf2a3ff6)

Look at my screenshot. I want to exit a small window here. I executed exit in the terminal and the window will be closed automatically. If it is not closed, I can connect to the local bash environment so that I You can debug many techniques in one tab window page, so you don’t have to switch back and forth between tab pages.

**Comment by godaizhan** [comment]
And we can split many windows in one tab, and many windows can link to different environment terminals, such as our local bash environment. In this way, we frequently update the code without frequently switching windows.

**Comment by godaizhan** [comment]
Hello, I am very happy to receive your reply.

I know what you mean, but it still doesn't work. If I choose to create a window with a new label, and switch the configuration from the current window, I will be prompted to close the current window. After closing it, a new window with a new label will be created. Got it

**Comment by godaizhan** [comment]
Am I doing something wrong? Can you give me a video or picture tutorial? I really want to read it.

**Comment by godaizhan** [comment]
![image](https://github.com/Eugeny/tabby/assets/103105164/1d8ba112-e7d0-4eb7-ba1f-fa524ae01459)
You see my screenshot, I right-clicked the tab for these windows > Split > Exit window

But sometimes we need a local bash environment or command window, which needs to be in a tab page, so that we can execute commands without frequently switching tabs! , this is very helpful for efficiency, and this time I came to you to communicate the reasons and seek your help, it is also because of this, I sincerely hope you can help me

Thank you so much

**Comment by Eugeny** [comment]
https://github.com/Eugeny/tabby/assets/161476/f58b61a8-5f69-41e8-86cf-6198d19a8ef5

**Comment by godaizhan** [comment]
![image](https://github.com/Eugeny/tabby/assets/103105164/854e2e59-26a7-4534-b215-6596313ede10)
My current version is: 1.0.207

![image](https://github.com/Eugeny/tabby/assets/103105164/55e66366-7c1a-4381-b194-550379ed498e)
I right-click on the window and paste

Hello, I saw your video. I don’t know if it is a version problem or other reasons.
When I click on the email in the window, it always pastes, and no menu pops up.

**Comment by Eugeny** [comment]
You can switch the right click behaviour in Settings - Terminal - Mouse. Or use a hotkey to switch the profile. Or long hold the right mouse button

**Comment by godaizhan** [comment]
Okay. Thank you very much. Thank you very much.
Exception, I reported a bug, that is, the window runs for a long time, nothing can be clicked in the tabby window, but it is running in the background, and all windows cannot be operated. I will give you feedback next time this happens.
