### ISSUE TITLE
color scheme not working

### ISSUE THREAD

**Issue by wucaitian** [Eugeny/tabby#9604]
Version: 1.0.207
Platform: macOS arm64 23.4.0
Plugins: none
Frontend: xterm-webgl

"In my macOS, the color scheme of Tabby hasn't taken effect, as there are no colors displayed in the opened terminal."
![Xnip2024-04-28_21-27-39](https://github.com/Eugeny/tabby/assets/27181616/0bac83af-a978-4f99-b422-8b1e15b91c84)
![Xnip2024-04-28_21-27-10](https://github.com/Eugeny/tabby/assets/27181616/5eb1747b-a6af-49b1-8078-8267ba58a24d)

**Comment by Eugeny** [comment]
https://github.com/Eugeny/tabby/discussions/5258
