### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by kuoiea** [Eugeny/tabby#9626]
Version: 1.0.207
Platform: macOS arm64 23.4.0
Plugins: none
Frontend: xterm-webgl

开启并排窗口，然后进行搜索， 这个搜索框怎么变得这么大

<img width="901" alt="image" src="https://github.com/Eugeny/tabby/assets/20547022/74f98c3f-b220-4651-89e8-789caab6b5ec">

**Comment by lhch102** [comment]
怎么解决的
