### ISSUE TITLE
search box is very big !

### ISSUE THREAD

**Issue by KingZonelzz** [Eugeny/tabby#9651]
/Version: 1.0.207
Platform: Windows x64 10.0.19044
Plugins: trzsz
Frontend: xterm-webgl

![Uploading 239748e1746ebdbf66adc61e487f345.png…]()

**Comment by lijzijie** [comment]
Same

![bigbigbig](https://github.com/Eugeny/tabby/assets/33867786/443655f9-0e1d-4a9c-a781-8cd41dbc0438)

**Comment by lijzijie** [comment]
Same 

![Uploading big.png…]()

**Comment by lijzijie** [comment]
Same 

![big](https://github.com/Eugeny/tabby/assets/33867786/600c8b3a-4ad9-4338-96b1-151827930bcc)
