### ISSUE TITLE
tabby cannot be installed in the ubuntu for the version 24.04

### ISSUE THREAD

**Issue by cyxinda** [Eugeny/tabby#9662]
I install tabby-1.0.207-linux-x64.deb in the version 24.04 of ubuntu,the dependency software of gconf2 and gconf-service not found.
It is like this:
```bash
cyxinda@old6:~/share$ sudo dpkg -i tabby-1.0.207-linux-x64.deb 
(正在读取数据库 ... 系统当前共安装有 156509 个文件和目录。)
准备解压 tabby-1.0.207-linux-x64.deb  ...
正在解压 tabby-terminal (1.0.207) 并覆盖 (1.0.207) ...
dpkg: 依赖关系问题使得 tabby-terminal 的配置工作不能继续：
 tabby-terminal 依赖于 gconf2；然而：
  未安装软件包 gconf2。
 tabby-terminal 依赖于 gconf-service；然而：
  未安装软件包 gconf-service。

dpkg: 处理软件包 tabby-terminal (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1.1ubuntu3) 的触发器 ...
正在处理用于 desktop-file-utils (0.27-2build1) 的触发器 ...
在处理时有错误发生：
 tabby-terminal

```

**Comment by Ericwln** [comment]
> I install tabby-1.0.207-linux-x64.deb in the version 24.04 of ubuntu,the dependency software of gconf2 and gconf-service not found. It is like this:
> 
> ```shell
> cyxinda@old6:~/share$ sudo dpkg -i tabby-1.0.207-linux-x64.deb 
> (正在读取数据库 ... 系统当前共安装有 156509 个文件和目录。)
> 准备解压 tabby-1.0.207-linux-x64.deb  ...
> 正在解压 tabby-terminal (1.0.207) 并覆盖 (1.0.207) ...
> dpkg: 依赖关系问题使得 tabby-terminal 的配置工作不能继续：
>  tabby-terminal 依赖于 gconf2；然而：
>   未安装软件包 gconf2。
>  tabby-terminal 依赖于 gconf-service；然而：
>   未安装软件包 gconf-service。
> 
> dpkg: 处理软件包 tabby-terminal (--install)时出错：
>  依赖关系问题 - 仍未被配置
> 正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
> 正在处理用于 gnome-menus (3.36.0-1.1ubuntu3) 的触发器 ...
> 正在处理用于 desktop-file-utils (0.27-2build1) 的触发器 ...
> 在处理时有错误发生：
>  tabby-terminal
> ```

先解决依赖问题啊

**Comment by cyxinda** [comment]
> > I install tabby-1.0.207-linux-x64.deb in the version 24.04 of ubuntu,the dependency software of gconf2 and gconf-service not found. It is like this:
> > ```shell
> > cyxinda@old6:~/share$ sudo dpkg -i tabby-1.0.207-linux-x64.deb 
> > (正在读取数据库 ... 系统当前共安装有 156509 个文件和目录。)
> > 准备解压 tabby-1.0.207-linux-x64.deb  ...
> > 正在解压 tabby-terminal (1.0.207) 并覆盖 (1.0.207) ...
> > dpkg: 依赖关系问题使得 tabby-terminal 的配置工作不能继续：
> >  tabby-terminal 依赖于 gconf2；然而：
> >   未安装软件包 gconf2。
> >  tabby-terminal 依赖于 gconf-service；然而：
> >   未安装软件包 gconf-service。
> > 
> > dpkg: 处理软件包 tabby-terminal (--install)时出错：
> >  依赖关系问题 - 仍未被配置
> > 正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
> > 正在处理用于 gnome-menus (3.36.0-1.1ubuntu3) 的触发器 ...
> > 正在处理用于 desktop-file-utils (0.27-2build1) 的触发器 ...
> > 在处理时有错误发生：
> >  tabby-terminal
> > ```
> 
> 先解决依赖问题啊

The problem is that the dependencies of software such as gconf2 cannot be installed in the ubuntu-24.04 operating system.

**Comment by 120dev** [comment]
thats work for me :)))
https://www.youtube.com/watch?v=Ve7g28nd1pY

**Comment by Eugeny** [comment]
Fixed in the latest release
