### ISSUE TITLE
Using ConPTY causes screen lag on interactive output

### ISSUE THREAD

**Issue by IgnusG** [Eugeny/tabby#968]
While using ConPTY, the screen lags behind after an interactive command ended. For example after quitting `most`. The part of the screen where the new command line is displayed gets redrawn but anything below stays.

Even just clicking on the window removes the artifact - typing does not though. 

### Steps
1. Open interactive command which renders output to the whole terminal window
2. Quit command - anything below the current input line *should* stay displayed

![image](https://user-images.githubusercontent.com/6438760/58484550-90586100-8162-11e9-8f9a-dc973be3e327.png)

### Versions
Windows 10 - 1903 Insider Preview
Terminus Alpha 78 using xterm and ConPTY enabled
Using ZSH 5.7.1

**Comment by IgnusG** [comment]
Edit: It happens to any content rendered below the current line.

![image](https://user-images.githubusercontent.com/6438760/58485789-fd6cf600-8164-11e9-83ea-cf35525a3f29.png)

PS: The plugin that renders the gray text is a fish like auto-suggestion for zsh. Disabling zsh plugins didn't fix the problem (when using with `most` or `git log` etc.)

**Comment by IgnusG** [comment]
Update: Disabling ConPTY solves the issue. I also noticed that scrolling isn't working when using ConPTY on the xterm backend which might explain the redraw issue? Scrolling with ConPTY disabled works as expected.

**Comment by IgnusG** [comment]
I think this is the cause https://github.com/xtermjs/xterm.js/issues/2148

Will probably be fixed in next release

**Comment by Eugeny** [comment]
That fix is included in the nightly builds now - let me know if it helped!

**Comment by IgnusG** [comment]
Still an issue
