### ISSUE TITLE
Ubuntu 24.04 LTS not supported

### ISSUE THREAD

**Issue by gauravcodepro** [Eugeny/tabby#9694]
Hi, i have seen that Tabby is not supported on Ubuntu 24.04 LTS due to the gconf2. Any news on the new release. I have manged to set it up on the 24.04 LTS release but it is getting broken multiple times. 

I use Tabby and Warp both as terminal side script and code development. 

Thank you,
Gaurav

**Comment by dheera** [comment]
+1

~/Downloads :) sudo dpkg -i tabby-1.0.207-linux-x64.deb 
Selecting previously unselected package tabby-terminal.
(Reading database ... 338757 files and directories currently installed.)
Preparing to unpack tabby-1.0.207-linux-x64.deb ...
Unpacking tabby-terminal (1.0.207) ...
dpkg: dependency problems prevent configuration of tabby-terminal:
 tabby-terminal depends on gconf2; however:
  Package gconf2 is not installed.
 tabby-terminal depends on gconf-service; however:
  Package gconf-service is not installed.

dpkg: error processing package tabby-terminal (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Errors were encountered while processing:
 tabby-terminal
~/Downloads :) ta^C
~/Downloads :) sudo apt -f install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  mailcap node-busboy node-cjs-module-lexer node-undici node-xtend nodejs-doc nvidia-modprobe
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  tabby-terminal
0 upgraded, 0 newly installed, 1 to remove and 24 not upgraded.
1 not fully installed or removed.
After this operation, 399 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 340756 files and directories currently installed.)
Removing tabby-terminal (1.0.207) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
