### ISSUE TITLE
希望支持快捷命令

### ISSUE THREAD

**Issue by henan01** [Eugeny/tabby#9722]
希望可以支持快捷命令，比如常用的密码，命令，保存在下面的快捷方式中，点击就可以快速执行

**Comment by nchj** [comment]
喜提CVE是吧

i think it is bad for secure resons and these functions can easily implemented by config you shell well

**Comment by henan01** [comment]
比如mysql的密码，常用命令，经常登录的个人的安全性还可以，怎么通过配置实现，可否详细说说

**Comment by nchj** [comment]
terminal is terminal it self, not a password manager(in fact tabby provide a vault funcion but i never use it).
use cert to login your server or mysql databse is a good choice, just config it.
if you **have to** remember password in you terminal,
`pass` may be a good choice for both security and easy to use(i do not use it), it can even copy your password to clipboard, you may like it.
or else you can store pass in you bashrc if you do not care about security(not recommended, at you own risk).
shortcut is a good way to save time, but for linux terminal, it is not necessary, you can use alias or use code completion to replace it and faster.
for shortcut of common used command, code completion of bash, zsh, fish, or even powershell can be used to find a command easily, so why a shortcut,
too many articles on the internet, just google it, a simple way is oh-my-zsh/oh-my-bash
