### ISSUE TITLE
Tabby doesn't run on Ubuntu 24

### ISSUE THREAD

**Issue by ChiefC0de** [Eugeny/tabby#9723]
Hi!
I wanted to ask how long will it take to release Tabby for Ubuntu 24? I can't install the deb package nor Appimage
Thanks.

**Comment by lkhung09** [comment]
Entirely possible install on U24.04. But you need install full package.
You can search follow error logs.
I think this is may be help you.
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13%2bdfsg-5_amd64.deb

sudo chmod 644 ./gconf2_3.2.6-8_amd64.deb
sudo apt install ./gconf2_3.2.6-8_amd64.deb

sudo chmod 644 ./gconf-service_3.2.6-8_amd64.deb
sudo apt install ./gconf-service_3.2.6-8_amd64.deb
sudo chmod 644  ./libgconf-2-4_3.2.6-8_amd64.deb
sudo apt install ./libgconf-2-4_3.2.6-8_amd64.deb

sudo chmod 644 ./gconf2-common_3.2.6-8_all.deb
sudo apt install ./gconf2-common_3.2.6-8_all.deb
sudo chmod 644 ./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb
sudo apt install ./libldap-2.5-0_2.5.13+dfsg-5_amd64.deb

**Comment by ChiefC0de** [comment]
Was able to run Appimage using Gear Lever (couldn't run Appimage by default, it was giving me errors everytime).
