### ISSUE TITLE
Rendering bug: Without input, all the contents will simply disappear after less than a minute

### ISSUE THREAD

**Issue by RavenMacDaddy** [Eugeny/tabby#9742]
Apologies if this is a duplicate. I searched the open issues for a while, but couldn't find anything that was exactly what I'm experiencing — relate if suitable.

- No plugins
- Running the latest version, installed through [Scoop](https://scoop.sh/)
- Should be running default rendering settings; don't recall changing anything related to that
- CPU: AMD Ryzen 3600 | GPU: NVIDIA GTX 1080
- Disabling GPU acceleration makes no difference

**Describe the problem**:
Without input, after less than a minute, the contents simply become blank. 

See the video below of it happening in real-time; just captured a small part of the screen to see the text disappear, but everything in the terminal does; all the text.

I should note that I'm running a horizontal split so that I've two vertical spaces to work with simultaneously; everything disappears in the two panes.

https://github.com/Eugeny/tabby/assets/67732686/cfda557e-160d-4c4d-b99f-35f7e1f53c0d

**To Reproduce**:
1. Do a horizontal split and run some commands in each
2. Close Tabby, then re-open, which makes Tabby restore the history by default
3. Wait a minute or two, and if you've got the same issue as I do, the contents will suddenly disappear

**Comment by ianw1974** [comment]
Happened to me as well on Fedora.  Reverted to previous version (1.0.207) until it's resolved.  Mine happened when just using the left pane - I have the terminal split into 3, two vertical panes, with the right vertical pane split into two smaller terminals horizontally.  I was only using the left terminal (full length of screen) running an ansible playbook when everything went blank.

**Comment by baka-gourd** [comment]
I had the same problem and it didn't improve after upgrading to 209

**Comment by moemoechu** [comment]
It seems to only occur when the session is recovered.
after session is recovered, and wait about 1minute, the content is gone, and the follow elements' weight and height become 0:
![image](https://github.com/user-attachments/assets/25d2943d-3d08-499b-abdc-97ae423863e8)
after change active tab, the weight and height become normal, and the content is back:
![image](https://github.com/user-attachments/assets/7bf57d1b-1e16-4fdd-912b-42e17786b078)

**Comment by ianw1974** [comment]
For me it happens on new sessions.  So it's not just on session recovery.
