### ISSUE TITLE
更新版本后程序使用经常崩溃

### ISSUE THREAD

**Issue by Lxiue** [Eugeny/tabby#9743]
Version: 1.0.208
Platform: Windows x64 10.0.19045
Plugins: background
Frontend: xterm
1.远程连接一个ssh页面后，经常白屏，就是该页面上会突然什么文字都没有，必须关闭重新连接才有效
2.经常无故崩溃闪退
3.使用linux系统sz下载文件经常出现下载的文件损坏。几个不通的linux系统都有出现

**Comment by all4fun** [comment]
+1
+1
+1

**Comment by xuxuejin** [comment]
+1
macOS

**Comment by ic4y** [comment]
+1
macos

**Comment by qigj** [comment]
+1
macos

**Comment by qigj** [comment]
<img width="948" alt="image" src="https://github.com/user-attachments/assets/5fa70b31-bd4e-4916-b959-fc341b282a72" />

**Comment by zhgqiang** [comment]
+1
macos m3

**Comment by qjl988** [comment]
+1

**Comment by B1ithe** [comment]
+1
