### ISSUE TITLE
SSH connection is very slow as compared to other apps like Putty.

### ISSUE THREAD

**Issue by dk4633** [Eugeny/tabby#9745]
SSH connection is very slow as compared to other apps like Putty.
SSH connection is very slow as compared to other apps like Putty.
SSH connection is very slow as compared to other apps like Putty.

for cisco switches and routers

Version: 1.0.208
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

**Comment by premyslc** [comment]
Same here. It's not usable because slow response.

Version: 1.0.208
Platform: Windows x64 10
Plugins: none
Frontend: xterm-webgl

**Comment by Eugeny** [comment]
Is likely fixed in 209+
