### ISSUE TITLE
Content disappear while using serial

### ISSUE THREAD

**Issue by GCTechnology** [Eugeny/tabby#9762]
Version: 1.0.208
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

I'm using serial feature. Sometimes the content on the termial will suddenly disappear.
![PIC1](https://github.com/Eugeny/tabby/assets/151746991/0dbb719c-59e8-4182-bc42-6f273ae48f40)
An 'enter' key still cannot work.

When i click 'unpin', they show up again.
![PIC2](https://github.com/Eugeny/tabby/assets/151746991/3e2a64e9-95bd-437a-8ae8-b16b1ab27c95)
That's strange. This issue appeared when updating to newest version.

**Comment by ianw1974** [comment]
Sounds similar to #9742

**Comment by GCTechnology** [comment]
So it's a bug?

**Comment by ianw1974** [comment]
I would say so yes, it never happened in 1.0.207.
