### ISSUE TITLE
blackscreen

### ISSUE THREAD

**Issue by yimingwangdell** [Eugeny/tabby#9763]
Version: 1.0.208
Platform: Windows x64 10.0.22621
Plugins: theme-gruvbox, search-in-browser, quick-restart
Frontend: xterm

connect with tmux 3.3a, sometimes whole screen becomes black,
but can be recovered by resizing window with drag and drop the title bar.

**Comment by ianw1974** [comment]
Possibly similar to #9742

**Comment by yimingwangdell** [comment]
![image](https://github.com/Eugeny/tabby/assets/121928908/f81764f4-b195-4f7b-8ff8-4dfafde90fcb)
for reference.
