### ISSUE TITLE
"@" and "|" not working 

### ISSUE THREAD

**Issue by Peachy74** [Eugeny/tabby#9779]
tabby terminal 1.0.209 on macos
option+l should normally be the @.
I get an ls - directory listing.
In an alternative terminal option+l (@) or option+7 (|) works.
A hotkey is also not set up.
does anyone have an idea?
Kind regards

**Comment by Peachy74** [comment]
No problem with tabby 1.0.207

**Comment by pebosi** [comment]
Same problem on mac os sonoma, problem was already on 1.0.208

**Comment by bh** [comment]
Duplicate of #9746
