### ISSUE TITLE
UI non reactive

### ISSUE THREAD

**Issue by lachnerd** [Eugeny/tabby#9791]
Version: 1.0.210
Platform: Windows x64 10.0.22631
Plugins: quick-cmds
Frontend: xterm-webgl

After upgrade to 1.0.210 or 1.0.209 i am unable to click any UI element except github & report a problem, pretty weird

**Comment by vecinohk** [comment]
Go back to Alpha 208 and be patient - https://github.com/Eugeny/tabby/issues/9787

**Comment by Eugeny** [comment]
Duplicate of #9787
