### ISSUE TITLE
By connecting via SSH and using a user switch (sudo -iu user) the SFTP folder tab has no permissions to do anything

### ISSUE THREAD

**Issue by simmelpatrick** [Eugeny/tabby#9797]
By ssh-ing with a global user into a server on our side, I can login without any issues. Afterwards I need to do a user switch with sudo -iu to be authenticated with our server-side user. The sftp tab follows the directory of that user but has no permissions, since it's user verification is probably still stuck on the previous global user.

Therefore I can't use the sftp browser tab while logged in as another user with "sudo -iu" because there are no permissions to create folders, rename and move stuff and so on.

**Comment by Eugeny** [comment]
`sudo` is just a shell command and is unrelated to how SFTP works. 

There is an [OpenSSH specific hack](https://unix.stackexchange.com/questions/111026/how-to-use-sftp-on-a-system-that-requires-sudo-for-root-access-ssh-key-based-a) that works in specific conditions (passwordless sudo) but that's it.

**Comment by gmvlasta** [comment]
I also miss this functionality in the sftp panel.  I think it would make sense to have a configuration option to run the server-side sftp as in the link above: 

sftp -s "sudo /usr/lib/openssh/sftp-server" targethost.fqdn

I read that some sftp clients have this option to use sftp with sudo.
