### ISSUE TITLE
Everything is broken

### ISSUE THREAD

**Issue by JKHSDTV** [Eugeny/tabby#9798]
Version: 1.0.210
Platform: Windows x64 10.0.19045
Plugins: docker
Frontend: xterm-webgl

I can't click on any of the 'Recent history' entries, I can't click on settings, I can't open my profile list, I can't click on pretty much anything other than, ironically, "Report a problem" 😂 just updated, and broke right after the update. I think it worked oddly right after updating and when I tried to restart to see if that helped, it got into this totally frozen state.

**Comment by shtuseriff** [comment]
Same issue here. Installed Tabby for the first time yesterday, and been having those issues where suddenly nothing works. Closing and re-opening SEVERAL times sometimes fixes it, albeit briefly.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by lachnerd** [comment]
same here last 3 releases broke it

**Comment by Clemens-E** [comment]
Same Issue. I updated, everything froze, all ssh profiles gone, cant open a new terminal.
The DevTools show no error.
Tried to install previous versions without luck

**Comment by Clemens-E** [comment]
I was able to fix this by:
copying the config file for backup
removing all profiles from the config file
uninstalling tabby
rebooting windows
installing the latest version
adding profiles back to the config file

seems to work now

**Comment by JKHSDTV** [comment]
This seems to be fixed in the latest version (`1.0.211`) so I'm closing, unless someone asks to reopen because they still experience it. Thanks for fixing it!
