### ISSUE TITLE
Tab disappeared when switching to full screen on Mac OS 

### ISSUE THREAD

**Issue by yfhu99-ali** [Eugeny/tabby#9805]
**Describe the problem**:
Tab on the top disappeared when switching to full screen mode on Mac OS.

**To Reproduce**:
1. On Macbook Pro (M3 Pro, OS X 14.5), open several terminals.
![image](https://github.com/user-attachments/assets/b002393d-3506-4253-af4a-cecd024b047c)

2. Click green button, all tabs disappeared.
![image](https://github.com/user-attachments/assets/17cdc9ac-bea5-4886-90f8-d2289864424d)

**Comment by Eugeny** [comment]
Settings -> Window -> Tabs -> Show in fullscreen
