### ISSUE TITLE
How to get root privileges with sftp

### ISSUE THREAD

**Issue by toyo2333** [Eugeny/tabby#9816]
I logged into a vps like ubuntu with a normal user name（not root user）, and when I use sftp to upload a file (or edit a file), it fails.

We know that executing sudo -i in the terminal can elevate the privileges to complete the operation, so in my case of logging in with normal user privileges, if yes, sftp can get root privileges to complete the file upload and file modification?

**Comment by siebsie23** [comment]
I'm having the same issue on v1.0.215. I don't remember this being a problem in an earlier version.

**Comment by Eugeny** [comment]
`sudo -i` launches a new text based shell as a different user. You cannot elevate the SSH connection itself.

**Comment by toyo2333** [comment]
> `sudo -i` launches a new text based shell as a different user. You cannot elevate the SSH connection itself.

is there any solution now？ i use sftp-edit ，start vscode open the json file on the server ，but it can not save the file to the server

**Comment by wbo2020** [comment]
> `sudo -i` launches a new text based shell as a different user. You cannot elevate the SSH connection itself.

People may not understand the underlying technicalities, but the point is SFTP root privileges. As an OpenSSH server is intended, there is a way to do it. request_subsystem and channel.exec should be able to grab custom subsystems or paths that pass passwordless sudo sftp-server, similar to the OpenSSH sftp -s command or putty WinSCP equivalent. Currently, I'm replacing the lines in sshd_config with a custom shell script to gain sftp root access. And it became a challenge for some "nonstandard systems" such as embedded or Android. I have to dial back to more productive old trusty OpenSSH and winscp/putty than this.
