### ISSUE TITLE
unable to connect to old cisco switches: Unknown DH Group

### ISSUE THREAD

**Issue by tiagocasalribeiro** [Eugeny/tabby#9830]
**Problem**:
After upgrading to version 1.0.209 I am unable to connect to old switches, with Unknown DH Group. Read somewhere else it is an error related to BoringSSH used by EletronJS, that have dropped support for diffie-hellman-group1-sha1.

**To Reproduce**:
1 - Upgrade to version 1.0.209 or newer;
2 - Try to connect to an old Cisco switch.

**Comment by Eugeny** [comment]
Check out https://github.com/Eugeny/tabby/issues/9810

**Comment by tiagocasalribeiro** [comment]
> Check out #9810

Tried the nightly, still having the same issue.

**Comment by tiagocasalribeiro** [comment]
> have you enabled the diffie-hellman-group1-sha1 kex in the profile settings in the nightly version?

Yes, I did.

**Comment by Eugeny** [comment]
Could you please post the output of connection setup log when connecting to the switch with `ssh -v`?

**Comment by tiagocasalribeiro** [comment]
> Could you please post the output of connection setup log when connecting to the switch with `ssh -v`?

here it is:

PS C:\Users\***********> ssh -v -oKexAlgorithms=+diffie-hellman-group1-sha1 -c3des-cbc ***********
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Connecting to ******** [**********] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\*********/.ssh/id_rsa type 0
debug1: identity file C:\\Users\\*********/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\*********/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\*********/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\*********/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\*********/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\*********/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\*********/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\*********/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\*********/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version Cisco-1.25
debug1: match: Cisco-1.25 pat Cisco-1.* compat 0x60000000
debug1: Authenticating to *********:22 as '***********'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group1-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: 3des-cbc MAC: hmac-sha1 compression: none
debug1: kex: client->server cipher: 3des-cbc MAC: hmac-sha1 compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:***********
debug1: Host '***********' is known and matches the RSA host key.
debug1: Found key in C:\\Users\\***********/.ssh/known_hosts:44
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\***********/.ssh/id_rsa RSA SHA256:***********
debug1: Will attempt key: C:\\Users\\***********/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\***********/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\***********/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\***********/.ssh/id_xmss
debug1: SSH2_MSG_SERVICE_ACCEPT received
-----------------------------------------------------
Banner
-----------------------------------------------------
debug1: Authentications that can continue: password
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: No such file or directory
***********@***********'s password:

**Comment by Eugeny** [comment]
Thanks - a new nightly with 3DES cipher support should be ready soon: https://github.com/Eugeny/tabby/actions/runs/10395680351

**Comment by tiagocasalribeiro** [comment]
> Thanks - a new nightly with 3DES cipher support should be ready soon: https://github.com/Eugeny/tabby/actions/runs/10395680351
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[bumped russh · Eugeny/tabby@c42ea8a](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

Tried this new build, now it only says "disconnect".

**Comment by Eugeny** [comment]
I've updated the build to show more detailed error messages - would appreciate if you could give it another try :v:

**Comment by Clem-Fern** [comment]
@tiagocasalribeiro just curious, is the command "ip ssh version 2" present on the switch you are trying to connect to ?

I bumped into a similar issue with the experimental build and some old devices without ssh server version 2 by default.

It seems that the old ssh2 lib wasnt bother by the version ssh.

**Comment by tiagocasalribeiro** [comment]
> @tiagocasalribeiro just curious, is the command "ip ssh version 2" present on the switch you are trying to connect to ?
> 
> I bumped into a similar issue with the experimental build and some old devices without ssh server version 2 by default.
> 
> It seems that the old ssh2 lib wasnt bother by the version ssh.

Now I am getting this: 
 X  NoCommonAlgo { kind: Key, ours: ["ecdsa-sha2-nistp256", "ecdsa-sha2-nistp521", "rsa-sha2-256", "rsa-sha2-512"], theirs: ["ssh-rsa"] }

**Comment by Eugeny** [comment]
Thank you! I've added it to the defaults list
