### ISSUE TITLE
When trying to double click a string to select, it selects some of the punctuation marks, but not all

### ISSUE THREAD

**Issue by Thwifty** [Eugeny/tabby#9831]
**Describe the problem**:
E.g. for a string like:
```
jintiantianqibucuo_AAAA===AA!!AA:
```

If I double-click the string, it copies the whole thing:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/49388314-437a-4cd1-b3a8-e32d70232535">

But I think a better way would be like the built-in Terminal for Mac or iTerm, which is to copy characters plus underline `_`, but not others, e.g.
<img width="280" alt="image" src="https://github.com/user-attachments/assets/62ca7f59-d3e9-4440-8742-61ad6f664b4a">
<img width="282" alt="image" src="https://github.com/user-attachments/assets/1d290096-bb91-437f-94e6-ec29cd2fac79">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/25a39bbb-dd6f-4583-8ad5-0b87285b11ac">

This is most (if not, all) of the apps' behaviour, I tried double clicking on this string in Chrome, and the logic of the select is the same as the one I described above.

**Comment by Eugeny** [comment]
Settings -> Terminal -> Mouse -> Word separators

**Comment by mboeker** [comment]
> Settings -> Terminal -> Mouse -> Word separators

Oh neat, didn't see that. Thanks!
