### ISSUE TITLE
can tabby jump to dir which I`m in shell when I open ftp?

### ISSUE THREAD

**Issue by kshq1996** [Eugeny/tabby#9846]
Can tabby jump to dir which I`m in shell when I open ftp?

<img width="1600" alt="image" src="https://github.com/user-attachments/assets/e99c134e-6ce2-41b0-b841-485689d2fcca">

**Comment by Eugeny** [comment]
Click the blue light bulb

**Comment by kshq1996** [comment]
but why XShell and Xftp can do it?

**Comment by Eugeny** [comment]
They do magic parsing of what the shell is showing on screen. I don't want to rely on this and not all shell configurations print the full current directory in the prompt.
