### ISSUE TITLE
No apt repository for ubuntu/noble (aka ubuntu 24.04)

### ISSUE THREAD

**Issue by qs5779** [Eugeny/tabby#9864]
I ran the script generate a apt repo list for tabby on a ubuntu noble server but that repo doesn't exist.

I installed the deb manually, but would be nice to have current ubuntu support in your repos.

Thanks

**Comment by kkumtree** [comment]
I also wait the support for ubuntu/noble 

![image](https://github.com/user-attachments/assets/4524b57d-e1e2-4cd8-b61b-7975c8a0701c)
