### ISSUE TITLE
Tabby Can`t Startup, Loading Progress bar not show

### ISSUE THREAD

**Issue by AkarinLiu** [Eugeny/tabby#9937]
**Describe the problem**:
[A clear and concise description of what the bug is.]
Recent, I Updated Tabby, I Discover a Huge Bug, Tabby Can`t Startup, Loading bar not show.

**To Reproduce**:
[Steps to reproduce the behavior]
1. Open the Settings
2. Click Update Button
3. Install Update

**Comment by Slopz** [comment]
Same here.

**Comment by QuentinHsu** [comment]
The same issue in v1.0.212
![image](https://github.com/user-attachments/assets/db79b978-3a0a-4e8e-abd0-30355c882a76)

**Comment by Eugeny** [comment]
Fixed in v213
