### ISSUE TITLE
tabby 1.0.212 doesn't start on macOS Sonoma 14.6.1 (arm64)

### ISSUE THREAD

**Issue by bogdanm** [Eugeny/tabby#9942]
I tried to update to the latest tabby version today (1.0.212) and I can't start it anymore. Attempting to start it results in a "The application "Tabby.app" can't be opened" dialog box, without further information. The previous version worked fine, unfortunately I don't remember its exact version number.
I tried installing tabby from the releases page (tabby-1.0.212-macos-arm64.dmg) and via homebrew, same result.

**Comment by Eugeny** [comment]
Fixed in v213
