### ISSUE TITLE
Tabby doesn't load on first click on windows 11

### ISSUE THREAD

**Issue by tismofied** [Eugeny/tabby#9947]
I downloaded the latest release and I have to click on the app twice to be able to open it and then it opens twice  so I end up with 2 tabbies open.
The first click nothing happens then I click the second time this happens
![Screenshot 2024-09-18 141804](https://github.com/user-attachments/assets/6e5a79bc-d6f1-4e0d-bd67-0fff0bc47115)

how can I troubleshoot this please?
 I am on the latest windows 11 build

**Comment by MonkeyHarris** [comment]
I'm seeing the same with the latest release on Windows 10. The first Tabby instance can be seen running in the process list but there's no window.

**Comment by tismofied** [comment]
> I'm seeing the same with the latest release on Windows 10. The first Tabby instance can be seen running in the process list but there's no window.
For a sec I thought I was the only one

**Comment by zjt000** [comment]
I always thought it was a problem with my computer

**Comment by justfunxin** [comment]
the same with me on windows 10

**Comment by flysunyang** [comment]
I also encountered the same problem on Windows 11.

**Comment by minidriverau** [comment]
Had the same issue, I found disabling hardware acceleration fixed the issue for me

**Comment by tisrico** [comment]
Having the same problem.

**Comment by ShiinaKin** [comment]
same here

**Comment by tismofied** [comment]
Update: did some testing at the suggestion of @minidriverau and the only window frame that's working is `Native`. Any other settings would break tabby.

**Comment by daniel347x** [comment]
Me as well - ugh! Was quite worried Tabby is not working any more. Takes a second click to get it to appear, and then there are two Tabby windows.

**Comment by daniel347x** [comment]
Resolution for me: Same as recommended by @minidriverau:

Settings | Window | Window Frame -> Native

**Comment by Eugeny** [comment]
Could you please verify that it's fixed in the latest nightly?

**Comment by mrevjd** [comment]
> Could you please verify that it's fixed in the latest nightly?

The nightly seems to have fixed the issue for me. Thanks.

**Comment by klassifyed** [comment]
> Could you please verify that it's fixed in the latest nightly?

The update has resolved the issue. Thank you.
