### ISSUE TITLE
Problems with activation

### ISSUE THREAD

**Issue by xiaocuanChina** [Eugeny/tabby#9952]
Version: 1.0.213
Platform: Windows x64 11
Plugins: none
Frontend: xterm-webgl
Description: After updating to this version, you need to double-click twice to start the program, and there are two main windows after starting the program.

**Comment by Nemric** [comment]
Same here on fedora 40 / gnome / wayland and since 1.0.212

**Comment by xiaocuanChina** [comment]
> Same here on fedora 40 / gnome / wayland and since 1.0.212自 1.0.212 版起，在 fedora 40 / gnome / wayland 上也是如此 see #9947 见 #9947

Thanks for the reply, I'll try to go back to the pre-1.0.212 version here!

**Comment by Nemric** [comment]
@xiaocuanChina It as been resolved in 1.0.215 so you can close if it's ok for you ;)
