### ISSUE TITLE
Windows 11 cannot open the window by double-clicking it

### ISSUE THREAD

**Issue by NerdyNomadPixelPilgrim** [Eugeny/tabby#9962]
Version: 1.0.214
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

Windows Version：
![image](https://github.com/user-attachments/assets/ebe869e1-afba-45a8-a32e-f922228ceb62)

Bug：It takes 4 clicks on the desktop icon before a window pops up, but there are two application windows.

![image](https://github.com/user-attachments/assets/fffc4a53-97e1-49ef-9c6c-d8be03e4a257)
This problem occurs when it is set to non-native

**Comment by Eugeny** [comment]
Fixed in the nightly
