### ISSUE TITLE
I want to disable the clickable function of URLs.

### ISSUE THREAD

**Issue by ramsydx** [Eugeny/tabby#9977]
There is a function to change the URL to a clickable one.
This is convenient, but it can lead to operational errors, so I'd like to see it improved.
How about adding the following to the settings and changing this behaviour?
===
1. launch url(Same behaviour as now)
2. launch url via modal(Insert a modal confirmation)
3. disabled(Do not make the URL clickable.)

**Comment by Eugeny** [comment]
Disable the Linkifier plugin in the settings.
