### ISSUE TITLE
The border style in the new version is inconsistent with the old version, and it looks quite unharmonious.

### ISSUE THREAD

**Issue by buhuiqizi** [Eugeny/tabby#9990]
### Describe the problem:
The border color of the terminal in the new version aligns with the theme rather than the terminal's background color, resulting in a visually unharmonious appearance.

The changes should originate from v1.0.213. https://github.com/Eugeny/tabby/issues/9894
<img width="910" alt="image" src="https://github.com/user-attachments/assets/0a3ac740-4b09-4141-b37b-c13fe2b86c9f">

**v1.0.211**
<img width="1920" alt="Snipaste_2024-10-09_15-24-40" src="https://github.com/user-attachments/assets/b246a8e4-2d6a-4389-9fc5-1f70f7dff747">

**v1.0.215**
<img width="1920" alt="Snipaste_2024-10-09_15-24-18" src="https://github.com/user-attachments/assets/8f9261dd-a2cd-4f7e-a9fb-b524b8b0e98b">

### System Details
macOS 15.0
Tabby 1.0.215

**Comment by saudiqbal** [comment]
Same problem on Kubuntu

**Comment by Eugeny** [comment]
The legacy themes are no longer supported and in particular won't work when the lightness/darkness doesn't match the color scheme. You can switch the theme to "follow the color scheme" in Settings -> Window and it will match your terminal colors automatically.
